- lib/models/page.js
- lib/models/user.js
- lib/routes/admin.js
> impl delete user

- local_modules/crowi-fileupload-local/index.js
It enables to upload images on Window.
Ref: crowi#217
> Use POSIX-style paths.

- README.md
- wercker.yml
- yarn.lock
* update `yarn.lock`
* update `wercker.yml`
* git reset before bumping version with npm
> release v1.1.3 (retry)

- lib/views/layout/layout.html
> ensure to load babel-polyfill from CDN

- README.md
Retry because pipeline for #134 has failed.
> release v2.0.0 

- lib/locales/ja/translation.json
- lib/models/page.js
- lib/routes/page.js
- lib/views/modal/rename.html
recursively option for Move operationは解決
recursively option for Delete operation, recursively option for Put back / Delete completely operationsは未解決
> Imprv/121 Add recursively option for Move operation

- app.json
> fix bonsai plan

- resource/js/components/SearchPage/DeletePageListModal.js
- resource/js/components/SearchPage/SearchResult.js
* Add delete-completely option in search result page for select deletion.
> # Improve/168 Selective batch deletion in search result page

- lib/views/admin/users.html
fix #179 
* Change self account unsuspendable in users management page.
* ユーザ管理ページのユーザの編集機能において、自身のアカウントが停止できないように修正
> # Improve/179 Suspend account

- resource/js/legacy/crowi-form.js
Added a grammatical correction.
> Correct message grammar

- resource/js/components/NewPageNameInputter.js
参考
====
- https://qiita.com/clockmaker/items/5e2207b14dac97c4ede1
`npm run build:dev:analyze` の結果
=======================
Before
-------
After
-----
> refactor import lines from 'react-bootstrap'

- lib/models/page-group-relation.js
- lib/models/page.js
- test/models/page.test.js
- test/utils.js
* Fix test utils cannot resolve models which filename includes '-'.
* add testcase for group acl.
> # Feature/196, 198, 199 Grouping users

- lib/models/page.js
- lib/models/user-group.js
- lib/routes/admin.js
* fix bugs of feature grouping-users.
> # Fix/Bugs of grouping users

- README.md
- package.json
:+1: version to release (BugFix of growi-docker)
> release v3.0.1

- config/webpack.common.js
- resource/styles/scss/theme/nature.scss
add theme 'nature' to webpack.common.js entry and make bundle.css, bundle.css.map, bundle.js and bundle.js.map files for theme 'nature' in /public/js
> add theme 'nature' to webpack.common.js entry

- lib/views/admin/customize.html
- resource/styles/agile-admin/inverse/colors/nature.scss
- resource/styles/scss/_admin.scss
add third selectTheme button for theme-nature but cannot select it now
> Add theme'nature' selectbutton 

- resource/js/components/PageEditor.js
> specify page_id param

- resource/js/components/PageAttachment/DeleteAttachmentModal.js
> Replace 'Icon' with '.speeding-wheel-sm'

- config/webpack.common.js
- lib/views/admin/customize.html
- resource/styles/agile-admin/inverse/colors/mono-blue.scss
- resource/styles/scss/theme/mono-blue.scss
> mono-blue-theme_v2

- lib/views/modal/unportalize.html
- resource/js/legacy/crowi.js
> fix unportalize modal template

- lib/views/_form.html
* Fix bug of invisible group choose select-box.
> # Fix bug of invisible group choose select-box.

- resource/js/app.js
- resource/js/components/PageComment/Comment.js
- resource/js/components/PageComments.js
- resource/js/util/GrowiRenderer.js
- GrowiRendererのインスタンスをPageComment.jsで作り、mode: 'comment'
- pagePath, highlightKeywordsをpropsから削除
> GrowiRenderer mode: comment

- config/webpack.common.js
- lib/views/admin/customize.html
- resource/styles/agile-admin/inverse/colors/blue-night.scss
- resource/styles/scss/theme/blue-night.scss
> add blue night theme

- lib/models/page.js
- lib/routes/page.js
> BugFix: v3.1.1 doesn't post to slack

- lib/crowi/index.js
Added `disable('x-powered-by')` on Express
Reference: https://expressjs.com/en/advanced/best-practice-security.html
> Disable Express header

- lib/locales/en-US/sandbox.md
- lib/locales/ja/sandbox.md
- package.json
- resource/js/util/markdown-it/blockdiag.js
- yarn.lock
* `markdown-it-fence` problem
* https://github.com/geekplux/markdown-it-fence/pull/2
* use new version of markdown-it-fence.
> fix #460 & add example to Sandbox

- lib/routes/comment.js
> ensure to update Page.updatedAt

- resource/js/components/PageComment/CommentForm.js
- resource/js/components/SlackNotification.js
make react-component for slack notification
> post comment notification takizawa

- src/server/routes/apiv3/healthcheck.js
- src/server/routes/apiv3/index.js
- src/server/routes/index.js
- src/server/util/search.js
> impl /_api/v3/healthcheck

- src/server/form/invited.js
- src/server/form/login.js
- src/server/form/me/password.js
- src/server/form/register.js
> fix #662: Login Form rejects weak password

- src/server/crowi/express-init.js
> Exclude /_api/v3/healthcheck from basic authentication.

- src/server/views/admin/app.html
> App lang form2

- src/client/js/components/SearchPage.js
- src/client/js/components/SearchPage/SearchResult.js
- src/client/styles/scss/_search.scss
As suggested search input is made position sticky. Also the search icon and search input are made same height. 
Fixes  #731
> Making search input affix

- src/server/views/admin/app.html
https://weseek.myjetbrains.com/youtrack/issue/GC-1340
> change en to en-US in radiobutton of global language.

- CHANGES.md
- package.json
> release v3.3.1

- src/client/js/util/GrowiRenderer.js
further implementation for #457
> add systax for showing line number

- src/server/views/admin/widget/passport/github.html
- src/server/views/admin/widget/passport/google-oauth.html
- src/server/views/admin/widget/passport/saml.html
- src/server/views/admin/widget/passport/twitter.html
> fix: #778 Wrong OAuth callback url are shown

- package.json
- yarn.lock
> upgrade node-sass

- src/client/js/util/reveal/plugins/growi-renderer.js
https://weseek.myjetbrains.com/youtrack/issue/GC-1401
data-separator のカスタム機能に対応.
> correspond with custom data-separator.

- src/client/js/util/reveal/plugins/growi-renderer.js
- src/server/views/page_presentation.html
https://weseek.myjetbrains.com/youtrack/issue/GC-1404
> correspond with custom data-separator '^-----$'.

- src/server/util/createGrowiPagesFromImports.js
> refactor createGrowiPages method

- src/client/js/app.js
> fix more i18n update issue

- package.json
- src/client/js/app.js
- src/client/js/components/PageEditor/Editor.jsx
- yarn.lock
> Upgrade react-dropzone

- src/client/js/app.js
> BugFix for CommentForm

- src/client/styles/agile-admin/inverse/eliteadmin.scss
タスクGC-1585を行うため
https://weseek.myjetbrains.com/youtrack/agiles/84-27/85-275?issue=GC-1585
> convert css

- src/client/js/legacy/crowi.js
- src/server/models/page.js
- delete documents on ES index when user completely deletes pages
- add documents on ES index when user duplicates pages
> add socketClientId to send data

- CHANGES.md
- src/lib/service/xss/recommendedXssWhiteList.js
> add '-' to whitelist

- .vscode/launch.json
- Debugger接続時のタイムアウトを10秒から30秒に延長
> increase debugger timeout

- src/server/models/attachment.js
- src/server/models/bookmark.js
- src/server/models/page.js
> fix mongoose schema

- package.json
- resource/locales/en-US/translation.json
- src/server/form/admin/securityPassportOidc.js
- src/server/form/index.js
- src/server/models/config.js
- src/server/routes/admin.js
- src/server/routes/index.js
- src/server/routes/login-passport.js
- src/server/service/passport.js
- src/server/util/swigFunctions.js
- src/server/views/admin/security.html
- src/server/views/admin/widget/passport/oidc.html
- src/server/views/login.html
- yarn.lock
This PR implements OpenID Connect authentication. (#893)
Tested with growi(master, f2c137d) and hydra(v1.0.0-rc.12).
> Impl oidc authentication

- src/client/js/components/PageEditor.jsx
> fix onUpload event handler of PageEditor

- src/client/js/app.js
- src/client/js/components/Admin/AdminRebuildSearch.jsx
> AdminRebuildSearch with unstated

- package.json
- resource/locales/en-US/translation.json
- src/server/crowi/index.js
- src/server/form/admin/securityPassportBasic.js
- src/server/form/index.js
- src/server/models/config.js
- src/server/routes/admin.js
- src/server/routes/index.js
- src/server/routes/login-passport.js
- src/server/service/passport.js
- src/server/util/swigFunctions.js
- src/server/views/admin/security.html
- src/server/views/admin/widget/passport/basic.html
- src/server/views/login.html
- yarn.lock
> Add Passport HTTP basic auth strategy

- src/client/js/app.js
- src/client/js/components/Admin/Importer.jsx
- src/server/views/admin/importer.html
> React is possible

- src/client/js/components/PageEditor/ScrollSyncHelper.js
> fix scroll for Edge

- resource/locales/en-US/translation.json
- resource/locales/ja/translation.json
- src/client/js/app.js
- src/client/js/components/Admin/FullTextSearchManagement/FullTextSearchPage.jsx
> Reactify Full Text Search Management Page

- src/client/js/components/Admin/Users/UserTable.jsx
- src/client/js/components/Admin/Users/Users.jsx
- src/server/views/admin/users.html
ユーザー情報がstateに入れられるようにしました。
また、paginationwrapperと設定ボタンも入れました。
Tableのbodyには現時点のPRでは何も入っていませんが、入れているところです。
出来次第PR出します。（早くできたらこのPRとまとめます）
> Render User Information

- src/client/js/components/Admin/Users/UserMenu.jsx
- src/client/js/components/Admin/Users/UserTable.jsx
- src/client/js/components/Admin/Users/Users.jsx
- src/server/views/admin/users.html
通信を行ったりすることはできない見た目だけのUserMenuです。
> Apparent User Menu

- CHANGES.md
- src/client/js/app.jsx
- src/client/js/components/TableOfContents.jsx
- src/client/js/legacy/crowi.js
- src/client/js/services/PageContainer.js
- src/client/js/util/GrowiRenderer.js
- src/client/js/util/markdown-it/toc-and-anchor.js
> reactify ToC

- CHANGES.md
- src/server/service/global-notification.js
- src/server/util/mailer.js
> BugFix: Global Notification

- src/server/crowi/index.js
GlobalNotificationSlack 実装時に追加した `Crowi.prototype.setupSlack` のバグを修正
> fix Crowi.prototype.setupSlack

- README.md
- src/server/service/config-loader.js
- src/server/service/file-uploader/gcs.js
- src/server/service/file-uploader/gridfs.js
> GW-318: limit file upoload size from gcs

- src/client/styles/scss/_layout.scss
- src/server/views/layout/layout.html
* Add link to https://docs.growi.org
* Displayed only when the user. (not guest)
> Add Link to docs.growi.org

- src/client/styles/scss/_override-bootstrap-variables.scss
> modify $font-family-monospace

- src/client/js/components/Admin/Customize/CustomizeBehaviorSetting.jsx
- src/client/js/components/Admin/MarkdownSetting/LineBreakSetting.jsx
- src/client/js/services/AdminCustomizeContainer.js
- src/server/routes/apiv3/customize-setting.js
> Create api v3 update behavior

- src/client/js/services/AdminCustomizeContainer.js
- src/server/routes/apiv3/customize-setting.js
> Create api v3 update function

- resource/locales/en-US/translation.json
- resource/locales/ja/translation.json
- src/client/js/components/Admin/Customize/CustomizeBehaviorSetting.jsx
> I18n customize behavior(英語⇨日本語)

- resource/locales/en-US/translation.json
- resource/locales/ja/translation.json
- src/client/js/app.jsx
- src/client/js/components/Admin/CustomScriptEditor.jsx
- src/client/js/components/Admin/Customize/Customize.jsx
- src/client/js/components/Admin/Customize/CustomizeCustomScriptSetting.jsx
- src/client/js/services/AdminCustomizeContainer.js
- src/server/models/config.js
> Create custom script setting frontside

- src/client/js/components/Admin/Customize/CustomizeHighlightSetting.jsx
- src/client/js/services/AdminCustomizeContainer.js
- src/server/routes/admin.js
- src/server/routes/apiv3/customize-setting.js
> Fetch highlight theme

- resource/locales/ja/translation.json
- src/client/js/components/Admin/MarkdownSetting/MarkDownSetting.jsx
- src/client/js/components/Admin/MarkdownSetting/PresentationForm.jsx
- src/server/routes/index.js
> Detail correction for master merge

- src/client/js/components/Admin/Security/SecurityManagement.jsx
> XSS configuration link

- resource/locales/en-US/translation.json
- resource/locales/ja/translation.json
- src/client/js/components/Admin/Security/SecurityLocalSetting.jsx
- src/client/js/components/Admin/Security/SecurityManagement.jsx
- src/client/js/services/AdminSecurityContainer.js
- src/server/models/config.js
- src/server/views/admin/widget/passport/local.html
> Create passport local component

- src/server/service/search.js
`/_api/v3/healthcheck?connectToMiddlewares` is not responding correct status after #1291.
```
$ curl -D - http://example.com/_api/v3/healthcheck?connectToMiddlewares
HTTP/2 503
(abbr)
{"err":{}}
```
> Fix healthcheck endpoint

- README.md
- src/server/service/config-loader.js
- src/server/service/file-uploader/aws.js
- src/server/service/file-uploader/gcs.js
- src/server/service/file-uploader/gridfs.js
- src/server/service/file-uploader/local.js
- src/server/service/file-uploader/uploader.js
- add  environment file upload disabled
> refs GC-621

- resource/locales/en-US/translation.json
- resource/locales/ja/translation.json
- src/client/js/components/Admin/Security/SecurityLdapSetting.jsx
- src/client/js/components/Admin/Security/SecurityLocalSetting.jsx
- src/client/js/components/Admin/Security/SecurityManagement.jsx
- src/client/js/services/AdminSecurityContainer.js
- src/server/models/config.js
- src/server/views/admin/widget/passport/local.html
> Create passport ldap component

- src/client/js/components/Admin/Customize/Customize.jsx
- src/client/js/components/Admin/Customize/CustomizeBehaviorSetting.jsx
- src/client/js/components/Admin/Customize/CustomizeCssSetting.jsx
- src/client/js/components/Admin/Customize/CustomizeFunctionSetting.jsx
- src/client/js/components/Admin/Customize/CustomizeHeaderSetting.jsx
- src/client/js/components/Admin/Customize/CustomizeHighlightSetting.jsx
- src/client/js/components/Admin/Customize/CustomizeLayoutSetting.jsx
- src/client/js/components/Admin/Customize/CustomizeScriptSetting.jsx
- src/client/styles/scss/_admin.scss
> Adjust layout customize page

- src/server/service/global-notification/global-notification-mail.js
> Fix 1143: defaultLang of GlobalNotificationMailService 

- resource/locales/en-US/translation.json
- resource/locales/ja/translation.json
- src/client/js/app.jsx
- src/client/js/components/Admin/Security/LocalSecuritySetting.jsx
- src/client/js/components/Admin/Security/SamlSecuritySetting.jsx
- src/client/js/components/Admin/Security/SecurityManagement.jsx
- src/client/js/services/AdminGeneralSecurityContainer.js
- src/client/js/services/AdminSamlSecurityContainer.js
> Reactify admin/saml security setting

- resource/locales/en-US/translation.json
- resource/locales/ja/translation.json
- src/client/js/app.jsx
- src/client/js/components/Admin/Security/OidcSecuritySetting.jsx
- src/client/js/components/Admin/Security/SamlSecuritySetting.jsx
- src/client/js/components/Admin/Security/SecurityManagement.jsx
- src/client/js/services/AdminGeneralSecurityContainer.js
- src/client/js/services/AdminLdapSecurityContainer.js
- src/client/js/services/AdminOidcSecurityContainer.js
> Reactify admin/oidc security setting

- resource/locales/en-US/translation.json
- resource/locales/ja/translation.json
- src/client/js/app.jsx
- src/client/js/components/Admin/Security/BasicSecuritySetting.jsx
- src/client/js/components/Admin/Security/SecurityManagement.jsx
- src/client/js/services/AdminBasicSecurityContainer.js
- src/client/js/services/AdminGeneralSecurityContainer.js
> Reactify admin/basic security setting

- resource/locales/en-US/translation.json
- resource/locales/ja/translation.json
- src/client/js/app.jsx
- src/client/js/components/Admin/Security/GoogleSecuritySetting.jsx
- src/client/js/components/Admin/Security/SecurityManagement.jsx
- src/client/js/services/AdminGeneralSecurityContainer.js
- src/client/js/services/AdminGoogleSecurityContainer.js
> Reactify admin/google security setting

- resource/locales/en-US/translation.json
- resource/locales/ja/translation.json
- src/client/js/app.jsx
- src/client/js/components/Admin/Security/GithubSecuritySetting.jsx
- src/client/js/components/Admin/Security/SecurityManagement.jsx
- src/client/js/services/AdminGeneralSecurityContainer.js
- src/client/js/services/AdminGithubSecurityConatainer.js
> Reactify admin/GitHub security setting

- src/client/js/components/Admin/ImportData/GrowiArchive/UploadForm.jsx
> .growi.zip -> .zip

- config/migrate.js
- src/test/config/migrate.test.js
> fix migrate.js

- src/server/views/layout/layout.html
- src/server/views/widget/page_tabs.html
- chromeでドロップダウンの見た目がおかしかったので修正
before
after
> fix-dropdown-layout

- src/client/js/components/Admin/Security/LdapAuthTestModal.jsx
- src/client/js/components/Admin/Security/LdapSecuritySetting.jsx
> Reactify admin/create an authentication test modal

- src/client/js/app.jsx
- src/client/js/components/Admin/Notification/NotificationSetting.jsx
- src/client/js/services/AdminNotificationContainer.js
- src/server/views/admin/notification.html
> Reactify admin/create notification component

- src/client/js/app.jsx
- src/client/js/components/Admin/Notification/ManageGlobalNotification.jsx
- src/client/js/components/Admin/Notification/TriggerEventCheckBox.jsx
- src/server/views/admin/global-notification-detail.html
> Reactify admin/add grobal notification component

- src/client/styles/scss/_page.scss
https://github.com/weseek/growi/issues/1527
- ライトテーマ
- ダークテーマ
> add color gray

- .github/workflows/build-rc.yml
- .github/workflows/build.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
v2になってfetchのdepthがデフォルトで1になってます
> Update github actions checkout to v2

- CHANGES.md
- src/client/js/components/SavePageControls.jsx
> show toastr when error is occured

- src/client/styles/scss/_comment.scss
changed the position of comments
> changed the position of comments

- src/client/js/components/Admin/Security/LdapSecuritySetting.jsx
2 点修正した。
- UserBind 時には input を入力できないようにする
- BindMode は boolean で管理する `bindMode` という state は存在しないのに参照していた
> Reactify admin/fix is user bind description

- src/client/styles/agile-admin/inverse/colors/spring.scss
https://github.com/weseek/growi/issues/1637
> changed the color of hover

- src/client/js/components/Admin/Security/LdapAuthTestModal.jsx
- src/server/routes/login-passport.js
> Reactify admin/fix ldap test log

- src/client/js/components/Admin/AdminHome/AdminHome.jsx
- src/client/js/components/Admin/AdminHome/SystemInfomationTable.jsx
- apply boostrap4 /admin
(before)
(after)
> Bst4 admin wikimanage

- src/client/js/services/AdminSamlSecurityContainer.js
- src/server/routes/apiv3/security-setting.js
> fix typo ABLC Rule

- src/client/js/services/AdminLocalSecurityContainer.js
- src/server/routes/apiv3/security-setting.js
fix https://github.com/weseek/growi/issues/1714
> registrationWhiteList-save-empty-array

- src/client/js/components/Admin/Security/SamlSecuritySetting.jsx
- src/server/routes/apiv3/security-setting.js
> get value from DB

- src/server/views/widget/page_tabs.html
> apply edit tab

- src/client/styles/scss/_navbar.scss
- src/client/styles/scss/_override-bootstrap.scss
https://github.com/weseek/growi/pull/1686/files#diff-c79a8f6d5559d7bd17d97a25d24879f1R77
でのdropdown の border 調整を修正
> adjust border of dropdown

- src/client/js/components/PageEditor.jsx
- src/client/js/services/EditorContainer.js
fix https://github.com/weseek/growi/issues/1780
> change timing conditional branch whether this page is first

- src/client/js/components/PageComment/CommentEditor.jsx
- src/client/js/services/CommentContainer.js
fix #1758
手元でgrowi 以外のアップロードができないことを確認。
> Can't upload image to comment 

- src/client/js/components/PageComment/Comment.jsx
- src/client/js/components/PageComment/ReplayComments.jsx
- src/client/js/components/PageComments.jsx
- src/client/js/components/User/UserPicture.jsx
- src/client/styles/scss/_comment_growi.scss
> Imprv mobile support for comments

- src/server/routes/login-passport.js
fix https://github.com/weseek/growi/issues/1775
> fix/G Suite Oauth name order is reversed

- src/client/js/components/BookmarkButton.jsx
- src/client/js/components/LikeButton.jsx
- src/client/js/components/Navbar/GrowiSubNavigation.jsx
- src/client/styles/scss/atoms/_buttons.scss
> adjust header buttons style

- src/client/js/components/PageEditorByHackmd.jsx
> adujust hackMD button

- src/client/styles/scss/_login.scss
- src/server/views/login.html
- external login のフォーム展開の挙動を修正
- LDAP 有効時のアカウント名インプットフォームのレイアウト修正
- ログイン画面のアラートのレイアウト修正
> fix external login form

- src/client/js/components/Admin/UserGroupDetail/UserGroupUserFormByInput.jsx
> adjsut button size

- src/client/js/components/Admin/ImportDataPage.jsx
> change color

- src/client/js/components/Admin/Common/AdminUpdateButtonRow.jsx
> change class

- src/client/js/components/Admin/App/MailSetting.jsx
> be responsive

- .github/workflows/ci.yml
> Feat/rewite ci.yml for new actions

- src/client/js/components/Admin/Security/GoogleSecuritySetting.jsx
> Chenge style

- src/client/styles/scss/_on-edit.scss
- src/server/views/_form.html
> adjust to fit

- src/client/js/components/Admin/UserManagement.jsx
> change to not to be two row

- src/client/styles/scss/_layout_kibela.scss
> change to expand width for limit on editor mode

- src/server/views/modal/rename.html
> ensure to hide recursively rename checkbox when the page grant is 2

- src/server/service/import.js
> use SchemaTyppe.cast for importing mongoose model documents

- src/server/views/widget/page_tabs.html
> replace old class with new one and refactoring

- config/webpack.common.js
- src/client/styles/scss/theme/spring.scss
> add spring-light

- config/webpack.common.js
- src/client/styles/scss/theme/mono-blue.scss
apply same style both light/dark modes temporarily
> enable mono-blue-light theme

- config/webpack.common.js
- src/client/styles/scss/theme/future.scss
> apply future theme

- src/client/js/components/PageComment/Comment.jsx
- src/client/styles/scss/_comment_growi.scss
- src/client/styles/scss/_comment_kibela.scss
> made user picture visible

- bin/download-cdn-resources.js
- src/client/js/components/Admin/ImportData/GrowiArchive/ImportForm.jsx
- src/server/service/import.js
- src/server/service/search-delegator/elasticsearch.js
I feel like `completed` is better than `terminated` for these situations.
* terminate: `to bring to an end; put an end to` (https://www.dictionary.com/browse/terminate)
* complete: `to make perfect` (https://www.dictionary.com/browse/complete)
> Correct wording for end of the task

- src/client/js/components/Admin/Users/UserTable.jsx
- src/client/styles/scss/_admin.scss
> made the dropdown menu visible

- src/client/js/app.jsx
- src/server/views/layout/layout.html
- src/server/views/modal/create_page.html
リリースのために create modal の部分を一旦コメントアウトして無効にしました
> Support/comment out for release dev4.0.0

- src/client/styles/scss/_layout_kibela.scss
> Fix gap navbar and content

- src/server/views/widget/not_creatable_content.html
> change list to tabs

- src/client/styles/scss/_layout.scss
> change to show scrollbar when modal's showing

- src/client/styles/scss/_search.scss
- src/client/styles/scss/theme/_apply-colors-light.scss
> change the position to apply background-color

- src/client/styles/scss/_on-edit.scss
- src/server/views/widget/not_found_tabs.html
- src/server/views/widget/page_tabs.html
- src/server/views/widget/page_tabs_kibela.html
> visible range correction

- src/server/views/widget/user_page_content.html
> change to display icon only within sm breakpoint

- src/client/styles/scss/_override-bootstrap.scss
- src/lib/components/PagePathHierarchicalLink.jsx
> override text-break and set to PagePathHierarchicalLink

- src/client/js/components/PageEditor.jsx
- src/client/styles/scss/_layout.scss
- src/client/styles/scss/_on-edit.scss
- src/client/styles/scss/style-app.scss
- src/server/views/layout-growi/base/layout.html
- src/server/views/layout/layout.html
> fix editor flexbox

- src/server/views/layout-growi/widget/liker-and-seenusers.html
> fix access counter

- src/client/js/services/AppContainer.js
> BugFix: await to set state in AppContainer

- src/client/js/components/Admin/Customize/CustomizeScriptSetting.jsx
> [admin/customize] Fix styling of table

- package.json
- src/server/crowi/index.js
- yarn.lock
* connect-mongo
* mongoose
* mongoose-gridfs
* mongoose-paginate-v2
> upgrade libs

- src/client/js/components/SearchTypeahead.jsx
- src/client/styles/scss/_search.scss
> adjust for SearchTypeahead

- src/client/js/components/PageEditor/LinkEditModal.jsx
create link-preview by label input & link input
> Change link preview by label input

- CHANGES.md
- src/client/styles/scss/_wiki.scss
> fix text overflow

- src/client/js/components/InstallerForm.jsx
- src/client/styles/scss/_login.scss
- src/client/styles/scss/theme/_apply-colors-light.scss
> change radio button to dropdown

- resource/locales/en_US/admin/admin.json
- src/client/js/components/Admin/Users/UserInviteModal.jsx
> adjust i18n

- CHANGES.md
- src/client/js/components/PageManagement/ApiErrorMessage.jsx
- src/server/models/page.js
- src/server/routes/page.js
> fix #2523 delete pages which grant is GRANT_RESTRICTED

- src/client/js/components/Navbar/PersonalDropdown.jsx
- src/client/styles/scss/_me.scss
> add title style

- src/server/views/widget/page_list.html
> disappear user image in page list

- README.md
There are some outdated contents in README.md. This PR will update them.
> Update outdated description in README

- package.json
- yarn.lock
* refs #2631 
* Update markdown-it-drawio-viewer
> Fix #2631 can render blockdiag

- src/client/js/components/Hotkeys/HotkeysDetector.jsx
> invoke preventDefault only when stroke is completed

- src/client/js/components/Page/CopyDropdown.jsx
> Fix "Copy to clipboard" anchor link

- src/client/js/components/PageEditor/GridEditModal.jsx
GW-3279 gridEditModal レスポンシブ対応
> Gw3279 responsive for modal

- src/client/js/components/PageEditor/LinkEditModal.jsx
- リンク先にパーマリンクが指定されているときもプレビューを取得できる
- リンク先にページパスが指定されていないときは画像のようなメッセージを表示（デザインはGW-3448で修正予定)
> enable to get preview with perma link

- src/client/js/components/Admin/ElasticsearchManagement/RebuildIndexControls.jsx
GW-3812 インデックスの Rebuild でスキップされた個数が表示される
> add a skip counts' message when importing completed

- resource/locales/en_US/translation.json
- resource/locales/ja_JP/translation.json
- resource/locales/zh_CN/translation.json
- src/client/js/components/PageAttachment.jsx
前回は発生しなかったバグです。
前回も再三確認はしたのですが、今回になって出現しました。
発生要件は、他のモーダルを表示してから、添付データをクリックすると発生します。
pageTimeline と同様に copmponentDidMount を変化させてレンダリングさせることにより、
解消しています。
> fix bug for pagination undhisplayed

- src/client/js/app.jsx
- src/client/js/components/Admin/Customize/CustomizeFunctionSetting.jsx
- src/client/js/components/MyBookmarkList/MyBookmarkList.jsx
- src/client/js/components/MyDraftList/MyDraftList.jsx
- src/client/js/components/PageAttachment.jsx
- src/client/js/components/PageHistory.jsx
- src/client/js/components/PageTimeline.jsx
- src/client/js/components/RecentCreated/RecentCreated.jsx
- src/client/js/services/AdminCustomizeContainer.js
- src/server/models/config.js
- src/server/routes/apiv3/customize-setting.js
- src/server/views/widget/user_page_content.html
これまでは、RecentlyCreated のみに pagination の Limit を設定できました。
しかし、機能の増加に伴い、他の場所でも pagination の Limit を設けるようになりました。
それに伴い、変数名を変更しました。
また変更にあたって、pagination の limit を 10 30 に設定して機能するかどうかを確認しています。
> Change name models config.js

- src/client/js/components/PageAccessoriesModal.jsx
- src/client/js/components/PageHistory.jsx
- src/client/js/components/PageList.jsx
- src/client/js/components/ShareLink/ShareLink.jsx
- src/client/styles/scss/_page_accessaries_modal.scss
> Adjust margin of modalbody

- src/client/js/app.jsx
- src/client/js/components/Page/DisplaySwitcher.jsx
- src/client/js/components/Page/ViewEditHackmd.jsx
- src/server/views/widget/page_content.html
本タスクのゴールは、三連ボタンによって view edit hackmd の画面に切り替わる操作の前段階である page_content.html ファイルの部分 react.js 化です。
実際に切り替えて表示するタスクは次のタスクで行います。
> Reactify page form in page content.html

- src/client/js/components/Admin/Security/ShareLinkSetting.jsx
there's a function didn't bind correctly so that so it prevents the pagination to work
> GW-4039 fixed the error in codes

- src/client/styles/scss/theme/default.scss
> Add theree-standed-button of default-dark color.

- src/server/service/search-delegator/elasticsearch.js
> rewrite with node v12 code (for v4.1.x)

- src/client/js/app.jsx
- src/client/js/components/Navbar/GrowiSubNavigation.jsx
- src/client/js/components/Page/NotFoundAlert.jsx
- src/client/js/services/PageContainer.js
- src/server/views/layout-growi/forbidden.html
- src/server/views/widget/forbidden_content.html
- src/server/views/widget/not_creatable_content.html
- src/server/views/widget/page_content.html
コンポーネントで表示させるか否かを判断させました。
forbidden page において「ページを作成しますか？」を非表示にしました。
実装前
実装後
#edit のときも一応確認済みです。
また変数名を変更しています。(isCreatable  => isNotCreatable)
> delete "create page " in forbidden page

- src/client/js/components/Admin/MarkdownSetting/LineBreakForm.jsx
2 different options looks same by this wrong message ID.
> Fix message IDs

- src/server/routes/apiv3/users.js
> add loginRequiredStrictry

- src/server/routes/apiv3/users.js
GC-6859 #6 user info を 4.1.xで修正
自分による動作確認も終了しました。
> add authentication for user info

- src/client/styles/scss/_attachments.scss
- src/client/styles/scss/_page_list.scss
> set vertical-align to picture of list

- src/client/js/app.jsx
- src/client/js/components/Page/NotFoundAlert.jsx
- src/client/js/services/PageContainer.js
> hidden notFoundAlert in trash

- src/client/styles/scss/_attachments.scss
- src/server/views/widget/page_attachments.html
> fix to display old user image icon in footer

- src/client/js/components/PageContentFooter.jsx
p 要素の中に div 要素が入る可能性があるような書き方をしていたところを怒られていたので修正しました
> warning about AuthorInfo

- src/client/styles/scss/_user_growi.scss
- src/client/styles/scss/style-app.scss
- src/server/views/layout-growi/user_page.html
> Fix layout in case of long toc in user page

- resource/locales/en_US/translation.json
- resource/locales/ja_JP/translation.json
- resource/locales/zh_CN/translation.json
- src/client/js/components/Me/ApiSettings.jsx
API Tokenの更新時に誤ったメッセージが表示されていたのを修正しました
修正前
修正後
> Fixed APIToken's update message.

- src/client/js/components/InstallerForm.jsx
> fix lang selected installer form is not set as default lang

- src/client/js/components/Admin/Customize/ThemeColorBox.jsx
- src/client/styles/scss/_admin.scss
> add _admin.scss webkit

- resource/locales/en_US/admin/admin.json
- resource/locales/ja_JP/admin/admin.json
- resource/locales/zh_CN/admin/admin.json
attachment が抜けていたので追加しています。
修正前
修正後
日本語
英語 中国語
> add attachment

- src/client/js/components/PageAttachment.jsx
- src/client/js/components/PageList.jsx
- src/client/js/components/PaginationWrapper.jsx
- src/client/js/services/PageHistoryContainer.js
- src/server/routes/apiv3/attachment.js
null についての精査
https://wsgrowi.slack.com/archives/CL5SMPHB2/p1605489876415100
> Fix/4302 4475 fix attachment list and refactor PaginationWrapper

- src/client/styles/scss/_wiki.scss
> adjust line-height

- src/client/js/components/Admin/Security/ShareLinkSetting.jsx
- src/client/js/components/Admin/UserGroup/UserGroupPage.jsx
- src/client/js/components/Admin/UserGroupDetail/UserGroupPageList.jsx
- src/client/js/components/Admin/UserManagement.jsx
> adjust align center

- src/client/js/components/BookmarkButton.jsx
- src/client/js/components/LikeButton.jsx
https://github.com/weseek/growi/pull/3088
ここのタスクでの変更が新しいバージョンに対応できていなかったよう
> 4302-4552-adjust-bookmark-and-like-buttons

- src/__mocks__/express.js
- src/server/routes/apiv3/users.js
- src/test/routes/users.test.js
- Add test
- Add manual mock for res.apiv3
- Fix selectedStatusList validater
> refs GW-4457 Add test routes apiv3 healthcheck

- src/client/js/components/Navbar/GrowiNavbarBottom.jsx
GrowiNavbarBottom のボタンを修正しています。
修正前
修正後
> fix layout

- src/server/routes/apiv3/attachment.js
- src/test/routes/attachment.test.js
> refs GW-4494 routes/apiv3/attachment.js

- src/migrations/20200903080025-remove-timeline-type.js.js
migration file に誤りがあったので修正しました。
migrate up / down で適切に想定している値が機能するか確認しています。
https://youtrack.weseek.co.jp/issue/GW-4582
> fix migrationfile

- src/server/service/import.js
4.1.x 系で適用させた vul-#5 を master にも適用させています。
> add vul #5

- src/server/routes/admin.js
- src/server/routes/apiv3/export.js
- src/server/routes/index.js
- src/server/service/import.js
詳細情報はwiki にあります。
そちらをご参照ください。
[詳細](https://growi.weseek.co.jp/Projects/GROWI/GROWI/%E8%84%86%E5%BC%B1%E6%80%A7%E5%AF%BE%E5%BF%9C/@stpr%E3%81%95%E3%82%93%E3%81%8B%E3%82%89%E3%81%AE%E8%84%86%E5%BC%B1%E6%80%A7%E5%A0%B1%E5%91%8A/02#edit)
> add validation

- src/server/routes/admin.js
- src/server/routes/apiv3/export.js
- src/server/routes/index.js
- src/server/service/import.js
v4.2 系で行った修正を v4.1.x 系にも適用させています。
動作確認
**server 側**
**攻撃側**
> Fix/vul #2 4.1.x

- src/server/routes/admin.js
- src/server/routes/apiv3/export.js
- src/server/service/import.js
> fix regex reference

- src/test/util/project-dir-utils.test.js
- src/utils/project-dir-utils.ts
実装
https://github.com/weseek/growi/blob/dev/5.0.x/src/utils/project-dir-utils.ts
> refs GW-4652 utils/project-dir-utils.ts

- src/server/crowi/index.js
- src/server/routes/page.js
4.1.x 系においても presentation mode で xss 対策を施しました。
> Fix vul 4.1.x of presentation mode

- src/server/routes/apiv3/users.js
- [外部仕様ページのURLをコメントとして残す](https://estoc.weseek.co.jp/redmine/issues/59889)
> added an URL about the user API specification

- src/server/models/page.js
- src/server/models/user-group.js
- src/server/routes/apiv3/pages.js
- src/server/routes/page.js
- src/server/service/page.js
[概要]
- delete アクションのリファクタを実施しました。
- page.js model での //TODO を実行しています。
[確認したこと]
- ページ の消去
- 再起的に消去
- 完全に消去
- 再起的に完全に消去
- Group を削除する際のpageの挙動について
- ページを消去する
以上が正常に動きました。 
このほかに確認すべき挙動がありましたら、助言いただけると幸いです。
> Imprv/refactoring page.js delete action

- src/migrations/20200827045151-remove-layout-setting.js
- src/server/routes/page.js
https://github.com/weseek/growi/commit/c5c1f86c3fad690cf346c995354216b131345d88
> revert changes of c5c1f86c3fad690cf346c995354216b131345d88

- src/client/styles/scss/_on-edit.scss
> change scroll position

- src/server/service/file-uploader/aws.js
aws.js において、attachment ファイルを複数削除する処理に deleteObjects をしようしました。
> multiple delete attachments in aws.js

- config/env.dev.js
- src/server/service/config-loader.js
GROWI_CLOUD_URLという環境変数をGROWIで使えるようにしました。
> feat/add environment viriable #4975

- src/server/service/bolt.js
> add echo command

- src/client/js/components/PageEditor/DrawioModal.jsx
- src/client/js/util/locale-utils.js
> add locale-utils for client

- resource/locales/en_US/translation.json
- resource/locales/ja_JP/translation.json
- resource/locales/zh_CN/translation.json
- src/client/js/admin.jsx
- src/client/js/components/Admin/Common/AdminNavigation.jsx
- src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
- src/server/routes/admin.js
- src/server/routes/index.js
- src/server/views/admin/slack-integration.html
> Slack Integration button added

- src/client/js/components/Admin/Common/Accordion.jsx
- src/client/js/components/Admin/SlackIntegration/BotSettingsAccordion.jsx
- src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> 5613 Make Accordion Component

- src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
Slack設定画面のAccess Tokenセクションをフロントから削除しました。
> Removed Access Token Section

- src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
Changed "Detailed Explanation" mouseover cursor to pointer
> Chaged to mouse pointer

- src/client/js/components/Admin/SlackIntegration/CustomBotWithProxyIntegrationCard.jsx
- src/client/js/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
- src/client/styles/scss/_admin.scss
Custom bot without proxy の連携図をコンポーネント化しました。
> with proxy integration diagram component

- src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
- src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
スラック連携の概念図において、Integration Successfulという文言が機械のデフォルトのフォントになってしまうのを、修正しました。
> 5820 Fix Serif font

- resource/locales/en_US/admin/admin.json
- resource/locales/ja_JP/admin/admin.json
- resource/locales/zh_CN/admin/admin.json
- src/client/js/components/Admin/SlackIntegration/CustomBotWithProxySettingsAccordion.jsx
- src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
> 5827 with proxy accordion 1 2

- src/server/models/slack-app-integration.js
[GW-5859](https://github.com/weseek/growi/pull/3722#discussion_r631667973) で指摘頂いた問題を修正しました。
> fix generateAccessToken func

- src/server/routes/apiv3/slack-integration-settings.js
どこからも参照されていないschemaの削除とBotTypeのdescriptionの修正
> fix swagger

- src/client/js/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
- src/client/js/components/Admin/SlackIntegration/OfficialBotSettings.jsx
official bot の管理画面に proxyURL の input を作成しました。
> proxy url input form

- packages/slackbot-proxy/src/services/RegisterService.ts
GW-6010 Order 作成時に、update を行わず insert のみを行う
> removing updating process

- src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
オールリセットを withoutProxy の場合も表示させています。
> unified all reset

- resource/locales/en_US/admin/admin.json
- resource/locales/ja_JP/admin/admin.json
- resource/locales/zh_CN/admin/admin.json
- src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
- src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
[GW-6050 デザインチェック第一弾による修正](https://youtrack.weseek.co.jp/agiles/84-39/current?issue=GW-6050) を行いました。
> design fix

- packages/slackbot-proxy/src/controllers/growi-to-slack.ts
- packages/slackbot-proxy/src/entities/order.ts
GW-5555 orderがisExpiredの場合、relationに昇格できないようにする
isExpiredの実装をしました
> implement isExpired

- resource/locales/en_US/admin/admin.json
- resource/locales/ja_JP/admin/admin.json
- resource/locales/zh_CN/admin/admin.json
- src/client/js/components/Admin/SlackIntegration/DeleteSlackBotSettingsModal.jsx
- src/client/js/components/Admin/SlackIntegration/OfficialBotSettings.jsx
文言の修正を行いました。
- officialBotのアコーディオン上
- Official bot Settings -> 連携手順
- 全ての Bot の設定を削除するモーダル 
- リセット -> Botの全ての設定がリセットされます。< br >よろしいですか?
> fix wording

- src/server/routes/apiv3/slack-integration-settings.js
GW-6161 put /regenerate-tokens に swaggerを追加する
> add swagger

- src/client/js/components/Admin/SlackIntegration/WithProxyAccordions.jsx
withProxy と official のアコーディオン（③GROWI Official Bot Proxy サービスへの登録）の 1 と 2 の間にスペースを追加しました。
> add margin

- src/server/views/widget/page_content.html
> If "deletedAt" is undefined, set "data-page-deleted-at" to an empty string.

- src/server/routes/apiv3/share-links.js
https://estoc.weseek.co.jp/redmine/issues/70547
> share link url

- src/server/routes/apiv3/share-links.js
https://estoc.weseek.co.jp/redmine/issues/70554
> add validator

- src/client/js/util/PreProcessor/XssFilter.js
- src/server/util/middlewares.js
- src/server/views/widget/page_content.html
I'm sending the PR for the unpatched bug I reported last year.
This should fix some of XSS-related issues caused by both client-side and server-side.
I set the threshold to 50 so that it doesn't loop infinitely.
> Security: Improving XSS filter

- src/client/styles/scss/theme/hufflepuff.scss
sidebar の resize button ，new pageモーダル ボタン，view⇆edit ボタン　の色調整
> change btn color

- src/client/styles/scss/theme/hufflepuff.scss
New page modal の下のボタンの色変更，
modalのheader色を調整するためにprimaryを変更，（ダーク）
primary基準で調整してたボタンの値も表示色が同じになるように変更
> modal header color

- src/client/styles/scss/theme/hufflepuff.scss
> line color

- src/client/styles/scss/theme/hufflepuff.scss
> list color

- src/client/styles/scss/theme/hufflepuff.scss
timelineのcardのheader色，
その他cardと名のつく部分の色調整
> card color

- src/server/models/user.js
[255行目](https://github.com/weseek/growi/blob/2b71a702a0f4c050d4c6a5432c1b6deacf122f4c/src/server/models/user.js#L255) に全く同じ function があったため削除しました。
> remove unnecessary func

- src/client/js/components/Sidebar/RecentChanges.jsx
閲覧数を RecentChanges に表示
（SeenUserInfo.jsxに倣って）
> add number of view

- packages/slackbot-proxy/package.json
- packages/slackbot-proxy/src/Server.ts
- packages/slackbot-proxy/src/views/top.ejs
- yarn.lock
- Bootstrap を導入しています。
- LP ページは暫定的なものです。
- official
- custom
> create lp and add settings

- packages/slack/src/index.ts
- packages/slack/src/utils/block-kit-builder.ts
- src/server/routes/apiv3/slack-integration.js
- src/server/service/slack-command-handler/create.js
- src/server/service/slack-command-handler/help.js
- src/server/service/slack-command-handler/search.js
- src/server/service/slack-command-handler/slack-command-handler.js
- src/server/service/slackbot.js
/commands エンドポイントのハンドラのみリファクタしました。
今回はとりあえず応急処置ぐらいにして、togetterコマンド実装し終わったらがっつりリファクタさせてください。
一応正常に動くことは確認済みです。
> Refactored

- package.json
> add build:prod

- src/server/models/one-time-url.js
- src/server/models/password-reset-order.js
> created one-time-url model

- resource/locales/en_US/admin/admin.json
- resource/locales/ja_JP/admin/admin.json
- resource/locales/zh_CN/admin/admin.json
- src/client/js/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
- src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
- src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
- src/client/js/components/Admin/SlackIntegration/OfficialBotSettings.jsx
- src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
- src/client/js/components/Admin/SlackIntegration/WithProxyAccordions.jsx
> Feat/gw 5614 add a link to the  docs

- src/server/routes/apiv3/pages.js
> inserting accessTokenParser

- src/server/routes/forgot-password.js
> apply i18n

- src/pages/admin/[[...path]].tsx
>  feat/6891 allow UserManegement to be displayed 

- src/client/js/components/Sidebar/RecentChanges.jsx
- src/server/models/page.js
- src/server/routes/apiv3/pages.js
> display tags

- resource/locales/en_US/translation.json
- resource/locales/ja_JP/translation.json
- resource/locales/zh_CN/translation.json
- src/client/js/components/PasswordResetRequestForm.jsx
- src/client/js/nologin.jsx
- src/server/routes/forgot-password.js
- src/server/routes/index.js
GW-6828 ユーザーが入力したemailアドレスを元に、メールを送信することができる
https://user-images.githubusercontent.com/59536731/127339067-3d4fc70e-0994-4a95-8871-dd206b833354.mov
> Imprv/gw 6268 send an email with inputValue

- src/server/models/password-reset-order.js
- src/server/routes/forgot-password.js
- src/server/routes/index.js
GW-6850 [back] パスワード再設定フォームのリンクにワンタイムトークンを利用する
> be able to access password reset execution form with one-time-URL

- src/client/js/components/Page/DisplaySwitcher.jsx
- src/client/js/components/PageEditor/EditorNavbarBottom.jsx
EditorSubNavbar を表示させています。
本コンポーネントには、NavigationContainer, EditorContainer が使用されています。
Container の改修は後続タスクにします。
また、本コンポーネントには、
- SlackNotification 
- SavePageControls
- OptionsSelector 
以上のコンポーネントが内包されており、これらも NavigationContainer と EditorContaine を使用しております。
一旦コメントアウトして、 後続タスクで改修していきます。
後続タスクにする理由は、タスクが重く 8/3 までに終わらないためです。
> dymamic import and fix

- src/client/js/components/Sidebar/RecentChanges.jsx
- src/client/styles/scss/_recent-changes.scss
- src/client/styles/scss/style-app.scss
- src/client/styles/scss/theme/mixins/_list-group.scss
左寄せ，サイズ，余白の調整
タグの折り返しは後続タスクでやる予定です。
> position views comments tags

- src/client/styles/scss/theme/_apply-colors.scss
- src/client/styles/scss/theme/mixins/_list-group.scss
> change background color

- src/client/js/components/Sidebar/RecentChanges.jsx
> adjust margins

- packages/slackbot-proxy/package.json
デプロイ作業のため slack-bot proxy の package.json にある version を変更しています
> fix version

- packages/slack/src/index.ts
- packages/slack/src/utils/check-communicable.ts
- packages/slack/src/utils/required-scopes.ts
- packages/slackbot-proxy/src/controllers/top.ts
GW-7111 PR & Merge(7105)のFBを反映
- featブランチにマージするためにPRを再度作成
> improved required scopes

- packages/app/src/components/Navbar/SubNavButtons.jsx
- packages/app/src/components/WatchButton.jsx
- packages/app/src/styles/_subnav.scss
- packages/app/src/styles/atoms/_buttons.scss
ページ毎に通知の可否を選択できる watcher をボタンを作成しました。
見た目のみで、isWatching という state を仮に作り動作させています。
- Watching時
- Watchingしていない時
> create watch button

- CHANGES.md
- src/client/js/components/Fab.jsx
- src/server/views/layout-growi/base/layout.html
> Backports: Layout is broken when editing users page 

- packages/slackbot-proxy/package.json
> version up

- packages/app/src/client/services/EditorContainer.js
- packages/app/src/components/PageEditor/OptionsSelector.jsx
GW-7262 isTextLintEnabledをfetchさせる
> fetch 'isTexlintEnabled' from DB

- packages/app/src/server/service/slack-command-handler/togetter.js
togetter の表示を oldest <-> newest の対比に修正しました
> Latest -> Newest

- packages/app/src/server/routes/apiv3/personal-setting.js
- Schemaをcrowi.modelから呼び出していたのを、正しいファイルから呼び出すように修正
- Getリクエストから不要なMiddlewareを削除
> GW-7315 UserSettingsがDBから情報を取ってこれてないBugを修正

- packages/app/src/components/Admin/SlackIntegration/ManageCommandsProcess.jsx
- packages/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
- packages/app/src/server/routes/apiv3/slack-integration-settings.js
コントローラーが機能するようになったので、フロントの SlackIntegration 画面にて Permission 情報が即時反映されるようにしています。
https://user-images.githubusercontent.com/57100766/132279516-3e8d843a-fa34-4811-9dbb-c910bc45783d.mov
> Imprv: get infro of permission status

- packages/app/src/components/Sidebar/RecentChanges.jsx
完全に共通である 閲覧者数, コメント数, 更新日時 を共通化しました。
> Commonization of PageItemLower

- packages/slackbot-proxy/src/controllers/slack.ts
- packages/slackbot-proxy/src/services/RelationsService.ts
slack.ts controler 層のリファクタを行いました。
肥大化していた箇所は relationService に委譲しています。
> Imprv:refactor

- packages/app/src/components/Me/EditorSettings.tsx
- packages/app/src/server/routes/apiv3/personal-setting.js
- GW-7347 ON/OFFのRequest Objを新しいSchemaに対応させる
- GW-7361 ON/OFFをするとDBのルールが消えてしまうのを修正
> personal-setting.js, EditorSettings.tsx

- packages/app/src/server/routes/apiv3/personal-setting.js
> GW-7365 ミドルウェア修正

- packages/app/src/components/Me/EditorSettings.tsx
GW-7405 クリーンインストール時のエラー修正
- DBが空の場合の処理と、そうでない場合の処理が逆転していたのを修正しました。
> fixed undefined error

- packages/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
task : GW-7352 WithProxyAccordions の CopyToClipboard
https://youtrack.weseek.co.jp/issue/GW-7352
before afterの動画です。
https://user-images.githubusercontent.com/60797707/133204634-e28ff37c-4942-4f0c-8d00-a4731cbe61fa.mp4
https://user-images.githubusercontent.com/60797707/133204642-75824e9e-4a6b-49e0-bb49-518a8dd23308.mp4
> imprv: Copy button in WithProxyAccordions

- packages/app/src/migrations/20210913153942-migrate-slack-app-integration-schema.js
SlackAppIntegration の migration file を修正しました。
1. オブジェクトのコピーを直した
2. supportedCommandsFor... カラムがないバージョンからのマイグレーションにも対応した
2. に関しては想定したスキーマで動作確認済みです。
> fix: migration

- packages/slack/src/index.ts
- packages/slack/src/interfaces/growi-command-processor.ts
- packages/slack/src/interfaces/growi-interaction-processor.ts
- packages/slack/src/utils/payload-interaction-id-helpers.ts
- packages/slackbot-proxy/src/controllers/slack.ts
- packages/slackbot-proxy/src/services/RegisterService.ts
- packages/slackbot-proxy/src/services/RelationsService.ts
- packages/slackbot-proxy/src/services/SelectGrowiService.ts
- packages/slackbot-proxy/src/services/UnregisterService.ts
GW-7495 GrowiCommandProcessor, GrowiInteractionProcessor 実装 & 改修
を実装しました。
unregister, register, search で一応動作確認済みです。
> imprv: commands interactions processors

- packages/app/src/styles/_override-codemirror.scss
ref: https://github.com/codemirror/CodeMirror/issues/4089
> fix: IME suggestion list obscures inputted text

- packages/app/resource/locales/en_US/admin/admin.json
- packages/app/resource/locales/ja_JP/admin/admin.json
- packages/app/resource/locales/zh_CN/admin/admin.json
- packages/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
- packages/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
public チャンネルで連携テストを行うような文言を追加しました。
> feat: add word

- packages/app/src/server/routes/apiv3/users.js
> fix: Recent Created of home is empty

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/SearchPage/IncludeSpecificPathButton.jsx
- packages/app/src/components/SearchPage/SearchResult.jsx
xd : https://xd.adobe.com/view/cd3cb2f8-625d-4a6b-b6e4-917f75c675c5-986f/screen/dad28d9f-d727-45e4-9853-bdcb9c083914/specs/
いったんcomponenn作成までです。
試しに写真のsearchResult内に設定した時の画像です。
> feat: Include setting button

- packages/app/src/server/service/slack-command-handler/search.js
- packages/app/src/server/service/slack-integration.ts
- packages/slack/src/utils/response-url.ts
- Set page limit to 7
- Add prev button
- Add a link to result page
- Replace original when moving to prev/next page
> imprv: Slackbot search

- packages/app/src/server/crowi/index.js
- packages/app/src/server/service/activity.ts
- packages/app/src/server/service/comment.ts
- packages/app/src/server/service/page.js
- packages/app/src/server/util/activityDefine.ts
https://estoc.weseek.co.jp/redmine/issues/78064
updatePage用のアクティビティを作成できる
> create activity when page updated

- packages/app/src/server/service/activity.ts
- packages/app/src/server/service/comment.ts
- [Comment ServiceでActivityと同時にInAppNotificationを作成できるようにする](https://estoc.weseek.co.jp/redmine/issues/78181)
> Imprv/#78067 create inAppNotification in commentService

- packages/app/src/server/service/activity.ts
- packages/app/src/server/service/comment.ts
- packages/app/src/server/service/page.js
- [PageServiceでActivityと同時にInAppNotifiationの作成をできるようにする(78181の後)](https://estoc.weseek.co.jp/redmine/issues/78176)
※ **https://github.com/weseek/growi/pull/4429 がマージされていたら、マージ先を`feat/notification`に変更お願いします。**
> Imprv/#78176 create inAppNotification in page service

- packages/app/src/migrations/20210921173042-add-is-trashed-field.js
- packages/app/src/server/models/page-tag-relation.js
- packages/app/src/server/service/page.js
/tags にて、page がゴミ箱に移動した際に tag のカウント数をカウントしないように変更しました。
> imprv: fix tag count problem

- packages/app/src/server/service/slack-command-handler/keep.js
initial value を変えた
- oldest datetime を現在時刻の1時間前に
- page path を適当に
> imprv: togetterMessageBlocks

- packages/app/src/client/services/PageContainer.js
- packages/app/src/server/routes/apiv3/page.js
fix #4565
- `/_api/v3/page/info`
- `/_api/v3/page/export/:pageId`
- `/_api/v3/page/exist-paths`
> fix: /pages/info API is broken

- packages/app/src/components/TagsList.jsx
- packages/app/src/server/views/tags.html
https://github.com/weseek/growi/pull/4590
> feat: upgrade tags page

- packages/app/src/server/routes/page.js
- packages/app/src/server/views/layout-growi/select-go-to-page.html
Redmine: https://estoc.weseek.co.jp/redmine/issues/80352
ただただハリボテを作りました
query params に関しては、ユーザーの思うページと遷移先のページが違う可能性があるのでこの場合は redirectFrom のみを renderVars に渡すようにしました
> feat: Select from same path pages

- packages/app/src/components/SearchPage/DeleteSelectedPageGroup.tsx
- packages/app/src/components/SearchPage/SearchResultListItem.tsx
- packages/app/src/styles/_search.scss
checkbox をXDのようになるべく左に寄せ、縦に見たときも checkboxが一列になるように修正
実装
XD
> feat(search-result): 80324 80529 adjust checkbox position

- packages/app/src/components/SearchPage/DeleteSelectedPageGroup.tsx
> 80534 fix tentative delete-all-button design

- packages/app/src/migrations/20210921173042-add-is-trashed-field.js
https://estoc.weseek.co.jp/redmine/issues/81191
マイグレーションファイルの ` mongoose.connect(getMongoUri(), mongoOptions);` を修正しました。
> fix: modify migration file

- packages/app/package.json
- yarn.lock
https://github.com/Automattic/mongoose/issues/10774
> support: Bump mpath with mongoose

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemNode.ts
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- packages/app/src/interfaces/page-listing-results.ts
- packages/app/src/interfaces/page.ts
- packages/app/src/server/routes/apiv3/page-listing.ts
- packages/app/src/stores/page-listing.tsx
Redmine: https://estoc.weseek.co.jp/redmine/issues/80788
各アイテムの children を読み込んで表示できるようにしました。
- SWR ではなく直で apiv3Get を使いました
- Item コンポーネントのメモ化は必要ないので消しました
> feat: Pt item get children

- packages/app/src/client/app.jsx
- packages/app/src/client/services/ContextExtractor.tsx
- packages/app/src/components/PageContentFooter.jsx
- packages/app/src/server/views/widget/page_content.html
- packages/app/src/stores/context.tsx
- packages/app/src/stores/use-static-swr.tsx
- packages/app/src/utils/swr-utils.ts
Redmine: https://redmine.weseek.co.jp/issues/81414, https://redmine.weseek.co.jp/issues/81432
PageContainer の DOM から取得している context を全て static swr 化しました。他にも getter などありますが、PT のブロックは解消できたので一旦ここまでにします
- useStaticSWR を移植してきました
- PT の方と全く同じ実装
> imprv: Use swr to extract context from DOM

- packages/app/package.json
- yarn.lock
- Downgrade passport version to 0.4.0
- Fix issue [https://github.com/weseek/growi/issues/4667](url)
> fix: cannot edit HackMD

- packages/app/src/components/FormattedDistanceDate.jsx
- packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
[#81491](https://redmine.weseek.co.jp/issues/81491) re: 時間表記の改善
> Imprv/81491 time notation 

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/SearchPage/SearchPageLayout.tsx
- packages/app/src/styles/_search.scss
[#81403](https://redmine.weseek.co.jp/issues/81403)
セレクトボックスの仮表示
> 81403 add tentative selectbox to search control

- packages/app/src/components/Navbar/PersonalDropdown.jsx
- packages/app/src/interfaces/user-ui-settings.ts
- packages/app/src/server/models/user-ui-settings.ts
- packages/app/src/server/routes/apiv3/user-ui-settings.ts
- packages/app/src/stores/ui.tsx
Redmine: https://redmine.weseek.co.jp/issues/81608
Drawer mode に関連する UI 設定を DB とシンクさせるようにしました。
- 見た目と動作を正常にする
- レンダリングの最適化確認
> [After #4670] feat: Sync UI settings with DB

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- packages/app/src/styles/_page-tree.scss
- packages/app/src/styles/style-app.scss
Redmine: https://redmine.weseek.co.jp/issues/80792
三角ボタンを isOpen に応じて回転できるようにしました
一旦枠組みだけで、細かなスタイルのブラッシュアップはどこかでまとめて行いたいと思います
https://user-images.githubusercontent.com/58432773/142163987-37e48b4c-f0ed-406c-9c5d-dba648eecf8d.mov
> feat: Impl triangle button

- packages/app/src/client/app.jsx
- packages/app/src/server/views/layout-growi/base/layout.html
Redmine: https://redmine.weseek.co.jp/issues/81887
Context extractor をトップレベルに持ってきました
> imprv: Moved context extractor to root

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- packages/app/src/styles/_page-tree.scss
- packages/app/src/styles/_sidebar.scss
Redmine: https://redmine.weseek.co.jp/issues/81904
Private legacy pages のリンクを常に下に配置するようにしました
> feat: Put private page migration link bottom

- packages/app/src/interfaces/named-query.ts
- packages/app/src/server/models/named-query.ts
Redmine: https://redmine.weseek.co.jp/issues/81970
NamedQuery モデルを実装しました
aliasOf または resolverName が null にならないようにバリデーションをかけました
> feat: Implement named query model

- packages/app/src/components/TagsList.jsx
- packages/app/src/server/models/page-tag-relation.js
- packages/app/src/server/routes/tag.js
https://redmine.weseek.co.jp/issues/81596
https://redmine.weseek.co.jp/issues/81594
tags.list へのアクセスコストを仕様検討の wiki に基づいて、削減しました。
- 使用検討 wiki url
https://dev.growi.org/%E8%B3%87%E6%96%99/%E5%86%85%E9%83%A8%E4%BB%95%E6%A7%98/%E3%82%BF%E3%82%B0%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E4%BB%95%E6%A7%98
現状の /tags ページでも発生しているbug fix
> Imprv: improve performance about tag page

- packages/app/src/server/views/tags.html
- tags ページに出現していたバグを修正しました
ページ下部分のエラーが消えました。
動作確認後、 master へマージ
> fix: fix bug in tags page

- packages/app/src/components/SearchPage.jsx
[81922](https://redmine.weseek.co.jp/issues/81922)
> 81922 add default value

- packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
- packages/app/src/server/routes/apiv3/bookmarks.js
- packages/app/src/server/service/page.js
- packages/app/src/server/util/activityDefine.ts
- [81861](https://redmine.weseek.co.jp/issues/81861) ブックマークしたときにイベントを受け取れるようにする
- [81860](https://redmine.weseek.co.jp/issues/81860) ブックマークしたときに Activityドキュメント, Notificationドキュメントを作成し、socket.Io を通じてフロント側で通知を受け取ることができる
> feat: 81861 81860 create bookmark event

- packages/app/src/server/models/activity.ts
[#82298](https://redmine.weseek.co.jp/issues/82298) 修正
サブスクライブしていないページに対してアクションが行われた際にページ作成者に対して通知が行われてしまう問題を修正しました
> fix: 82298 notification target users

- packages/app/src/interfaces/page.ts
- packages/app/src/server/crowi/index.js
- packages/app/src/server/interfaces/search.ts
- packages/app/src/server/middlewares/auto-reconnect-to-search.js
- packages/app/src/server/models/index.js
- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/service/search-delegator/private-legacy-pages.ts
- packages/app/src/server/service/search.ts
- packages/app/src/test/integration/service/search/search-service.test.js
Redmine: https://redmine.weseek.co.jp/issues/82098
- Private legacy pages 用 delegator
- SearchService の delegator の初期化処理
- SearchService のテストをリファクタ & 追加
> feat: Impl custom delegator and initialization

- packages/app/src/migrations/20211129125654-initialize-private-legacy-pages-named-query.js
Redmine: https://redmine.weseek.co.jp/issues/82305
Private legacy pages のための NamedQuery ドキュメントを insert するマイグレーションファイルを実装しました
> feat: Migrate initial named queries

- packages/app/src/components/SearchPage.jsx
- packages/app/src/components/SearchPage/SearchPageLayout.tsx
https://redmine.weseek.co.jp/issues/82578
ヒットした時
0件ヒットの時（XDにはない見た目。デザインチェック中のため必要あれば後続タスクで対応予定。
> 82578 render showing page count infomation

- packages/app/src/client/services/PageContainer.js
- packages/app/src/components/Page.jsx
- packages/app/src/components/PageEditor.jsx
- packages/app/src/components/PageEditorByHackmd.jsx
- packages/app/src/components/SavePageControls.jsx
Redmine: https://redmine.weseek.co.jp/issues/82987
Update Create ボタンを正常化しました
一旦 class component をラップして editorMode を swr から取って流しました
> fix: Page create update button

- packages/app/src/components/Navbar/SubNavButtons.tsx
- packages/app/src/components/SearchTypeahead.jsx
Redmine: https://redmine.weseek.co.jp/issues/83014
navigationContainer を SubNavButtons から削除しました
検索バーの初期値を修正しました
> fix: Normalize default search bar input & like/bookmark button

- packages/app/src/components/PageDeleteModal.tsx
- packages/app/src/styles/_layout.scss
https://redmine.weseek.co.jp/issues/82894
> 82894 make path path scrollable

- packages/app/src/server/models/page.ts
- packages/app/src/server/routes/page.js
Redmine: https://redmine.weseek.co.jp/issues/83183
PageTree の表示に必要なページの取得に適切なフィルタがかかるようにしました
> fix: page listing restriction

- packages/app/src/components/SearchPage/SearchResultListItem.tsx
- packages/app/src/interfaces/search.ts
- packages/app/src/server/service/search-delegator/elasticsearch.ts
- packages/app/src/server/service/search.ts
Redmine: https://redmine.weseek.co.jp/issues/83087
検索結果にスニペットが表示できるように修正しました
ES 以外による結果の場合は Clamp 自体をレンダリングしないようにしました
> imprv: Search show snippet

- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/Sidebar/PageTree.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- packages/app/src/server/models/obsolete-page.js
Redmine: https://redmine.weseek.co.jp/issues/82579
ページツリーの３点リーダーからも delete modal を表示できるようにしました
> feat: Show delete modal

- packages/app/src/server/service/search.ts
https://redmine.weseek.co.jp/issues/83399
> refs #83399: fix display snnipet

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/zh_CN/translation.json
https://youtrack.weseek.co.jp/issue/GW-7584
> fix: translation user_id_is_not_available by delete '.' string character

- packages/app/src/client/services/PageContainer.js
- packages/app/src/components/PageEditor/ConflictDiffModal.tsx
- packages/app/src/components/PageEditor/Editor.jsx
https://redmine.weseek.co.jp/issues/83140
- conflict 解消後にページリロードをなくして、Ctrl + S と同じ挙動にしました 😂 
動作確認
> feat: prevent reload when resolve conflict

- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/SearchPage.jsx
- packages/app/src/components/SearchPage/SearchResultList.tsx
- packages/app/src/components/SearchPage/SearchResultListItem.tsx
- packages/app/src/components/Sidebar/PageTree.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- packages/app/src/server/routes/apiv3/page-listing.ts
- packages/app/src/stores/page-listing.tsx
Redmine: https://redmine.weseek.co.jp/issues/83407
ゲストユーザーもページツリーを表示できるようにしました
ゲストユーザーの時は Control の項目の一部を非表示にしました
> fix: Pt for guest user

- packages/app/src/styles/_override-bootstrap-variables.scss
- packages/app/src/styles/_search.scss
- packages/app/src/styles/_subnav.scss
- packages/app/src/styles/_tag.scss
https://docs.microsoft.com/ja-jp/windows/apps/design/signature-experiences/design-principles
> imprv: Respect Win 11 design

- packages/app/src/components/SearchPage.jsx
- packages/app/src/components/SearchPage/SearchResultList.tsx
- packages/app/src/components/SearchPage/SearchResultListItem.tsx
- packages/app/src/server/routes/apiv3/page-listing.ts
- packages/app/src/server/service/page.js
Redmine: https://redmine.weseek.co.jp/issues/81413
検索結果に必ずスニペットが表示されるようにしました(フロントのみ実装)
- バックエンド実装
> feat: Show snippet (frontend)

- packages/app/src/components/Sidebar.tsx
> fix: Set min-height to sidebar scroll target

- yarn.lock
https://youtrack.weseek.co.jp/issue/GW-7589
> imprv: fix and debug mixin-deep dependabot alert

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- [#83806](https://redmine.weseek.co.jp/issues/83806) + ボタン正常化
https://user-images.githubusercontent.com/59536731/146179218-4d0768c8-c7ca-496c-bd32-14b1fd523421.mov
> fix plus button bug

- packages/app/src/components/Sidebar/PageTree.tsx
Task :
https://redmine.weseek.co.jp/issues/83819
> Feat/#83819 pageTree loading

- packages/app/src/client/app.jsx
Redmine: https://redmine.weseek.co.jp/issues/83814
NotFoundAlert を表示できるように修正しました
> fix: Show not found alert

- packages/app/src/components/Navbar/GrowiNavbarBottom.jsx
https://redmine.weseek.co.jp/issues/83784
モバイル下部のボタンを押すと新規作成ボタンが出るようになりました。
> imprv: Open PageCreateModal on mobile when button is pressed

- packages/app/src/server/service/slack-command-handler/search.js
> fix: GROWI Bot search command after transplanting search service from dev/5.0.x

- packages/app/src/components/SearchPage/SortControl.tsx
Task : 
https://redmine.weseek.co.jp/issues/83851
xd: https://xd.adobe.com/view/cd3cb2f8-625d-4a6b-b6e4-917f75c675c5-986f/screen/9aa528ff-a75e-4e9a-adb9-b4b942647f29/
写真:
> 83851 sort design

- packages/app/src/styles/_page-tree.scss
[#84124](https://redmine.weseek.co.jp/issues/84124) 11レベル以上のものは、10と同じ階層にする
> apply hierarchy more than level 10

- packages/app/src/components/SearchPage/SearchResultListItem.tsx
- packages/app/src/stores/ui.tsx
https://redmine.weseek.co.jp/issues/84232
> 84232 change break point

- packages/app/src/stores/bookmark.ts
- packages/app/src/stores/page.tsx
Task : 
https://redmine.weseek.co.jp/issues/84109
やったこと：
page-infoのpage idがnullの時(存在しないpageにアクセスした時)
にswrでdata fetchingしないようにしました。
bookmarkの方もついでに直しました。
> 84109 conditional fetching

- yarn.lock
https://youtrack.weseek.co.jp/issue/GW-7624
- Rebuild packages axios v0.21.1
- axios v0.21.1 resolved by v0.21.4
> fix: dependabot alert axios

- packages/app/src/components/SearchPage/SearchResultContentSubNavigation.tsx
https://redmine.weseek.co.jp/issues/84399
before
after
> remove unnecessary code

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/Common/ClosableTextInput.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/styles/_page-tree.scss
- packages/app/src/styles/theme/_apply-colors-dark.scss
- packages/app/src/styles/theme/_apply-colors-light.scss
Redmine:  https://redmine.weseek.co.jp/issues/84198
子ページ数をダミーデータで表示させました
Light mode
Dark mode
XD
ついでにアラートメッセージも改善しました
> imprv: PageTree text input style & Show not implemented features

- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/Page/CopyDropdown.jsx
- packages/app/src/components/RevisionComparer/RevisionComparer.jsx
- packages/app/src/styles/_search.scss
- packages/app/src/styles/_sidebar.scss
https://redmine.weseek.co.jp/issues/84398
> show menu in front of right pane content

- packages/app/src/client/services/ContextExtractor.tsx
- packages/app/src/components/SearchPage/SearchControl.tsx
- packages/app/src/components/SearchPage/SearchPageLayout.tsx
- packages/app/src/components/SearchPage/SearchResultListItem.tsx
- packages/app/src/components/SearchPage/SortControl.tsx
- packages/app/src/styles/_search.scss
- packages/app/src/styles/theme/_apply-colors-dark.scss
- packages/app/src/styles/theme/_apply-colors-light.scss
- packages/app/src/styles/theme/_apply-colors.scss
https://redmine.weseek.co.jp/issues/84304
若干明るくなってます
before : after
#eff1f3 : #f8f9fa
<div style="display: flex;">
</div>
dark theme
> change color for light and dark theme

- packages/app/src/components/SearchPage.jsx
https://redmine.weseek.co.jp/issues/84449
> reset checkbox state

- packages/app/src/components/Navbar/GrowiSubNavigation.jsx
https://redmine.weseek.co.jp/issues/84473
> hide page pagemanagement btn

- packages/app/src/components/SearchPage/SortControl.tsx
- packages/app/src/styles/_search.scss
動作確認終了になったらdev5に僕がmergeします。
https://redmine.weseek.co.jp/issues/84446
min-width 160pxひつ要だったので12 rem（1 rem = 14 px)設定しました。
https://user-images.githubusercontent.com/60797707/147222213-330bf0ac-daec-459a-a653-dc7b8fd19116.mov
> 84446 set min width

- packages/app/.env.development
- packages/app/package.json
- packages/app/src/server/service/config-loader.ts
- packages/app/src/server/service/search-delegator/elasticsearch.ts
- yarn.lock
- change key for `host` to `node` for @elastic/elasticsearch Client initiation
- add ssl configuration on Client init
- change `httpAuth` to `auth` and it's parameter format
- make client.indices.exists() to destructuring variable assignment
- make stats() to destructuring variable assignment
- make getAlias() to destructuring variable assignment
- make .search() to destructuring variable assignment
- Investigated the search feature can only working while using old index
- Investigated indexing not working
- Compare @elastic/elasticsearch `index status` and `index meta` with elasticsearch.js
- Check and debug the client API result on elasticsearch.ts
- Research writing index data flow
- Bring back requestTimeout on client initiation
- Remove requestTimeout on bulkWrite index
> feat: update elasticsearch to @elastic/elasticsearch@6

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/Hotkeys/HotkeysManager.jsx
- packages/app/src/components/Hotkeys/Subscribers/FocusToGlobalSearch.jsx
- packages/app/src/components/Navbar/GlobalSearch.tsx
- packages/app/src/components/SearchForm.tsx
- packages/app/src/components/SearchTypeahead.tsx
- packages/app/src/server/views/modal/shortcuts.html
- packages/app/src/stores/ui.tsx
- packages/app/src/styles/_search.scss
> feat: Hotkey to focus to search

- packages/app/src/server/service/passport.ts
- Add method to check if OIDC issuer host reachable
- Call the method before OIDC issuer discovery
- Set CLOCK_TOLERANCE to 5 (seconds) to prevent error AssertionError [ERR_ASSERTION]: id_token issued in the future (OIDC auth)
> feat: update OIDC Reconnection

- packages/app/src/server/routes/apiv3/pages.js
[#84741](https://redmine.weseek.co.jp/issues/84741) ページが duplicate されたときに自動的にサブスクライブできる（親ページのみ）
> feat: Automatically subscribe when page is duplicated

- packages/app/src/server/service/passport.ts
https://youtrack.weseek.co.jp/issue/GW-7634
- Modify connection check
- Add method to initialize OIDCIssuer instance
- Implement OIDCIssuer initialize method to setupOidcStrategy
> feat: Implement retry OIDCIssuer discovery

- packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
- packages/app/src/styles/_navbar.scss
[#84747](https://redmine.weseek.co.jp/issues/84747) 通知ドロップダウンを開き、各通知をホバーしたときに指のカーソルが表示できる
> feat: 84747 add cursor

- README_JP.md
* Fix markdown format
* github -> GitHub
> Fix README_JP.md

- yarn.lock
https://youtrack.weseek.co.jp/issue/GW-7621
- Rebuild ssri packages
- ssri v6.0.1 resolved by v6.0.2
- ssri v8.0.0 resolved by v8.0.1
> support: dependabot alert ssri

- packages/app/src/components/BookmarkButton.tsx
- packages/app/src/interfaces/bookmarks.ts
- packages/app/src/stores/bookmarks.tsx
[#84997](https://redmine.weseek.co.jp/issues/84997) /bookmarks/info を SWR で取得する
> feat: 84997 Retrieve Bookmarks Info with SWR

- packages/app/src/client/services/PageContainer.js
PageContainer 内の使用されていない state を削除しました。
> imprv: Delete unused states

- packages/app/src/components/BookmarkButton.tsx
- packages/app/src/interfaces/bookmarks.ts
- packages/app/src/server/models/bookmark.js
- packages/app/src/server/routes/apiv3/bookmarks.js
- packages/app/src/stores/bookmarks.tsx
[#85058](https://redmine.weseek.co.jp/issues/85058) bookmarks/info を叩いた時に、bookmark を行ったユーザーIDの配列を返却できるようにする
> feat: 85058 Retrieve bookmarked users

- packages/app/src/interfaces/page.ts
- packages/app/src/server/models/page.ts
https://redmine.weseek.co.jp/issues/85201
> add descendantCount to PageModel schema

- packages/app/src/server/models/user-group.js
- packages/app/src/server/routes/apiv3/user-group.js
Redmine: https://redmine.weseek.co.jp/issues/85091
UserGroup の作成処理を実装しました
> imprv: User group create

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- [85037](https://redmine.weseek.co.jp/issues/85037) useDrop hook を使用して、dropした時にlogを出力できる
https://user-images.githubusercontent.com/59536731/148890039-34b442f7-7c7d-4cbe-b299-137854f53382.mov
このタスクではログに出力するのみです。ページの移動は後続タスクで着手します
> Imprv/85037 show log when  page item is dropped

- packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> fix: Built-in editor was broken

- packages/app/src/server/models/user.js
- packages/app/src/server/routes/page.js
- packages/app/src/server/service/page.js
- packages/app/src/server/util/swigFunctions.js
- packages/app/src/server/views/widget/page_content.html
> fix: /_api/v3/page is broken and dump 500 error "get-page-failed TypeError: user.canDeleteCompletely is not a function"

- packages/app/src/server/models/page.ts
- packages/app/src/server/service/page.js
https://redmine.weseek.co.jp/issues/86114
> add condition to match

- packages/app/src/server/service/page.js
https://redmine.weseek.co.jp/issues/85349
> Update dcount on public migration

- packages/app/src/server/service/search-delegator/elasticsearch-client-types.ts
- packages/app/src/server/service/search-delegator/elasticsearch-client.ts
- packages/app/src/server/service/search-delegator/elasticsearch.ts
https://youtrack.weseek.co.jp/issue/GW-7608
> Imprv: elasticsearch clean code

- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/models/page.ts
- packages/app/src/server/service/page-grant.ts
Redmine: https://redmine.weseek.co.jp/issues/86022
ページの更新に権限のバリデーションを追加しました
バリデーション処理でバグってたところも修正しました
> imprv: Update page validation

- packages/app/src/server/models/page.ts
- packages/app/src/server/service/page.js
- packages/core/src/utils/page-path-utils.ts
https://redmine.weseek.co.jp/issues/86054
> Implement update ancestor dcount

- packages/app/src/server/routes/apiv3/pages.js
- packages/app/src/server/service/page.js
- packages/app/src/server/service/page.ts
- packages/app/src/test/integration/service/page.test.js
Redmine: https://redmine.weseek.co.jp/issues/86331
- 他の PR でコード変更を見やすくするために先に PageService を TS 化しました
- 型は妥協してますが8割くらいのコードは後続で再実装されるのでその時にちゃんと型づけします
- page.test.js でコメントアウトされていたテストコードのコメントを外しました
- テストは2個後の後続( https://redmine.weseek.co.jp/issues/84911 )で修正されるのでスルーしてください
> imprv: Typescriptize page service

- packages/app/src/server/models/page.ts
- packages/app/src/server/service/page-grant.ts
- packages/app/src/server/util/compare-objectId.ts
- packages/app/src/test/integration/service/page-grant.test.js
Redmine: https://redmine.weseek.co.jp/issues/86023
PageGrantService のテストコードを追加しました
テスト書いてから気づいたバグも修正しました
> imprv: Add test code for PageGrantService

- packages/app/src/server/routes/apiv3/users.js
- packages/app/src/stores/middlewares/user.ts
- packages/app/src/stores/page.tsx
- packages/app/src/stores/user.tsx
[#85860](https://redmine.weseek.co.jp/issues/85860) /page/info が叩かれた時に、/users/update.imageUrlCache を叩く middleware を実装する
> feat: 85860 Create middleware

- packages/app/src/components/Common/ClosableTextInput.tsx
- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/Page/PageListItem.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
[#86348](https://redmine.weseek.co.jp/issues/86348) ページアイテムの三点リーダーdropdownから rename 操作ができる（見た目のみ）
https://user-images.githubusercontent.com/34241526/150494310-06c2e608-11c5-467c-90ef-3025dcba850f.mov
> feat: 86348 create rename operation

- yarn.lock
- Checked the websocket, all are working well
https://youtrack.weseek.co.jp/issue/GW-7673
> imprv: Update engine.io version to 5.2.1

- packages/app/package.json
- yarn.lock
- Research colors plugin
- Adjust package.json
- Check the plugin
https://youtrack.weseek.co.jp/issue/GW-7675
> imprv: colors

- packages/app/src/server/service/page.js
> fix: Internal server error occured when "Restrict complete deletion of pages" option's value is "Admin and author"

- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/service/page.ts
Redmine: https://redmine.weseek.co.jp/issues/86890
parent で再帰的に子孫を取得できるようにしました
ReadableStream という形は残したかったので、generator で実装しました
> feat: Custom readable stream using parent

- packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
- packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
- packages/app/src/interfaces/user-group-response.ts
- packages/app/src/stores/user-group.tsx
- [#85445](https://redmine.weseek.co.jp/issues/85445) UserGroupDetailPage の SWR化
- [#86808](https://redmine.weseek.co.jp/issues/86808) [Front] UserGroupPage.tsx の mutate の引数を改善する
> feat: 85445 SWRize user group detail page

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/styles/_page-tree.scss
https://redmine.weseek.co.jp/issues/87041
分かりやすくするために子孫数を表示してます（このPRではそのコードは含んでません。数値の実装→[5184](https://github.com/weseek/growi/pull/5184)）
> hide pagetree triangle

- .eslintrc.js
- packages/app/.eslintrc.js
- packages/app/package.json
- packages/app/src/components/Page/RevisionRenderer.jsx
- packages/codemirror-textlint/package.json
- packages/core/package.json
- packages/core/src/models/devided-page-path.js
- packages/plugin-attachment-refs/package.json
- packages/plugin-lsx/package.json
- packages/plugin-pukiwiki-like-linker/package.json
- packages/slack/package.json
- packages/slackbot-proxy/package.json
- packages/ui/package.json
- yarn.lock
add eslint plugin regex
add eslint rule for regex negative lookahead and positive lookahead.
> refs #84709: add test and lint

- packages/app/src/components/Sidebar/PageTree/Item.tsx
https://redmine.weseek.co.jp/issues/87010
> show descendantCount

- packages/app/src/server/models/page-redirect.ts
Redmine: https://redmine.weseek.co.jp/issues/86761
PageRedirect モデルを追加しました
> feat: Page redirect model

- packages/app/src/server/service/passport.ts
https://youtrack.weseek.co.jp/issue/GW-7681
- Add function to sanitize issuer host / URL to match accepted format
> fix: OIDC issuer host

- packages/app/src/components/Sidebar/PageTree/Item.tsx
[#87170](https://redmine.weseek.co.jp/issues/87170) PageItemControl で path が /user/hoge の場合削除ボタンを表示しないようにする
> fix: 87170 Do not show delete button if under user pages

- packages/app/src/server/service/passport.ts
> fix: Resolving OIDC issure host (for v4.5.x)

- packages/app/src/server/models/page-redirect.ts
- packages/app/src/server/service/page.ts
Redmine: https://redmine.weseek.co.jp/issues/86762
PageRedirect の作成削除を実装しました
- Page.create の際に存在したら削除するようにします
> feat: Page redirect crud

- packages/app/package.json
- packages/app/src/server/util/importer.js
- yarn.lock
https://youtrack.weseek.co.jp/issue/GW-7663
> support: Replace esa-nodejs with esa-node

- packages/app/src/server/crowi/index.js
- packages/app/src/server/service/page.ts
- packages/app/src/test/integration/service/page.test.js
- packages/app/src/test/integration/service/v5-migration.test.js
Redmine: https://redmine.weseek.co.jp/issues/87397
既にあったテストが全て通るように修正しました。redirectTo が PageRedirect モデルに置き換わるなどの変更によってテストが通らなくなっていたためです
- ２箇所妥協している箇所があるのでそこを以下のストーリーで改善します
- https://redmine.weseek.co.jp/issues/87537
> fix: Normalize v4 test

- packages/app/src/components/PageHistory/RevisionDiff.jsx
> fix: Revision diff

- packages/app/src/server/routes/apiv3/user-group.js
[#85191](https://redmine.weseek.co.jp/issues/85191) [API] UserGroup 検索
> feat: 85844 User Group Search API

- packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
- packages/app/src/interfaces/user-group-response.ts
- packages/app/src/server/routes/apiv3/user-group.js
- packages/app/src/stores/user-group.tsx
[#85844](https://redmine.weseek.co.jp/issues/85844) [Front & API] /user-groups/selectable-groups を SWR で取得する
> feat: 85844 Get selectable groups with SWR

- packages/app/src/client/base.jsx
- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/Sidebar/PageTree.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
[#87568](https://redmine.weseek.co.jp/issues/87568) [ItemsTree] SWRを使用してModalを表示させる
> feat: 87568 Use SWR to display delete modal

- packages/app/src/server/models/page.ts
- packages/app/src/server/routes/page.js
- packages/app/src/server/service/page.ts
Redmine: https://redmine.weseek.co.jp/issues/87623
Delete, DeleteCompletely, Revert をした時に子孫数を更新できるようにしました
> feat: Updating descendant count for delete, deleteCompletely, revert method

- packages/app/src/client/base.jsx
- packages/app/src/components/PageRenameModal.jsx
- packages/app/src/server/views/layout/layout.html
- packages/app/src/stores/ui.tsx
- [87214](https://redmine.weseek.co.jp/issues/87214) PageRenameModalのSWR化
※仮でFabアイコンからrenameModalを開いています。
https://user-images.githubusercontent.com/59536731/152523638-1e35bd88-b1e2-46d1-a516-1e4ec8a0e0f4.mov
> open rename modal with swr

- packages/app/src/server/service/page.ts
https://redmine.weseek.co.jp/issues/87749
> update descendantCount on rename

- packages/app/src/server/models/page.ts
- packages/app/src/server/service/page.ts
https://redmine.weseek.co.jp/issues/87810
> recount descendantCount of formerly empty page

- packages/app/src/server/models/page.ts
- packages/app/src/server/routes/page.js
- packages/app/src/server/service/page.ts
Redmine: https://redmine.weseek.co.jp/issues/87667
ページの移動・削除・完全削除後に、末端の空ページを削除できるようにしました
> feat: Remove leaf empty pages

- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/models/page-redirect.ts
- packages/app/src/server/routes/page.js
- packages/app/src/server/service/page.ts
Redmine: https://redmine.weseek.co.jp/issues/87959
リダイレクトページの unlink を修正 & １ヶ所旧 redirect page のコードが残っていたので修正
> feat: Removed redirect page process completely

- packages/app/src/components/PageList/PageListItemL.tsx
[#87755](https://redmine.weseek.co.jp/issues/87755) ドロップダウンメニューから複製ボタンをクリックしてPageDuplicateModalを表示する
> feat: 87755 Use SWR to display duplicate modal (search dropdown)

- packages/app/src/components/PageList/PageListItemL.tsx
> Revert "feat: 87755 Use SWR to display duplicate modal (search dropdown)"

- packages/app/src/components/Page/TrashPageAlert.jsx
[87567](https://redmine.weseek.co.jp/issues/87567) [TrashPageAlert] SWRを使用してModalを表示させる
> feat:87567 Use SWR to display delete modal (TrashPageAlert)

- packages/app/src/components/PageList/PageListItemL.tsx
- https://redmine.weseek.co.jp/issues/88095
> fix: Change pagetitle links to parmanent url

- .devcontainer/docker-compose.yml
- packages/app/.env.development
- packages/app/src/server/routes/index.js
- packages/app/src/server/routes/ogp.ts
- packages/app/src/server/service/config-loader.ts
- packages/app/src/server/util/stream.ts
- packages/app/src/server/views/layout-growi/page.html
- 元祖 PR
- https://github.com/weseek/growi/pull/5242
- 元祖 PR 差分
- https://github.com/weseek/growi/pull/5242/files
https://redmine.weseek.co.jp/issues/88253
> feat: OGP in public wiki

- packages/app/src/server/service/user-group.ts
Redmine: https://redmine.weseek.co.jp/issues/88277
updateGroup メソッドを修正しました
> fix: UserGroup model updateGroup method

- packages/app/test/cypress/integration/2-basic-features/access-to-admin-page.spec.ts
- Add test: access to admin page spec
> imprv: Add visual regression test

- packages/app/test/cypress/integration/2-basic-features/access-to-me-page.spec.ts
> imprv: Added VRT for me page

- packages/app/src/server/models/page.ts
- packages/app/src/server/routes/apiv3/pages.js
- packages/app/src/server/service/page-grant.ts
- packages/app/src/server/service/page.ts
- packages/app/test/integration/service/v5-migration.test.js
Redmine: https://redmine.weseek.co.jp/issues/88305
Sub と Main Operation を区別しました
引数の統一もしました
VRT のエラーはスルーでお願いします。(チェックボックスの部分っぽいです)
> imprv: Separate Main & Sub Operation

- packages/app/src/server/models/page.ts
getParentAndFillAncestors メソッドを修正しました(元の姿に戻しました)
> imprv: Create page

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/Sidebar/PageTree/Item.tsx
[#88078](https://redmine.weseek.co.jp/issues/88078) i18n & toastSuccess を削除する
> feat: 88078 i18n & delete toastSuccess 

- packages/app/src/server/service/page.ts
Redmine: https://redmine.weseek.co.jp/issues/88619
待避所からのマイグレーション処理を正常化しました
Main Sub のことも考えてリファクタも兼ねました
> imprv: Refactor & fix normalize parent recursively

- packages/app/src/components/Sidebar/PageTree/Item.tsx
https://redmine.weseek.co.jp/issues/88629
> fix: navigate user to pages correctly

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/client/app.jsx
- packages/app/src/client/base.jsx
- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/LegacyPrivatePagesMigrationModal.tsx
- packages/app/src/components/Navbar/SubNavButtons.tsx
- packages/app/src/components/PageList/PageListItemL.tsx
- packages/app/src/components/PrivateLegacyPages.tsx
- packages/app/src/components/SearchPage.tsx
- packages/app/src/components/SearchPage/SearchResultContent.tsx
- packages/app/src/components/SearchPage/SearchResultList.tsx
- packages/app/src/components/SearchPage2/SearchPageBase.tsx
- packages/app/src/components/Sidebar/PageTree.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/PrivateLegacyPagesLink.tsx
- packages/app/src/server/routes/apiv3/pages.js
- packages/app/src/server/routes/index.js
- packages/app/src/server/views/layout/layout.html
- packages/app/src/server/views/private-legacy-pages.html
- packages/app/src/server/views/search.html
- packages/app/src/stores/modal.tsx
- packages/app/src/stores/search.tsx
- packages/app/src/styles/_override-bootstrap.scss
- packages/app/test/cypress/integration/3-search/access-to-private-legacy-pages-directly.spec.ts
- packages/core/src/test/util/page-path-utils.test.js
- packages/core/src/utils/page-path-utils.ts
- https://redmine.weseek.co.jp/issues/88599
- https://redmine.weseek.co.jp/issues/88262
> feat: Migrate page format from v4 to v5 on private legacy pages

- packages/app/src/client/services/ContextExtractor.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/stores/context.tsx
[#88261](https://redmine.weseek.co.jp/issues/88261) isEnabledAttachTitleHeader を参照してボディにタイトルのヘッダをあらかじめ挿入できる
> feat: 88261 Add header to the body of the page

- packages/app/src/server/models/page-operation.ts
- packages/app/src/server/service/page.ts
Redmine: https://redmine.weseek.co.jp/issues/88200
PageOperation ドキュメントを作成・更新・削除できるようにしました
> feat: CRUD Page Operation documents

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
[#88686](https://redmine.weseek.co.jp/issues/88686) isEnabledAttachTitleHeader を props で渡す
> imprv: 88686 Pass boolean with props

- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/server/routes/apiv3/page.js
- packages/app/src/server/service/page.ts
https://redmine.weseek.co.jp/issues/88634
> fix: not allow user page to be moved

- packages/app/src/components/Navbar/SubNavButtons.tsx
- packages/app/src/components/User/SeenUserInfo.tsx
fix: #5371 
- https://redmine.weseek.co.jp/issues/88519
- https://redmine.weseek.co.jp/issues/88520
足跡が15で止まっていたのを修正しました
> fix: Page view count stops at 15

- packages/app/src/client/base.jsx
- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/Page/TrashPageAlert.jsx
- packages/app/src/components/PageList/PageListItemL.tsx
- packages/app/src/components/PrivateLegacyPages.tsx
- packages/app/src/components/PutbackPageModal.jsx
- packages/app/src/interfaces/page.ts
- packages/app/src/server/routes/apiv3/page.js
- packages/app/src/server/service/page.ts
- packages/app/src/server/views/layout/layout.html
- packages/app/src/stores/modal.tsx
https://redmine.weseek.co.jp/issues/88640
> imprv: can open global putback page modal

- packages/app/src/components/Page/TrashPageAlert.jsx
- packages/app/src/components/PageList/PageListItemL.tsx
- packages/app/src/components/PutbackPageModal.jsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/stores/modal.tsx
- [88684](https://redmine.weseek.co.jp/issues/88684)  [Item] useSWRxPageInfoをPageItemControlから取得する
Itemコンポーネント内で`useSWRxPageInfo` を使用していたのを、PageItemControlから取得するように修正しました。
https://user-images.githubusercontent.com/59536731/154546273-7558d61e-9ff7-420d-8aec-8b9e870f28ab.mov
> imprv: get PageInfo from PageItemControl

- packages/app/src/components/PageList/PageListItemL.tsx
- packages/app/src/components/PagePathHierarchicalLink.jsx
https://redmine.weseek.co.jp/issues/88630
> fix: show highlight on paths

- packages/app/src/server/crowi/index.js
- packages/app/src/server/models/page-operation.ts
- packages/app/src/server/models/page.ts
- packages/app/src/server/service/page-operation.ts
- packages/app/src/server/service/page.ts
- packages/app/test/integration/service/page.test.js
- packages/app/test/integration/service/v5.page.test.ts
Redmine(２つ): https://redmine.weseek.co.jp/issues/88307, https://redmine.weseek.co.jp/issues/86540
PageOperation の最低限のブロックを実装しました
> feat: Block page operation

- packages/app/src/components/PrivateLegacyPages.tsx
- packages/app/src/components/SearchPage.tsx
- packages/app/src/server/service/search-delegator/private-legacy-pages.ts
https://redmine.weseek.co.jp/issues/88843
> fix: Reset offset when search

- packages/app/src/components/Page/TrashPageAlert.jsx
- packages/app/src/server/models/page.ts
- packages/app/src/server/service/page.ts
- packages/app/test/integration/service/page.test.js
Redmine: https://redmine.weseek.co.jp/issues/88764
TrashPageAlert からの完全削除を正常化しました
> fix: Delete trash page recursively

- packages/app/src/components/Admin/UserGroup/UserGroupCreateModal.tsx
- packages/app/src/components/Admin/UserGroup/UserGroupModal.tsx
- packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
[#87614](https://redmine.weseek.co.jp/issues/87614) [Front] UserGroup 新規作成フォームをモーダルで表示できる
https://user-images.githubusercontent.com/34241526/154886000-1f0d80b0-1d3b-4ab1-95bd-5180569b392f.mov
> feat: Modal to create UserGroup

- packages/app/src/styles/_sidebar.scss
- packages/app/test/cypress/support/commands.ts
https://redmine.weseek.co.jp/issues/86679
> fix: Layer stack of grw-navigation-resize-button

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/PageDuplicateModal.jsx
- packages/app/src/components/PageRenameModal.jsx
- packages/app/src/server/routes/apiv3/pages.js
Redmine: https://redmine.weseek.co.jp/issues/88981
/_api/v3/pages/subordinated-list を空ページでも動作するように改修しました
その他 translation を修正などしました
> fix: Subordinated list api for empty pages

- packages/app/src/client/services/PersonalContainer.js
- packages/app/src/components/Me/BasicInfoSettings.jsx
- packages/app/src/server/models/user.js
- packages/app/src/server/routes/apiv3/personal-setting.js
- packages/app/src/server/service/slack-command-handler/create-page-service.js
- packages/app/src/server/service/slack-command-handler/keep.js
https://youtrack.weseek.co.jp/issue/GW-7697
> feat: gw7697 linking growi user with slack

- README.md
- README_JP.md
> fix: remove dead links from README

- packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
- packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
[#88978](https://redmine.weseek.co.jp/issues/88978) [Front] 詳細画面で子グループを作成できる
https://user-images.githubusercontent.com/34241526/155084167-78772d90-db43-44d2-b93a-ce8e402c03d6.mov
> feat: 88978 Display user group create modal in detail screen

- packages/app/src/components/PageRenameModal.jsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- [89242](https://redmine.weseek.co.jp/issues/89242) [Bug] rename Modalが表示できないbug fix
マージ先はマスターです。
> fix: 89241 open rename modal

- packages/app/src/interfaces/websocket.ts
- packages/app/src/server/service/page.ts
- packages/app/test/integration/setup-crowi.js
Redmine: https://redmine.weseek.co.jp/issues/89149
祖先の descendantCount 更新時に更新内容を websocket で emit するところまで実装しました
> imprv: Send update through websocket

- packages/app/src/components/SearchPage/SearchResultContent.tsx
https://redmine.weseek.co.jp/issues/89268
> imprv: show toastr on delete

- packages/app/src/components/Page.jsx
- packages/app/src/components/Page/RevisionLoader.jsx
- packages/app/src/components/Page/RevisionRenderer.jsx
- packages/app/src/components/PageTimeline.jsx
- packages/app/src/components/SearchPage/SearchResultContent.tsx
https://redmine.weseek.co.jp/issues/89324
> fix: show revision body

- packages/app/src/client/services/ContextExtractor.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- packages/app/src/interfaces/websocket.ts
- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/service/page.ts
- packages/app/src/stores/ui.tsx
- packages/app/src/stores/websocket.tsx
Redmine(２つ): https://redmine.weseek.co.jp/issues/89151, https://redmine.weseek.co.jp/issues/89155
UI 上で子孫数が リアルタイムに更新されるようにしました
> imprv: Items tree socket client

- packages/app/src/client/services/ContextExtractor.tsx
- packages/app/src/components/Page/NotFoundAlert.tsx
- packages/app/src/interfaces/page-listing-results.ts
- packages/app/src/server/models/page.ts
- packages/app/src/server/routes/page.js
- packages/app/src/server/views/layout-growi/not_found.html
- packages/app/src/stores/context.tsx
- packages/app/src/stores/ui.tsx
Redmine: https://redmine.weseek.co.jp/issues/88529
パーマリンクでページが見つからない場合の挙動を改善しました
> fix: Permalink not found

- packages/app/src/components/Page/TrashPageAlert.jsx
https://redmine.weseek.co.jp/issues/89487
> fix: TrashPageAlert.openPageDeleteModalHandler

- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/models/page.ts
- packages/app/src/server/routes/page.js
- packages/app/src/server/service/page-grant.ts
- packages/app/src/server/service/page.ts
- packages/app/test/integration/service/v5.migration.test.js
Redmine: https://redmine.weseek.co.jp/issues/89335
ページの parent 正常化処理を修正しました
> fix: Normalize parent

- packages/app/test/integration/service/v5.page.test.ts
https://redmine.weseek.co.jp/issues/89367
> imprv: v5 test for rename

- packages/app/src/components/Common/ClosableTextInput.tsx
https://redmine.weseek.co.jp/issues/89586
初回
入力後
> imprv: hide alert on first focus

- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
Redmine: https://redmine.weseek.co.jp/issues/89671
ItemsTree の socket io 系の処理が動作を遅くしている問題を修正しました
> imprv: Tune ItemsTree socket conn performance

- packages/app/src/components/PagePresentationModal.jsx
- packages/app/test/cypress/integration/2-basic-features/open-presentation-modal.spec.ts
- [#89052](https://redmine.weseek.co.jp/issues/89052 ) テストコードの文言修正
> fix: 89052 VRT for Presentation modal 

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
[#89743](https://redmine.weseek.co.jp/issues/89743) 3点ドロップダウンボタンにて、inputFormからのrenameができる
> feat: 89743 Rename from PageTree input

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- [89818](https://redmine.weseek.co.jp/issues/89818) ホバーしてページアイテムがisOpenになるまでの時間を短くする
https://user-images.githubusercontent.com/59536731/156745693-5940552d-d575-4d0f-abfa-360b11972322.mov
https://user-images.githubusercontent.com/59536731/156745680-ad78e561-e9c2-469d-86a7-5ad7b6964d95.mov
> imprv: time to open page item directory

- packages/app/resource/locales/en_US/admin/admin.json
- packages/app/resource/locales/ja_JP/admin/admin.json
- packages/app/resource/locales/zh_CN/admin/admin.json
- packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
- packages/app/src/interfaces/user-group-response.ts
- packages/app/src/server/routes/apiv3/user-group.js
- packages/app/src/stores/user-group.tsx
[#85240](https://redmine.weseek.co.jp/issues/85240) [Front & Back] 詳細画面:祖先への戻るリンク
https://user-images.githubusercontent.com/34241526/156895864-2b3e6d2e-f3ed-4dc4-8072-5473695a791e.mov
> feat: Link back to ancestor group

- packages/app/test/cypress/integration/7-other-menu/changelog.spec.ts
- packages/app/test/cypress/integration/7-other-menu/create-edit-template.spec.ts
- packages/app/test/cypress/integration/7-other-menu/duplicate-page.spec.ts
- packages/app/test/cypress/integration/7-other-menu/export-page-in-markdown-format.spec.ts
- packages/app/test/cypress/integration/7-other-menu/presentation.spec.ts
https://youtrack.weseek.co.jp/issue/GW-7727
> imprv: vrt other menu

- packages/app/src/server/routes/page.js
Redmine: https://redmine.weseek.co.jp/issues/89861
Anyone with link がパスリンクでアクセスできない問題を修正しました
> fix: Path link anyone with link

- packages/app/src/server/routes/apiv3/personal-setting.js
- https://github.com/weseek/growi/pull/5470 ← の PR と同様の内容
- 4.5.16 でのリリースに含めるため
> fix: issue 5408 for release

- packages/app/src/server/models/page.js
- https://github.com/weseek/growi/pull/5398 ← の PR と同様の内容
- 4.5.16 でのリリースに含めるため
> fix: GrantedGroup issue when adding tag (for 4.5.x)

- packages/app/src/components/PageList/PageListItemL.tsx
> Revert "fix: checkbox position on search page"

- packages/app/src/components/Page.jsx
- packages/app/src/components/Page/RevisionLoader.jsx
- packages/app/src/components/Page/RevisionRenderer.jsx
- packages/app/src/components/PageEditor.jsx
- packages/app/src/components/PageTimeline.jsx
- packages/app/src/components/SearchPage/SearchResultContent.tsx
- packages/app/src/components/Sidebar/CustomSidebar.tsx
[#89859](https://redmine.weseek.co.jp/issues/89859) isRenderable という Props を剥がす
> imprv: 89859 Omit renderable props

- packages/app/src/server/service/search.ts
https://redmine.weseek.co.jp/issues/89909
- 検索結果リストのスニペットにコメントを表示するように変更しました
> imprv: add snippet highlight comment

- packages/app/src/server/service/page.ts
Redmine: https://redmine.weseek.co.jp/issues/90150
shouldUseV4Process と Rename を修正しました
> fix: Rename & shouldUseV4Process

- packages/app/test/integration/global-setup.js
- packages/app/test/integration/service/v5.non-public-page.test.ts
refs [#90324: テスト用のユーザーグループを global-setup に用意](https://redmine.weseek.co.jp/issues/90324)
> imprv: Prepare UserGroup for integration test

- packages/app/src/client/services/AdminAppContainer.js
- packages/app/src/client/services/AdminHomeContainer.js
- packages/app/src/components/Admin/AdminHome/AdminHome.jsx
- packages/app/src/components/Admin/App/AppSettingsPageContents.jsx
- packages/app/src/components/Admin/App/ConfirmModal.tsx
- packages/app/src/components/Admin/App/MaintenanceMode.tsx
- packages/app/src/components/Admin/App/V5PageMigration.tsx
- packages/app/src/server/middlewares/unavailable-when-maintenance-mode.ts
- packages/app/src/server/routes/apiv3/admin-home.js
- packages/app/src/server/routes/apiv3/app-settings.js
- packages/app/src/server/routes/index.js
- packages/app/src/server/service/app.ts
Redmine: https://redmine.weseek.co.jp/issues/90149
管理画面からメンテナンスモードを on off できるようにしました
ルートの整理もたりてなかったのでそれもやりました
見た目こうした方がいいとかあれば FB お願いします
i18n は後続です
i18n
> feat: Toggle maintenance mode from admin console

- packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
- packages/app/src/components/Navbar/GrowiSubNavigation.tsx
https://redmine.weseek.co.jp/issues/89981
> imprv: add space btw page list meta and page view control 

- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
Add a `isInstantRename` Boolean property and change the Rename label with it.
refs: https://redmine.weseek.co.jp/issues/90521
> imprv: #90521: rename page tree rename control label

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- [90577](https://redmine.weseek.co.jp/issues/90577) /user/${user_name}/hoge というページを dnd できるようにする
> imprv: isDraggable variable

- packages/app/src/server/crowi/index.js
- packages/app/src/server/service/page-operation.ts
https://redmine.weseek.co.jp/issues/90612
> imprv: empty page operation collection

- packages/app/src/components/PageCreateModal.jsx
- [90547](https://redmine.weseek.co.jp/issues/90547) [PageCreateModal] /user直下にページを作成しようとすると、エラーが表示されsubmitボタンがdisabledになる
OK(PageCreateModalはまだ検出されない)
https://user-images.githubusercontent.com/59536731/158325680-9492c622-0859-4412-874b-36e2de189bb5.mov
> imprv: 90547 show err on page create modal

- packages/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
- packages/app/src/components/Admin/UserGroup/UserGroupForm.tsx
- packages/app/src/components/Admin/UserGroup/UserGroupModal.tsx
- packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
- packages/app/src/components/Admin/UserGroup/UserGroupTable.tsx
- packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
[#90063](https://redmine.weseek.co.jp/issues/90063) [front] 詳細画面 UserGroupTable の edit を押した時に、モーダルを開く
https://user-images.githubusercontent.com/34241526/158220866-a01482b1-52e1-4a48-98b8-525c83d33fd7.mov
> feat: Update UserGroups from modal

- packages/app/test/integration/service/v5.migration.test.js
Redmine: https://redmine.weseek.co.jp/issues/90684
待避所からのマイグレーション処理(バックエンド)用にテストコードを追加しました
ci は test の部分スルーで OK です
> imprv: Add test for nomalizing parent

- .github/workflows/reusable-app-prod.yml
- disable upcoming VRT, wait until all VRT ready, use feat/7723-vrt as main branch for vrt tasks
> imprv: Disable upcoming VRT, wait until all VRT ready

- packages/app/test/integration/models/v5.page.test.js
https://redmine.weseek.co.jp/issues/90696
> imprv: add test for updatePage

- packages/app/resource/locales/ja_JP/translation.json
https://youtrack.weseek.co.jp/issue/GW-7733
- Improve Japanese translation
> feat: improve translation

- packages/app/src/interfaces/page-delete-config.ts
- packages/app/src/server/service/page.ts
- packages/app/src/utils/page-delete-config.ts
- packages/app/test/unit/utils/page-delete-config.test.ts
- packages/app/test/unit/utils/page-delete-configs.test.ts
Redmine: https://redmine.weseek.co.jp/issues/90956
新しい削除権限の Config 値が正常かどうかを判断する utility を実装しました
テストも書きました
> imprv: Validate deletion settings

- packages/app/src/components/Admin/UserGroup/UserGroupModal.tsx
- packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx
- packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
[#90801](https://redmine.weseek.co.jp/issues/90801) [front] Create, Updateモーダルで送信した時にモーダルが閉じる
> fix: 90801 Close modal if Update / Create is successful

- packages/app/src/server/interfaces/page-operation.ts
- packages/app/src/server/models/page-operation.ts
- packages/app/src/server/service/page.ts
Redmine: https://redmine.weseek.co.jp/issues/91040
descendantCount の更新を正常化しました
> fix: Save ex-descendant count

- packages/app/resource/locales/en_US/admin/admin.json
- packages/app/resource/locales/ja_JP/admin/admin.json
- packages/app/resource/locales/zh_CN/admin/admin.json
- packages/app/src/components/Admin/UserGroup/UserGroupForm.tsx
[#91117](https://redmine.weseek.co.jp/issues/91117)  [UserGroup] 詳細画面の基本情報から親を解除できる
https://user-images.githubusercontent.com/34241526/159468764-8e3906dd-d265-4a54-89c0-cbdfcbbbdca7.mov
> feat: Release parent group

- packages/app/src/components/Admin/AdminHome/AdminHome.jsx
> fix: fix i18n for maintenance mode

- packages/app/src/server/routes/apiv3/index.js
healthcheck をメンテナンスモード中でも叩けるように改修
> fix: Add healthcheck to admin router

- packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
- packages/app/src/components/PageEditor/EmojiPicker.tsx
https://youtrack.weseek.co.jp/issue/GW-7751
- Remove autofocus prop of Picker component
- Remove timeout on typing colons
> feat: gw7751 Specify emoji by typing colons

- packages/app/src/components/PageEditor/EmojiPicker.tsx
https://youtrack.weseek.co.jp/issue/GW-7749
- Get color mode from color-scheme
- Implement theme of EmojiPicker based on color mode
> feat: apply color mode to EmojiPicker

- packages/app/resource/locales/en_US/admin/admin.json
- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/admin/admin.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/admin/admin.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/Admin/UserGroupDetail/UpdateParentConfirmModal.tsx
Redmine: https://redmine.weseek.co.jp/issues/91516
ユーザーグループ設定の確認モーダルの見た目を整えて i18n しました
> imprv: Usergroup confirm modal i18n design

- packages/app/resource/locales/en_US/admin/admin.json
- packages/app/resource/locales/ja_JP/admin/admin.json
- packages/app/resource/locales/zh_CN/admin/admin.json
- packages/app/src/client/services/ContextExtractor.tsx
- packages/app/src/components/Admin/App/V5PageMigration.tsx
- packages/app/src/interfaces/websocket.ts
- packages/app/src/server/service/page.ts
- packages/app/src/stores/websocket.tsx
Redmine: https://redmine.weseek.co.jp/issues/80433
管理画面でマイグレーションの進行状況を確認できるようにしました。マイグレーションを開始すると、再度ボタンが押せないように改善しました
動作確認は先に済んでいますのでそのまま master に入れて大丈夫です
> imprv: Show v5 migration status with a progress bar

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/Page/RevisionLoader.jsx
- packages/app/src/components/PageList/PageListItemL.tsx
- packages/app/src/components/SearchPage/SearchResultList.tsx
- packages/app/src/components/SearchPage2/SearchPageBase.tsx
- packages/app/src/interfaces/search.ts
- packages/app/src/server/routes/apiv3/revisions.js
- packages/app/src/server/routes/search.js
- packages/app/src/server/service/search.ts
Redmine: https://redmine.weseek.co.jp/issues/91680
自分に閲覧権限がないページのスニペットは表示されないように改修しました
- UI 改善
- 必要あればエラーレスポンスのハンドリング改善
> fix: Hide snippet when private

- packages/app/src/components/PageEditor.jsx
https://redmine.weseek.co.jp/issues/91752
> fix: Redering preview

- packages/app/src/server/routes/search.js
- packages/app/src/server/service/search.ts
- packages/app/src/utils/page-delete-config.ts
Redmine: https://redmine.weseek.co.jp/issues/91699
検索リストでハイライトされない問題を修正しました
> fix: Search highlight snippet

- packages/app/src/server/middlewares/register-form-validator.ts
- packages/app/src/server/routes/apiv3/user-activation.ts
https://redmine.weseek.co.jp/issues/86758
パスワード7文字入力で確定時の挙動（正）
> fix: Displaying minimum length of password

- .devcontainer/docker-compose.yml
https://redmine.weseek.co.jp/issues/91537
> fix: display kibana v7 on growi v5 in dev

- packages/app/src/components/Sidebar/InfiniteScroll.tsx
- packages/app/src/components/Sidebar/RecentChanges.tsx
- packages/app/src/stores/page.tsx
https://youtrack.weseek.co.jp/issue/GW-7757
> feat: gw7757 implement use swr inifinitex recently updated

- packages/app/src/stores/ui.tsx
Merge this branch into the branch from which this branch is derived
変更前
変更後
> add condition for showing authors

- packages/app/src/server/interfaces/search.ts
- packages/app/src/server/models/page.ts
- packages/app/src/server/models/vo/error-search.ts
- packages/app/src/server/routes/search.ts
- packages/app/src/server/service/search-delegator/elasticsearch.ts
- packages/app/src/server/service/search-delegator/private-legacy-pages.ts
- packages/app/src/server/service/search.ts
Redmine: https://redmine.weseek.co.jp/issues/92049
NamedQuery の検索における keyword (terms) フィルタを実装しました
- test を修正する
- CI の test はスルーして OK です
> feat: Implement namedquery filter by prefix

- .devcontainer/docker-compose.yml
https://redmine.weseek.co.jp/issues/91815
手元動作確認済み
> change version

- packages/app/src/components/PageCreateModal.jsx
[#92043](https://redmine.weseek.co.jp/issues/92043) [5.x] /user/hoge にいる状態で PageCreateModal を開くとパスが自動入力されていない (テンプレート作成の部分にはパスが出ている)
┗ [#92093](https://redmine.weseek.co.jp/issues/92093) 修正
> fix: Page path is not pre populated

- packages/app/resource/search/mappings-es7-for-ci.json
- packages/app/src/server/service/search-delegator/elasticsearch-client-types.ts
- packages/app/src/server/service/search-delegator/elasticsearch-client.ts
- packages/app/src/server/service/search-delegator/elasticsearch.ts
https://redmine.weseek.co.jp/issues/92267
> fix: Elasticsearch doesn't work properly on production

- packages/app/src/client/services/AdminCustomizeContainer.js
- packages/app/src/components/Admin/Customize/CropLogoModal.jsx
- packages/app/src/components/Admin/Customize/Customize.jsx
- packages/app/src/components/Admin/Customize/CustomizeLogoSetting.jsx
https://youtrack.weseek.co.jp/issue/GW-7771
> feat: gw 7771 create component for logo upload

- packages/app/src/components/Me/PasswordSettings.jsx
https://redmine.weseek.co.jp/issues/90645
> fix: Prevent auto completing email with username stored by browser in /me page

- packages/app/src/components/Me/PasswordSettings.jsx
https://redmine.weseek.co.jp/issues/92789
> fix: Prevent auto completing email with username stored by browser in /me page for v4.5.x

- packages/app/resource/locales/en_US/admin/admin.json
- packages/app/resource/locales/ja_JP/admin/admin.json
- packages/app/resource/locales/zh_CN/admin/admin.json
- packages/app/src/client/services/AdminCustomizeContainer.js
- packages/app/src/client/services/PersonalContainer.js
- packages/app/src/components/Admin/Customize/CustomizeLogoSetting.jsx
- packages/app/src/components/Navbar/GrowiNavbar.tsx
- packages/app/src/server/models/attachment.js
- packages/app/src/server/models/config.ts
- packages/app/src/server/routes/apiv3/customize-setting.js
- packages/app/src/server/routes/attachment.js
- packages/app/src/server/routes/index.js
- packages/app/src/server/service/attachment.js
https://youtrack.weseek.co.jp/issue/GW-7772
> feat: gw7772 store and retrieve logo settings

- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
[#92816](https://redmine.weseek.co.jp/issues/92816) [GROWI] 三点ボタンを押して開いたメニューアイテムの順番を変更
┗ [#92817](https://redmine.weseek.co.jp/issues/92817) 実装
> imprv: Change the order of menu items

- packages/app/test/integration/service/search/search-service.test.js
Redmine: https://redmine.weseek.co.jp/issues/92050
既存の SearchService 用のテストコードが動くように修正しました
> imprv: Fixed search service test code

- packages/app/src/components/PageEditor/EmojiPicker.tsx
https://youtrack.weseek.co.jp/issue/GW-7783
- Apply theme to emojiPicker according app theme color
> Apply dark theme to emojiPicker

- packages/app/src/server/models/user.js
- packages/app/test/integration/models/user.test.js
> fix: New user notification email is also sent TO: deleted_at_<epoch_time>@deleted

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/PrivateLegacyPages.tsx
- packages/app/src/components/SearchPage.tsx
- packages/app/src/components/SearchPage/SearchControl.tsx
- packages/app/src/components/SearchTypeahead.tsx
- packages/app/src/server/service/search-delegator/private-legacy-pages.ts
- packages/app/src/stores/page-listing.tsx
- packages/app/src/stores/search.tsx
Redmine: https://redmine.weseek.co.jp/issues/91874
待避所から検索できるようにしました
https://user-images.githubusercontent.com/58432773/164054600-c42aa675-d2ad-4c10-9dba-32fbb42e4c35.mov
> feat: Add searchbar plpages

- packages/app/src/client/app.jsx
- packages/app/src/components/PrivateLegacyPages.tsx
- packages/app/src/components/PrivateLegacyPagesMigrationModal.tsx
- packages/app/src/stores/modal.tsx
Redmine: https://redmine.weseek.co.jp/issues/91871
待避所からパスを入力してコンバートできるようにしました
- i18n
- スタイリング
> feat: Private legacy pages convert by path

- packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
- packages/app/src/components/PageEditor/EmojiPicker.tsx
- packages/app/src/components/PageEditor/EmojiPickerHelper.ts
https://youtrack.weseek.co.jp/issue/GW-7750
> feat: gw7750 set emoji picker position relative to cursor

- packages/app/src/components/PageEditor/EmojiPicker.tsx
- packages/app/src/styles/_on-edit.scss
- packages/app/src/styles/theme/_apply-colors.scss
https://youtrack.weseek.co.jp/issue/GW-7799
> feat: gw7799 remove background color of emoji picker modal

- packages/app/resource/locales/ja_JP/translation.json
https://youtrack.weseek.co.jp/issue/GW-7801
- Improve Japanese translation for emojiPicker
> Improve Japanese translation for emojiPicker

- packages/app/src/components/PrivateLegacyPages.tsx
- packages/app/src/interfaces/websocket.ts
- packages/app/src/server/routes/apiv3/pages.js
- packages/app/src/server/service/page.ts
https://redmine.weseek.co.jp/issues/92133
待避所からページのページのマイグレーションを行ったときに
・処理開始
・処理が正常に終了
・処理中にエラー発生
の3つのタイミングでsocket通信で通知をするようにした
UIは未実装。
> feat: 92133 page migration toast backend

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/PrivateLegacyPages.tsx
- packages/app/src/server/service/page.ts
Redmine: https://redmine.weseek.co.jp/issues/93925
待避所のパスを入力して変換するモーダルを i18n しました
若干フロントの処理も修正しました
> imprv: Add style to private legacy pages convert modal & i18n

- packages/app/src/styles/_page-tree.scss
- packages/app/src/styles/theme/_apply-colors-dark.scss
- packages/app/src/styles/theme/_apply-colors-light.scss
- packages/app/src/styles/theme/christmas.scss
- packages/app/src/styles/theme/default.scss
- packages/app/src/styles/theme/future.scss
- packages/app/src/styles/theme/island.scss
- packages/app/src/styles/theme/kibela.scss
- packages/app/src/styles/theme/mixins/_list-group.scss
- https://redmine.weseek.co.jp/issues/90388
- https://redmine.weseek.co.jp/issues/93361 
- https://redmine.weseek.co.jp/issues/94042
- 透明色を使っているため、hover時の見た目が変にはなっている。これは別途対応が必要
- 対応タスク→ https://redmine.weseek.co.jp/issues/94469
> feat: designed light theme and refactored the part about the theme of pagetree.

- packages/app/src/components/PageRenameModal.tsx
- packages/app/src/server/routes/apiv3/page.js
[#94219](https://redmine.weseek.co.jp/issues/94219) [S社FB] 検索ページで移動/名前変更した際にエラーが表示される(ページは移動できている)
└ [#94229](https://redmine.weseek.co.jp/issues/94229) 修正
> fix: Error when renaming

- packages/app/package.json
- packages/app/src/components/PageEditor/EmojiPicker.tsx
- yarn.lock
https://youtrack.weseek.co.jp/issue/GW-7798
> feat: gw7798 pick an emoji with keyboard operation

- packages/app/src/components/Navbar/AppearanceModeDropdown.tsx
- packages/app/src/components/Navbar/GrowiNavbar.tsx
- packages/app/src/components/Navbar/GuestDropdown.tsx
- packages/app/src/components/Navbar/PersonalDropdown.jsx
- packages/app/src/styles/theme/_apply-colors.scss
https://redmine.weseek.co.jp/issues/94054
実装したドロップダウンメニュー
変更したデザイン
https://wsgrowi.slack.com/archives/C0111HG81GB/p1652248810533789
https://wsgrowi.slack.com/archives/C0111HG81GB/p1652254959944939
- PersonalDropdownから見た目の設定を分離し、別のドロップダウンメニューを作成（フロントのみ、機能は未実装）
- ドロップダウンメニューのアイコンの画像の色を微調整
> feat: 94054 navbar menu for guest front

- packages/app/resource/locales/en_US/sandbox.md
- packages/app/resource/locales/ja_JP/sandbox.md
- packages/app/resource/locales/zh_CN/sandbox.md
- packages/app/src/client/util/markdown-it/emoji-mart-data.ts
https://youtrack.weseek.co.jp/issue/GW-7803
> fix: gw7803 some emoji not displayed correctly on preview

- packages/app/src/client/services/ContextExtractor.tsx
- packages/app/src/components/Page/FixPageGrantAlert.tsx
- packages/app/src/interfaces/page-grant.ts
- packages/app/src/server/models/page.ts
- packages/app/src/server/models/user-group-relation.js
- packages/app/src/server/routes/apiv3/page.js
- packages/app/src/server/service/page-grant.ts
- packages/app/src/server/views/widget/page_content.html
- packages/app/src/stores/context.tsx
- packages/app/src/stores/page.tsx
Redmine: https://redmine.weseek.co.jp/issues/94525
権限修復用モーダルのレンダリングに必要な GET api を実装しました
クライアントコードの変更は見ていただかなくて大丈夫です
- クライアントコードを修正しました
- interface を改善しました
- 権限修正 api の実装
- i18n & スタイリング
- 余裕あればテストコード追加
> feat: Fix grant alert applicable data apis

- packages/app/src/components/Page/FixPageGrantAlert.tsx
- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/models/page.ts
- packages/app/src/server/routes/apiv3/page.js
Redmine: https://redmine.weseek.co.jp/issues/94872
権限修正用 api を実装しました
- i18n & スタイリング
- 更新成功後にページをリロード
> feat: Fix grant alert update grant api

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/styles/_mixins.scss
- packages/app/src/styles/_page-tree.scss
- packages/app/src/styles/theme/_apply-colors-dark.scss
- packages/app/src/styles/theme/_apply-colors-light.scss
- packages/app/src/styles/theme/mixins/_list-group.scss
- packages/app/src/styles/theme/nature.scss
- https://redmine.weseek.co.jp/issues/94577
- cout-badgeをmixin化した
- ついでにemptyPageの文字の色の設定も調整
> feat: 94577-grw-count-badge

- packages/app/src/server/routes/search.js
- packages/app/src/server/service/search.ts
[#94638](https://redmine.weseek.co.jp/issues/94638) [要調査] 検索時のエラーを修正する
└ [#94873](https://redmine.weseek.co.jp/issues/94873) 修正
> fix: Error on searching

- packages/app/src/components/Navbar/AppearanceModeDropdown.tsx
- packages/app/src/stores/ui.tsx
- NavBarのドロップダウンからサイドバーモードを設定したときにlocalStorageにも保存するように変更
> feat: 94005 navbar manu backend

- packages/app/src/interfaces/errors/v5-conversion-error.ts
- packages/app/src/server/events/user.js
- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/models/page.ts
- packages/app/src/server/models/revision.js
- packages/app/src/server/routes/apiv3/pages.js
- packages/app/src/server/routes/attachment.js
- packages/app/src/server/routes/page.js
- packages/app/src/server/service/installer.ts
- packages/app/src/server/service/page.ts
- packages/app/src/server/service/slack-command-handler/create-page-service.js
- packages/app/src/server/util/createGrowiPagesFromImports.js
- packages/app/test/integration/models/v5.page.test.js
Redmine: https://redmine.weseek.co.jp/issues/91872
待避所からパスによるコンバートで、入力されたパスにページが存在しなくてもページを自動作成することでコンバートできるようにしました
- フロントエンドの改修
- 確認モーダルの実装
- エンドポイント修正
- その他必要なメソッドの実装
- テストコード拡充
> feat: Enable to convert pages by path for admin users

- packages/app/src/components/Page/FixPageGrantAlert.tsx
- 権限修正モーダルの中で自分に権限のないラジオボタンは押せないようにする
> feat: button disabled depending on applicable grant

- packages/app/src/server/crowi/index.js
- packages/app/src/server/models/page-operation.ts
- packages/app/src/server/service/page-operation.ts
https://redmine.weseek.co.jp/issues/95517
> feat: Delete all PageOperation documents except ones with actionType set to Rename

- packages/app/src/components/PageEditor/EmojiPicker.tsx
https://youtrack.weseek.co.jp/issue/GW-7810
- Set focus to search input when emojiPicker opened from icon
> feat: Auto focus on open emojiPicker from icon

- packages/app/src/components/PrivateLegacyPages.tsx
- packages/app/src/server/models/page.ts
- packages/app/src/server/service/page.ts
Redmine: https://redmine.weseek.co.jp/issues/95237
パスにマッチするページが存在しなくてもそのパス配下のページを待避所から変換できるようにしました
> feat: Implement methods for normalize by path

- packages/app/src/components/Me/PasswordSettings.jsx
https://redmine.weseek.co.jp/issues/96017
> imprv: Move code to the appropriate place for fix browser auto-complete email wiith username

- packages/app/src/server/service/page-grant.ts
Redmine: https://redmine.weseek.co.jp/issues/96003
calcApplicableGrantData を修正しました
> fix: calcApplicableGrantData conditions

- packages/app/src/components/PageEditor/EmojiPickerHelper.ts
https://youtrack.weseek.co.jp/issue/GW-7814
- Update emoji regex pattern and add constant outside the class
- Add emoji pattern test url
> feat: Update emoji regex pattern

- packages/app/src/components/PageEditor/CommentMentionHelper.ts
- packages/app/src/server/models/user.js
- packages/app/src/server/routes/apiv3/users.js
https://redmine.weseek.co.jp/issues/96220
feat/auditlog に対して作成した API (https://github.com/weseek/growi/pull/5864) を master 向けにも作成しました
> feat: API to find username

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/PrivateLegacyPages.tsx
https://redmine.weseek.co.jp/issues/95157
> feat: Add path recovery btn to page item control

- packages/app/src/components/Sidebar/CustomSidebar.tsx
- packages/app/src/components/Sidebar/Tag.tsx
[94774](https://redmine.weseek.co.jp/issues/94774) サイドバーのリロードボタンの見た目を統一させる
┗ [95026](https://redmine.weseek.co.jp/issues/95026) 実装
> imprv: Unify reload buttons

- packages/app/src/components/Admin/AuditLog/DateRangePicker.tsx
- packages/app/src/components/Admin/AuditLog/SearchUsernameInput.tsx
- packages/app/src/components/Admin/AuditLog/SearchUsernameTypeahead.tsx
- packages/app/src/components/Admin/AuditLog/SelectActionDropdown.tsx
- packages/app/src/components/Admin/AuditLogManagement.tsx
- packages/app/src/server/routes/apiv3/activity.ts
- packages/app/src/stores/activity.ts
- packages/app/src/stores/user.tsx
[#93768](https://redmine.weseek.co.jp/issues/93768) [GROWI] [AuditLog] 特定の username を指定して検索できる
└ [#95195](https://redmine.weseek.co.jp/issues/95195) [frontend] react-bootstrap-typeahead を使ってユーザー名のインクリメントサーチを実装する
https://user-images.githubusercontent.com/34241526/171027009-b48ad862-3dca-4875-9786-62c3d4c79229.mov
> feat: Icremental search for username

- packages/app/resource/locales/en_US/admin/admin.json
- packages/app/resource/locales/ja_JP/admin/admin.json
- packages/app/resource/locales/zh_CN/admin/admin.json
- packages/app/src/components/Admin/AuditLog/ActivityTable.tsx
- packages/app/src/components/Admin/AuditLog/DateRangePicker.tsx
- packages/app/src/components/Admin/AuditLog/SearchUsernameTypeahead.tsx
- packages/app/src/components/Admin/AuditLog/SelectActionDropdown.tsx
- packages/app/src/components/Admin/AuditLogManagement.tsx
- packages/app/src/server/routes/apiv3/activity.ts
- packages/app/src/stores/activity.ts
[#94757](https://redmine.weseek.co.jp/issues/94757) [GROWI] [AuditLog] UI / UX 改善
└ [#96323](https://redmine.weseek.co.jp/issues/96323) リロードボタンを実装する
└ [#96324](https://redmine.weseek.co.jp/issues/96324) ローディング時にページングボタンを非表示にしない
└ [#96411](https://redmine.weseek.co.jp/issues/96411) テーブルのカラム名を i18n  かつ ユーザーフレンドリーなものにする
> imprv: Audit log  UI / UX improvement

- packages/app/resource/Contributor.js
https://redmine.weseek.co.jp/issues/96484
太田さんをスタッフクレジットに追加する
場所はコミットをいつしたかを参考にきめた
> imprv: add name to staff credits

- packages/app/src/components/Sidebar/Tag.tsx
- packages/app/src/components/TagList.tsx
- packages/app/src/styles/_page_list.scss
https://redmine.weseek.co.jp/issues/96381
fontやmerginの調整
> imprv adjustment style

- packages/app/src/server/service/comment.ts
- packages/app/src/server/util/slack.js
https://youtrack.weseek.co.jp/issue/GW-7816
- Create sendNotificationToSlackUsers method
- Create getUserModel method
- Implement prepareSlackMessageForComment method
- Modify getMentionedUsers and getComment method and their return type
- Initialize and implement slackIntegrationService
- Update channel attribute of message variable in util/slack
- ### Mention `@username` in the comment 
- ### Slack notification
> Implement send notification to slack users

- packages/app/src/components/Admin/UserGroupDetail/UserGroupUserFormByInput.jsx
https://redmine.weseek.co.jp/issues/95974
> imprv: 95974 eliminate reload in adding name to group

- packages/app/src/server/models/page-operation.ts
- packages/app/src/server/service/page-operation.ts
- packages/app/src/server/service/page.ts
#5888 の後続タスクです
https://redmine.weseek.co.jp/issues/95971
> dynamically change isProcessable

- packages/app/src/interfaces/activity.ts
- packages/app/src/server/middlewares/add-activity.ts
- packages/app/src/server/models/activity.ts
- packages/app/src/server/service/activity.ts
- packages/app/src/server/service/in-app-notification.ts
[#96622](https://redmine.weseek.co.jp/issues/96622) [GROWI] [AuditLog] activity ドキュメントを生成する Express Middleware を実装する
└ [#96655](https://redmine.weseek.co.jp/issues/96655) 実装
> feat: add-activity express middleware

- packages/app/src/components/PageList/PageList.tsx
- packages/app/src/styles/theme/_apply-colors-dark.scss
- packages/app/src/styles/theme/_apply-colors.scss
- ページリストの色が真っ白で変だったので修正した
- task: https://redmine.weseek.co.jp/issues/96375
> feat: 96375-darktheme-pagelist-bg

- packages/app/test/cypress/integration/9-view-edit-hackmd/view-edit-hackmd.spec.ts
- Make view-edit-hackmd.spec.ts
- Create flow of view edit hackmd
- Make condition for hackmd first view button
- Assert screenshots each steps
- Check and debug the results
https://youtrack.weseek.co.jp/issue/GW-7729
> imprv: view edit hackmd vrt

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/client/services/page-operation.ts
- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/server/routes/apiv3/pages.js
https://redmine.weseek.co.jp/issues/93222
> feat: Fire resume rename operation from client side

- packages/app/src/components/Sidebar/PageTree/Item.tsx
https://redmine.weseek.co.jp/issues/93522
> show draw attention icon based on condition

- packages/app/src/server/crowi/index.js
- packages/app/src/server/events/activity.ts
- packages/app/src/server/routes/apiv3/logout.js
- packages/app/src/server/routes/apiv3/pages.js
- packages/app/src/server/routes/login-passport.js
- packages/app/src/server/service/activity.ts
- packages/app/src/server/service/in-app-notification.ts
[#96622](https://redmine.weseek.co.jp/issues/96622) [GROWI] [AuditLog] activity ドキュメントを生成する Express Middleware を実装する
└ [#96900](https://redmine.weseek.co.jp/issues/96900) activity の更新、inAppNotification を作成する EventEmitter を実装する
> feat: Activity Event Emitter

- packages/app/src/server/middlewares/api-rate-limiter.ts
- packages/app/src/server/util/api-rate-limit-config/defaultApiRateLimitConfig.ts
- packages/app/src/server/util/api-rate-limit-config/generateApiRateLimitConfig.ts
https://github.com/weseek/growi/pull/5953
の続き
追加修正
- 環境変数からtargetを取得する仕組みを改善
- 正規表現でtargetを取得する仕組みを改善
> feat: 96209 default config

- packages/app/src/components/Admin/Security/SecurityManagementContents.jsx
- packages/app/src/components/Admin/Security/SecuritySetting.jsx
- packages/app/src/components/Admin/Security/ShareLinkSetting.jsx
- packages/app/src/components/Admin/Security/TwitterSecuritySettingContents.jsx
- packages/app/src/components/Admin/UserGroupDetail/CheckBoxForSerchUserOption.jsx
- packages/app/src/components/Admin/Users/InviteUserControl.jsx
- packages/app/src/components/Admin/Users/UserRemoveButton.jsx
Target Task: [97111](https://redmine.weseek.co.jp/issues/97111)
> imprv: Convert to useTranslation 7 files

- packages/app/resource/locales/en_US/admin/admin.json
- packages/app/resource/locales/ja_JP/admin/admin.json
- packages/app/resource/locales/zh_CN/admin/admin.json
- packages/app/src/components/Admin/AuditLog/ActivityTable.tsx
> imprv: Activity table

- packages/app/src/server/service/page.ts
https://redmine.weseek.co.jp/issues/97386
https://dev.growi.org/62149d019311629d4ecd91cf#Handling%20of%20descendantCount%20in%20case%20of%20unexpected%20process%20interruption
> feat: Increase and decrease the number of parent's descendantCount in rename(Main/Sub)Operation

- packages/app/src/components/Admin/MarkdownSetting/PresentationForm.jsx
- packages/app/src/components/Admin/MarkdownSetting/WhiteListInput.jsx
- packages/app/src/components/Admin/MarkdownSetting/XssForm.jsx
- packages/app/src/components/Admin/Notification/GlobalNotification.jsx
- packages/app/src/components/Admin/Notification/GlobalNotificationList.jsx
- packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx
- packages/app/src/components/Admin/Notification/NotificationDeleteModal.jsx
- packages/app/src/components/Admin/Notification/TriggerEventCheckBox.jsx
- packages/app/src/components/Admin/Notification/UserNotificationRow.jsx
- packages/app/src/components/Admin/Notification/UserTriggerNotification.jsx
- packages/app/src/components/Admin/Security/BasicSecuritySettingContents.jsx
- packages/app/src/components/Admin/Security/DeleteAllShareLinksModal.jsx
[#96330](https://redmine.weseek.co.jp/issues/96330) [Omit Unstated] withTranslation を useTranslation に置き換える
└ [#97301](https://redmine.weseek.co.jp/issues/97301) 12個置き換えるD
> imprv: Replace withTranslation with useTranslation 

- packages/app/src/components/Admin/UserGroupDetail/RadioButtonForSerchUserOption.jsx
- packages/app/src/components/Admin/UserGroupDetail/UserGroupPageList.jsx
- packages/app/src/components/Admin/UserGroupDetail/UserGroupUserFormByInput.jsx
- packages/app/src/components/Admin/UserGroupDetail/UserGroupUserModal.jsx
- packages/app/src/components/Admin/UserGroupDetail/UserGroupUserTable.jsx
- packages/app/src/components/Admin/Users/ExternalAccountTable.jsx
- packages/app/src/components/Admin/Users/GiveAdminButton.jsx
- packages/app/src/components/Admin/Users/PasswordResetModal.jsx
- packages/app/src/components/Admin/Users/RemoveAdminButton.jsx
- packages/app/src/components/Admin/Users/StatusActivateButton.jsx
- packages/app/src/components/Admin/Users/StatusSuspendedButton.jsx
- packages/app/src/components/Admin/Users/UserInviteModal.jsx
- packages/app/src/components/Admin/Users/UserMenu.jsx
[#96330](https://redmine.weseek.co.jp/issues/96330) [Omit Unstated] withTranslation を useTranslation に置き換える
└ https://redmine.weseek.co.jp/issues/97348 12個置き換えるD
> imprv: integrate/convert to useTranslation in 13 files

- packages/app/src/server/service/file-uploader/gcs.js
https://redmine.weseek.co.jp/issues/97755
> feat: Get GCS instance that uses Application Default Credentials for v5

- packages/app/src/server/service/file-uploader/gcs.js
https://redmine.weseek.co.jp/issues/97756
> feat: Get GCS instance that uses Application Default Credentials for v4

- packages/app/src/server/routes/page.js
https://redmine.weseek.co.jp/issues/98623
削除するページが空ページの時に creatorId を実体のある祖先から取得
> feat: Inherit creator from the closest non-empty ancestor page if the page is empty on delete

- packages/app/src/client/services/PersonalContainer.js
- packages/app/src/components/Me/AssociateModal.jsx
- packages/app/src/components/Me/DisassociateModal.jsx
- packages/app/src/components/Me/ExternalAccountLinkedMe.jsx
- packages/app/src/interfaces/external-account.ts
- packages/app/src/stores/personal-settings.tsx
Omit Unstated] [SWR化] PersonalContainer
┗[98158](https://redmine.weseek.co.jp/issues/98158) apiv3Get /personal-setting/external-accounts をSWR化
https://user-images.githubusercontent.com/59536731/175013872-09ac77e9-c803-4180-8e7e-7c86767030c2.mov
> imprv/ SWRize apiv3 get personal external accounts

- packages/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
ストーリー: https://redmine.weseek.co.jp/issues/98564
issue: https://github.com/weseek/growi/issues/6099
> fix: issue slack integration

- packages/app/test/cypress/integration/20-basic-features/click-page-icons.spec.ts
https://youtrack.weseek.co.jp/issue/GW-7730
- Create spec file for click page icons
- Add test for subscribe/unsubscribe, like/dislike, bookmark/unbookmark and display list of seen by user
> support: gw7730 VRT click page icons

- packages/app/src/server/crowi/express-init.js
- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/views/widget/page_alerts.html
https://redmine.weseek.co.jp/issues/98997
> feat: Remove getGrantLabels and use i18n

- packages/app/src/components/PageAlert/PageAlerts.tsx
- packages/app/src/components/PageAlert/PageStaleAlert.tsx
- packages/app/src/interfaces/page.ts
- packages/app/src/pages/[[...path]].page.tsx
- packages/app/src/server/service/page.ts
- packages/app/src/stores/context.tsx
https://redmine.weseek.co.jp/issues/98986
> feat: Implement page stale alert

- packages/app/src/components/Admin/SlackIntegration/DeleteSlackBotSettingsModal.jsx
- packages/app/src/components/Admin/Users/StatusSuspendMenuItem.tsx
- packages/app/src/components/Common/ClosableTextInput.tsx
タスク：https://redmine.weseek.co.jp/issues/99077
もともとsupport/apply-nextjs-2に直コミットしても良かったのですが、不安なのでレビューお願いします。
> Fix: displayname eslint error

- packages/app/src/components/BasicLayout.tsx
- packages/app/src/components/Page.jsx
- packages/app/src/components/PageEditor.tsx
- packages/app/src/components/PageEditorByHackmd.jsx
- packages/app/src/pages/[[...path]].page.tsx
https://github.com/weseek/growi/pull/6154 のPR によるlint err を修正
> fix lint errs

- packages/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
- packages/app/src/server/service/search-delegator/elasticsearch.ts
ストーリー: https://redmine.weseek.co.jp/issues/98564
issue: https://github.com/weseek/growi/issues/6099
> fix: Slack integration connection test

- packages/app/src/components/BookmarkButtons.tsx
- packages/app/src/components/LikeButtons.tsx
- packages/app/src/components/Navbar/SubNavButtons.tsx
- packages/app/src/components/SubscribeButton.tsx
- packages/app/src/components/User/SeenUserInfo.tsx
- packages/app/src/styles/atoms/_buttons.scss
target ticket:https://redmine.weseek.co.jp/issues/99672
・アイコンを変更したい
・Subscribe buttonだけ, box-shadowがついている.
・他と合わせてbox-shadowがつかないように修正.
> imprv: update subscribe button icon on Navbar

- packages/app/src/components/Sidebar.tsx
https://redmine.weseek.co.jp/issues/99271
> feat :Display navigation resize hexagon

- packages/app/src/components/CompleteUserRegistrationForm.tsx
- packages/app/src/components/InstallerForm.jsx
- packages/app/src/server/routes/apiv3/index.js
- packages/app/src/server/routes/index.js
- packages/app/src/server/views/invited.html
- packages/app/src/server/views/login.html
[GROWI] get check_username を apiv3に統一させる
┗ [99929](https://redmine.weseek.co.jp/issues/99929) 修正
マージはまだやらずにお願いします。
動作確認後にマージ依頼出します。
> fix: Use APIv3 for api get check_username

- packages/app/src/components/DescendantsPageListModal.tsx
- packages/app/src/components/Page/DisplaySwitcher.tsx
- packages/app/test/cypress/integration/20-basic-features/access-to-pagelist.spec.ts
https://youtrack.weseek.co.jp/issue/GW-7741
- Create spec file for vrt pagelist
- Add test for access pagelist and timeline
- Add data-testid attribute to page list button
- Add  data-testid attribute to page list modal
> support: gw7741 VRT pagelist

- packages/app/src/components/Sidebar.tsx
https://redmine.weseek.co.jp/issues/100031
> feat: Remove useEffect to enable transition for sidebar mode

- packages/app/src/components/Sidebar.tsx
Target task: https://redmine.weseek.co.jp/issues/100071
- dynamic インポートから static インポートに修正
> feat: update static import NavigationResizeHexagon

- packages/app/src/services/renderer/growi-renderer.ts
- packages/app/src/stores/renderer.tsx
> support: Refactor growi renderer using hooks 2

- packages/app/src/components/TableOfContents.tsx
https://redmine.weseek.co.jp/issues/100207
上のタスクのts化の部分のみのPR
tocをts化しました
> imprv: typescriptize toc

- packages/app/src/components/Sidebar/Bookmarks.tsx
- packages/app/src/components/Sidebar/SidebarContents.tsx
- packages/app/src/components/Sidebar/SidebarNav.tsx
- packages/app/src/interfaces/ui.ts
https://youtrack.weseek.co.jp/issue/GW-7831
- Add bookmarks to SidebarContentsType
- Add bookmarks button to sidebar
- Add bookmark item to sidebar content
- Create Bookmarks component (empty item but has a title)
> feat: add bookmark item on the sidebar

- packages/app/src/server/crowi/express-init.js
- packages/app/src/server/service/config-loader.ts
> feat: Made 'trust proxy' for express configurable
