growilabs/growi

packages/app/src/server/crowi/express-init.js
packages/app/src/server/service/config-loader.ts

imprv: Corrected to WESEEK style

---

packages/app/src/components/Layout/BasicLayout.tsx
packages/app/src/server/crowi/express-init.js

https://redmine.weseek.co.jp/issues/100659

feat: Render duplicate modal

---

packages/app/src/components/Layout/BasicLayout.tsx
packages/app/src/server/routes/apiv3/users.js

https://redmine.weseek.co.jp/issues/100660
https://redmine.weseek.co.jp/issues/100661

feat: Render Page Rename/Delete Modal

---

packages/app/src/components/Layout/BasicLayout.tsx
packages/app/src/components/PageCreateModal.jsx

https://redmine.weseek.co.jp/issues/100671

render page create modal

---

packages/app/src/stores/ui.tsx
packages/core/src/utils/with-utils.ts

https://redmine.weseek.co.jp/issues/100641

feat: Improve withUtils type check

---

packages/app/src/styles/_vendor.scss
packages/app/src/styles/style-next.scss

https://redmine.weseek.co.jp/issues/100837

addstyle for simplebar to enable scroll on sidebar

---

packages/app/src/components/Navbar/GrowiSubNavigation.module.scss
packages/app/src/components/Navbar/GrowiSubNavigationSwitcher.jsx
packages/app/src/components/Navbar/GrowiSubNavigationSwitcher.module.scss
packages/app/src/pages/[[...path]].page.tsx

https://redmine.weseek.co.jp/issues/100937
- GrowiSubNavigationSwitcherを表示

show GrowiSubNavigationSwitcher

---

packages/app/src/server/routes/login-passport.js

[#100955](https://redmine.weseek.co.jp/issues/100955) [AuditLog][Bug] ログインした際に作成される activity ドキュメントに username が保存されない
└ [#100956](https://redmine.weseek.co.jp/issues/100956) 修正

fix: Username is not saved in activity

---

packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/Sidebar/CustomSidebar.tsx
packages/app/src/components/Sidebar/SidebarContents.tsx

https://redmine.weseek.co.jp/issues/99841

feat: Render custom sidebar with i18n

---

packages/app/src/migrations/20220613064207-add-attachment-type-to-existing-attachments.js

https://youtrack.weseek.co.jp/issue/GW-7822
- Create migration for attachmentType of existing attachments

feat: create migration for attachmentType of existing attachments

---

packages/app/src/components/Theme/ThemeJadeGreen.module.scss
packages/app/src/components/Theme/ThemeJadeGreen.tsx
packages/app/src/components/Theme/utils/ThemeProvider.tsx

https://redmine.weseek.co.jp/issues/100736

feat: Apply theme jade-green

---

packages/app/src/components/Layout/BasicLayout.tsx
packages/app/src/components/PagePresentationModal.jsx
packages/app/src/components/PagePresentationModal.module.scss

https://redmine.weseek.co.jp/issues/100678
プレゼンテーションモーダルの表示
プレゼンテーション形式での表示（別タスク対応：https://redmine.weseek.co.jp/issues/101068）

render presentation modal

---

packages/app/src/components/Theme/ThemeFireRed.module.scss
packages/app/src/components/Theme/ThemeFireRed.tsx
packages/app/src/components/Theme/utils/ThemeProvider.tsx

[Next.js] テーマのスタイルを動的にロードできる
┗[100730](https://redmine.weseek.co.jp/issues/100730) ThemeFireRed を有効化する
https://user-images.githubusercontent.com/59536731/180749999-be7d3cff-8114-470e-8d8f-11f77d00bb25.mov

apply fire-red theme

---

packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/Page/FixPageGrantAlert.tsx

issue: https://github.com/weseek/growi/issues/6005
task: https://redmine.weseek.co.jp/issues/101317
- add a grant label in case of public

fix: "Error: cannnot get grant label" occured with lsx

---

packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/Page/FixPageGrantAlert.tsx

issue: https://github.com/weseek/growi/issues/6005
task: https://redmine.weseek.co.jp/issues/101317
- add a grant label in case of public

fix: "Error: cannnot get grant label" occured with lsx (for v5.0.x)

---

packages/app/src/interfaces/activity.ts

[#101392](https://redmine.weseek.co.jp/issues/101392) [AuditLog] 削除関連のアクション（完全削除、ゴミ箱を空にする）を SMALL グループに含める
└ [#101394](https://redmine.weseek.co.jp/issues/101394) 実装

imprv(auditlog): Include delete-related actions in small group

---

packages/app/src/components/Sidebar/Bookmarks.tsx

https://youtrack.weseek.co.jp/issue/GW-7847
- Disable fade transition of UncontrolledTooltip

fix: Fix tooltip behavior

---

.devcontainer/devcontainer.json
packages/app/package.json
packages/app/src/components/ShareLink/ShareLink.jsx
packages/app/src/components/ShareLink/ShareLinkList.tsx
packages/app/src/migrations/20211129125654-initialize-private-legacy-pages-named-query.js
packages/app/src/server/middlewares/inject-reset-order-by-token-middleware.ts
packages/app/src/server/middlewares/inject-user-registration-order-by-token-middleware.ts
packages/app/src/server/models/password-reset-order.ts
packages/app/src/server/models/user-registration-order.ts
yarn.lock

タスク：https://redmine.weseek.co.jp/issues/100966
TS化とSWR化はタスクを切って着手するつもりです！
レビューお願いします！

support: Update cc to fc sharelink

---

packages/app/src/pages/installer.page.tsx

next化においてinstallerページのデザインを修正する。
以下タスク参照。
https://redmine.weseek.co.jp/issues/101249

support: Modify and brush up the installer page design

---

.devcontainer/devcontainer.json
packages/app/src/components/ShareLink/ShareLink.jsx

タスク：https://redmine.weseek.co.jp/issues/100966
元PR：https://github.com/weseek/growi/pull/6362

support: Fc update sharelink use cherry pick

---

packages/app/src/pages/[[...path]].page.tsx
packages/app/src/server/models/page-redirect.ts
packages/app/test/integration/models/page-redirect.test.js

https://redmine.weseek.co.jp/issues/100384

imprv: Implement page redirection

---

packages/app/src/components/Common/Dropdown/PageItemControl.tsx
packages/app/src/components/Sidebar/PageTree/Item.tsx
packages/app/src/interfaces/page-operation.ts
packages/app/src/server/crowi/index.js
packages/app/src/server/models/page-operation.ts
packages/app/src/server/routes/apiv3/pages.js
packages/app/src/server/service/page-operation.ts
packages/app/src/server/service/page.ts
packages/app/src/utils/page-operation.ts
packages/app/test/integration/service/v5.page.test.ts
packages/app/test/integration/service/v5.public-page.test.ts

Redmine: 
https://redmine.weseek.co.jp/issues/101639
https://redmine.weseek.co.jp/issues/101640
https://redmine.weseek.co.jp/issues/101641
ページのパス修復機能の修正

fix: Fix page path

---

packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts

Fix In-app notification VRT
https://youtrack.weseek.co.jp/issue/GW-7852

fix: In-app notification VRT

---

packages/app/src/components/Common/Dropdown/PageItemControl.tsx
packages/app/src/components/SearchPage/SearchResultContent.tsx
packages/app/src/server/views/layout/layout.html
packages/app/src/stores/ui.tsx

https://youtrack.weseek.co.jp/issue/GW-7844
- Create method to change body class
- Remove change body class from useEffect
- Update condition to add body class by page.isContainerFluid

fix: gw7844 fix flickering problem on view change

---

packages/app/src/components/Admin/AuditLog/DateRangePicker.tsx
packages/app/src/styles/_admin.scss

[#101680](https://redmine.weseek.co.jp/issues/101680) [AuditLog] 期間検索部分の UI 改善
└ [#101688](https://redmine.weseek.co.jp/issues/101688) 実装
https://user-images.githubusercontent.com/34241526/182506474-0e495071-5ba9-4fa2-ab41-9a94838892db.mov

imprv(auditlog): Date Range Picker 

---

packages/app/src/components/Navbar/GrowiSubNavigationSwitcher.jsx

[GROWI][Next.js][Admin][Customize以外] 残存の不具合を修正し、全てのページで正常に表示 & 更新ができる
┗[101819](https://redmine.weseek.co.jp/issues/101819) [fix] TypeError: Cannot read properties of null (reading 'bottom')

TypeError: Cannot read properties of Cannot read properties of null (reading 'bottom')

---

packages/app/src/components/InstallerForm.jsx

[#101207](https://redmine.weseek.co.jp/issues/101207) [Next.js] Installerページ　i18nとスタイルの修正
└ [#101953](https://redmine.weseek.co.jp/issues/101953) installerForm で changeLanguage を機能させる

fix: Make change language work

---

lerna.json
package.json
packages/app/package.json
packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/Page/FixPageGrantAlert.tsx
packages/codemirror-textlint/package.json
packages/core/package.json
packages/plugin-attachment-refs/package.json
packages/plugin-lsx/package.json
packages/plugin-pukiwiki-like-linker/package.json
packages/slack/package.json
packages/slackbot-proxy/package.json
packages/ui/package.json

* fix: "Error: cannnot get grant label" occured with lsx (for v5.0.x) (#6352) @yukendev

Release v5.0.12

---

packages/app/src/components/PageAlert/PageRedirectedAlert.tsx
packages/app/src/pages/[[...path]].page.tsx
packages/app/src/stores/context.tsx
packages/app/src/stores/page-redirect.tsx

https://redmine.weseek.co.jp/issues/101741

feat: Unlink pages

---

packages/app/src/components/ShareLink/ShareLink.tsx
packages/app/src/interfaces/share-link.ts

タスク：https://redmine.weseek.co.jp/issues/101564

support: Update js to ts

---

packages/app/src/components/Page.tsx
packages/app/src/components/Page/RevisionRenderer.tsx
packages/app/src/services/renderer/renderer.ts
packages/app/src/stores/context.tsx
packages/app/src/stores/renderer.tsx

Redmine: https://redmine.weseek.co.jp/issues/102294
TOC が表示されるように修正しました

fix: Show toc correctly

---

packages/app/src/components/Sidebar/PageTree/PrivateLegacyPagesLink.tsx
packages/app/src/pages/_private-legacy-pages.page.tsx
packages/app/src/server/routes/index.js

https://redmine.weseek.co.jp/issues/102682
- PrivateLegacyページを表示する
スタイルを当てるのは別タスクでやります（https://redmine.weseek.co.jp/issues/102700）

imprv: 101262 next private legacy page

---

packages/app/src/components/PageEditorByHackmd.tsx
packages/app/src/interfaces/hackmd.ts

https://redmine.weseek.co.jp/issues/100171
やったこと
- PageEditorByHackmdのtypescript化
- EditorContainerの削除
AppContainerとPageContainerの削除は割と大きな改修になりそうだったのでPRを分けます

imprv: 100171 typescriptize page editor by hackmd

---

packages/app/src/components/ContentLinkButtons.tsx
packages/app/src/components/Icons/RecentlyCreatedIcon.tsx

タスク: [103108](https://redmine.weseek.co.jp/issues/103108)
- RecentlyCreatedIcon のNext化
- import先, grepして app.jsx 以外修正

supprot: Create RecentlyCreatedIcon.tsx

---

packages/app/src/components/PageEditor.tsx
packages/app/src/components/SavePageControls.tsx
packages/app/src/pages/[[...path]].page.tsx

[GROWI][Nextjs化] Editorでページの保存 / 編集 ができる
┗[103282](https://redmine.weseek.co.jp/issues/103282) GRANT_PUBLIC 等の const を @growi/core にし、参照する
ページ新規作成時に isUsersHomePageを使っている部分 でエラーが表示されてしまっていたので修正しました。

Imprv/103282 use grant type and fix isUsersHomePage err

---

packages/app/package.json
packages/app/src/server/views/widget/headers/drawio.html
yarn.lock

https://user-images.githubusercontent.com/1567423/186660507-a11c3b08-43a3-4d45-970f-ec09edd093aa.mov
* Update markdown-it-drawio (`1.3.1` -> `1.4.0`)
* https://github.com/kaishuu0123/markdown-it-drawio-viewer/commit/cce4f00a451f7699aead4b4abcf36d0d20ec4993
* refs: https://www.diagrams.net/doc/faq/embed-html-options
* Set z-index for drawio's lightbox.
* `packages/app/src/server/views/widget/headers/drawio.html`

imprv: Improvement behavior when click on drawio diagram.

---

packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
packages/app/src/server/routes/tag.js

[#102203](https://redmine.weseek.co.jp/issues/102203) [GROWI][bug] Viewモードでタグを更新した時に、ページの最終編集者の名前で「xxx さんがこのページを編集しました。」と表示されてしまう
└ [#103060](https://redmine.weseek.co.jp/issues/103060) 修正

fix: Label of alert when updating tags

---

packages/app/src/components/Layout/BasicLayout.tsx
packages/app/src/components/PageComment/DeleteCommentModal.tsx
packages/app/src/components/PageCreateModal.jsx
packages/app/src/components/PageDeleteModal.tsx
packages/app/src/components/PageDuplicateModal.tsx
packages/app/src/components/PageRenameModal.tsx
packages/app/src/components/PutbackPageModal.jsx
packages/app/src/components/ShortcutsModal.tsx
packages/app/src/pages/[[...path]].page.tsx

https://redmine.weseek.co.jp/issues/101510
- 軽そうなものは除いて、以下Modal内の要素を右の関数の中に移動
- ModalHeader => headerContent
- ModalBody => bodyContent
- ModalFooter => footerContent
- useEffect 内の処理を不要なタイミングで実行しないように修正
- Component 内での dyamic import を見つけたのでついでに修正

feat: Optimize rendering modal performance

---

packages/app/src/pages/[[...path]].page.tsx

タスク: [103190](https://redmine.weseek.co.jp/issues/103190)
- flexの有効化

imprv: Enable flex layout

---

packages/app/src/components/Layout/BasicLayout.tsx
packages/app/src/components/PageAccessoriesModal.tsx

https://redmine.weseek.co.jp/issues/100680
最適化したモーダルの表示
内部データの適切な表示
- シェアリンクの作成
- https://redmine.weseek.co.jp/issues/103648
- attachment list の表示
- https://redmine.weseek.co.jp/issues/103649
- 更新履歴の差分の style 適用
- https://redmine.weseek.co.jp/issues/103647

feat: Render page accessories modal

---

packages/app/src/components/PageHistory/Revision.jsx
packages/app/src/components/PageHistory/RevisionDiff.jsx

https://redmine.weseek.co.jp/issues/104251

Fix: Render old revision alert

---

packages/app/src/server/routes/apiv3/page.js

https://redmine.weseek.co.jp/issues/104280

fix: Disallow retrieval of revision data that does not match the page for v4

---

packages/app/src/components/Page/RevisionRenderer.tsx
packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts

100752 [GROWI][Nextjs] Built-in Editorでeditorとpreviewの表示ができる
┗[103606](https://redmine.weseek.co.jp/issues/103606) ReactMarkdown にRevisionBodyのidを追加する

fix vrt related to ReactMarkdown

---

packages/app/src/styles/style-next.scss

https://redmine.weseek.co.jp/issues/104242

feat: Render three dot btn icon for pagetree

---

packages/app/src/server/service/global-notification/global-notification-mail.js
packages/app/src/server/service/global-notification/index.js

Redmine: https://redmine.weseek.co.jp/issues/104510
メール本文にページの URL が含まれるように改善

imprv: Added page URL to mail subject

---

packages/app/src/server/service/global-notification/global-notification-mail.js
packages/app/src/server/service/global-notification/index.js

Redmine: https://redmine.weseek.co.jp/issues/104511
https://github.com/weseek/growi/pull/6554 の apply-nextjs-2 用

imprv: Add full page url to mail subject for apply nextjs 2

---

packages/app/src/server/routes/index.js

https://redmine.weseek.co.jp/issues/104361
non-admin user での /admin アクセスによるリダイレクト確認済み

fix: Redirect access from non admin user

---

packages/app/src/components/Common/ClosableTextInput.tsx
packages/app/src/components/Sidebar/PageTree/Item.tsx
packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts

Redmine: https://redmine.weseek.co.jp/issues/104067
https://github.com/weseek/growi/pull/6525 を apply-nextjs-2 にマージ

fix: PageTree input for apply nextjs 2

---

packages/app/src/components/IdenticalPathPage.tsx
packages/app/src/pages/[[...path]].page.tsx

https://redmine.weseek.co.jp/issues/104244

feat: Render identical path page

---

packages/app/src/client/services/ContextExtractor.tsx
packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
packages/app/src/components/Navbar/GrowiSubNavigation.tsx
packages/app/src/components/Page/DisplaySwitcher.tsx
packages/app/src/pages/[[...path]].page.tsx
packages/app/src/stores/context.tsx
packages/app/src/stores/ui.tsx

タスク: [104427](https://redmine.weseek.co.jp/issues/104427)

fix: Rendering button on UserPages

---

packages/app/docker/Dockerfile
packages/app/next.config.js
packages/plugin-lsx/package.json

Redmine: https://redmine.weseek.co.jp/issues/103391
v6 の GROWI を production build できるように Dockerfile とその他の設定を改善しました

support: Configure rc deployment for apply nextjs 2

---

packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts

https://redmine.weseek.co.jp/issues/105041

support: Add cy.collapseSidebar(false) to use-tools.spec.ts

---

packages/app/src/server/service/installer.ts

Redmine: https://redmine.weseek.co.jp/issues/105026
Sandbox ページの作成順序を保証するように改善しました

imprv: Ensure initial pages order

---

packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts

[#105029](https://redmine.weseek.co.jp/issues/105029) タグ追加時のトースターの透明度を一定にする

imprv: Constant toastr transparency (VRT)

---

packages/app/test/cypress/integration/21-basic-features-for-guest/access-to-page.spec.ts
packages/app/test/cypress/support/commands.ts
packages/app/test/cypress/support/index.ts

https://redmine.weseek.co.jp/issues/105093

support: Activate collapse sidebar for guest user's access to page

---

packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
packages/app/test/cypress/integration/21-basic-features-for-guest/access-to-page.spec.ts

タスク: https://redmine.weseek.co.jp/issues/105088

support: Update access-to-page.spec.ts for VRT normalization

---

packages/app/package.json
packages/app/resource/locales/en_US/sandbox-diagrams.md
packages/app/resource/locales/ja_JP/sandbox-diagrams.md
packages/app/resource/locales/zh_CN/sandbox-diagrams.md
packages/app/src/services/renderer/remark-plugins/plantuml.ts
packages/app/src/services/renderer/renderer.tsx
yarn.lock

~~~ plantuml
@startuml
class SimplePlantUMLPlugin {
+ transform(syntaxTree: AST): AST
}
@enduml
~~~
~~~ plantuml
``` plantuml
class SimplePlantUMLPlugin {
+ transform(syntaxTree: AST): AST
}
```
~~~
or
~~~ plantuml
``` plantuml
@startuml
class SimplePlantUMLPlugin {
+ transform(syntaxTree: AST): AST
}
@enduml
```
~~~

feat: PlantUML with remark-simple-plantuml

---

packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts

https://redmine.weseek.co.jp/issues/105232

support: wait for toastr to change its color occured by mouseover

---

packages/app/src/server/routes/index.js
packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts

https://redmine.weseek.co.jp/issues/105207

support: Close sidebar in unnecessary pages

---

packages/app/src/server/crowi/express-init.js
packages/app/src/server/service/app.ts

Redmine: https://redmine.weseek.co.jp/issues/105124
Installer が動くようにしました。
- `req.t` は別ストーリーで整備予定っぽいでこのタスクではワークアラウンドにしました。

fix: Normalize installer

---

packages/app/src/components/Page/TagLabels.tsx
packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts

https://redmine.weseek.co.jp/issues/105271

support: Take screenshot after #grw-tag-labels is visible for VRT normalization

---

packages/app/src/components/PrivateLegacyPages.tsx
packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
packages/app/test/cypress/integration/30-search/search.spec.ts

タスク:https://redmine.weseek.co.jp/issues/105240

support: Update search.spec.ts use-tools.spec.ts for VRT normalization

---

packages/app/src/server/service/installer.ts

Redmine: https://redmine.weseek.co.jp/issues/105262
この改修で [こちら](https://growi-vrt-snapshots.s3.amazonaws.com/0d8c68401ad4bb11e59d1be5204abf0ebe8c6d75/index.html?id=changed-30-search/search.spec.ts/search-all-pages-1-insert-search-text-with-tag.png) の VRT が治ります

imprv: VRT search by tag

---

packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
packages/app/test/cypress/integration/30-search/search.spec.ts

タスク：https://redmine.weseek.co.jp/issues/105298

support: Update search.spec.ts for VRT normalization

---

packages/app/src/server/service/installer.ts

Redmine: https://redmine.weseek.co.jp/issues/105269

imprv: VRT search by tag for apply-nextjs-2

---

packages/app/test/cypress/integration/21-basic-features-for-guest/access-to-page.spec.ts

Redmine: https://redmine.weseek.co.jp/issues/105267
[こちら](https://growi-vrt-snapshots.s3.amazonaws.com/0d8c68401ad4bb11e59d1be5204abf0ebe8c6d75/index.html?id=changed-21-basic-features-for-guest/access-to-page.spec.ts/access-to-page-by-guest--sandbox-headers.png) の VRT を正常化

imprv: VRT access to page by guest

---

packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/LoginForm.tsx
packages/app/src/pages/login.page.tsx
packages/app/src/server/middlewares/register-form-validator.ts
packages/app/src/server/routes/apiv3/index.js
packages/app/src/server/routes/index.js
packages/app/src/server/routes/login.js

以下４つまとめたPR
https://redmine.weseek.co.jp/issues/104523
https://redmine.weseek.co.jp/issues/104532
https://redmine.weseek.co.jp/issues/104537
https://redmine.weseek.co.jp/issues/104744
- 新規登録のリクエストを XHRリクエストに変更
- サーバーサイドでの req.t を廃止
- リダイレクト先に表示する req.flash を廃止
- エラーメッセージはそのページのフォーム内で表示するように変更
- LoginForm を TS/FC化
- middlewareで発生するエラーも新規登録フォームでエラーとして表示
- サーバー側ではなくクライアントでリダイレクトするように変更

feat: Use XHR for POST /register

---

packages/app/test/cypress/integration/30-search/search.spec.ts

https://redmine.weseek.co.jp/issues/105390
対象のVRT
https://growi-vrt-snapshots.s3.amazonaws.com/1f843d47edcc5b947fab253cf8a079cdb7f7de87/index.html?id=changed-30-search/search.spec.ts/search-all-pages-3-search-page-results.png
waitで確実にスクロールを待ってからスクショを撮るようにしました。

support: VRT fix scroll timing

---

packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts

[#105461](https://redmine.weseek.co.jp/issues/105461) エラーモーダル

imprv: Remove unnecessary test

---

packages/app/src/pages/tags.page.tsx

[#104172](https://redmine.weseek.co.jp/issues/104172) [Nextjs]Hydration-errorで全てのタグを表示できない
└ [#105595](https://redmine.weseek.co.jp/issues/105595) 修正

fix: Hydration error on tags page

---

packages/app/src/client/util/smooth-scroll.ts
packages/app/src/components/Fab.tsx
packages/app/src/components/Icons/CreatePageIcon.tsx
packages/app/src/components/Icons/ReturnTopIcon.tsx
packages/app/src/components/Layout/BasicLayout.tsx
packages/app/src/components/Layout/SearchResultLayout.tsx
packages/app/src/components/Navbar/GrowiNavbar.tsx

タスク: [104686](https://redmine.weseek.co.jp/issues/104686), [103754](https://redmine.weseek.co.jp/issues/103754)
- Fab関連のファイルをtsx化しました。
- sticky-eventsエラー回避のため、GrowiSubNavigationSwitcher.jsx を参考に、Fab.tsx 内でコメントアウトしました。
sticky-events関連の後続タスク:[102126](https://redmine.weseek.co.jp/issues/102126)

feat: Avoid Fab sticky-events errors

---

packages/app/src/components/Layout/BasicLayout.tsx

https://redmine.weseek.co.jp/issues/105449
HotkeysManagerのレンダリングまで。
- 打鍵による各ショートカットの起動（のみ）は確認済み。
- 例：実際にミラーモードなるかどうかはスコープ外

feat: Activate HotkeysManager

---

packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/Admin/Customize/CustomizeLogoSetting.tsx
packages/app/src/components/Common/ImageCropModal.tsx
packages/app/src/components/Me/ProfileImageSettings.tsx

https://youtrack.weseek.co.jp/issue/GW-7876
- Add isShouldCrop prop type
- Add method to convert base64 to blob
- Modify crop method based on isCropImage state
- Add conditional rendering of Image crop according to isCropImage value
- Show toggle checkbox of crop option on Image crop Modal
- Update crop/save translation according isCropImage value
- Add onModalCloseHandler  method to clear uploadedLogoSrc and close modal
- Call onModalCloseHandler on crop completed
- Implement onModalCloseHandler
- Adjust props of CustomizeLogoSetting and ProfileImageSettings component

Add option to crop logo

---

packages/app/src/components/Layout/ShareLinkLayout.tsx

Buildエラー修正
一行かつ他に影響しないため ryoji-s (@jam411) がマージします。

support: Update Fab dynamic import to ShareLinkLayout.tsx

---

packages/app/src/components/Fab.tsx

grw-bg-image-wrapperに wiki等が隠れる の修正

support: Enable Fab

---

packages/app/src/components/Common/Dropdown/PageItemControl.tsx
packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts

VRT正常化_2022_09_16
┗ [105462](https://redmine.weseek.co.jp/issues/105462) 検索ページ3点ボタンメニュー

fix: VRT page-control-item-menu on search page

---

packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
packages/app/src/components/PagePathNav.tsx

タスク: 
https://redmine.weseek.co.jp/issues/105624
https://redmine.weseek.co.jp/issues/105625

fix: Update PagePathHierarchicalLink for hydration error

---

packages/app/src/components/PasswordResetExecutionForm.tsx
packages/app/src/pages/forgot-password-errors.page.tsx
packages/app/src/pages/reset-password.page.tsx
packages/app/src/server/middlewares/inject-reset-order-by-token-middleware.ts
packages/app/src/server/routes/forgot-password.ts
packages/app/src/server/routes/index.js

[#104170](https://redmine.weseek.co.jp/issues/104170) [Next.js] Forgot Password? をレンダリングし、機能させる
└ [#104986](https://redmine.weseek.co.jp/issues/104986) forgot-password/:token をレンダリングできる

feat: Render reset password page

---

packages/app/src/components/PageComment/CommentEditor.tsx

タスク: https://redmine.weseek.co.jp/issues/105828
- CommentEditor での有効無効化を選べる
- Slack名入力できるように修正
- `EditorNavbarBotton.tsx` 参考

feat: Update CommentEditor for enable SlackChannels

---

packages/app/src/styles/molecules/toastr.scss
packages/app/src/styles/style-next.scss

https://redmine.weseek.co.jp/issues/105959
style が付与されていないだけだったので master を参考に `:root`下で import

feat: Display toastr success/error

---

packages/app/src/components/InvitedForm.tsx
packages/app/src/server/middlewares/invited-form-validator.ts
packages/app/src/server/routes/apiv3/invited.ts
packages/app/src/server/routes/login.js

タスク:https://redmine.weseek.co.jp/issues/104290

feat: Exception handling

---

packages/app/src/components/InvitedForm.tsx
packages/app/src/components/Layout/NoLoginLayout.module.scss

タスク: https://redmine.weseek.co.jp/issues/104295
- 横幅は `NologinLayout.module.scss` で全体に影響するので未調整

feat: Attach styles

---

packages/app/src/components/ReactMarkdownComponents/CodeBlock.module.scss
packages/app/src/styles/atoms/_code.scss
packages/app/src/styles/atoms/_mixins.scss
packages/app/src/styles/style-next.scss
packages/app/src/styles/theme/_apply-colors.scss

imprv: Add style for code element

---

packages/app/src/components/Admin/Customize/CustomizeCssSetting.tsx
packages/app/src/components/Admin/Customize/CustomizeFunctionSetting.tsx
packages/app/src/components/Admin/Customize/CustomizeHeaderSetting.tsx
packages/app/src/components/Admin/Customize/CustomizeHighlightSetting.tsx
packages/app/src/components/Admin/Customize/CustomizeLogoSetting.tsx
packages/app/src/components/Admin/Customize/CustomizeScriptSetting.tsx
packages/app/src/components/Admin/Customize/CustomizeThemeSetting.tsx
packages/app/src/components/Admin/Customize/CustomizeTitle.tsx

https://redmine.weseek.co.jp/issues/106351

fix: i18n in Customize Settings

---

packages/app/src/client/services/AdminCustomizeContainer.js
packages/app/src/components/Admin/Customize/CustomizeFunctionSetting.tsx
packages/app/src/migrations/20221014130200-remove-customize-is-saved-states-of-tab-changes.js
packages/app/src/server/models/config.ts
packages/app/src/server/routes/apiv3/customize-setting.js

https://redmine.weseek.co.jp/issues/106493

feat: Remove config customize:isSavedStatesOfTabChanges and add migration to remove the data from DB

---

packages/app/src/client/services/PageContainer.js
packages/app/src/client/util/editor.ts
packages/app/src/components/PageEditor.tsx
packages/app/src/components/PageEditor/ConflictDiffModal.tsx
packages/app/src/server/crowi/dev.js

[GROWI][Issue][Bug] コンフリクト解消モーダルから3つの選択肢のどれを選んでも「解消し保存する」ボタンを押すと「r.getCurrentOptionsToSave is not a function」エラーが出て保存できない。
┗[106336](https://redmine.weseek.co.jp/issues/106336) 修正
https://user-images.githubusercontent.com/59536731/195782841-a8c69b1e-5d0c-4ba6-abb6-afa625aa8f11.mov

fix: Conflict Diff Modal Error getCurrentOptionsToSave is not a function

---

packages/app/docker/Dockerfile

https://redmine.weseek.co.jp/issues/106406
- プロダクションビルド時にpackages/hackmdもビルドに加えた

add hackmd to packages

---

packages/app/src/components/DescendantsPageList.tsx
packages/app/src/components/SearchPage.tsx
packages/app/src/pages/_search.page.tsx
packages/app/src/pages/trash.page.tsx
packages/app/src/stores/context.tsx
packages/app/src/stores/page-listing.tsx

https://redmine.weseek.co.jp/issues/106122
以下画像の内、下2つの設定が適用されるようにした。
customize:isSavedStatesOfTabChanges の廃止は [106493](https://redmine.weseek.co.jp/issues/106493) で対応予定

feat: Enable function section in admin/customize

---

packages/app/src/components/LoginForm.tsx

https://redmine.weseek.co.jp/issues/106657

fix: Cannot login because of the error occured by passing undefined/null to router.push()

---

packages/app/src/server/routes/apiv3/g2g-transfer.ts
packages/app/src/server/service/g2g-transfer.ts

https://redmine.weseek.co.jp/issues/106418

feat: check write permission before g2g

---

packages/app/src/pages/[[...path]].page.tsx

https://redmine.weseek.co.jp/issues/106561
https://growi-vrt-snapshots.s3.amazonaws.com/5df4142683cc8c101c26bd217210205fe3f314df/index.html?id=changed-20-basic-features/access-to-page.spec.ts/Access%20to%20Template%20Editing%20Mode%20--%20Access%20to%20Template%20Editor%20mode%20including%20decendants%20successfully%20(failed).png

support: Add missing div with id=grw-subnav-container

---

packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
packages/app/src/components/PageEditor/Editor.tsx

Redmine: https://redmine.weseek.co.jp/issues/106654
KeyMap のロードがエディタでの入力のたびに発生してしまう問題を修正

fix: Load KeyMap correctly

---

packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/Page.tsx
packages/app/src/components/PageEditor.tsx

https://redmine.weseek.co.jp/issues/107028

fix: Show toastr 

---

packages/app/src/components/Admin/ElasticsearchManagement/ElasticsearchManagement.tsx

[#107082](https://redmine.weseek.co.jp/issues/107082) 修正21

fix: Normalize VRT (task-21)

---

packages/app/src/components/Fab.tsx

[#107086](https://redmine.weseek.co.jp/issues/107086) 修正22

fix: Normalize VRT (task-22)

---

packages/app/src/components/Admin/ImportData/GrowiArchive/ImportForm.jsx
packages/app/src/components/Admin/ImportData/GrowiArchiveSection.jsx

[Admin][Import] ImportForm を表示 & 機能させる
┗107208 修正
エラーが出ているが、本PRに該当するものはないのでスルーして良い

imprv: Show Import Form

---

packages/app/test/cypress/integration/30-search/search.spec.ts

fix: Normalize VRT (30-search)

---

packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/ForbiddenPage.tsx

[#106881](https://redmine.weseek.co.jp/issues/106881) [Nextjs]Forbiddenページのページリストが永遠とロードしている見た目になっている
└ [#107226](https://redmine.weseek.co.jp/issues/107226) 修正

fix: Remove pagelist from forbidden page component

---

packages/app/src/components/Admin/Notification/ManageGlobalNotification.jsx

[Nextjs][Admin][ExternalNotification] GlobalNotification trigger を 作成できる
┗[107215](https://redmine.weseek.co.jp/issues/107215) 修正
https://user-images.githubusercontent.com/59536731/197415910-6647d4b7-16a5-4bb7-a63f-2f25852b8243.mov
エラーが出ているが、本PRに該当するものはないのでスルーして良い

imprv: Create a new global notification trigger

---

packages/app/src/components/Admin/ImportData/GrowiArchive/ImportForm.jsx

[Admin][Import] ImportForm を表示 & 機能させる
┗[107390](https://redmine.weseek.co.jp/issues/107390) 107208 の追加修正
https://github.com/weseek/growi/pull/6809#discussion_r1003414878
の修正です
確認お願いします。動作確認済みです。

imprv: Pass non-null socket to props for ImportForm component

---

packages/app/src/components/PageAttachment/DeleteAttachmentModal.module.scss
packages/app/src/components/PageAttachment/DeleteAttachmentModal.tsx
packages/app/src/pages/trash.page.tsx
packages/app/src/styles/_attachments.scss

タスク:https://redmine.weseek.co.jp/issues/106970

feat: Attach scss module styles for DeleteAttachmentModal

---

packages/app/src/server/models/page.ts
packages/app/src/server/service/page.ts

https://redmine.weseek.co.jp/issues/106884

fix: Finding "Anyone with the link" page

---

packages/app/src/server/routes/apiv3/pages.js

Redmine: https://redmine.weseek.co.jp/issues/107352
https://github.com/weseek/growi/pull/6823 の master むけ cherry-pick

fix: pageMove notification message

---

packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts

https://redmine.weseek.co.jp/issues/106918

support: Fix error caused by the absence of a reference

---

packages/app/src/components/PutbackPageModal.jsx
packages/app/src/server/service/page.ts

https://redmine.weseek.co.jp/issues/107611
https://github.com/weseek/growi/pull/6835
このPRと同じ修正をmasterに向けて出しなおしただけです

fix: 107357 fix put back parent from trash for master

---

packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx

https://redmine.weseek.co.jp/issues/107540

imprv: Use next/router after page processing

---

packages/app/public/static/locales/en_US/admin.json
packages/app/public/static/locales/ja_JP/admin.json
packages/app/public/static/locales/zh_CN/admin.json
packages/app/src/components/Admin/G2GDataTransfer.tsx
packages/app/src/server/service/g2g-transfer.ts

https://redmine.weseek.co.jp/issues/106426

feat: show g2g error

---

packages/app/src/components/SavePageControls/GrantSelector.tsx

[#106886](https://redmine.weseek.co.jp/issues/106886) [Nextjs]特定グループのみの設定でページを作成/更新できない
└ [#107973](https://redmine.weseek.co.jp/issues/107973) 修正

fix: Cannot create / update pages by specifying groups

---

packages/app/public/static/locales/en_US/commons.json
packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/commons.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/commons.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/Admin/Notification/GlobalNotificationList.jsx
packages/app/src/components/Admin/Notification/ManageGlobalNotification.tsx
packages/app/src/components/Admin/Notification/NotificationDeleteModal.jsx
packages/app/src/components/Admin/SlackIntegration/ConfirmBotChangeModal.jsx
packages/app/src/components/Common/ImageCropModal.tsx
packages/app/src/components/Navbar/GlobalSearch.tsx
packages/app/src/components/Navbar/PersonalDropdown.jsx
packages/app/src/components/Page/CopyDropdown.jsx
packages/app/src/components/RevisionComparer/RevisionComparer.tsx
packages/app/src/pages/admin/global-notification/new.page.tsx

story: [107157](https://redmine.weseek.co.jp/issues/107157)
The image before fixed is pasting onto the task ticket.

fix: 107157 Update Admin i18n

---

packages/app/test/cypress/integration/60-home/home.spec.ts

https://redmine.weseek.co.jp/issues/108010

fix: Normalize VRT (60-home/home.spec.ts/home--visit-home.png)

---

packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
packages/app/test/cypress/integration/20-basic-features/click-page-icons.spec.ts

Target Redmine Tasks (TRTs) :
[107913](https://redmine.weseek.co.jp/issues/107913)
[107991](https://redmine.weseek.co.jp/issues/107991)
[107992](https://redmine.weseek.co.jp/issues/107992)
[107993](https://redmine.weseek.co.jp/issues/107993)
[107994](https://redmine.weseek.co.jp/issues/107994)

imprv: VRT normalization 107991

---

packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
packages/app/test/cypress/integration/60-home/home.spec.ts

https://redmine.weseek.co.jp/issues/108009

fix: Normalize VRT (50-sidebar/access-to-side-bar.spec.ts/access-to-sidebar-recent-changes-1-page-list.png)

---

packages/app/public/static/locales/en_US/admin.json
packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/admin.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/admin.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/Admin/App/AppSetting.jsx
packages/app/src/components/Admin/App/AppSettingsPageContents.tsx
packages/app/src/components/Admin/Common/AdminNavigation.jsx
packages/app/src/components/Admin/Security/GitHubSecuritySettingContents.jsx
packages/app/src/components/Admin/Security/GoogleSecuritySettingContents.jsx
packages/app/src/components/Admin/Security/OidcSecuritySettingContents.jsx
packages/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
packages/app/src/components/Admin/Security/TwitterSecuritySettingContents.jsx
packages/app/src/components/AlertSiteUrlUndefined.tsx
packages/app/src/pages/admin/app.page.tsx
packages/app/src/pages/admin/index.page.tsx
packages/app/src/stores/context.tsx

task: https://redmine.weseek.co.jp/issues/108203

fix: 108203 Enable Open GROWI Cloud Settings

---

packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts

https://redmine.weseek.co.jp/issues/108008

fix: Normalize VRT (50-sidebar/access-to-side-bar.spec.ts/access-to-sidebar-page-tree-1-access-to-page-tree.png)

---

packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts

https://redmine.weseek.co.jp/issues/108007

fix: Normalize VRT (50-sidebar/access-to-side-bar.spec.ts/access-to-sidebar-access-to-trash-page.png)

---

packages/app/src/server/models/obsolete-page.js

Redmine:
- https://redmine.weseek.co.jp/issues/108417
子孫まとめて権限更新する処理のパフォーマンスを改善しました

imprv: Bulk update scope

---

packages/app/src/components/Admin/UserGroup/UserGroupDropdown.tsx
packages/app/src/components/Admin/UserGroup/UserGroupForm.tsx
packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
packages/app/src/components/Admin/UserGroupDetail/UserGroupUserTable.tsx

task: 
[108331](https://redmine.weseek.co.jp/issues/108331)
[108332](https://redmine.weseek.co.jp/issues/108332)

fix: Fix User group bugs

---

packages/app/src/server/routes/login-passport.js

[#108325](https://redmine.weseek.co.jp/issues/108325) [Next.js] Twitter 認証を用いて正常にログインできない
└ [#108326](https://redmine.weseek.co.jp/issues/108326) 修正
[#107909](https://redmine.weseek.co.jp/issues/107909) [Next.js][Admin]Googleアカウント連携した後に正しくページ遷移される
└ [#108461](https://redmine.weseek.co.jp/issues/108461) 修正

fix: Cannot automatically transition to root when login with external account

---

packages/app/src/server/models/vo/g2g-transfer-error.ts
packages/app/src/server/routes/apiv3/g2g-transfer.ts
packages/app/src/server/service/export.js
packages/app/src/server/service/g2g-transfer.ts

https://redmine.weseek.co.jp/issues/106417

feat: skip dupe attachment transfer

---

packages/app/src/stores/page.tsx

https://redmine.weseek.co.jp/issues/107941
swrに初期値を設定する際に、mutateを呼んでcacheに初期値をセットしていた部分をリファクタし、fallbackオプションで初期値を設定するようにした。
軽く動作確認をして、正常に動作することは確認しています

support: refactor swr initialize

---

packages/app/public/static/locales/en_US/admin.json
packages/app/public/static/locales/ja_JP/admin.json
packages/app/public/static/locales/zh_CN/admin.json
packages/app/src/components/Admin/G2GDataTransfer.tsx
packages/app/src/components/Admin/G2GDataTransferStatusIcon.tsx
packages/app/src/interfaces/g2g-transfer.ts
packages/app/src/server/service/g2g-transfer.ts

https://redmine.weseek.co.jp/issues/106419
https://user-images.githubusercontent.com/27652080/200617599-90b36c2b-79ba-443a-b440-1a718a3b8f02.mov

feat: show detailed progress

---

packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/CompleteUserRegistration.tsx
packages/app/src/components/CompleteUserRegistrationForm.tsx
packages/app/src/components/LoginForm.tsx
packages/app/src/interfaces/registration-mode.ts
packages/app/src/pages/login.page.tsx
packages/app/src/pages/user-activation.page.tsx
packages/app/src/server/routes/apiv3/index.js
packages/app/src/server/routes/apiv3/user-activation.ts
packages/app/src/server/routes/login.js

[#108280](https://redmine.weseek.co.jp/issues/108280) [Next.js] ユーザー作成制限時にユーザーを作成後ログインできてしまう
└ [#108283](https://redmine.weseek.co.jp/issues/108283) 修正

fix: Do not allow users to login when user registration is restricted

---

packages/app/src/server/service/page.ts

https://redmine.weseek.co.jp/issues/108046
- ページ作成時に、expandContentWidthを初期化している部分を削除

fix: page wide view not working

---

packages/app/src/server/service/page.ts

https://redmine.weseek.co.jp/issues/108046
- ページ作成時に、expandContentWidthを初期化している部分を削除
masterに向けて同じ修正内容のPRを出していて、すでに増山のレビュー&マージ済みです
https://github.com/weseek/growi/pull/6911

fix: page content width not working

---

packages/app/test/cypress/integration/30-search/search.spec.ts

- https://redmine.weseek.co.jp/issues/108003
- https://redmine.weseek.co.jp/issues/108004
- https://redmine.weseek.co.jp/issues/108005
画像の右上と、下二つ

support: VRT search all page

---

packages/app/src/server/routes/apiv3/user-activation.ts
packages/app/src/server/routes/login.js

[#108671](https://redmine.weseek.co.jp/issues/108671) [Next.js] 登録許可メールアドレスのホワイトリストに任意のメールアドレス設定した常態で、ホワイトリストに登録されていないメールアドレスをメール認証用フォームに入力し送信できてしまう
└ [#108672](https://redmine.weseek.co.jp/issues/108672) 修正

fix: Check if entered email address is included in whitelist

---

packages/app/src/components/Admin/Customize/CustomizeLogoSetting.tsx
packages/app/src/pages/utils/commons.ts
packages/app/src/server/routes/apiv3/customize-setting.js

https://youtrack.weseek.co.jp/issue/GW-7906

feat: Cannot display default logo on sidebar

---

packages/app/src/components/LoginForm.tsx
packages/app/src/pages/login.page.tsx
packages/app/src/server/routes/apiv3/user-activation.ts

[#108664](https://redmine.weseek.co.jp/issues/108664) [Next.js] ユーザーの新規作成が非公開になっている時に新規作成フォームが表示されてしまう
└ [#108665](https://redmine.weseek.co.jp/issues/108665) 修正

fix: User registration form is not displayed when registration mode is close

---

packages/app/src/server/models/interfaces/page-operation.ts
packages/app/src/server/service/installer.ts
packages/app/src/server/service/page.ts

Redmine: https://redmine.weseek.co.jp/issues/108950
ページの作成処理を修正しました。詳細は https://github.com/weseek/growi/pull/6930#discussion_r1022301215

fix: Create page at installer

---

packages/app/src/interfaces/bookmark-info.ts
packages/app/src/server/models/bookmark-folder.ts
packages/app/src/server/models/errors.ts
packages/app/src/server/routes/apiv3/bookmark-folder.ts
packages/app/src/server/routes/apiv3/index.js
packages/app/src/stores/bookmark.ts

https://youtrack.weseek.co.jp/issue/GW-7833

feat: gw7833 create bookmarkfolder model and api

---

packages/app/cypress.json

https://redmine.weseek.co.jp/issues/109056

support: Extend defaultCommandTimrout for VRT

---

packages/app/src/components/PageCreateModal.jsx

[#109037](https://redmine.weseek.co.jp/issues/109037) [Next化] テンプレートページの種類を選択して作成できない
└ [#109038](https://redmine.weseek.co.jp/issues/109038) 修正

fix: Template page selection dropdown not working

---

packages/app/public/static/locales/ja_JP/translation.json

task: https://redmine.weseek.co.jp/issues/109072

feat: Update not latest version alert for ja

---

packages/app/test/cypress/integration/60-home/home.spec.ts

https://redmine.weseek.co.jp/issues/108867
修正前
https://growi-vrt-snapshots.s3.amazonaws.com/4a4d3cd24e7f0d6ea6d98b7360acacd2d323b69b/index.html?id=changed-60-home/home.spec.ts/Access%20Home%20--%20Visit%20home%20(failed).png#changed-60-home/home.spec.ts/Access%20Home%20--%20Visit%20home%20(failed).png
修正後
https://growi-vrt-snapshots.s3.amazonaws.com/65bff78ab2122152284794999cc90547496145fa/index.html?id=deleted-60-home/home.spec.ts/home--visit-home.png

fix: visit home vrt

---

lerna.json
package.json
packages/app/package.json
packages/codemirror-textlint/package.json
packages/core/package.json
packages/hackmd/package.json
packages/plugin-attachment-refs/package.json
packages/plugin-lsx/package.json
packages/remark-growi-plugin/package.json
packages/slack/package.json
packages/slackbot-proxy/package.json
packages/ui/package.json

support: Bump version 6.0.0-RC.9

---

packages/app/src/server/service/page-operation.ts

Redmine: https://redmine.weseek.co.jp/issues/109243
GROWI 起動時にクリーンアップされる PageOperation に Create と Update を追加しました

imprv: Cleanup pageoperations on boot for create update

---

packages/app/src/pages/[[...path]].page.tsx

[#109077](https://redmine.weseek.co.jp/issues/109077) [Next.js] テンプレートページが機能していない
└ [#109119](https://redmine.weseek.co.jp/issues/109119) ボディテンプレートを機能させる

fix: Make body template work

---

packages/app/src/components/PageEditor.tsx
packages/app/src/components/PageEditorByHackmd.tsx
packages/app/src/components/SavePageControls.tsx
packages/app/src/components/UnsavedAlertDialog.tsx
packages/app/src/stores/editor.tsx
packages/app/src/stores/page.tsx

- https://redmine.weseek.co.jp/issues/108796
- https://redmine.weseek.co.jp/issues/108998
- `useSWRxPage` 改修
- `UnsavedAlertDialog` コンポーネントと `useIsEnabledUnsavedWarning` 修正

fix: Show footer and not show alert

---

packages/app/public/static/locales/en_US/commons.json
packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/commons.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/commons.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
packages/app/src/components/InAppNotification/InAppNotificationPage.tsx
packages/app/src/components/Navbar/AppearanceModeDropdown.tsx
packages/app/src/pages/me/[[...path]].page.tsx

task:
[109347](https://redmine.weseek.co.jp/issues/109347)
[109350](https://redmine.weseek.co.jp/issues/109350)

fix: Update Admin i18n

---

packages/app/src/components/PageHistory/Revision.tsx
packages/app/src/stores/ui.tsx

task:https://redmine.weseek.co.jp/issues/109389

fix: Keep URL parameter when change editor mode

---

packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts

https://redmine.weseek.co.jp/issues/109428

fix: Normalize VRT (20-basic-features/access-to-page.spec.ts/access-to-page--sandbox-headers.png)

---

packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts

https://redmine.weseek.co.jp/issues/109430

fix: Normalize VRT (20-basic-features/access-to-page.spec.ts/access-to-page--sandbox-math.png)

---

packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/Sidebar/Bookmarks.tsx
packages/app/src/components/Sidebar/Bookmarks/BookmarkContents.tsx
packages/app/src/components/Sidebar/Bookmarks/BookmarkFolder.tsx
packages/app/src/components/Sidebar/Bookmarks/BookmarkFolderItem.tsx
packages/app/src/components/Sidebar/Bookmarks/BookmarkFolderItemControl.tsx
packages/app/src/components/Sidebar/Bookmarks/BookmarkFolderNameInput.tsx
packages/app/src/components/Sidebar/Bookmarks/BookmarkFolderTree.tsx
packages/app/src/components/Sidebar/Bookmarks/DeleteBookmarkFolderModal.tsx
packages/app/src/interfaces/bookmark-info.ts
packages/app/src/server/models/bookmark-folder.ts
packages/app/src/server/routes/apiv3/bookmark-folder.ts
packages/app/src/stores/bookmark-folder.ts

https://youtrack.weseek.co.jp/issue/GW-7905
https://user-images.githubusercontent.com/92426728/201890935-a9891c8c-6931-474d-8ad9-8d82b4ac6635.mp4

feat : gw7905 implement action button to rename and delete bookmark folder

---

packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx

https://redmine.weseek.co.jp/issues/107883 の対応漏れ

support: Add dependency to ItemsTree > onClickDeleteMenuItem

---

packages/app/src/pages/tags.page.tsx
packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts

https://redmine.weseek.co.jp/issues/109444

fix: Normalize VRT (20-basic-features/access-to-page.spec.ts/access-to-special-pages--tags.png)

---

packages/app/test/cypress/integration/20-basic-features/access-to-pagelist.spec.ts

fix: Normalize VRT (20-basic-features/access-to-pagelist.spec.ts/access-to-pagelist-6-page-list-modal-size-normal.png)

---

packages/app/src/components/Navbar/PersonalDropdown.jsx
packages/app/test/cypress/integration/60-home/home.spec.ts

https://redmine.weseek.co.jp/issues/109445
何かしらの要素が取得できずに、Changed に存在していたが、消えてしまったのでスクショへのリンクは無し。
各要素取得を改善

support: Normalize VRT 109445

---

packages/app/public/static/locales/en_US/commons.json
packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/commons.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/commons.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/Navbar/GrowiNavbar.tsx

task: https://redmine.weseek.co.jp/issues/109796

fix: Update admin i18n GrowiNavbar

---

packages/app/src/components/BookmarkButtons.tsx
packages/app/src/components/LikeButtons.tsx
packages/app/src/components/SubscribeButton.tsx
packages/app/src/components/User/SeenUserInfo.tsx
packages/app/test/cypress/integration/20-basic-features/click-page-icons.spec.ts

- https://redmine.weseek.co.jp/issues/109699
- https://redmine.weseek.co.jp/issues/109697
- https://redmine.weseek.co.jp/issues/109701

fix: Normalize VRT (20-basic-features/click-page-icons)

---

packages/app/test/cypress/integration/20-basic-features/access-to-pagelist.spec.ts

https://redmine.weseek.co.jp/issues/109706

fix: Normalize VRT (20-basic-features/access-to-pagelist)

---

packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts

https://redmine.weseek.co.jp/issues/109702

fix: Normalize VRT (20-basic-features/access-to-page.spec.ts)

---

packages/app/src/components/PageEditor.tsx
packages/app/src/components/PageStatusAlert.tsx

https://redmine.weseek.co.jp/issues/109673
- PageUpdatedAlertの最新版をロードするボタンの機能を実装
- コンフリクトの解消機能は後続タスクで実装します
- https://redmine.weseek.co.jp/issues/107700

support: load latest revision from updated alert

---

packages/app/src/components/ReactMarkdownComponents/Table.tsx
packages/app/src/services/renderer/remark-plugins/table.ts
packages/app/src/services/renderer/renderer.tsx

task: https://redmine.weseek.co.jp/issues/110228

feat: Optimize table component rerendering on Preview

---

packages/app/src/pages/me/[[...path]].page.tsx
packages/app/src/pages/tags.page.tsx
packages/app/src/pages/trash.page.tsx

[#110222](https://redmine.weseek.co.jp/issues/110222) [Next.js]  /me ,/tags ,/trash ページでカスタムサイドバーが表示されない
└ [#110505](https://redmine.weseek.co.jp/issues/110505) 修正

fix: Custom sidebar does not appear on certain pages

---

packages/app/src/components/InAppNotification/InAppNotificationList.tsx
packages/app/src/components/InAppNotification/PageNotification/PageModelNotification.tsx
packages/app/src/interfaces/in-app-notification.ts
packages/app/src/models/serializers/in-app-notification-snapshot/page.ts
packages/app/src/stores/in-app-notification.ts

[#110808](https://redmine.weseek.co.jp/issues/110808) [Next化] inAppNotification.snapshot の JSON.parse とその例外処理をuseSWRxInAppNotifications の中でやる
└ [#110809](https://redmine.weseek.co.jp/issues/110809) 改善

imprv: In-app notification snapshot parsing process in SWR

---

packages/app/public/static/locales/en_US/admin.json
packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/admin.json
packages/app/public/static/locales/zh_CN/admin.json
packages/app/public/static/locales/zh_CN/translation.json

https://redmine.weseek.co.jp/issues/110967
Screenshot 箇所が i18n されてなかったついでに `admin.json` を整理した。

feat: Update admin json

---

packages/app/src/components/Page/DisplaySwitcher.tsx
packages/app/src/components/PageEditor.tsx
packages/app/src/components/PageEditor/ConflictDiffModal.tsx
packages/app/src/components/PageStatusAlert.tsx
packages/app/src/stores/remote-latest-page.ts

https://redmine.weseek.co.jp/issues/110608
- コンフリクト解消モーダルでコンフリクトを解消できるようにした
- 更新時のoptionsToSaveはまだ有効になっていませんが、後続タスクでやります
- https://redmine.weseek.co.jp/issues/111080

support: 110608 resolve conflict by modal

---

packages/app/package.json
packages/app/src/components/Common/Dropdown/PageItemControl.tsx
packages/app/src/components/NotAvailableForGuest.tsx
packages/app/src/components/Page/RenderTagLabels.tsx
packages/app/src/components/PageComment/CommentEditor.tsx
packages/app/src/components/Sidebar/PageTree/Item.tsx
yarn.lock

https://redmine.weseek.co.jp/issues/111189
- [react-disable](https://github.com/kitze/react-disable)を導入
- 未ログイン状態でサイドバーのページ作成ボタンとオプションボタンを押せなくした

fix: disable sidebar button for guest

---

packages/app/src/client/services/page-operation.ts
packages/app/src/components/PageEditor.tsx
packages/app/src/components/PageEditorByHackmd.tsx
packages/app/src/stores/context.tsx

https://redmine.weseek.co.jp/issues/111358
- 編集画面でタグを編集して更新した後に、Viewモードで更新が反映されるようにした

fix: save tag

---

packages/app/src/styles/theme/_apply-colors.scss
packages/preset-themes/src/styles/default.scss
packages/preset-themes/src/styles/theme/_apply-colors.scss
packages/preset-themes/src/styles/theme/_hsl-functions.scss
packages/preset-themes/src/styles/theme/_override-functions.scss
packages/preset-themes/src/styles/theme/mixins/_hsl-button.scss

Task
┗[111149](https://redmine.weseek.co.jp/issues/111149)
本体側の_apply-colors.scss(apply to bootstrap部分)をcss var化して、
preset-themes 側の_apply-colors.scss内の記述をコメントアウトしました

imprv:apply colors apply to bootstrap

---

packages/app/src/styles/theme/_apply-colors.scss
packages/preset-themes/src/styles/theme/_apply-colors.scss

Task
┗[111654](https://redmine.weseek.co.jp/issues/111654)
本体側の_apply-colors.scss(apply to bootstrap部分)をcss var化して、
preset-themes 側の_apply-colors.scss内の記述をコメントアウトしました

imprv:apply colors div.grw contextual navigation

---

packages/app/src/components/Common/Dropdown/PageItemControl.tsx
packages/app/src/components/PageComment.tsx
packages/app/src/components/SearchPage.tsx

https://redmine.weseek.co.jp/issues/111740
https://redmine.weseek.co.jp/issues/111741
https://redmine.weseek.co.jp/issues/111807
- 検索画面のページの3点ボタン
- 検索画面の一括削除ボタン
- コメントの返信ボタン
以上の3つのコンポーネントにゲストは使用できない旨のツールチップを実装した

fix: 111740 guest tooltip

---

packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx

https://redmine.weseek.co.jp/issues/111958

fix: update state after save

---

packages/app/src/styles/theme/_apply-colors.scss
packages/preset-themes/src/styles/default.scss
packages/preset-themes/src/styles/theme/_apply-colors.scss

Task
┗[111658](https://redmine.weseek.co.jp/issues/111658)
本体側の_apply-colors.scss(apply to bootstrap部分)をcss var化して、
preset-themes 側の_apply-colors.scss内の記述をコメントアウトしました
preset-themes 側の_apply-colors.scssは全てコメントアウトしました

imprv:apply colors emoji picker modal

---

packages/app/src/server/routes/login.js

feat: fix i18n error message

---

packages/app/src/styles/theme/_apply-colors-light.scss
packages/app/src/styles/theme/_apply-colors.scss
packages/preset-themes/src/styles/default.scss
packages/preset-themes/src/styles/theme/_apply-colors-light.scss

Task
┗[112063](https://redmine.weseek.co.jp/issues/112063)
app側のapply-colors-light.scssを
本体側の_apply-colors-light.scssをcss var化して、
preset-themes 側の_apply-colors-light.scss内の記述を全てコメントアウトしました

imprv:apply colors light last

---

packages/app/public/static/locales/en_US/admin.json
packages/app/public/static/locales/ja_JP/admin.json
packages/app/public/static/locales/zh_CN/admin.json
packages/app/src/components/Admin/Common/AdminNavigation.jsx
packages/app/src/components/Admin/PluginsExtension/PluginCard.tsx
packages/app/src/components/Admin/PluginsExtension/PluginInstallerForm.tsx
packages/app/src/components/Admin/PluginsExtension/PluginsExtensionPageContents.tsx
packages/app/src/pages/admin/plugins.page.tsx

task: https://redmine.weseek.co.jp/issues/110894

feat: Enable plugin i18n

---

packages/app/src/components/PageEditor/Editor.tsx

fix: show navbar

---

packages/app/src/pages/_app.page.tsx
packages/app/src/styles/theme/_apply-colors-dark.scss
packages/app/src/styles/theme/_apply-colors-light.scss
packages/app/src/styles/theme/_apply-colors.scss
packages/preset-themes/src/styles/default.scss
packages/preset-themes/src/styles/theme/_apply-colors-dark.scss

Task
┗[112341](https://redmine.weseek.co.jp/issues/112341)
app側のapply-colors-dark.scssをcss var化して、
preset-themes 側の_apply-colors-dark.scss内の記述を全てコメントアウトしました

imprv:apply colors dark growitoc

---

packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/Page/TagEditModal.jsx
packages/app/src/components/Page/TagsInput.tsx

task: 
https://redmine.weseek.co.jp/issues/112578
https://redmine.weseek.co.jp/issues/112579
- 英語と中国語はもともと用意されていたので対処不要
- 日本語
- 中国語

fix: Attach i18n User Setting and TagEditModal

---

packages/app/public/static/locales/en_US/admin.json
packages/app/public/static/locales/ja_JP/admin.json
packages/app/public/static/locales/zh_CN/admin.json
packages/app/src/client/services/g2g-transfer.ts
packages/app/src/components/Admin/G2GDataTransfer.tsx
packages/app/src/components/Admin/G2GDataTransferExportForm.tsx
packages/app/src/components/DataTransferForm.tsx
packages/app/src/server/routes/apiv3/g2g-transfer.ts
packages/app/src/server/service/g2g-transfer.ts

imprv: error handling

---

packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/pages/[[...path]].page.tsx
packages/app/src/pages/_search.page.tsx
packages/app/src/pages/admin/[...path].page.tsx
packages/app/src/pages/admin/index.page.tsx
packages/app/src/pages/installer.page.tsx
packages/app/src/pages/invited.page.tsx
packages/app/src/pages/login/index.page.tsx
packages/app/src/pages/me/[[...path]].page.tsx
packages/app/src/pages/share/[[...path]].page.tsx
packages/app/src/pages/tags.page.tsx
packages/app/src/pages/trash.page.tsx
packages/app/src/pages/user-activation.page.tsx
packages/app/src/pages/utils/commons.ts

task: https://redmine.weseek.co.jp/issues/112813
- header にタイトルが表示されるようにしました。

imprv: Display the header title on each page

---

packages/app/src/pages/[[...path]].page.tsx

https://redmine.weseek.co.jp/issues/112805
- ページ新規作成時にgetServerSidePropsで親のページの権限をpropsにセットして、クライアント側でその値を使って権限wの初期化するようにした

fix: Initial value of the page grant respects the parent page's one

---

packages/remark-lsx/src/services/renderer/lsx.ts

fix: Lsx encode prefix twice

---

packages/app/src/styles/theme/_apply-colors-light.scss
packages/app/src/styles/theme/_hsl-reboot-bootstrap-theme-colors.scss
packages/preset-themes/src/styles/blackboard.scss
packages/preset-themes/src/styles/christmas.scss
packages/preset-themes/src/styles/fire-red.scss
packages/preset-themes/src/styles/halloween.scss
packages/preset-themes/src/styles/hufflepuff.scss
packages/preset-themes/src/styles/island.scss
packages/preset-themes/src/styles/jade-green.scss
packages/preset-themes/src/styles/nature.scss
packages/preset-themes/src/styles/spring.scss
packages/preset-themes/src/styles/theme/mixins/_hsl-button.scss
packages/preset-themes/src/styles/wood.scss
packages/remark-lsx/src/services/renderer/lsx.ts

**Task**
[Next.js] 全てのテーマの CSS Variables 対応
┗[112479](https://redmine.weseek.co.jp/issues/112479)
**やったこと**
- halloween・island・spring・woodの書き換え
- 画像URLの修正
- その他表示がおかしかった箇所の修正

fix:halloween island spring wood

---

packages/app/src/styles/theme/_apply-colors.scss
packages/preset-themes/src/styles/default.scss
packages/preset-themes/src/styles/mono-blue.scss

fix:border-image-navbar

---

packages/app/src/styles/theme/_apply-colors-light.scss
packages/app/src/styles/theme/_reboot-bootstrap-theme-colors.scss

borderの色が競合していたのを修正
ログイン画面のcolor-gradientを修正

fix:border and color-gradient

---

packages/app/src/server/routes/apiv3/import.js
packages/app/src/server/service/g2g-transfer.ts
packages/app/src/server/service/import.js

Redmine: https://redmine.weseek.co.jp/issues/113051

fix: Should normalize pages

---

packages/app/public/static/locales/en_US/admin.json
packages/app/public/static/locales/en_US/commons.json
packages/app/public/static/locales/zh_CN/admin.json
packages/app/src/components/Admin/G2GDataTransferStatusIcon.tsx
packages/app/src/interfaces/g2g-transfer.ts
packages/app/src/server/routes/apiv3/g2g-transfer.ts
packages/app/src/server/routes/apiv3/import.js
packages/app/src/server/service/export.js
packages/app/src/server/service/g2g-transfer.ts
packages/app/src/server/service/import.js
packages/app/src/server/util/createGrowiPagesFromImports.js

https://redmine.weseek.co.jp/issues/113021
移行先のストレージタイプが none の時に内部仕様通りの挙動になる

feat: fileuploadtype none

---

.github/workflows/release.yml

* feat: Enable features used sticky-event (#7187) @jam411
* imprv: Do not retrieve page data using API in shared page (#7240) @miya
* imprv: Use CSS variables (#7093) @yuki-takei
* imprv: Do not request /pages.getPageTag when on a shared page (#7214) @miya
* fix: Refactor axios date serializer config (#7249) @yukendev
* fix: DeletePageModal shows an incorrect label when open (#7224) @yukendev
* fix: Page path is not displayed in browser tab on shared page (#7243) @miya
* fix: Lsx encode prefix twice (#7239) @yuki-takei
* fix: Initial value of the page grant respects the parent page's one (#7232) @yukendev

release v6.0.3-TEST (2)

---

.github/workflows/release.yml

* feat: Enable features used sticky-event (#7187) @jam411
* imprv: Do not retrieve page data using API in shared page (#7240) @miya
* imprv: Use CSS variables (#7093) @yuki-takei
* imprv: Do not request /pages.getPageTag when on a shared page (#7214) @miya
* fix: Refactor axios date serializer config (#7249) @yukendev
* fix: DeletePageModal shows an incorrect label when open (#7224) @yukendev
* fix: Page path is not displayed in browser tab on shared page (#7243) @miya
* fix: Lsx encode prefix twice (#7239) @yuki-takei
* fix: Initial value of the page grant respects the parent page's one (#7232) @yukendev

Release v6.0.3-TEST

---

.github/workflows/release.yml

* feat: Enable features used sticky-event (#7187) @jam411
* imprv: Do not retrieve page data using API in shared page (#7240) @miya
* imprv: Use CSS variables (#7093) @yuki-takei
* imprv: Do not request /pages.getPageTag when on a shared page (#7214) @miya
* fix: Refactor axios date serializer config (#7249) @yukendev
* fix: DeletePageModal shows an incorrect label when open (#7224) @yukendev
* fix: Page path is not displayed in browser tab on shared page (#7243) @miya
* fix: Lsx encode prefix twice (#7239) @yuki-takei
* fix: Initial value of the page grant respects the parent page's one (#7232) @yukendev

Release v6 Test

---

packages/app/src/styles/theme/_apply-colors-dark.scss
packages/app/src/styles/theme/_apply-colors-light.scss

**Task**
[Next.js] 全てのテーマの CSS Variables 対応
┗[113532](https://redmine.weseek.co.jp/issues/113532)
**やったこと**
- apply-colors-light と apply-colors-dark 内のgrw-skeleton部分の記述を修正

fix: grw-skeleton

---

packages/app/src/components/Questionnaire/Question.tsx
packages/app/src/components/Questionnaire/QuestionnaireModal.tsx
packages/app/src/components/Questionnaire/QuestionnaireToast.tsx
packages/app/src/interfaces/questionnaire/question.ts
packages/app/src/interfaces/questionnaire/questionnaire-order.ts
packages/app/src/server/models/questionnaire/questionnaire-order.ts
packages/app/src/server/models/questionnaire/schema/question.ts
packages/app/test/integration/service/questionnaire-cron.test.ts

Redmine: https://redmine.weseek.co.jp/issues/113328

imprv: i18n questionnaire text

---

packages/app/src/components/Admin/G2GDataTransfer.tsx

Redmine: https://redmine.weseek.co.jp/issues/113663

support: Comment out file upload setting form

---

packages/app/src/styles/theme/_apply-colors-dark.scss
packages/app/src/styles/theme/_apply-colors-light.scss
packages/app/src/styles/theme/_apply-colors.scss
packages/app/src/styles/theme/_hsl-reboot-bootstrap-theme-colors.scss
packages/preset-themes/src/styles/future.scss
packages/preset-themes/src/styles/halloween.scss

**Task**
[Next.js] 全てのテーマの CSS Variables 対応
┗[113593](https://redmine.weseek.co.jp/issues/113593)
**やったこと**
不要な記述の削除
- _hsl-reboot-bootstrap-theme-colors.scss
ダークモード時に表示がおかしくなる部分の修正
- タグ作成画面のフォーム・ドロップダウンメニューの文字色修正
- 編集履歴の背景色修正
- コードブロックの背景色(future & halloween特有の問題だと判明)
- カードの背景にtheme-colorが反映されていない
- tableのborder-color
モード関係なくscssの読み込み順変更の関係で表示がおかしくなっていた部分の修正
- 検索バーについていた枠線の削除
- ~~画面幅が狭い時のnavbarのホバー時の背景色~~ 不要でした
- ~~ヘッダー背景色がtheme-colorになっているモーダルのホバー時の背景色~~ 不要でした

fix: apply-colors-dark

---

packages/core/src/test/util/page-path-utils.test.js
packages/core/src/utils/page-path-utils.ts

fix: Ignore backslash in page path

---

packages/app/src/components/Admin/App/FileUploadSetting.tsx
packages/app/src/components/Admin/G2GDataTransfer.tsx

https://redmine.weseek.co.jp/issues/113806

feat: UI file upload settings at src growi

---

packages/preset-themes/src/styles/antarctic.scss
packages/preset-themes/src/styles/default.scss
packages/preset-themes/src/styles/fire-red.scss
packages/preset-themes/src/styles/future.scss
packages/preset-themes/src/styles/halloween.scss
packages/preset-themes/src/styles/island.scss
packages/preset-themes/src/styles/jade-green.scss
packages/preset-themes/src/styles/kibela.scss
packages/preset-themes/src/styles/mono-blue.scss
packages/preset-themes/src/styles/nature.scss
packages/preset-themes/src/styles/wood.scss

各テーマのbgcolor-blinked-sectionの値がおかしかったものを修正

fix: Color for blinked section

---

packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/Me/OtherSettings.tsx
packages/app/src/components/Me/PersonalSettings.jsx
packages/app/src/server/models/user.js
packages/app/src/server/routes/apiv3/personal-setting.js
packages/core/src/interfaces/user.ts

Redmine: https://redmine.weseek.co.jp/issues/113318
ユーザーごとにアンケートを on/off する設定を追加

feat: Questionnaire settings for each user

---

packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/Navbar/PersonalDropdown.tsx
packages/app/src/components/Questionnaire/ProactiveQuestionnaireModal.tsx

Redmine: https://redmine.weseek.co.jp/issues/114063
能動的なアンケート機能

feat: Proactive questionnaire

---

packages/app/src/components/Questionnaire/ProactiveQuestionnaireModal.tsx
packages/app/src/server/routes/apiv3/questionnaire.ts

Redmine: https://redmine.weseek.co.jp/issues/114131
能動的なアンケート回答用ルート実装

imprv: Post for proactive questionnaire

---

packages/app/src/components/Questionnaire/QuestionnaireToast.tsx
packages/app/src/interfaces/questionnaire/questionnaire-order.ts
packages/app/src/server/models/questionnaire/questionnaire-order.ts
packages/app/test/integration/service/questionnaire-cron.test.ts

Redmine: https://redmine.weseek.co.jp/issues/114272
shortTitle attr 追加

imprv: Add short title

---

packages/app/src/stores/personal-settings.tsx

[#112285](https://redmine.weseek.co.jp/issues/112285) [Next.js] ゲストユーザーアクセス時に /_api/v3/personal-settings へのリクエスト(及び 403 レスポンス)が行われている問題を修正する
└ [#114251](https://redmine.weseek.co.jp/issues/114251) 修正

fix:  Request to "/_api/v3/personal-settings"  occurs when in guest mode

---

packages/app/src/components/Questionnaire/QuestionnaireModal.tsx
packages/app/src/components/Questionnaire/QuestionnaireToast.tsx
packages/app/src/stores/modal.tsx

Redmine: https://redmine.weseek.co.jp/issues/114350

imprv: No closing toasts when closing modal

---

packages/app/public/static/locales/ja_JP/translation.json
packages/app/src/components/Admin/App/QuestionnaireSettings.tsx
packages/app/src/components/Questionnaire/Question.tsx
packages/app/src/components/Questionnaire/QuestionnaireModal.tsx

Redmine: https://redmine.weseek.co.jp/issues/114348
アンケートの UI を改善

imprv: UI questionnaire modal

---

packages/app/src/components/Admin/App/QuestionnaireSettings.tsx

Redmine: https://redmine.weseek.co.jp/issues/114271
アンケート設定の文言を修正し、docs へのリンクを記載した

imprv: Admin link to docs

---

packages/app/src/server/routes/apiv3/users.js

https://redmine.weseek.co.jp/issues/114395

fix: Can delete own user (v5)

---

packages/app/public/static/locales/ja_JP/commons.json

https://redmine.weseek.co.jp/issues/114771
誤字を修正

fix: Typo in G2G alert component

---

packages/app/src/client/services/layout.ts
packages/app/src/components/PageEditor/Preview.tsx
packages/app/src/pages/[[...path]].page.tsx
packages/app/src/pages/share/[[...path]].page.tsx
packages/app/src/pages/trash.page.tsx
packages/app/src/styles/_editor.scss
packages/app/src/styles/theme/_apply-colors.scss

SSR 時に isContainerFluid の決定を行うように変更
- [Next.js] editing-sidebar class を適用する
- https://redmine.weseek.co.jp/issues/114895

imprv: classname for fluid layout

---

packages/app/src/components/PageEditor.tsx

https://redmine.weseek.co.jp/issues/115044

fix: Routing after creating page with shortcut

---

packages/app/src/components/Comments.tsx
packages/app/src/components/Page/PageView.tsx
packages/app/src/components/PageComment/Comment.module.scss
packages/app/src/components/SearchPage/SearchResultContent.tsx
packages/app/src/styles/_variables.scss
packages/app/src/styles/organisms/_wiki.scss

https://redmine.weseek.co.jp/issues/112441

fix: Scroll into view by anchor

---

packages/app/src/components/Bookmarks/BookmarkFolderMenuItem.tsx

https://youtrack.weseek.co.jp/issue/GW-7914

feat: gw 7914 remove bookmark from subnavigation

---

packages/app/package.json
packages/app/src/components/Page/RevisionLoader.tsx
packages/app/src/components/PageTimeline.tsx
packages/app/src/components/Sidebar/InfiniteScroll.tsx
packages/app/src/components/Sidebar/RecentChanges.tsx
packages/app/src/server/routes/apiv3/pages.js
packages/app/src/stores/page-listing.tsx
yarn.lock

- bug: Loading method for PageTimeline
- bug: `limit` and `offset` params for `/pages/recent` API

fix: Recent changes and Timeline

---

bin/data-migrations/v6/src/processor.js

https://redmine.weseek.co.jp/issues/115314
discussion: https://github.com/weseek/growi/discussions/7180
- `MIGRATION_TYPE`の値に`custom`を追加]
- discussionに`MIGRATION_TYPE`に`custom`を選択できることを追記

feat: Add custom migration type for v6

---

packages/app/public/static/locales/en_US/admin/admin.json
packages/app/public/static/locales/ja_JP/admin/admin.json
packages/app/public/static/locales/zh_CN/admin/admin.json
packages/app/src/client/services/AdminAppContainer.js
packages/app/src/components/Admin/App/AwsSetting.jsx
packages/app/src/server/routes/apiv3/app-settings.js

https://redmine.weseek.co.jp/issues/115496

imprv: Omit S3 credentials from the response for `/_api/v3/app-settings` (v5)

---

bin/data-migrations/v6/README.md

https://redmine.weseek.co.jp/issues/114575
- v6マイグレーションスクリプトのREADME.mdを作成
- このPRがマージされ次第、discussionに英語版をコピペします

support: create README.md for v6 migration

---

packages/app/src/components/PagePresentationModal.tsx
packages/presentation/src/components/Slides.tsx
packages/presentation/src/consts/index.ts
packages/presentation/src/services/renderer/extract-sections.ts
packages/ui/src/index.ts
packages/ui/src/utils/use-fullscreen.ts

- Fullscreen enter/exit action
- Add `disableSeparationByHeader` option

imprv: Presentation behavior

---

packages/app/src/components/Questionnaire/QuestionnaireModalManager.module.scss

https://redmine.weseek.co.jp/issues/116074

refs 116073: put questionnaire toast above Fab

---

packages/app/src/interfaces/questionnaire/growi-info.ts
packages/app/src/server/service/questionnaire.ts
packages/app/test/integration/service/questionnaire-cron.test.ts
packages/app/test/integration/service/questionnaire.test.ts

https://redmine.weseek.co.jp/issues/116383

refs 116148: questionnaire service test

---

packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/BookmarkButtons.tsx
packages/app/src/components/Bookmarks/BookmarkFolderItem.tsx
packages/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
packages/app/src/components/Bookmarks/BookmarkFolderMenuItem.tsx
packages/app/src/components/Bookmarks/BookmarkFolderTree.module.scss
packages/app/src/components/Bookmarks/BookmarkFolderTree.tsx
packages/app/src/components/Bookmarks/BookmarkItem.tsx
packages/app/src/components/Sidebar/Bookmarks/BookmarkContents.tsx
packages/app/src/components/UsersHomePageFooter.module.scss
packages/app/src/components/UsersHomePageFooter.tsx
packages/app/src/interfaces/bookmark-info.ts
packages/app/src/server/models/bookmark-folder.ts
packages/app/src/server/routes/apiv3/bookmark-folder.ts
packages/app/src/server/routes/apiv3/bookmarks.js
packages/app/src/stores/bookmark-folder.ts
packages/app/src/stores/bookmark.ts
packages/app/src/styles/molecules/_bookmark-folder-tree.scss
packages/app/src/styles/theme/_apply-colors-dark.scss
packages/app/src/styles/theme/_apply-colors-light.scss

https://youtrack.weseek.co.jp/issue/GW-7920

feat: gw7920 save and display bookmarks outside folder

---

packages/app/src/server/service/config-loader.ts
packages/app/test/cypress/integration/40-admin/40-admin--access-to-admin-page.spec.ts

https://redmine.weseek.co.jp/issues/116944

refs 116539: change default appappSiteUrl hash settings to false

---

packages/app/public/static/locales/en_US/commons.json
packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/commons.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/commons.json
packages/app/public/static/locales/zh_CN/translation.json

https://redmine.weseek.co.jp/issues/116947

refs 116946: fix proactive questionnaire answered modal i18n

---

packages/app/public/static/locales/en_US/translation.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/translation.json
packages/app/src/components/Bookmarks/BookmarkFolderItem.tsx
packages/app/src/components/Bookmarks/BookmarkFolderTree.module.scss
packages/app/src/components/Bookmarks/BookmarkFolderTree.tsx
packages/app/src/components/UsersHomePageFooter.module.scss
packages/app/src/styles/theme/_apply-colors-dark.scss
packages/app/src/styles/theme/_apply-colors-light.scss

https://youtrack.weseek.co.jp/issue/GW-7923

feat: gw7923 fix droppable item status

---

packages/app/src/server/routes/apiv3/pages.js
packages/app/src/server/service/page.ts

[#116862](https://redmine.weseek.co.jp/issues/116862) [v6] 検索結果から複数ページ選択して削除ができない
└ [#116864](https://redmine.weseek.co.jp/issues/116864) 修正

fix: Unable to delete multiple pages

---

packages/app/src/client/services/page-operation.ts
packages/app/src/client/services/side-effects/hackmd-draft-updated.ts
packages/app/src/client/services/side-effects/page-updated.ts
packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
packages/app/src/components/Page/PageContentsUtilities.tsx
packages/app/src/components/Page/PageView.tsx
packages/app/src/components/PageAlert/OldRevisionAlert.tsx
packages/app/src/components/PageAlert/PageAlerts.tsx
packages/app/src/components/PageAttachment.tsx
packages/app/src/components/PageEditor.tsx
packages/app/src/components/PageEditor/ConflictDiffModal.tsx
packages/app/src/components/PageEditorByHackmd.tsx
packages/app/src/components/PageHistory.tsx
packages/app/src/components/PagePathNav.tsx
packages/app/src/components/SavePageControls.tsx
packages/app/src/components/ShareLink/ShareLink.tsx
packages/app/src/components/ShareLink/ShareLinkForm.tsx
packages/app/src/components/ShareLink/ShareLinkPageView.tsx
packages/app/src/components/Sidebar/PageTree.tsx
packages/app/src/pages/[[...path]].page.tsx
packages/app/src/pages/share/[[...path]].page.tsx
packages/app/src/pages/trash.page.tsx
packages/app/src/stores/context.tsx
packages/app/src/stores/page.tsx
packages/app/src/stores/ui.tsx

[#115878](https://redmine.weseek.co.jp/issues/115878) [v6] ページ新規作成時に画像を添付して保存しようとすると保存に失敗する
└ [#115996](https://redmine.weseek.co.jp/issues/115996) 修正

fix: Error when trying to create a new page with attachments

---

packages/app/public/static/locales/en_US/commons.json
packages/app/public/static/locales/ja_JP/commons.json
packages/app/public/static/locales/ja_JP/translation.json
packages/app/public/static/locales/zh_CN/commons.json
packages/app/src/client/util/bookmark-utils.ts
packages/app/src/client/util/input-validator-utils.ts
packages/app/src/components/BookmarkButtons.tsx
packages/app/src/components/Bookmarks/BookmarkFolderItem.tsx
packages/app/src/components/Bookmarks/BookmarkFolderItemControl.tsx
packages/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
packages/app/src/components/Bookmarks/BookmarkFolderMenuItem.tsx
packages/app/src/components/Bookmarks/BookmarkFolderNameInput.tsx
packages/app/src/components/Bookmarks/BookmarkFolderTree.tsx
packages/app/src/components/Bookmarks/BookmarkItem.tsx
packages/app/src/components/DeleteBookmarkFolderModal.tsx
packages/app/src/components/Icons/CompressIcon.tsx
packages/app/src/components/Icons/ExpandIcon.tsx
packages/app/src/components/Icons/FolderIcon.tsx
packages/app/src/components/Icons/FolderPlusIcon.tsx
packages/app/src/components/Icons/TriangleIcon.tsx
packages/app/src/components/Layout/BasicLayout.tsx
packages/app/src/components/Navbar/SubNavButtons.tsx
packages/app/src/components/PageList/BookmarkList.tsx
packages/app/src/components/Sidebar/Bookmarks.tsx
packages/app/src/components/Sidebar/Bookmarks/BookmarkContents.tsx
packages/app/src/components/Sidebar/PageTree/Item.tsx
packages/app/src/components/Sidebar/SidebarContents.tsx
packages/app/src/components/UsersHomePageFooter.tsx

https://youtrack.weseek.co.jp/issue/GW-7926

feat: refactor and clean code

---

packages/app/src/interfaces/questionnaire/proactive-questionnaire-answer.ts
packages/app/src/server/models/questionnaire/proactive-questionnaire-answer.ts
packages/app/src/server/models/questionnaire/questionnaire-answer.ts
packages/app/src/server/models/questionnaire/schema/answer.ts
packages/app/src/server/models/questionnaire/schema/growi-info.ts
packages/app/src/server/models/questionnaire/schema/user-info.ts
packages/app/src/server/routes/apiv3/questionnaire.ts

https://redmine.weseek.co.jp/issues/117533
新しく追加した interface、schema、model はアンケートサーバのコードから大部分をコピペしています。

refs 117514: save questionnaire answers when failed to send

---

packages/app/src/components/Admin/App/QuestionnaireSettings.tsx
packages/app/src/components/Me/OtherSettings.tsx

lint error の修正
master 取り込みで発生してた conflict 解消のつづき
https://github.com/weseek/growi/pull/7316/commits/fd6f4e583e4c506a9ca41ef76157f250d8185d2a
https://github.com/weseek/growi/pull/7316/commits/c0c5f50c00069f117e35e6f314feafd80e258947

fix: Lint error

---

packages/app/src/components/ReactMarkdownComponents/Attachment.tsx

task: https://redmine.weseek.co.jp/issues/117432
p タグの中に div タグがあったことが問題だったので span タグを使う

fix: Rich attachment hydration error

---

packages/app/src/components/ReactMarkdownComponents/NextLink.tsx

task: https://redmine.weseek.co.jp/issues/118602

fix: Attachment links do not work correctly

---

packages/app/src/components/PageEditor/DrawioModal.jsx

https://redmine.weseek.co.jp/issues/118904

support: draw.io 21.1.3 for v5

---

packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
packages/app/src/components/PageEditor/CodeMirrorEditor.module.scss
packages/app/src/components/PageEditor/CommentMentionHelper.ts

https://youtrack.weseek.co.jp/issue/GW-7938
- Move import of codemirror/addon/hint/show-hint.css to CodemirrorEditor
- Define type for getUsersList return type
- Implement translation for user not found hint
- Replace substr with slice
- Fix typo of getUsenameHint menthod
- Import i18n from next-i18next and implement t function

fix: search username in comment not working

---

packages/app/test/cypress/integration/20-basic-features/20-basic-features--username-mention.spec.ts

https://youtrack.weseek.co.jp/issue/GW-7939
- Add cypress spec for mention username in comment

feat: Add cypress test for mention username in comment 

---

packages/app/src/components/PageComment/CommentEditor.tsx
packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
packages/app/src/components/PageEditor/CodeMirrorEditor.module.scss
packages/app/src/components/PageEditor/CommentMentionHelper.ts
packages/app/src/components/PageSideContents.tsx
packages/app/test/cypress/integration/20-basic-features/20-basic-features--username-mention.spec.ts

An username incremental search in the comment field is not working
https://youtrack.weseek.co.jp/issue/GW-7937
[GROWI][Mudanaさんに依頼] コメント欄の username インクリメントサーチが機能していない
- 修正 & マージ依頼
- [119484](https://redmine.weseek.co.jp/issues/119484)
このあたり
https://growi-vrt-snapshots.s3.amazonaws.com/c3566f854c637756c3b91496990174f639bfcd37/index.html?id=new-20-basic-features--username-mention.spec.ts/mention-username-1-username-found.png

fix: Username incremental search is not working in comment

---

packages/app/src/components/Admin/ExportArchiveDataPage.tsx

[119882](https://redmine.weseek.co.jp/issues/119882)

fix: Is not working i18n on `/admin/export` 

---

packages/app/test/cypress/integration/20-basic-features/20-basic-features--access-to-page.spec.ts

[#119757](https://redmine.weseek.co.jp/issues/119757) [GROWI] テンプレートページが適用される階層にページツリーからページを作成した時にテンプレートが適用されない
└ [#119866](https://redmine.weseek.co.jp/issues/119866) VRT 拡充

feat: VRT expansion of template page operations

---

packages/app/src/components/ReactMarkdownComponents/Attachment.tsx
packages/app/src/components/ReactMarkdownComponents/NextLink.tsx

task: https://redmine.weseek.co.jp/issues/119498
- PDF を別タブで開けるようにする
- こちらで入れていただいたコードを削除 😥 [7430](https://github.com/weseek/growi/pull/7430)

feat: Be able to preview PDFs

---

apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx

task: https://redmine.weseek.co.jp/issues/120816

feat: Fix bookmark status unchanged bug

---

apps/app/src/components/ReactMarkdownComponents/Attachment.tsx
apps/app/src/server/routes/apiv3/attachment.js
apps/app/src/stores/attachment.tsx
apps/app/src/stores/modal.tsx

task: https://redmine.weseek.co.jp/issues/118145
- attachment id を渡すと attachment data を個別に取得できる useSWRxAttachment を作成しました。
- IAttachmentHasId を関連個所のみで使用しました。 ref: [7597](https://github.com/weseek/growi/pull/7597)

feat: Create useSWRxAttachment

---

apps/app/src/components/Common/Dropdown/PageItemControl.tsx
packages/ui/src/interfaces/popper-data.ts
packages/ui/src/utils/reactstrap-modifiers.ts

task:https://redmine.weseek.co.jp/issues/121201

imprv: Create getCustomModifiers

---

apps/app/src/server/models/user.js
apps/app/src/server/routes/apiv3/users.js

task: 
- https://redmine.weseek.co.jp/issues/120954
- https://redmine.weseek.co.jp/issues/121032
ROM user のエンドポイントとスキーマの作成

feat: Create giveReadOnly and removeReadOnly endpoints

---

apps/app/src/components/UsersHomePageFooter.tsx

task: https://redmine.weseek.co.jp/issues/121191

feat: Remove Create bookmark folder button from UsersHomePageFooter

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
apps/app/src/components/Bookmarks/BookmarkFolderMenuItem.tsx

task: https://redmine.weseek.co.jp/issues/119728
- 子フォルダはインデント表示
- ブックマークをフォルダに含めないときは「フォルダに含めない」を選択

feat: Update BookmarkFolderMenu

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
apps/app/src/components/Bookmarks/BookmarkFolderMenuItem.tsx

task:https://redmine.weseek.co.jp/issues/120911

feat: Apply design FB to BookmarkFolderMenu

---

apps/app/src/server/service/config-loader.ts

task: https://redmine.weseek.co.jp/issues/122043

feat: Set questionnaire server origin

---

bin/data-migrations/v6/src/processor.js

[#118665](https://redmine.weseek.co.jp/issues/118665) DOM clobbering 対策のための mdcont- prefix の廃止
└ [#121595](https://redmine.weseek.co.jp/issues/121595) data-migrations script 作成

feat: Create mdcont prefix processor (data-migration script)

---

.devcontainer/docker-compose.yml
apps/app/package.json
apps/app/src/server/models/activity.ts
apps/app/src/server/service/in-app-notification.ts
apps/app/src/server/service/page.ts
apps/app/src/server/util/mongoose-utils.ts
apps/app/test/integration/service/questionnaire-cron.test.ts
yarn.lock

task: https://redmine.weseek.co.jp/issues/122359

support: mongoose update

---

.devcontainer/docker-compose.yml

[#120343](https://redmine.weseek.co.jp/issues/120343) [GROWI]  ElasticSearch v8 アップグレード
└ [#122348](https://redmine.weseek.co.jp/issues/122348) docker-compose の v8 対応 (本体)

imprv: Update docker-compse

---

apps/app/src/components/Admin/AdminHome/AdminHome.jsx
apps/app/src/components/Admin/AdminHome/EnvVarsTable.tsx

- https://redmine.weseek.co.jp/issues/121647
`apps/app/src/components/Admin/AdminHome/EnvVarsTable.jsx` をTS/FC 化

imprv: Change from EnvVarsTable.jsx to EnvVarsTable.tsx

---

apps/app/src/components/DuplicatedPathsTable.tsx

DuplicatedPathsTable.jsxをTS/FC化
https://redmine.weseek.co.jp/issues/121992

imprv: Change from DuplicatedPathsTable.jsx to DuplicatedPathsTable.tsx

---

apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
apps/app/src/server/models/bookmark-folder.ts

task: https://redmine.weseek.co.jp/issues/122625
- `dev/6.1.x` 向け

fix: Able to delete other users bookmarks

---

apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
apps/app/src/components/PageList/PageListItemL.tsx
apps/app/src/components/Sidebar/Bookmarks/BookmarkContents.tsx
apps/app/src/components/Sidebar/PageTree/Item.tsx
apps/app/src/components/UsersHomePageFooter.tsx
apps/app/src/server/routes/apiv3/bookmark-folder.ts
apps/app/src/stores/bookmark-folder.ts
apps/app/src/stores/bookmark.ts

[#122549](https://redmine.weseek.co.jp/issues/122549) [GROWI] 自分以外の user ページの bookmark 一覧に自分の bookmark が表示されてしまっている
└ [#122554](https://redmine.weseek.co.jp/issues/122554) 修正

fix: Your bookmarks are displayed on other users home pages

---

apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
apps/app/src/interfaces/bookmark-info.ts
apps/app/src/server/models/bookmark-folder.ts
apps/app/src/server/routes/apiv3/bookmark-folder.ts
apps/app/src/server/routes/apiv3/bookmarks.js

task: https://redmine.weseek.co.jp/issues/122714
Bookmark 関連の修正(不具合内容はストーリー説明欄に詳細)で [master 向け PR](https://github.com/weseek/growi/pull/7673) があったので `dev/6.1.x` 向けとして用意しました。

fix: User picture of bookmark not showing inside bookmark folder (v6.1.x)

---

apps/app/src/components/PageRenameModal.tsx

task: https://redmine.weseek.co.jp/issues/122713

imprv: Update name attribute of PageRenameModal.tsx (v6.1.x)

---

apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
apps/app/src/components/Bookmarks/BookmarkItem.tsx
apps/app/src/components/Sidebar/Bookmarks/BookmarkContents.tsx
apps/app/src/components/UsersHomePageFooter.tsx
apps/app/src/server/models/bookmark-folder.ts

[#122761](https://redmine.weseek.co.jp/issues/122761) [GROWI] 他人の bookmark folder を update, delete できてしまう
└ [#122774](https://redmine.weseek.co.jp/issues/122774) 修正

fix: Bookmark folders owned by others are accessible for manipulation

---

apps/app/src/components/PageRenameModal.tsx

task: https://redmine.weseek.co.jp/issues/122829
関連PR(dev/v6.1.x 向け): https://github.com/weseek/growi/pull/7677

fix: Update name attribute of PageRenameModal.tsx

---

apps/app/src/client/util/bookmark-utils.ts
apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
apps/app/src/interfaces/bookmark-info.ts
apps/app/src/server/models/bookmark-folder.ts
apps/app/src/server/models/serializers/bookmark-serializer.js
apps/app/src/server/routes/apiv3/bookmark-folder.ts
apps/app/src/server/routes/apiv3/bookmarks.js

redmine task: https://redmine.weseek.co.jp/issues/122715
https://github.com/weseek/growi/pull/7685
https://github.com/weseek/growi/pull/7678
Edited by ryoji-s
-----------------------
https://youtrack.weseek.co.jp/issue/GW-7955
- Bookmark item user image not showing inside bookmarks folder but showing in root folder
- `lastUpdateUser` on the page object does not populate user object but the user id. So, UserPicture component uses default image instead of the user's profile image
- Populate user object (`lastUpdateUser`) in page object of bookmark folder items
https://github.com/weseek/growi/assets/92426728/46ef1e7a-9903-405a-aa59-b9df32d2edba

fix:  User picture of bookmark not showing inside bookmark folder

---

apps/app/src/client/util/bookmark-utils.ts
apps/app/src/components/Bookmarks/BookmarkFolderItem.tsx
apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
apps/app/src/components/Bookmarks/BookmarkItem.tsx
apps/app/src/components/PageList/PageListItemL.tsx
apps/app/src/components/PageRenameModal.tsx
apps/app/src/components/Sidebar/Bookmarks/BookmarkContents.tsx
apps/app/src/components/Sidebar/PageTree/Item.tsx
apps/app/src/components/UsersHomePageFooter.tsx
apps/app/src/interfaces/bookmark-info.ts
apps/app/src/server/models/bookmark-folder.ts
apps/app/src/server/models/serializers/bookmark-serializer.js
apps/app/src/server/routes/apiv3/bookmark-folder.ts
apps/app/src/server/routes/apiv3/bookmarks.js
apps/app/src/stores/bookmark-folder.ts
apps/app/src/stores/bookmark.ts
packages/remark-attachment-refs/vite.client.config.ts

* fix: Bookmark folders owned by others are accessible for manipulation (#7688) @miya
* fix: remark-attachment-refs does not work in production (#7681) @yuki-takei
* fix: User picture of bookmark not showing inside bookmark folder (#7678) @mudana-grune
* fix: Update name attribute of PageRenameModal.tsx (#7677) @jam411
* fix: The user's bookmarks are displayed on unrelated user's home (#7668) @miya
* fix: The user's bookmarks are updated by unrelated user's operation (#7670) @jam411

Release v6.1.1

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/components/PageList/PageList.tsx
apps/app/src/components/PageTimeline.tsx
apps/app/src/stores/page-timeline.tsx

- 概要
- ページリスト > タイムライン を無限スクロール可能に。
- Task
- https://redmine.weseek.co.jp/issues/115299

imprv: Implement infinite scroll into PageTimeline

---

.eslintrc.js
apps/app/src/server/models/eslint-rules-dir/test/no-populate.spec.ts
apps/app/src/services/renderer/rehype-plugins/relative-links-by-pukiwiki-like-linker.spec.ts
apps/app/src/services/renderer/rehype-plugins/relative-links-by-pukiwiki-like-linker.ts
apps/app/src/services/renderer/rehype-plugins/relative-links.spec.ts
apps/app/src/services/renderer/rehype-plugins/relative-links.ts
apps/app/src/services/renderer/remark-plugins/pukiwiki-like-linker.spec.ts

fix: Hash and search query in the relative link are omitted wrongly

---

bin/data-migrations/README.md

[#122342](https://redmine.weseek.co.jp/issues/122342) [GROWI] migration script のリファクタ
└  [#123012](https://redmine.weseek.co.jp/issues/123012) README.md の更新

imprv: Update migration script docs

---

apps/app/package.json
apps/app/src/components/TemplateModal.tsx
apps/app/src/components/TemplateModal/index.tsx
apps/app/src/components/TemplateModal/use-formatter.spec.tsx
apps/app/src/components/TemplateModal/use-formatter.tsx
apps/app/src/stores/modal.tsx
apps/app/src/stores/template.tsx
yarn.lock

- https://redmine.weseek.co.jp/issues/123485
- https://redmine.weseek.co.jp/issues/123473

imprv: Update preset templates

---

apps/app/public/static/locales/en_US/admin.json
apps/app/public/static/locales/ja_JP/admin.json
apps/app/public/static/locales/zh_CN/admin.json
apps/app/src/components/Admin/Users/PasswordResetModal.jsx
apps/app/src/components/PageRenameModal.tsx
apps/app/src/server/routes/apiv3/users.js

https://redmine.weseek.co.jp/issues/122638
パスワードリセットモーダルにメール送信用のチェックボックスを表示

imprv: Add checkbox to reset-password-modal

---

apps/app/public/static/locales/en_US/admin.json
apps/app/public/static/locales/ja_JP/admin.json
apps/app/public/static/locales/zh_CN/admin.json
apps/app/src/components/Admin/Security/SecuritySetting.jsx

task: https://redmine.weseek.co.jp/issues/114672

imprv: Add i18n json property

---

apps/app/src/stores/editor.tsx

fix: Slack channels data for User Triggered Notification is not loaded

---

apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
apps/app/src/components/Navbar/SubNavButtons.tsx
apps/app/src/components/PageList/PageListItemL.tsx
apps/app/src/components/Sidebar/PageTree/Item.tsx
apps/app/src/stores/bookmark.ts

- add `useSWRMUTxCurrentUserBookmarks`
- refactoring

fix: Bookmarks mutation for the current user

---

apps/app/src/components/Admin/AuditLog/ActivityTable.tsx
apps/app/src/components/Navbar/AuthorInfo.tsx
apps/app/src/components/Navbar/PersonalDropdown.jsx
apps/app/src/components/PageCreateModal.jsx
apps/app/src/components/User/Username.tsx
apps/app/src/server/events/user.ts
apps/app/src/server/routes/apiv3/users.js
packages/core/src/utils/page-path-utils/index.ts
packages/ui/src/components/User/UserPicture.tsx

task: https://redmine.weseek.co.jp/issues/124324
- `/user/{username}` の path を返す定数のユーティリティ関数化
- すでに同じような責務の userPageRoot という関数があったのでそちらと統合しました。

imprv: Utilitize userHomepagePath

---

packages/remark-lsx/src/server/routes/list-pages/index.ts
packages/remark-lsx/src/services/renderer/lsx.ts

fix(lsx): Prefix is not uniquely determined by usage

---

apps/app/src/server/events/user.ts
apps/app/src/server/routes/apiv3/users.js
apps/app/src/server/service/page.ts

task: https://redmine.weseek.co.jp/issues/124326
- `Page.findByPath()` の引数を修正
- `deleteCompletelyUserHomeBySystem` にも user を渡さない方針で修正する (PageOperation スキーマで user が required なので必要かもしれない)
後続タスク: https://redmine.weseek.co.jp/issues/124592

imprv: Delete user arguments

---

apps/app/src/components/LoginForm.tsx

https://redmine.weseek.co.jp/issues/125024
ログインフォームでloading中の場合、フォームのswitchができないようにしました。
https://github.com/weseek/growi/assets/112812878/82522de9-a7d6-40fd-b645-ffc46cd1e874

imprv: Don't switch login form  while loading

---

apps/app/src/server/routes/apiv3/users.js

https://redmine.weseek.co.jp/issues/125886

imprv: Change from txt to ejs

---

apps/app/src/pages/[[...path]].page.tsx

[#126306](https://redmine.weseek.co.jp/issues/126306) skipSSR 時にページ本文が表示されない

fix: Page body is not displayed when skipSSR

---

packages/remark-lsx/src/server/routes/list-pages/index.ts

fix(lsx): Except option

---

apps/app/src/services/renderer/remark-plugins/attachment.ts

https://redmine.weseek.co.jp/issues/126434

imprv: Add type guard

---

apps/app/src/components/TemplateModal/TemplateModal.tsx
apps/app/test/cypress/e2e/23-editor/23-editor--template-modal.cy.ts

- https://redmine.weseek.co.jp/issues/126557

support: Cypress test for TemplateModal

---

apps/app/src/components/PageEditor.tsx
apps/app/src/pages/[[...path]].page.tsx

https://redmine.weseek.co.jp/issues/125923
- https://github.com/weseek/growi/pull/7844
- cause: Decrease in DX
- https://github.com/weseek/growi/compare/6c3b393...67575ff

fix: Revert current page mutation and add workaround for saving page

---

apps/app/src/components/ReactMarkdownComponents/NextLink.tsx
packages/core/src/utils/page-path-utils/index.ts

[#126253](https://redmine.weseek.co.jp/issues/126253) 不要な next routing を回避する
└ [#126288](https://redmine.weseek.co.jp/issues/126288) 修正

fix: Avoid unnecessary next routing

---

apps/app/src/components/Layout/BasicLayout.tsx
apps/app/src/components/Page/PageView.tsx
apps/app/src/components/ReactMarkdownComponents/Header.tsx
apps/app/src/components/Sidebar.tsx
apps/app/test/cypress/e2e/20-basic-features/20-basic-features--access-to-page.cy.ts
apps/app/test/cypress/e2e/20-basic-features/20-basic-features--use-tools.cy.ts
apps/app/test/cypress/e2e/21-basic-features-for-guest/21-basic-features-for-guest--access-to-page.cy.ts
apps/app/test/cypress/e2e/22-sharelink/22-sharelink--access-to-sharelink.cy.ts
apps/app/test/cypress/e2e/23-editor/23-editor--saving.cy.ts
apps/app/test/cypress/support/assertions.ts
apps/app/test/cypress/support/commands.ts
apps/app/test/cypress/support/index.ts

fix: Auto-scroll does not work when accessing the page when the header string is CJK

---

apps/app/test/integration/service/ldap-user-group-sync.test.ts

https://redmine.weseek.co.jp/issues/126409

refs 126409: LdapUserGroupSync test

---

apps/app/src/components/SearchPage/SearchPageBase.tsx

https://redmine.weseek.co.jp/issues/127029

support: Render SearchPageBase in CSR

---

apps/app/src/components/PageAlert/TrashPageAlert.tsx

- https://redmine.weseek.co.jp/issues/127121
image

imprv: Show alert for trashed pages only when the page is not empty

---

apps/app/src/features/questionnaire/server/service/questionnaire.ts
apps/app/test/integration/service/questionnaire.test.ts
turbo.json

- Change answer data source.
- https://redmine.weseek.co.jp/issues/127253

fix: Questionnaire wikiType

---

apps/app/src/client/services/page-operation.ts
apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
apps/app/src/components/PageEditor.tsx
apps/app/src/components/SavePageControls.tsx

- fix #7924
- related to
- #7877
- https://github.com/weseek/growi/pull/7844#discussion_r1252716884
- Story: https://redmine.weseek.co.jp/issues/127705
- Task: https://redmine.weseek.co.jp/issues/127708

fix: Page creation and update process

---

apps/app/src/components/Comments.tsx
apps/app/src/components/Page/RevisionLoader.tsx
apps/app/src/components/PageComment.tsx
apps/app/src/components/SearchPage/SearchResultContent.tsx

https://redmine.weseek.co.jp/issues/127418

fix: Auto-scroll search result content

---

apps/app/config/logger/config.dev.js
apps/app/src/migrations/20230731075753-add_installed_date_to_config.js
apps/app/src/server/models/config.ts

- https://redmine.weseek.co.jp/issues/127339

imprv: Persist the installed date in the Config collection

---

apps/app/src/components/SearchPage/SearchResultContent.tsx

- Calculate the current relative position from the scrollElement

fix: Auto-scroll search result content 2

---

apps/app/_obsolete/src/components/PageEditor/ConflictDiffModal.tsx
apps/app/src/components/Admin/Users/UserMenu.tsx
apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
apps/app/src/components/DescendantsPageListModal.tsx
apps/app/src/components/Page/CopyDropdown.jsx
apps/app/src/components/PageAccessoriesModal/PageAccessoriesModal.tsx
apps/app/src/components/PageEditor/HandsontableModal.tsx
apps/app/src/components/PageList/PageListItemL.tsx
apps/app/src/components/RevisionComparer/RevisionComparer.tsx
apps/app/src/components/SearchPage/OperateAllControl.tsx
apps/app/src/components/Sidebar/RecentChanges/RecentChangesContentSkeleton.tsx

- https://redmine.weseek.co.jp/issues/128494
- https://redmine.weseek.co.jp/issues/128768
- https://redmine.weseek.co.jp/issues/128769
- https://redmine.weseek.co.jp/issues/128495
- CustomInput を reactstrap の Input に置き換え
- positionFixed を strategy='fixed' に置き換え
- left/right を end/start にする
- RecentChangesContentSkeleton を有効化
- breaking changes 対応最後のタスクを後続タスク化 https://redmine.weseek.co.jp/issues/128470
- https://github.com/weseek/growi/pull/7983

support: reactstrap breaking changes

---

apps/app/src/components/ParentPageSelectModal.tsx
apps/app/src/components/Sidebar/PageTree/Item.tsx

https://redmine.weseek.co.jp/issues/128324
これまでpage treeのページのリンクを変更しました。具体的にはLinkをやめてonclickで挙動を制御するようにしました。
https://redmine.weseek.co.jp/issues/128325
https://redmine.weseek.co.jp/issues/128326
https://redmine.weseek.co.jp/issues/128145

feat: Refactoring of page tree link

---

apps/app/src/components/PageEditor/PageEditor.tsx
packages/editor/package.json
packages/editor/src/components/playground/PlaygroundController.tsx
packages/editor/src/services/codemirror-editor/use-codemirror-editor.ts
yarn.lock

- https://redmine.weseek.co.jp/issues/128972
- https://redmine.weseek.co.jp/issues/129127

feat(editor): setCursor method

---

apps/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
apps/app/src/components/CustomNavigation/CustomNav.tsx
apps/app/src/components/PageEditor/Cheatsheet.tsx
apps/app/src/components/PageEditor/Editor.tsx
apps/app/src/components/PageSideContents.tsx
apps/app/src/components/PasswordResetExecutionForm.tsx
apps/app/src/components/PasswordResetRequestForm.tsx
apps/app/src/components/Sidebar/Bookmarks/BookmarkContents.tsx
apps/app/src/components/Sidebar/PersonalDropdown.tsx
apps/app/src/features/questionnaire/client/components/Question.tsx
packages/remark-lsx/src/client/components/Lsx.tsx

- https://redmine.weseek.co.jp/issues/129174
btn-block, btn-group-toggle, data-toggle="button" を削除

support: Bootstrap v5 braking changes Buttons

---

apps/app/src/components/Admin/Common/Accordion.jsx
apps/app/src/components/Admin/Customize/CustomizeLayoutSetting.tsx
apps/app/src/components/Admin/Customize/CustomizeSidebarSetting.tsx
apps/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
apps/app/src/components/CreateTemplateModal.jsx

https://redmine.weseek.co.jp/issues/129175
- card-deck をリプレース
- accordion は後続タスク https://redmine.weseek.co.jp/issues/129222

support: Bootstrap v5 braking changes Card

---

apps/app/src/styles/theme/_apply-colors-dark.scss

https://redmine.weseek.co.jp/issues/129284

support: Bootstrap v5 breaking changes Popover

---

apps/app/src/components/LoginForm.tsx
apps/app/src/components/PageEditor/Editor.tsx

https://redmine.weseek.co.jp/issues/129283

support: Bootstrap v5 breaking changes Helpers

---

apps/app/src/styles/atoms/mixins/_buttons.scss
apps/app/src/styles/theme/_apply-colors-dark.scss
apps/app/src/styles/theme/_hsl-reboot-bootstrap-theme-colors.scss
apps/app/src/styles/theme/_reboot-bootstrap-dropdown.scss
apps/app/src/styles/theme/_reboot-bootstrap-nav.scss
apps/app/src/styles/theme/_reboot-bootstrap-theme-colors.scss
apps/app/src/styles/theme/apply-colors.scss
apps/app/src/styles/theme/mixins/_hsl-badge.scss
apps/app/src/styles/theme/mixins/_hsl-button.scss
packages/preset-themes/src/styles/atoms/mixins/_buttons.scss
packages/preset-themes/src/styles/theme/mixins/_hsl-button.scss

https://redmine.weseek.co.jp/issues/129382

support: Bootstrap v5 breaking changes Sass

---

apps/app/src/client/services/AdminCustomizeContainer.js
packages/presentation/src/components/Presentation.tsx
packages/presentation/src/services/growi-marpit.ts

管理者設定画面のファンクションにおいて、更新が成功しているときはその旨を正しく表示するようにする
- https://redmine.weseek.co.jp/issues/129384
- https://redmine.weseek.co.jp/issues/129404

imprv: Correct update message

---

CHANGELOG.md
apps/app/src/client/services/search-operation.ts
apps/app/src/components/Navbar/GlobalSearch.tsx
apps/app/src/components/Page/RenderTagLabels.tsx
apps/app/src/components/SearchPage.tsx
apps/app/src/components/SearchPage/SearchControl.tsx
apps/app/src/components/Sidebar/RecentChanges.tsx
apps/app/src/components/TagCloudBox.tsx
apps/app/src/components/TagList.tsx
apps/app/src/stores/tag.tsx

https://redmine.weseek.co.jp/issues/129156

imprv: Search behavior

---

apps/app/src/components/ReactMarkdownComponents/LightBox.tsx

https://redmine.weseek.co.jp/issues/130872
https://github.com/weseek/growi/pull/7988

fix: Do not work img tag if use style property 62x

---

apps/app/src/components/ReactMarkdownComponents/LightBox.tsx

https://redmine.weseek.co.jp/issues/130873
https://github.com/weseek/growi/pull/7988
https://github.com/weseek/growi/pull/8092

fix: Do not work img tag if use style property 70x

---

apps/app/src/features/approval-workflow/interfaces/workflow.ts
apps/app/src/features/approval-workflow/server/models/serializers/workflow-seroalizer.ts
apps/app/src/features/approval-workflow/server/routes/apiv3/workflow.ts

[#130307](https://redmine.weseek.co.jp/issues/130307) [approval-workflow] ワークフロー一覧画面からワークフロー詳細画面に遷移できる
└ [#130921](https://redmine.weseek.co.jp/issues/130921) [server] GET: /{workflowId} のロジック実装

feat: Implement endpoints to retrieve workflow

---

packages/presentation/src/services/renderer/slides.ts

- Marp を無効化しているのに Marp が表示できる問題の修正
- https://redmine.weseek.co.jp/issues/131158
- https://redmine.weseek.co.jp/issues/131159

fix: Marp is enabled incorrectly problem

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/features/approval-workflow/client/components/WorkflowListPage.tsx
apps/app/src/features/approval-workflow/client/components/WorkflowModal.tsx
apps/app/src/features/approval-workflow/client/services/workflow.ts

[#129959](https://redmine.weseek.co.jp/issues/129959) [approval-workflow] ワークフローを削除できる
└ [#130366](https://redmine.weseek.co.jp/issues/130366) [client] ワークフロー一覧画面にワークフローの削除ボタンを実装
└ [#130367](https://redmine.weseek.co.jp/issues/130367) [client] 削除ボタンを押下した時に workflow の削除ができる

feat: Delete button on the list page

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/features/approval-workflow/client/components/WorkflowListPage.tsx

[#129959](https://redmine.weseek.co.jp/issues/129959) [approval-workflow] ワークフローを削除できる
└ [#131297](https://redmine.weseek.co.jp/issues/131297) [client] 削除権限が無いユーザーに対して理由を tooltip で表示する

feat: Tooltip for workflow delete button

---

apps/app/src/components/PageEditor/PageEditor.tsx

https://redmine.weseek.co.jp/issues/130932

feat: Use global socket ns

---

apps/app/src/server/service/socket-io.js

https://redmine.weseek.co.jp/issues/130773

feat: Add error handling

---

apps/app/src/features/external-user-group/server/service/keycloak-user-group-sync.integ.ts
apps/app/src/features/external-user-group/server/service/keycloak-user-group-sync.ts

task
https://redmine.weseek.co.jp/issues/130395

add test for keycloak user group sync serivce

---

apps/app/public/static/locales/en_US/admin.json
apps/app/public/static/locales/ja_JP/admin.json
apps/app/public/static/locales/zh_CN/admin.json

https://redmine.weseek.co.jp/issues/131841

support: Internationalization USER_REGISTRATION_APPROVAL_REQUEST label for v61x

---

apps/app/public/static/locales/en_US/admin.json
apps/app/public/static/locales/ja_JP/admin.json
apps/app/public/static/locales/zh_CN/admin.json

https://redmine.weseek.co.jp/issues/131841
- 手元では dev 環境を立ち上げて i18n されているか確認しました。
- ref: https://github.com/weseek/growi/pull/8129

support: Internationalization USER_REGISTRATION_APPROVAL_REQUEST label for v62x

---

apps/app/src/utils/promise.spec.ts
apps/app/src/utils/promise.ts

https://github.com/weseek/growi/pull/7884#discussion_r1274437824 の対応
task
https://redmine.weseek.co.jp/issues/132373

add throwIfRejected parameter

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowDetailModalContent.tsx
apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowEditModalContent.tsx
apps/app/src/features/approval-workflow/client/components/ModalComponents/index.ts
apps/app/src/features/approval-workflow/client/components/WorkflowModal.tsx

[#131556](https://redmine.weseek.co.jp/issues/131556) [approval-workflow] ワークフロー編集画面からワークフローを編集できる
└ [#131564](https://redmine.weseek.co.jp/issues/131564) [front] 詳細画面から編集画面に遷移できる

feat: Can move detail page to edit page

---

apps/app/src/features/external-user-group/server/routes/apiv3/external-user-group.ts
apps/app/src/server/models/config.ts

task https://redmine.weseek.co.jp/issues/132995

set default values for boolean values

---

apps/app/src/features/external-user-group/client/components/ExternalUserGroup/SyncExecution.tsx

task https://redmine.weseek.co.jp/issues/132998

set sync status to syncExecuting before API request

---

apps/app/src/components/SavePageControls/GrantSelector/GrantSelector.tsx

https://redmine.weseek.co.jp/issues/133245

show badge next to external user group

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/features/approval-workflow/client/components/ModalComponents/ApproverGroupCards.tsx
apps/app/src/features/approval-workflow/client/components/ModalComponents/SearchUserTypeahead.tsx
apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowCreationModalContent.tsx

[#130338](https://redmine.weseek.co.jp/issues/130338) [approval-workflow] XD 通りにワークフロー作成画面を実装しワークフローの作成ができる
┗ [#133700](https://redmine.weseek.co.jp/issues/133700) [front] 細かい UI/UX の修正

imprv: Minor UI / UX modifications

---

packages/remark-lsx/src/client/components/LsxPageList/LsxPage.tsx

fix: Show liker counts in lsx

---

apps/app/src/components/PageEditor/PageEditor.tsx
apps/app/src/components/SavePageControls.tsx
apps/app/src/server/routes/attachment.js

task:
https://redmine.weseek.co.jp/issues/133122
https://redmine.weseek.co.jp/issues/133121
Editor モードに移行できるときは必ずページが作成されているようになったので、
attachment を添付したときにページを作成する機構を omit しました。

feat: Omit `/attachemnts.add` endpoint page creating code

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/features/approval-workflow/client/components/ModalComponents/ApproverGroupCards.tsx
apps/app/src/features/approval-workflow/client/components/ModalComponents/SearchUserTypeahead.tsx
apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowCreationModalContent.tsx
apps/app/src/features/approval-workflow/client/services/workflow.ts
apps/app/src/server/models/user.js
apps/app/src/server/routes/apiv3/users.js
apps/app/src/stores/user.tsx

[#130338](https://redmine.weseek.co.jp/issues/130338) [approval-workflow] XD 通りにワークフロー作成画面を実装しワークフローの作成ができる
┗ [#133229](https://redmine.weseek.co.jp/issues/133229) [server] GET: /_api/v3/users に excludedUserIds オプションを追加して特定の user を検索対象から除外できる
┗ [#133495](https://redmine.weseek.co.jp/issues/133495) [front] user 検索を行う API への fetcher を実装しインクリメントサーチできる
https://github.com/weseek/growi/assets/34241526/b19da21a-1baf-4f4c-b9b7-622591f317c1

feat: Incremental search for user

---

apps/app/src/components/Layout/MainPane.tsx
apps/app/src/components/Navbar/GrowiNavbarBottom.tsx
apps/app/src/components/PageSideContents.tsx

- Hide side contents
- Support Chrome
- Hide navbar bottom

imprv: Printing styles 2

---

apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowEditModalContent.tsx
apps/app/src/features/approval-workflow/client/components/WorkflowModal.tsx
apps/app/src/features/approval-workflow/client/services/workflow.ts
apps/app/src/features/approval-workflow/client/stores/workflow.ts

[#132622](https://redmine.weseek.co.jp/issues/132622) [approval-workflow] XD 通りにワークフロー編集画面を実装しワークフローを編集できる
┗ [#133879](https://redmine.weseek.co.jp/issues/133879) [client] PUT: /:workflowId を行う fetcher 実装

feat: Implementation of an api fetcher to edit the workflow

---

apps/app/src/components/ReactMarkdownComponents/RichAttachment.tsx
apps/app/src/server/routes/index.js

https://redmine.weseek.co.jp/issues/134182

fix: 134182 can see attachment if shared page

---

apps/app/src/features/external-user-group/client/components/ExternalUserGroup/SyncExecution.tsx
apps/app/src/features/external-user-group/server/routes/apiv3/external-user-group.ts
apps/app/src/features/external-user-group/server/service/external-user-group-sync.ts

グループ同期中にページをリロードした際に、グループ同期が実行中であるかのステータスとその進捗を取得し、UI に反映させる。
https://redmine.weseek.co.jp/issues/134449

show sync status as 'in progress' on page reload

---

apps/app/package.json
yarn.lock

[#134381](https://redmine.weseek.co.jp/issues/134381) [v7][search] subnavigation の search アイコンクリックで全文検索用モーダルを表示できる
┗ [#134540](https://redmine.weseek.co.jp/issues/134540) react-instantsearch のインストール
github: https://github.com/algolia/instantsearch
document: https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/

support: react-instantsearch

---

apps/app/src/server/events/user.ts
apps/app/src/server/models/page.ts
apps/app/src/server/service/page.ts

https://redmine.weseek.co.jp/issues/134631

imprv: Refactor deleteCompletelyUserHomeBySystem

---

apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowDetailModalContent.tsx
apps/app/src/features/approval-workflow/client/components/ModalComponents/WorkflowListModalContent.tsx
apps/app/src/features/approval-workflow/utils/workflow.ts

[#135604](https://redmine.weseek.co.jp/issues/135604) [expand-notification] ワークフロー名が設定されていない場合はページ名を表示できる
┗ [#135606](https://redmine.weseek.co.jp/issues/135606) 実装

feat: Display the page name when the workflow name is not set

---

apps/app/src/client/services/layout.ts
apps/app/src/components/Common/PageViewLayout.module.scss
apps/app/src/components/Common/PageViewLayout.tsx
apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
apps/app/src/components/Page/PageView.tsx
apps/app/src/components/PageControls/PageControls.tsx
apps/app/src/components/PageEditor/PageEditor.tsx
apps/app/src/components/PageEditor/Preview.module.scss
apps/app/src/components/PageEditor/Preview.tsx
apps/app/src/components/SearchPage/SearchResultContent.module.scss
apps/app/src/components/SearchPage/SearchResultContent.tsx
apps/app/src/components/ShareLinkPageView.tsx
apps/app/src/components/Sidebar/Tag.tsx
apps/app/src/pages/[[...path]].page.tsx
apps/app/src/pages/me/[[...path]].page.tsx
apps/app/src/pages/share/[[...path]].page.tsx
apps/app/src/pages/tags.page.tsx
apps/app/src/pages/trash.page.tsx
apps/app/src/styles/_layout.scss
apps/app/src/styles/_mixins.scss
apps/app/src/styles/mixins/_fluid-layout.scss
apps/app/test/cypress/e2e/50-sidebar/50-sidebar--access-to-side-bar.cy.ts

https://redmine.weseek.co.jp/issues/134024

imprv: Fluid layout switching

---

apps/app/src/features/page-bulk-export/interfaces/page-bulk-export.ts
apps/app/src/features/page-bulk-export/server/models/page-bulk-export-job.ts
apps/app/src/features/page-bulk-export/server/models/page-bulk-export-page-info.ts
apps/app/src/features/page-bulk-export/server/models/page-bulk-export-result.ts

https://redmine.weseek.co.jp/issues/135776
https://dev.growi.org/655834752aa37f82842a2034

page bulk export related models

---

apps/app/src/server/events/user.ts
apps/app/src/server/service/page.ts

https://redmine.weseek.co.jp/issues/135893

fix: Update deleteCompletelyUserHomeBySystem for v4 process

---

apps/app/test/integration/service/external-user-group-sync.test.ts

https://redmine.weseek.co.jp/issues/136022

imprv: improve external user group sync service test

---

packages/editor/src/stores/use-collaborative-editor-mode.ts

task: https://redmine.weseek.co.jp/issues/135637

feat: Avoid leaving the awareness cursor when moving pages

---

apps/app/src/features/search/client/components/SearchResultMenuItem.tsx

[#134384](https://redmine.weseek.co.jp/issues/134384) [v7][search] 全文検索用モーダルでインクリメンタルサーチ結果を表示し、それを選択することで検索結果画面へ遷移できる
┗ [#136144](https://redmine.weseek.co.jp/issues/136144) loading 画面の実装

feat: Display loading screen when searching

---

packages/remark-drawio/src/components/DrawioViewer.module.scss
packages/remark-drawio/src/components/DrawioViewer.tsx

imprv: Refactor DrawioViewer re-rendering by the resizing trigger

---

apps/app/src/server/events/user.ts
apps/app/src/server/models/page.ts
apps/app/src/server/routes/apiv3/users.js
apps/app/src/server/service/page/consts.ts
apps/app/src/server/service/page/delete-completely-user-home-by-system.integ.ts
apps/app/src/server/service/page/delete-completely-user-home-by-system.ts
apps/app/src/server/service/page/index.ts
apps/app/src/server/service/page/page-service.ts
apps/app/src/server/service/page/should-use-v4-process.ts

task: https://redmine.weseek.co.jp/issues/123652
メソッドを移動させたので `deleteCompletelyUserHomeBySystem()` を使う 
- ユーザー削除時
- 削除済みユーザーと同じ username のユーザー作成時
と、
- ユーザー削除済みであれば user homepage も削除できる
を確認し期待通りの動作でした。

support: Add test for delete-completely-user-home-by-system.ts

---

apps/app/public/static/locales/en_US/commons.json
apps/app/public/static/locales/ja_JP/commons.json
apps/app/public/static/locales/zh_CN/commons.json
apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx

task: https://redmine.weseek.co.jp/issues/136321

feat: Apply i18n to `Create today's ...` page path

---

apps/app/package.json
apps/app/src/features/growi-plugin/server/services/growi-plugin/growi-plugin.ts
yarn.lock

マージする前に #8358 修正時に実施していたテストを行い、正常動作を確認する

imprv: Add types for unzip-stream

---

packages/preset-themes/src/styles/jade-green.scss
packages/preset-themes/vite.themes.config.ts

https://redmine.weseek.co.jp/issues/137467
JadeGreenテーマの実装

support: New JadeGreen

---

apps/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
apps/app/src/components/InAppNotification/InAppNotificationElm.tsx
apps/app/src/components/InAppNotification/InAppNotificationList.tsx
apps/app/src/components/InAppNotification/InAppNotificationPage.tsx
apps/app/src/components/Sidebar/InAppNotification/InAppNotification.tsx
apps/app/src/components/Sidebar/InAppNotification/InAppNotificationSubstance.tsx

[#137966](https://redmine.weseek.co.jp/issues/137966) [v7] サイドバーに通知を表示できる
┗ [#137968](https://redmine.weseek.co.jp/issues/137968) サイドバーに通知を表示させる
ほぼ旧通知の Dropdown の中身を持ってきただけ

feat: Show notifications in sidebar

---

apps/app/test/cypress/e2e/20-basic-features/20-basic-features--access-to-pagelist.cy.ts

https://github.com/weseek/growi/actions/runs/7622018654/job/20759385986?pr=8399#step:17:1481

fix: Normalization of 20-basic-features--access-to-pagelist.cy.ts

---

apps/app/src/components/PageControls/SearchButton.tsx
apps/app/src/features/search/client/components/SearchForm.tsx
apps/app/src/features/search/client/components/SearchMethodMenuItem.tsx
apps/app/src/features/search/client/components/SearchModal.tsx
apps/app/test/cypress/e2e/30-search/30-search--search.cy.ts

https://github.com/weseek/growi/actions/runs/7625369260/job/20769651102?pr=8403#step:17:698

fix: Normalization of 30-search--search.cy.ts

---

apps/app/test/cypress/e2e/21-basic-features-for-guest/21-basic-features-for-guest--access-to-page.cy.ts
apps/app/test/cypress/e2e/21-basic-features-for-guest/21-basic-features-for-guest--sticky-for-guest.cy.ts

https://github.com/weseek/growi/actions/runs/7650518257/job/20846782245?pr=8407#step:17:486
https://github.com/weseek/growi/actions/runs/7650518257/job/20846782245?pr=8407#step:17:707

fix: Normalization of 21-basic-features-for-guest--access-to-page.cy.ts

---

apps/app/src/components/PageEditor/EditorNavbarBottom.tsx
apps/app/test/cypress/e2e/20-basic-features/20-basic-features--sticky-features.cy.ts

https://github.com/weseek/growi/actions/runs/7651217185/job/20848683456?pr=8408#step:17:2600

fix: Normalization of 20-basic-features--sticky-features.cy.ts

---

apps/app/src/components/Common/Dropdown/PageItemControl.tsx
apps/app/src/server/service/page/index.ts
packages/core/src/interfaces/page.ts

task: https://redmine.weseek.co.jp/issues/139029
v62x 向け PR: https://github.com/weseek/growi/pull/8391

fix: Non-admin user cannot rename pages v63x

---

apps/app/src/components/PageComment/CommentEditor.tsx
packages/editor/src/components/index.ts

[#139301](https://redmine.weseek.co.jp/issues/139301) [v7] 新しい CodeMirrorEditor でコメントを追加できる
┗ [#139306](https://redmine.weseek.co.jp/issues/139306) 実装
https://github.com/weseek/growi/assets/34241526/f6d34b8b-061a-4af9-bf05-841bdcb3edc8

feat: Commentable using CodeMirrorEditor

---

apps/app/src/components/PageTags/RenderTagLabels.tsx
apps/app/src/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
apps/app/src/components/Sidebar/Tag.tsx
apps/app/src/components/TagCloudBox.tsx
apps/app/src/components/TagList.module.scss
apps/app/src/components/TagList.tsx
apps/app/src/styles/_tag.scss
apps/app/src/styles/atoms/_tag.scss
apps/app/src/styles/style-app.scss
packages/core/scss/bootstrap/apply.scss
packages/core/scss/bootstrap/override/_helpers.scss
packages/core/scss/bootstrap/override/helpers/_color-bg.scss
packages/core/scss/bootstrap/theming/_variables.scss
packages/core/scss/bootstrap/utilities.scss

- https://redmine.weseek.co.jp/issues/138329
- https://redmine.weseek.co.jp/issues/138328

feat: color bg

---

apps/app/test/cypress/e2e/20-basic-features/20-basic-features--comments.cy.ts

https://github.com/weseek/growi/actions/runs/7706371641/job/21001848259?pr=8420#step:17:1541

fix: Normalization of 20-basic-features--comments.cy.ts

---

apps/app/src/components/PageSideContents/PageAccessoriesControl.tsx
apps/app/src/server/models/obsolete-page.js
apps/app/test/cypress/e2e/20-basic-features/20-basic-features--comments.cy.ts

[#139467](https://redmine.weseek.co.jp/issues/139467) [v7] コメントを削除しようとすると 500 エラーになる
┗ [#139472](https://redmine.weseek.co.jp/issues/139472) 修正
[#139431](https://redmine.weseek.co.jp/issues/139431) [v7] 投稿したコメントが view 画面_右カラムの
「Comments」に表示される件数に反映されない
┗ [#139525](https://redmine.weseek.co.jp/issues/139525) 修正

fix: Error when deleting comments

---

apps/app/src/components/PageDeleteModal.tsx
packages/core/src/interfaces/page.ts

https://redmine.weseek.co.jp/issues/138209

fix: Page being able to delete completely when not allowed

---

apps/app/src/components/SavePageControls.tsx
apps/app/src/components/SavePageControls/GrantSelector/GrantSelector.tsx

- https://redmine.weseek.co.jp/issues/139873

fix: Dropdown container

---

apps/app/test/integration/service/v5.non-public-page.test.ts

ページツリーにある全てのページとグループ権限を複製する際に、正常に複製と normalize が行われているかのテストを追加
https://redmine.weseek.co.jp/issues/140252

feat: Multi group grant duplication (add test for when onlyDuplicateUserRelatedResources is false)

---

apps/app/src/client/services/create-page/use-create-page-and-transit.tsx
apps/app/src/client/services/page-operation.ts
apps/app/src/components/CreateTemplateModal.tsx
apps/app/src/components/Navbar/PageEditorModeManager.tsx
apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx
apps/app/src/server/routes/apiv3/page/check-page-existence.ts
apps/app/src/server/routes/apiv3/page/index.js
apps/app/src/server/routes/index.js
apps/app/src/server/routes/page.js

- https://redmine.weseek.co.jp/issues/140634
- https://redmine.weseek.co.jp/issues/140635

fix: Check page existence

---

packages/ui/src/components/Attachment.tsx

task: https://redmine.weseek.co.jp/issues/140575

imprv: Update page accessories modal design

---

apps/app/src/components/Common/ClosableTextInput.tsx
apps/app/src/components/PageEditor/PageEditor.tsx
apps/app/src/components/PageHeader/PageHeader.module.scss
apps/app/src/components/PageHeader/PageHeader.tsx
apps/app/src/components/PageHeader/PagePathHeader.module.scss
apps/app/src/components/PageHeader/PagePathHeader.tsx
apps/app/src/components/PageHeader/PageTitleHeader.module.scss
apps/app/src/components/PageHeader/PageTitleHeader.tsx
apps/app/src/models/linked-page-path.js

- https://redmine.weseek.co.jp/issues/140133
-

fix: PageHeader behavior and position

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/client/services/page-operation.ts
apps/app/src/components/SavePageControls.tsx
apps/app/src/server/models/page.ts
apps/app/src/server/routes/apiv3/page/index.js
apps/app/src/server/routes/apiv3/page/unpublish-page.ts
apps/app/src/server/service/page/index.ts

[#136286](https://redmine.weseek.co.jp/issues/136286) [WIP page] ページをWIPページとして保存できる
┗[#140129](https://redmine.weseek.co.jp/issues/140129) 編集画面の WIP 保存ボタンから保存すると WIP ページとして保存できる
https://github.com/weseek/growi/assets/34241526/d79d18b5-98f3-4a4c-b23c-cc1e8cc1d9d5

feat: Turn existing pages into wip pages

---

apps/app/src/components/Sidebar/PageTreeItem/PageTreeItem.tsx
apps/app/src/components/TreeItem/NewPageInput/use-new-page-input.tsx

https://redmine.weseek.co.jp/issues/140922

imprv: Use createPage in useNewPageInput

---

apps/app/src/components/Common/PagePathNav/PagePathNav.tsx
apps/app/src/components/Page/PageView.tsx
apps/app/src/components/PageHeader/PageTitleHeader.tsx

[#136985](https://redmine.weseek.co.jp/issues/136985) [WIP page] WIP バッジを表示できる
┗ [#140680](https://redmine.weseek.co.jp/issues/140680) 実装 (タイトル)
View
https://xd.adobe.com/view/26f3cef5-06c1-4ed2-9871-b86d5d00adce-73a0/screen/fc4bb8e1-4e44-4123-a2ef-c982859df6fb
Editor
https://xd.adobe.com/view/26f3cef5-06c1-4ed2-9871-b86d5d00adce-73a0/screen/fcd4d51c-090b-4c02-94d3-4cc26bab1464
https://github.com/weseek/growi/assets/34241526/dcf7c0fa-31a6-476e-9eed-6a453fe36d91

feat: Wip badge (page title)

---

apps/app/src/components/Sidebar/PageCreateButton/PageCreateButton.tsx
apps/app/src/components/Sidebar/Sidebar.module.scss
apps/app/src/components/Sidebar/SidebarNav/PrimaryItems.tsx

ストーリー: https://redmine.weseek.co.jp/issues/140020
タスク: https://redmine.weseek.co.jp/issues/140992
- ページツリーの背景色の透明度を修正
- Create New Pageボタンの上部マージンを修正
- ページツリーアイコンを変更
ふみやさんの動作、デザイン確認済みです

feat: 140020 140992 sidebar style

---

apps/app/src/client/services/page-operation.ts
apps/app/src/client/services/side-effects/drawio-modal-launcher-for-view.ts
apps/app/src/client/services/side-effects/handsontable-modal-launcher-for-view.ts
apps/app/src/client/util/bookmark-utils.ts
apps/app/src/components/ContentLinkButtons.tsx
apps/app/src/components/Page/PageView.tsx
apps/app/src/components/PageAccessoriesModal/PageAttachment.tsx
apps/app/src/components/PageContentFooter.tsx
apps/app/src/components/PageControls/PageControls.tsx
apps/app/src/components/PageEditor/PageEditor.tsx
apps/app/src/components/PageEditor/page-path-rename-utils.ts
apps/app/src/components/PagePresentationModal.tsx
apps/app/src/components/PageSideContents/PageSideContents.tsx
apps/app/src/components/PageStatusAlert.tsx
apps/app/src/components/PageTimeline.tsx
apps/app/src/components/SearchPage/SearchResultContent.tsx
apps/app/src/components/ShareLinkPageView.tsx
apps/app/src/components/Sidebar/Custom/CustomSidebarSubstance.tsx
apps/app/src/pages/[[...path]].page.tsx
apps/app/src/server/models/page.ts
apps/app/src/stores/page.tsx
packages/core/src/interfaces/page.ts

- https://redmine.weseek.co.jp/issues/141205

fix: Mutation for current page

---

apps/app/src/components/PageEditor/PageEditor.tsx
apps/app/src/stores/page.tsx

- Produced by https://github.com/weseek/growi/pull/8517/files#diff-4c1708c4f959974166c15435c6b35950ba01bbf35e7e4b8e99efeb125a8000a7R60-R80
- https://redmine.weseek.co.jp/issues/141410
- https://redmine.weseek.co.jp/issues/141412

fix: Mutation for current page 2

---

apps/app/package.json
apps/app/src/services/renderer/remark-plugins/xsv-to-table.ts
packages/editor/package.json
yarn.lock

- https://redmine.weseek.co.jp/issues/141585
- https://redmine.weseek.co.jp/issues/141586

support: Downgrade string-width

---

apps/app/src/components/PageEditor/PageEditor.tsx
apps/app/src/components/PageEditor/Preview.tsx
packages/ui/src/utils/index.ts
packages/ui/src/utils/use-rect.ts

- https://redmine.weseek.co.jp/issues/141622

imprv: pastEnd for Preview

---

apps/app/src/components/PageEditor/PageEditor.tsx
packages/editor/src/components/CodeMirrorEditorMain.tsx
packages/editor/src/stores/use-collaborative-editor-mode.ts

story: https://redmine.weseek.co.jp/issues/140921
task: https://redmine.weseek.co.jp/issues/141818

fix: Unable to displaying content on the editor when opened on the same page, browser, and user, 

---

bin/data-migrations/README.md
bin/data-migrations/src/migrations/v70x/bootstrap5.js
bin/data-migrations/src/migrations/v70x/index.js

[#141784](https://redmine.weseek.co.jp/issues/141784) [v7] bs4 から bs5 へのマイグレーションスクリプトの実装
┗ [#141793](https://redmine.weseek.co.jp/issues/141793) 実装

feat: Migration script for Bootstrap5

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json

[#141875](https://redmine.weseek.co.jp/issues/141875) [v7][design] WIP の「執筆途中」関連のテキスト修正
┗ [#141928](https://redmine.weseek.co.jp/issues/141928) 修正

imprv: WIP Page wording

---

apps/app/src/components/Common/PagePathHierarchicalLink/PagePathHierarchicalLink.module.scss
apps/app/src/components/Common/PagePathHierarchicalLink/PagePathHierarchicalLink.tsx
apps/app/src/components/Common/PagePathNav/PagePathNav.tsx

Home アイコンのサイズをパスの大きさに合わせる
- https://redmine.weseek.co.jp/issues/141434
- https://redmine.weseek.co.jp/issues/141835

imprv: Change home material icon size in path

---

apps/app/src/components/PageSideContents/PageSideContents.tsx
apps/app/src/components/TableOfContents.tsx

task: https://redmine.weseek.co.jp/issues/141066

imprv: Re-calculate TOC height when Tags Element height updated

---

apps/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx
apps/app/src/components/Admin/UserGroup/UserGroupPage.tsx
apps/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
apps/app/src/features/external-user-group/client/components/ExternalUserGroup/ExternalUserGroupManagement.tsx
apps/app/src/features/external-user-group/server/routes/apiv3/external-user-group.ts
apps/app/src/server/routes/apiv3/user-group.js

https://redmine.weseek.co.jp/issues/141312

fix: Show both UserGroups and ExternalUserGroups for group delete modal transfer select

---

apps/app/src/styles/molecules/_list-group-item.scss

- https://redmine.weseek.co.jp/issues/142092

fix: Text color for .list-group-item.active

---

apps/app/src/components/Admin/AuditLog/AuditLogSettings.tsx
apps/app/src/components/Admin/Security/SecuritySetting.jsx
apps/app/src/components/PageRenameModal.tsx
apps/app/src/styles/style-app.scss
packages/core/scss/_rotate.scss

- https://redmine.weseek.co.jp/issues/141620

imprv: 133910 141620 replace fa rotate

---

apps/app/src/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
apps/app/src/components/Admin/SlackIntegration/OfficialBotSettings.jsx
apps/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx

- https://redmine.weseek.co.jp/issues/142520
Icon size is fixed to be closer to the original

imprv: replace icon external link

---

apps/app/src/components/Admin/UserGroup/UserGroupDeleteModal.tsx

- https://redmine.weseek.co.jp/issues/142586

imprv: remove user group modal select icon option

---

apps/app/src/pages/_private-legacy-pages.page.tsx
apps/app/src/pages/_search.page.tsx
apps/app/src/pages/me/[[...path]].page.tsx
apps/app/src/pages/tags.page.tsx
apps/app/src/pages/trash.page.tsx

- https://redmine.weseek.co.jp/issues/142935

imprv: Supress re-rendering

---

apps/app/src/components/Admin/AuditLog/AuditLogDisableMode.tsx
apps/app/src/components/Common/PageViewLayout.module.scss
apps/app/src/components/Common/PageViewLayout.tsx
apps/app/src/components/Layout/AdminLayout.tsx
apps/app/src/components/Navbar/GroundGlassBar.module.scss
apps/app/src/components/Navbar/GroundGlassBar.tsx
apps/app/src/components/Navbar/GrowiContextualSubNavigation.module.scss
apps/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
apps/app/src/components/Navbar/GrowiNavbarBottom.module.scss
apps/app/src/components/Navbar/GrowiNavbarBottom.tsx
apps/app/src/pages/forgot-password-errors.page.tsx
apps/app/src/pages/forgot-password.page.tsx
apps/app/src/pages/maintenance.page.tsx
apps/app/src/pages/me/[[...path]].page.tsx
apps/app/src/pages/reset-password.page.tsx
apps/app/src/pages/share/[[...path]].page.tsx
apps/app/src/pages/tags.page.tsx
apps/app/src/pages/trash.page.tsx
apps/app/src/styles/_layout.scss

https://redmine.weseek.co.jp/issues/142915

imprv: Special page layout

---

apps/app/next-env.d.ts
apps/app/src/components/Admin/UserGroup/UserGroupTable.tsx
apps/app/src/components/PageEditor/EditorNavbarBottom.module.scss
apps/app/src/components/SavePageControls/GrantSelector/GrantSelector.tsx

- グループのみ公開モーダルのスタイルの修正
- https://redmine.weseek.co.jp/issues/139716
- https://redmine.weseek.co.jp/issues/141685
- https://xd.adobe.com/view/26f3cef5-06c1-4ed2-9871-b86d5d00adce-73a0/screen/075dc64e-4d7b-4a06-bf80-57762e438cb1/

imprv: Styling publish specific group modal

---

apps/app/src/components/PageControls/PageControls.tsx

story: https://redmine.weseek.co.jp/issues/141566
task: https://redmine.weseek.co.jp/issues/143038
期待する動作は story の通りです。

feat: Show search icon and footprints on page control when guest user seeing pages

---

apps/app/src/components/DataTransferForm.tsx
apps/app/src/components/InstallerForm.tsx
apps/app/src/components/Layout/NoLoginLayout.module.scss
apps/app/src/pages/installer.page.tsx

https://redmine.weseek.co.jp/issues/142720
- インストーラー画面・移行画面の実装
- スタイル調整がメインのためXDはなし

support: New Installer design 

---

apps/app/src/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
apps/app/src/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
apps/app/src/components/Admin/SlackIntegration/OfficialBotSettings.jsx
apps/app/src/components/Admin/SlackIntegration/WithProxyAccordions.jsx
apps/app/src/components/Me/UISettings.tsx
apps/app/src/pages/installer.page.tsx
apps/app/src/styles/_fonts.scss
packages/editor/src/components/CodeMirrorEditor/Toolbar/DiagramButton.tsx
packages/editor/src/components/CodeMirrorEditor/Toolbar/TextFormatTools.tsx

- https://redmine.weseek.co.jp/issues/142875

imprv: 137284 142875 original icon font size frexible

---

apps/app/src/components/Admin/App/AppSetting.jsx
apps/app/src/components/Sidebar/AppTitle/AppTitle.module.scss
apps/app/src/components/Sidebar/AppTitle/AppTitle.tsx

task: https://redmine.weseek.co.jp/issues/143042
https://xd.adobe.com/view/26f3cef5-06c1-4ed2-9871-b86d5d00adce-73a0/screen/02f976ba-5719-471f-8d1c-1a823784a0c2/
text は左揃え（confidential は `Special wikiSpecial wikiSpecial wikiSpecial wiki`）

feat: Update App Title presentation to show confidential

---

apps/app/src/server/service/passport.ts

- https://redmine.weseek.co.jp/issues/143600

imprv: Disable RequestedAuthnContext in SAML authentication

---

apps/app/src/server/service/passport.ts

- https://redmine.weseek.co.jp/issues/143601

imprv: Disable RequestedAuthnContext in SAML authentication (v7.0.x)

---

apps/app/package.json
apps/app/src/components/PageHistory/RevisionDiff.module.scss
apps/app/src/components/PageHistory/RevisionDiff.tsx
apps/app/src/components/RevisionComparer/RevisionComparer.module.scss
apps/app/src/components/RevisionComparer/RevisionComparer.tsx
yarn.lock

https://redmine.weseek.co.jp/issues/143609

imprv: Support color scheme in Page History (diff2html)

---

apps/app/src/components/PageHistory/PageRevisionTable.tsx
apps/app/src/stores/modal.tsx

- https://redmine.weseek.co.jp/issues/143612

fix: Supress PageAccessoriesModal rerendering for keeping radio button selections of PageHistory

---

apps/app/src/components/LoginForm/LoginForm.module.scss

- https://redmine.weseek.co.jp/issues/143807

fix: Login form style is broken

---

.devcontainer/docker-compose.yml
.github/workflows/ci-app-prod.yml
.github/workflows/release-rc.yml
.github/workflows/release-slackbot-proxy.yml
.github/workflows/release.yml
.github/workflows/reusable-app-build-image.yml
apps/app/docker/codebuild/buildspec.yml
apps/app/package.json
apps/app/src/server/service/passport.ts
apps/slackbot-proxy/package.json
package.json
packages/core/package.json
packages/hackmd/package.json
packages/presentation/package.json
packages/preset-templates/package.json
packages/preset-themes/package.json
packages/remark-attachment-refs/package.json
packages/remark-drawio/package.json
packages/remark-growi-directive/package.json
packages/remark-lsx/package.json
packages/slack/package.json
packages/ui/package.json
yarn.lock

* imprv: Disable RequestedAuthnContext in SAML authentication (v6.3.x) (#8634) @yuki-takei

Release v6.3.3

---

CHANGELOG.md
apps/app/package.json
package.json
packages/core/package.json
packages/hackmd/package.json
packages/presentation/package.json
packages/preset-templates/package.json
packages/preset-themes/package.json
packages/remark-attachment-refs/package.json
packages/remark-drawio/package.json
packages/remark-growi-directive/package.json
packages/remark-lsx/package.json
packages/slack/package.json
packages/ui/package.json
yarn.lock

Prepare v6.3.4

---

packages/core/scss/bootstrap/_variables.scss

https://redmine.weseek.co.jp/issues/143624

imprv: Enable box-shadow

---

apps/app/src/components/FontFamily/use-growi-custom-icons.tsx
apps/app/src/components/FontFamily/use-lato.tsx
apps/app/src/components/FontFamily/use-material-symbols-outlined.tsx
apps/app/src/components/FontFamily/use-source-han-code-jp.tsx

ref: https://nextjs.org/docs/pages/api-reference/components/font#display

imprv: Set font-display to icon fonts

---

apps/app/src/components/PageEditor/EditorNavbar/EditorNavbar.tsx
apps/app/src/components/PageHeader/PageHeader.tsx
apps/app/src/components/PageHeader/PagePathHeader.tsx
apps/app/src/components/PageHeader/PageTitleHeader.module.scss
apps/app/src/components/PageHeader/PageTitleHeader.tsx

- https://redmine.weseek.co.jp/issues/143965
- https://redmine.weseek.co.jp/issues/143966

imprv: Add border to the page title header when editing

---

apps/app/src/client/util/toastr.ts
apps/app/src/components/Layout/RawLayout.module.scss
apps/app/src/components/Layout/RawLayout.tsx

- https://redmine.weseek.co.jp/issues/130065

fix: react-toastify colors

---

apps/app/src/features/search/client/components/SearchModal.tsx
apps/app/src/features/search/client/components/SearchResultMenuItem.tsx

https://redmine.weseek.co.jp/issues/143131
┗ https://redmine.weseek.co.jp/issues/143144

imprv: Border in search modal

---

apps/app/src/client/util/apiv3-client.ts
apps/app/src/features/external-user-group/server/models/external-user-group-relation.ts
apps/app/src/server/models/page.ts
apps/app/src/server/models/user-group-relation.ts
apps/app/src/server/routes/apiv3/page-listing.ts
apps/app/src/stores/page-listing.tsx

https://redmine.weseek.co.jp/issues/143628

fix: Page content preview not shown in duplicate alert page

---

.github/workflows/reusable-app-prod.yml
.github/workflows/reusable-app-reg-suit.yml

support: Upgrade actions from v3 to v4 (2)

---

.github/workflows/ci-app-prod.yml
.github/workflows/reusable-app-prod.yml
.github/workflows/reusable-app-reg-suit.yml

task: https://redmine.weseek.co.jp/issues/144152

fix: Failed upload cypress test result screenshots

---

apps/app/src/components/PageEditor/PageEditor.tsx
apps/app/src/components/SavePageControls.tsx
apps/app/src/interfaces/apiv3/page.ts
apps/app/src/interfaces/page.ts
apps/app/src/server/models/page.ts
apps/app/src/server/routes/apiv3/page/update-page.ts
apps/app/src/server/service/page/index.ts

[#144090](https://redmine.weseek.co.jp/issues/144090) [v7] 「WIP ページとして保存」ボタンをクリックした時にページ本文も保存できるようにする
┗ [#144181](https://redmine.weseek.co.jp/issues/144181) 改善
[#144122](https://redmine.weseek.co.jp/issues/144122) [v7] Ctrl + S を押下した時に WIP 状態を維持できるようにする 
┗ [#144226](https://redmine.weseek.co.jp/issues/144226) 改善

imprv: WIP Page behavior

---

apps/app/src/server/service/page-grant.ts
apps/app/test/integration/service/page-grant.test.ts

task: https://redmine.weseek.co.jp/issues/143103

test for getPageGroupGrantData

---

apps/app/public/static/locales/en_US/commons.json
apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/ja_JP/commons.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/commons.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/components/AuthorInfo/AuthorInfo.tsx
apps/app/src/components/Common/CopyDropdown/CopyDropdown.jsx
apps/app/src/components/ContentLinkButtons.tsx
apps/app/src/components/PageHistory/Revision.tsx
apps/app/src/components/PageSideContents/PageSideContents.tsx
apps/app/src/components/Sidebar/InAppNotification/InAppNotificationSubstance.tsx
apps/app/src/components/UsersHomepageFooter.tsx

https://redmine.weseek.co.jp/issues/140552
https://redmine.weseek.co.jp/issues/140553
https://redmine.weseek.co.jp/issues/140557
https://redmine.weseek.co.jp/issues/140558
https://redmine.weseek.co.jp/issues/140559
https://redmine.weseek.co.jp/issues/140560
https://redmine.weseek.co.jp/issues/140561
https://redmine.weseek.co.jp/issues/140565
- `apps/app`配下で必要な t 化 及び日本語でのローカライズ
- 中国語の別の場所で使われているものは反映した

support: Localize in app

---

apps/app/src/components/Comments.tsx
apps/app/src/components/Page/DisplaySwitcher.tsx
apps/app/src/components/PageComment.tsx
apps/app/src/components/PageComment/CommentEditor.tsx
apps/app/src/components/SearchPage/SearchResultContent.tsx
apps/app/src/server/routes/comment.js
apps/app/src/stores/comment.tsx
apps/app/src/stores/ui.tsx
packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
packages/editor/src/components/CodeMirrorEditorComment.tsx
packages/editor/src/components/CodeMirrorEditorMain.tsx
packages/editor/src/consts/global-code-mirror-editor-key.ts

- https://redmine.weseek.co.jp/issues/144070

imprv: Comment editor performance

---

.github/workflows/release.yml
apps/app/docker/codebuild/buildspec.yml
apps/app/package.json
apps/slackbot-proxy/package.json
package.json
packages/core/package.json
packages/hackmd/package.json
packages/presentation/package.json
packages/preset-templates/package.json
packages/preset-themes/package.json
packages/remark-attachment-refs/package.json
packages/remark-drawio/package.json
packages/remark-growi-directive/package.json
packages/remark-lsx/package.json
packages/slack/package.json
packages/ui/package.json
yarn.lock

* fix: Add filePath to the schema of attachement for backward compatibility for v3.3 or earlier (v6.3.x) (#8680) @yuki-takei

Release v6.3.4

---

apps/app/src/components/Comments.tsx
apps/app/src/components/PageComment.tsx
apps/app/src/components/PageComment/Comment.tsx
apps/app/src/components/PageComment/CommentEditor.tsx

- https://redmine.weseek.co.jp/issues/144845

fix: Close the comment editor after the post

---

apps/app/src/components/PageComment/CommentEditor.module.scss
packages/editor/src/components/CodeMirrorEditor/CodeMirrorEditor.tsx
packages/editor/src/components/CodeMirrorEditor/Toolbar/Toolbar.tsx
packages/editor/src/components/CodeMirrorEditorComment.tsx

- border-radius
- scrollPastEnd for comment editor

fix: Editor styles

---

apps/app/src/components/ReactMarkdownComponents/CodeBlock.module.scss
apps/app/src/components/ReactMarkdownComponents/CodeBlock.tsx

- https://redmine.weseek.co.jp/issues/144393

fix: Word break does not work with long code block

---

apps/app/src/components/Layout/BasicLayout.tsx
apps/app/src/components/ReactMarkdownComponents/CodeBlock.module.scss
apps/app/src/components/ReactMarkdownComponents/CodeBlock.tsx

- https://redmine.weseek.co.jp/issues/144549
- #8750

fix: Codeblock overflow

---

apps/app/test/cypress/e2e/50-sidebar/50-sidebar--access-to-side-bar.cy.ts

https://redmine.weseek.co.jp/issues/144995

fix: Cypress test (50-sidebar--access-to-side-bar.cy.ts)

---

apps/app/src/server/service/mail.ts
yarn.lock

https://redmine.weseek.co.jp/issues/144652
- ejsのtypeに関するts errorを解決しました。
- promisify関数のジェネリクスを指定することで、promisifyする前と後で引数の数が変わってしまう問題を解決しました。
https://wsgrowi.slack.com/archives/C05LB9T4KR9/p1713266440886999

fix: ts error about type of ejs

---

apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/components/PageControls/PageControls.tsx

Task
https://redmine.weseek.co.jp/issues/140549
┗https://redmine.weseek.co.jp/issues/140564

support: Localize in app tags language en change ja ch revision

---

apps/app/src/server/service/i18next.ts

https://redmine.weseek.co.jp/issues/145643

fix: Dynamic import the locale file

---

apps/app/src/client/services/side-effects/yjs.ts
apps/app/src/components/Navbar/PageEditorModeManager.tsx
apps/app/src/components/Page/DisplaySwitcher.tsx
apps/app/src/interfaces/websocket.ts
apps/app/src/interfaces/yjs.ts
apps/app/src/pages/[[...path]].page.tsx
apps/app/src/server/routes/apiv3/page/get-yjs-data.ts
apps/app/src/server/routes/apiv3/page/index.ts
apps/app/src/server/service/page/index.ts
apps/app/src/server/service/page/page-service.ts
apps/app/src/server/service/socket-io.js
apps/app/src/stores/yjs.ts

[#132775](https://redmine.weseek.co.jp/issues/132775) [v7][New Editor][collab] Editor で編集中またはドラフトが存在することを subnav から確認できる
┗ [#145652](https://redmine.weseek.co.jp/issues/145652) Editor を開いているユーザーがおらず、revision.Body と yjs ドラフトに差分がある時に PageEditorModeManager 右上の circle の色を bg-muted にする
https://github.com/weseek/growi/assets/34241526/2d530b2c-ac9e-439b-bbc7-e570b4dcae9b

feat: Show the indicator that there is a difference between RevisionBody and Yjs draft

---

apps/app/src/server/models/activity.ts
apps/app/src/server/models/in-app-notification.ts
apps/app/src/server/models/page.ts
apps/app/src/server/models/user.js

- https://redmine.weseek.co.jp/issues/145980
- https://redmine.weseek.co.jp/issues/145981
- https://redmine.weseek.co.jp/issues/145982
- https://redmine.weseek.co.jp/issues/145967

imprv: Add indexes for performance

---

apps/app/src/server/service/config-loader.ts
apps/app/src/server/service/file-uploader/aws.ts

Follows https://github.com/weseek/growi/pull/8778

support: Modify env var for S3 Object-ACL

---

apps/app/src/components/Bookmarks/BookmarkItem.tsx
apps/app/src/server/service/page/index.ts
apps/app/test/integration/service/page.test.js
apps/app/test/integration/service/v5.public-page.test.ts

- https://redmine.weseek.co.jp/issues/146310

fix: BookmarkItem occures an error when the related page has been deleted

---

apps/app/src/components/Sidebar/PageTree/PageTreeSubstance.tsx

[#145796](https://redmine.weseek.co.jp/issues/145796): [v7] サイドバー「ページツリー」の三点リーダー内ドロップダウンのトグル押下後の挙動の修正
┗ [#145916](https://redmine.weseek.co.jp/issues/145916): 実装

imprv: Behavior of dropdown toggle for WIP in 'Page Tree' sidebar

---

apps/app/src/components/Bookmarks/BookmarkFolderMenu.tsx
apps/app/src/components/Bookmarks/BookmarkFolderTree.tsx
apps/app/src/interfaces/bookmark-info.ts
apps/app/src/stores/bookmark.ts

- https://redmine.weseek.co.jp/issues/146627

fix: BookmarkItem occures an error when the related page has been deleted 2

---

apps/app/src/components/CompleteUserRegistrationForm.tsx
apps/app/src/pages/user-activation.page.tsx
apps/app/src/server/routes/user-activation.ts

[#145786](https://redmine.weseek.co.jp/issues/145786): ユーザー登録時のメール認証」を有効時に「Activation」画面で「作成」ボタンを押下しても反応しない件の修正
┗ [#147134](https://redmine.weseek.co.jp/issues/147134) 実装

fix: [v6] An error occurred during user activation via email

---

apps/app/src/components/Admin/App/AppSetting.jsx

[#143954](https://redmine.weseek.co.jp/issues/143954) [v7][bug]特定の環境における admin/app でアプリ名やコンフィデンシャルフォームの日本語入力の挙動を修正されている
┗ [#147929](https://redmine.weseek.co.jp/issues/147929) 修正

fix: Behaviour of input during Japanese input

---

apps/app/src/components/PageSelectModal/PageSelectModal.tsx
apps/app/src/components/PageSelectModal/TreeItemForModal.module.scss

- https://redmine.weseek.co.jp/issues/145787

imprv: PageSelectModal list item active color

---

apps/app/src/components/Common/SubmittableInput/use-submittable.ts

- https://redmine.weseek.co.jp/issues/148193

fix: Suppress continuous calls to submit by blur event

---

apps/app/src/components/Script/DrawioViewerScript/DrawioViewerScript.tsx
apps/app/src/components/Script/DrawioViewerScript/use-viewer-min-js-url.spec.ts
apps/app/src/components/Script/DrawioViewerScript/use-viewer-min-js-url.ts
apps/app/src/pages/[[...path]].page.tsx
apps/app/src/pages/_private-legacy-pages.page.tsx
apps/app/src/pages/_search.page.tsx
apps/app/src/pages/share/[[...path]].page.tsx

Refactor DrawioViewerScript not to use SWR

imprv: DrawioViewerScript should respect the base path in DRAWIO_URI 2

---

apps/app/src/components/LoginForm/LoginForm.tsx
apps/app/src/interfaces/errors/external-account-login-error.ts
apps/app/src/pages/login/index.page.tsx
apps/app/src/server/routes/login-passport.js

https://redmine.weseek.co.jp/issues/147475
https://github.com/weseek/growi/assets/106868314/e96adfa8-0144-4900-a4d1-05916f3cbd52

fix: Missing HTTP Response in SAML Login With ABLC Callback

---

apps/app/src/client/components/Bookmarks/BookmarkItem.tsx

- https://redmine.weseek.co.jp/issues/149346

imprv: Rename label for bookmark item

---

apps/app/src/server/service/config-loader.ts
apps/app/src/server/service/search-delegator/elasticsearch.ts
apps/app/src/server/service/search.ts

https://redmine.weseek.co.jp/issues/149629

imprv: Add env var for set Elasticsearch reindex bulk size

---

apps/app/src/client/components/Admin/ExportArchiveData/ArchiveFilesTable.tsx
apps/app/src/client/components/Admin/ExportArchiveData/ArchiveFilesTableMenu.tsx
apps/app/src/client/components/Admin/ExportArchiveData/SelectCollectionsModal.tsx
apps/app/src/client/components/Admin/ExportArchiveDataPage.tsx
apps/app/src/client/components/Common/CopyDropdown/CopyDropdown.jsx
apps/app/src/client/components/PageComment/DeleteCommentModal.tsx
apps/app/src/client/components/RevisionComparer/RevisionComparer.tsx

- exclude some collections
- fix ArchiveFilesTableMenu trimmed
- fix card styles

imprv: Archive importing and exporting

---

apps/app/src/client/components/PageCreateModal.tsx
apps/app/src/client/components/PageHeader/PageTitleHeader.tsx

- https://redmine.weseek.co.jp/issues/149557

fix: PageTitleHeader rename input status

---

apps/app/src/server/models/revision.ts
apps/app/src/server/service/normalize-data/convert-revision-page-id-to-string.ts
apps/app/src/server/service/normalize-data/index.ts

[#150649](https://redmine.weseek.co.jp/issues/150649) revision.pageId の値を ObjectId から String に変換するためのマイグレーションスクリプトの実装
┗ [#150650](https://redmine.weseek.co.jp/issues/150650) マイグレーションスクリプトの実装

support: Normalize Revision.pageId (for #8954)

---

apps/app/src/client/components/Navbar/GrowiContextualSubNavigation.tsx
apps/app/src/client/services/page-operation.ts
apps/app/src/interfaces/yjs.ts
apps/app/src/server/service/yjs/yjs.ts

https://redmine.weseek.co.jp/issues/150769

fix: Hide the sync to the latest revision menu item when not editing

---

packages/editor/src/client/services/use-codemirror-editor/utils/fold-drawio.ts

fix: Handle error when folding drawio blocks

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/fr_FR/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/client/components/Navbar/GrowiContextualSubNavigation.tsx

- Show the menu item even when the view mode

fix: Sync the editor text with the latest revision menu (2)

---

apps/app/src/migrations/20211227060705-revision-path-to-page-id-schema-migration--fixed-7549.js

https://redmine.weseek.co.jp/issues/151330

fix: Migration script (20211227060705-revision-path-to-page-id-schema-migration--fixed-7549.js)

---

apps/app/config/next-i18next.config.js
apps/app/src/pages/_app.page.tsx
apps/app/src/pages/_document.page.tsx
apps/app/src/pages/utils/commons.ts
packages/core/src/interfaces/index.ts
packages/core/src/interfaces/locale.ts

task: https://redmine.weseek.co.jp/issues/149981

imprv: lang attribute in Html element

---

packages/editor/src/client/components-internal/CodeMirrorEditor/Toolbar/TextFormatTools.tsx
packages/editor/src/client/components-internal/CodeMirrorEditor/Toolbar/Toolbar.tsx

Task: https://redmine.weseek.co.jp/issues/149933

fix: Use the scrollbar to prevent the toolbar from being hidden

---

.github/workflows/reusable-app-prod.yml
package.json
yarn.lock

https://redmine.weseek.co.jp/issues/152219

fix: Tests fail due to docker image and playwright version mismatch on CI

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/fr_FR/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/client/components/Navbar/GrowiContextualSubNavigation.tsx
apps/app/src/pages/[[...path]].page.tsx
apps/app/src/pages/share/[[...path]].page.tsx
apps/app/src/stores-universal/context.tsx

task: https://redmine.weseek.co.jp/issues/149611

imprv: Add UI and logic for disabled user registration

---

apps/app/src/pages/_app.page.tsx
apps/app/src/pages/_document.page.tsx
apps/app/src/pages/utils/commons.ts
packages/core/src/interfaces/locale.ts

task: https://redmine.weseek.co.jp/issues/152730

imprv: translation modification

---

apps/app/src/interfaces/services/rehype-sanitize.ts
apps/app/src/services/renderer/recommended-whitelist.spec.ts
apps/app/src/services/renderer/recommended-whitelist.ts

https://redmine.weseek.co.jp/issues/151931

fix: Type and linting for updating hast-util-sanitize

---

.changeset/warm-hounds-relate.md
apps/app/src/pages/[[...path]].page.tsx
packages/core/src/interfaces/page.ts

https://redmine.weseek.co.jp/issues/151974

fix: Serializer for accessing to an empty page

---

apps/app/src/server/routes/apiv3/page/update-page.ts

express-validator の isInt は string の数字も通してしまう (c.f https://github.com/express-validator/express-validator/issues/596) ため、/_api/v3/page で grant が string で渡されるとそのまま処理が走り、正常な grant 処理がされない。
そのため、grant が string で渡された時に明示的に弾くように変更。
```
% curl -X PUT http://localhost:3000/_api/v3/page -H "Content-Type: application/json" -d '{"access_token": "JgOHotb0pSegI0UDPL2XhF2KwOegHqZ+ePZsLIbsVZs=", "pageId": "66d0617fdc440a4db31be179", "body": "Hello, World!", "grant": "5", "userRelatedGrantUserGroupIds": [{"item": "66d061c6dc440a4db31be2e6", "type": "UserGroup"}], "revisionId": "66d9824fe7ed2d3391de52f1"}'
{"errors":[{"code":"validation_failed","message":"grant: Invalid value"}]}
% curl -X PUT http://localhost:3000/_api/v3/page -H "Content-Type: application/json" -d '{"access_token": …
```

fix: Return error when grant is string for PUT /_api/v3/page

---

apps/app/src/client/components/Bookmarks/BookmarkFolderItemControl.tsx
apps/app/src/client/components/Bookmarks/BookmarkFolderMenu.tsx
apps/app/src/client/components/Common/Dropdown/PageItemControl.spec.tsx
apps/app/src/client/components/Common/Dropdown/PageItemControl.tsx
apps/app/src/client/components/InAppNotification/InAppNotificationDropdown.tsx

- https://redmine.weseek.co.jp/issues/153662

fix: Supress rendering too many invisible DropdownMenu components

---

.github/workflows/ci-app.yml
apps/app/package.json
apps/app/src/client/components/PageComment.tsx
apps/app/src/server/routes/comment.js
apps/app/turbo.json

fix: Removing comment doesn't work

---

apps/app/playwright/40-admin/access-to-admin-page.spec.ts

https://redmine.weseek.co.jp/issues/153544

supoort: Add Playwright test for data transfer

---

apps/app/src/client/components/PageAccessoriesModal/PageAccessoriesModal.module.scss
apps/app/src/client/components/PageAccessoriesModal/PageAccessoriesModal.tsx

- https://redmine.weseek.co.jp/issues/154148

fix: Make PageAccessoriesModal responsive

---

apps/app/src/client/components/PageControls/RagSearchButton.tsx
apps/app/src/pages/[[...path]].page.tsx
apps/app/src/stores-universal/context.tsx

- [#153750](https://redmine.weseek.co.jp/issues/153750) [RAG][AI chat] ゲストユーザーでは AI chat 機能を使えないようにする
- [#154432](https://redmine.weseek.co.jp/issues/154432) 実装

feat: Make AI chat unavailable to guest users

---

packages/markdown-splitter/test/index.spec.ts
packages/markdown-splitter/vitest.config.ts

https://redmine.weseek.co.jp/issues/154989

imprv: Vitest environment for markdown-splitter

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/fr_FR/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/features/openai/chat/components/AiChatModal/AiChatModal.module.scss
apps/app/src/features/openai/chat/components/AiChatModal/AiChatModal.tsx
apps/app/src/features/openai/chat/components/AiChatModal/MessageCard.module.scss
apps/app/src/features/openai/chat/components/AiChatModal/MessageCard.tsx
apps/app/src/server/routes/apiv3/openai/message.ts

- https://redmine.weseek.co.jp/issues/155088
- https://redmine.weseek.co.jp/issues/155087
- https://redmine.weseek.co.jp/issues/155086

imprv: In-progress behavior for AiChatModal

---

apps/app/src/server/service/config-loader.ts

This is a preparation PR for https://redmine.weseek.co.jp/issues/155281

support: Evaluate whether env vars are secret or not by the `isSecret` property

---

apps/app/src/server/middlewares/certify-ai-service.ts
apps/app/src/server/service/config-loader.ts
apps/app/src/server/service/openai/assistant/assistant.ts
apps/app/src/server/service/openai/client-delegator/openai-client-delegator.ts
apps/app/src/server/service/openai/client.ts
apps/app/src/server/service/openai/embeddings.ts
apps/app/src/server/service/openai/openai.ts

https://redmine.weseek.co.jp/issues/155281

support: Hide env vars for OpenAI

---

apps/app/src/server/service/openai/openai.ts

https://redmine.weseek.co.jp/issues/155308

fix: Error occurs when creating or duplicating an empty page

---

apps/app/src/server/service/config-loader.ts

- [#155197](https://redmine.weseek.co.jp/issues/155197) [RAG][AI chat] プロンプトの改善
- [#154681](https://redmine.weseek.co.jp/issues/154681) 合宿でのテスト用プロンプトをリリース可能な程度にブラッシュアップする
こちらのタスクですが、修正箇所が多くなかったので実装して pr にしました。
thread や run instruction については、調べられませんでした。

feat: brush up assistant instruction

---

packages/editor/package.json
yarn.lock

- https://redmine.weseek.co.jp/issues/155914

fix: Collaborative editing occurs unstable behavior

---

apps/app/src/client/components/ReactMarkdownComponents/Header.tsx
apps/app/src/pages/[[...path]].page.tsx
apps/app/src/stores/yjs.ts

- https://redmine.weseek.co.jp/issues/155919
- https://redmine.weseek.co.jp/issues/155918

fix: Edit button appear for the side of header

---

apps/app/src/stores/page.tsx

- https://redmine.weseek.co.jp/issues/156150
- https://redmine.weseek.co.jp/issues/156152

fix: Couln't show old revision

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/fr_FR/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/features/openai/chat/components/AiChatModal/AiChatModal.tsx
apps/app/src/features/openai/interfaces/message-error.ts
apps/app/src/features/openai/server/routes/message.ts
apps/app/src/features/openai/server/services/getStreamErrorCode.ts

- [#155004](https://redmine.weseek.co.jp/issues/155004) [RAG] OpenAI API 実行時のエラーを GROWI 本体のフロントエンドで確認できる
- [#156111](https://redmine.weseek.co.jp/issues/156111) Monthly Badget 対応 (2) 
https://github.com/user-attachments/assets/8277a133-e3a7-4c96-afb5-997d4b937fee
https://github.com/user-attachments/assets/5526ce25-22fb-4958-90ec-9763fc754a7e

imprv: Error handling for when monthly usage limit is exceeded (2)

---

apps/app/src/server/service/config-loader.ts

- https://redmine.weseek.co.jp/issues/146626

imprv: Update default value for S3_OBJECT_ACL

---

apps/app/docker/README.md
apps/app/src/server/service/search-delegator/aggregate-to-index.ts

- https://redmine.weseek.co.jp/issues/153981
Revert https://github.com/weseek/growi/pull/8985

support: Omit MongoDB 4.x compatible code

---

apps/app/src/features/openai/server/services/thread-deletion-cron.ts
apps/app/src/features/openai/server/services/vector-store-file-deletion-cron.ts

- [#156751](https://redmine.weseek.co.jp/issues/156751) [RAG] cron job を App ごとにランダムな時間に実行できる
-  [#156753](https://redmine.weseek.co.jp/issues/156753) 実装

feat: Execute cron jobs at random times for each app

---

apps/app/src/components/ReactMarkdownComponents/NextLink.tsx

https://redmine.weseek.co.jp/issues/156931

fix: NextLink isCreatablePage always returns false

---

apps/app/src/server/routes/apiv3/app-settings.js
apps/app/src/server/routes/apiv3/page/create-page.ts
apps/app/src/server/routes/apiv3/security-settings/index.js
apps/app/src/server/routes/login-passport.js
apps/app/src/server/service/i18next.ts

- https://redmine.weseek.co.jp/issues/157134
- Keys in `security-settings/index.js`
- Prioritize user lang than system lang

fix(i18n): i18n for server side

---

apps/app/src/features/openai/server/services/thread-deletion-cron.ts
apps/app/src/features/openai/server/services/vector-store-file-deletion-cron.ts

https://github.com/weseek/growi/pull/9341 の考慮漏れ

fix: Add await

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/fr_FR/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/client/components/Sidebar/Custom/CustomSidebar.tsx
apps/app/src/client/components/Sidebar/InAppNotification/PrimaryItemForNotification.tsx
apps/app/src/client/components/Sidebar/SidebarNav/PrimaryItem.tsx
apps/app/src/migrations/20211227060705-revision-path-to-page-id-schema-migration--fixed-7549.js
apps/app/src/stores/ui.tsx

- サイドバーのボタンがツールチップを表示するように変更
- https://redmine.weseek.co.jp/issues/149280
- https://redmine.weseek.co.jp/issues/156770
https://github.com/user-attachments/assets/5779bac4-37ae-47e4-a170-f0d235c4121a
https://github.com/user-attachments/assets/7d8d292b-84a6-4323-9e19-975f690b1dcc

imprv: Sidebar button displays tooltip

---

apps/app/package.json
apps/app/src/services/renderer/remark-plugins/echo-directive.ts
apps/app/src/services/renderer/renderer.tsx
pnpm-lock.yaml

fix: Output TextDirective and LeafDirective HTML

---

apps/app/bin/swagger-jsdoc/definition-apiv3.js
apps/app/src/server/routes/apiv3/admin-home.js

Add swagger document to `GET /_api/v3/admin-home/`

support(jsdoc): Add Swagger doc to /_api/v3/admin-home/

---

apps/app/bin/swagger-jsdoc/definition-apiv3.js

- セキュリティスキーマとして、Cookieを追加
- 各APIについては認証状態を調べて、個別に適用する必要あり

support(jsdoc): Add Security schema

---

apps/app/src/features/openai/server/routes/index.ts
apps/app/src/features/openai/server/routes/message.ts
apps/app/src/features/openai/server/services/cron/index.ts
apps/app/src/features/openai/server/services/cron/thread-deletion-cron.ts
apps/app/src/features/openai/server/services/cron/vector-store-file-deletion-cron.ts
apps/app/src/features/openai/server/services/index.ts
apps/app/src/features/openai/server/services/is-ai-enabled.ts
apps/app/src/server/crowi/index.js
apps/app/src/server/routes/apiv3/index.js
apps/app/src/server/routes/apiv3/page/create-page.ts
apps/app/src/server/routes/apiv3/page/update-page.ts
apps/app/src/server/service/page/index.ts

- features/openai 配下のモジュールを静的 import から動的 import に変える
- これにより AI 機能が無効ならモジュールロードしない

support: Import OpenAI features dynamically

---

apps/app/src/features/openai/server/models/thread-relation.ts
apps/app/src/features/openai/server/services/normalize-data/index.ts
apps/app/src/features/openai/server/services/normalize-data/normalize-thread-relation-expired-at/index.ts
apps/app/src/features/openai/server/services/normalize-data/normalize-thread-relation-expired-at/normalize-thread-relation-expired-at.integ.ts
apps/app/src/features/openai/server/services/normalize-data/normalize-thread-relation-expired-at/normalize-thread-relation-expired-at.ts
apps/app/src/server/service/config-loader.ts
apps/app/src/server/service/normalize-data/index.ts

- https://redmine.weseek.co.jp/issues/157670
- https://redmine.weseek.co.jp/issues/157671

imprv(ai): Shorten thread deletion expiredAt

---

apps/app/public/static/locales/en_US/admin.json
apps/app/public/static/locales/fr_FR/admin.json
apps/app/public/static/locales/ja_JP/admin.json
apps/app/public/static/locales/zh_CN/admin.json
apps/app/src/features/openai/client/components/AiIntegration/AiIntegrationDisableMode.tsx

- [#157642](https://redmine.weseek.co.jp/issues/157642) AI 機能無効時の管理画面 (/admin/ai-integration) の文言改善
- [#157643](https://redmine.weseek.co.jp/issues/157643) 改善

imprv: AI Integration page wording

---

apps/app/src/server/routes/login.js

ref: https://github.com/weseek/growi/pull/8715#discussion_r1853270598

fix: Notification for new user creation

---

apps/app/src/server/routes/apiv3/attachment.js

Add document to attachment.js
- GET /_api/v3/attachment/list
- GET /_api/v3/attachment/limit
- POST /_api/v3/attachment/
- GET `/_api/v3/attachment/:id`

support(jsdoc): Add document to attachment.js

---

apps/app/bin/swagger-jsdoc/definition-apiv3.js
apps/app/src/server/routes/apiv3/bookmark-folder.ts

Add document to bookmark-folder.ts
- POST /_api/v3/bookmark-folder/
- GET /_api/v3/bookmark-folder/list/:userId
- DELETE /_api/v3/bookmark-folder/:id
- PUT /_api/v3/bookmark-folder/
- POST /_api/v3/bookmark-folder/add-boookmark-to-folder
- PUT /_api/v3/bookmark-folder/update-bookmark

support(jsdoc): API v3 documents for bookmark folder

---

apps/app/src/pages/[[...path]].page.tsx
apps/app/src/server/service/config-manager/config-definition.ts
apps/app/src/server/service/installer.ts

- https://redmine.weseek.co.jp/issues/157743
https://github.com/weseek/growi/pull/9473

support: New config manager (2)

---

apps/app/src/features/opentelemetry/server/start.ts
apps/app/src/server/app.ts
apps/app/src/server/crowi/index.js
apps/app/src/server/service/config-manager/config-manager.ts

- https://redmine.weseek.co.jp/issues/157747
- https://redmine.weseek.co.jp/issues/157748

imprv: Start instrumentation at first

---

apps/app/bin/swagger-jsdoc/definition-apiv3.js
apps/app/src/server/routes/apiv3/installer.ts

support(jsdoc): add swagger document to installer.ts

---

apps/app/src/server/routes/apiv3/invited.ts

support(jsdoc): add swagger document to invited.ts

---

apps/app/public/static/locales/en_US/admin.json
apps/app/public/static/locales/fr_FR/admin.json
apps/app/public/static/locales/ja_JP/admin.json
apps/app/public/static/locales/zh_CN/admin.json
apps/app/src/client/components/Admin/Security/OidcSecuritySettingContents.jsx

Admin の OIDC 設定画面のローカライズ不備を修正
https://wsgrowi.slack.com/archives/C4V5ZG4UC/p1735313451084949

fix: Fix i18n of oidc settings

---

apps/app/src/server/routes/apiv3/page/index.ts

Corrected revision_id to revisionId.

Update Swagger documentation for the PUT endpoint to update a page.

---

apps/app/src/features/openai/interfaces/ai-assistant.ts
apps/app/src/features/openai/server/models/ai-assistant.ts
apps/app/src/features/openai/server/models/vector-store.ts
apps/app/src/features/openai/server/routes/ai-assistant.ts
apps/app/src/features/openai/server/routes/index.ts
apps/app/src/features/openai/server/routes/rebuild-vector-store.ts
apps/app/src/features/openai/server/routes/thread.ts
apps/app/src/features/openai/server/services/client-delegator/azure-openai-client-delegator.ts
apps/app/src/features/openai/server/services/client-delegator/interfaces.ts
apps/app/src/features/openai/server/services/client-delegator/openai-client-delegator.ts
apps/app/src/features/openai/server/services/openai.ts
apps/app/src/server/models/page.ts
apps/app/src/server/routes/apiv3/page/create-page.ts
apps/app/src/server/routes/apiv3/page/update-page.ts
apps/app/src/server/service/page/index.ts
packages/core/src/utils/page-path-utils/index.ts

- [#159151](https://redmine.weseek.co.jp/issues/159151) [GROWI AI Next][特化型アシスタント] 新規作成モーダルから作成ボタンをクリックした時アシスタントデータが作成される
- [#160044](https://redmine.weseek.co.jp/issues/160044) 特化型の VectorStore を作成できる

feat: Implement logic for creating specialized VectorStore

---

apps/app/src/features/openai/server/services/openai.ts

- [#159151](https://redmine.weseek.co.jp/issues/159151) [GROWI AI Next][特化型アシスタント] 新規作成モーダルから作成ボタンをクリックした時アシスタントデータが作成される
- [#160099](https://redmine.weseek.co.jp/issues/160099) 実行ユーザーが考慮された VectorStoreFile が作成できる

feat: Condition for owners access scope

---

apps/app/src/server/routes/apiv3/logout.js

support(jsdoc): add swagger document to logout.js

---

apps/app/src/server/routes/apiv3/mongo.js

- GET /_api/v3/mongo/collections

support(jsdoc): add swagger document to mongo.js

---

apps/app/src/server/routes/apiv3/page/index.ts

support(jsdoc): add swagger document to page/index.ts for update page

---

apps/app/src/features/openai/client/components/AiAssistant/AiAssistantManagementModal/AiAssistantManagementEditPages.tsx
apps/app/src/features/openai/client/components/AiAssistant/AiAssistantManagementModal/AiAssistantManagementHome.tsx
apps/app/src/features/openai/client/components/AiAssistant/AiAssistantManagementModal/AiAssistantManagementModal.tsx
apps/app/src/features/openai/client/components/Common/SelectedPageList.tsx

- [#160853](https://redmine.weseek.co.jp/issues/160853) [GROWI AI Next][特化型アシスタント] 確定されたデザインで新規アシスタント作成画面を表示できる
- [#160855](https://redmine.weseek.co.jp/issues/160855) 参照するページ画面の実装

feat: Edit referenced page

---

bin/data-migrations/src/index.js

- [#160696](https://redmine.weseek.co.jp/issues/160696) MongoDB 内に意図しない page や revision のデータが存在する時に、途中で data migration の実行が止まってしまい、処理が継続できない
- [#160721](https://redmine.weseek.co.jp/issues/160721) n+1 問題の解消

imprv: Data migration script performance

---

apps/app/src/pages/share/[[...path]].page.tsx

https://redmine.weseek.co.jp/issues/161023

fix: Serializing page data for share link

---

apps/app/src/features/openai/client/services/ai-assistant.ts
apps/app/src/features/openai/interfaces/ai-assistant.ts
apps/app/src/features/openai/server/routes/ai-assistant.ts
apps/app/src/features/openai/server/routes/ai-assistants.ts
apps/app/src/features/openai/server/routes/delete-ai-assistant.ts
apps/app/src/features/openai/server/routes/index.ts
apps/app/src/features/openai/server/routes/middlewares/upsert-ai-assistant-validator.ts
apps/app/src/features/openai/server/routes/rebuild-vector-store.ts
apps/app/src/features/openai/server/routes/thread.ts
apps/app/src/features/openai/server/routes/update-ai-assistant.ts
apps/app/src/features/openai/server/services/openai.ts
apps/app/src/utils/is-deep-equal.ts
packages/core/src/utils/index.ts
packages/core/src/utils/is-deep-equals.ts
packages/editor/src/client/stores/codemirror-editor.ts

- [#161500](https://redmine.weseek.co.jp/issues/161500) [GROWI AI Next][特化型アシスタント] 作成したアシスタントを更新できる
- [#161504](https://redmine.weseek.co.jp/issues/161504) アシスタントを更新するための API の実装

feat: Implement api to update ai assistant

---

apps/app/src/features/openai/client/components/AiAssistant/AiAssistantManagementModal/AiAssistantManagementEditShare.tsx
apps/app/src/features/openai/client/components/AiAssistant/AiAssistantManagementModal/AiAssistantManagementHome.tsx
apps/app/src/features/openai/client/components/AiAssistant/AiAssistantManagementModal/AiAssistantManagementModal.tsx
apps/app/src/features/openai/client/components/AiAssistant/Sidebar/AiAssistantSubstance.tsx
apps/app/src/features/openai/client/components/AiAssistant/Sidebar/AiAssistantTree.tsx
apps/app/src/features/openai/client/services/ai-assistant.ts
apps/app/src/features/openai/client/stores/ai-assistant.tsx
apps/app/src/features/openai/server/models/ai-assistant.ts
apps/app/src/features/openai/server/services/openai.ts

- [#161500](https://redmine.weseek.co.jp/issues/161500) [GROWI AI Next][特化型アシスタント] 作成したアシスタントを更新できる
- [#161525](https://redmine.weseek.co.jp/issues/161525) アシスタント一覧画面から AiassistantManagementModal を開ける
https://github.com/user-attachments/assets/1785748c-8fd7-4e04-8b65-4f65dcdaf53d

feat: Open update modal from assistant list view

---

apps/app/src/features/openai/server/services/openai.ts
apps/app/src/server/routes/apiv3/page/create-page.ts
apps/app/src/server/routes/apiv3/page/update-page.ts

- [#160335](https://redmine.weseek.co.jp/issues/160335) [GROWI AI Next][特化型アシスタント] ページを更新した時に既存の VectorStoreFile を削除して新規に VectorStoreFile を作成できる
- [#161931](https://redmine.weseek.co.jp/issues/161931) 実装

feat: Rebuild vector store

---

apps/app/src/features/openai/server/services/openai.ts
apps/app/src/server/service/page/index.ts

- [#160337](https://redmine.weseek.co.jp/issues/160337) [GROWI AI Next][特化型アシスタント]  ページを削除した時に VectorStoreFile を削除できる
- [#162017](https://redmine.weseek.co.jp/issues/162017) 実装

feat: Delete associated vector store files when deleting page

---

apps/app/src/features/openai/client/components/AiAssistant/AiAssistantChatSidebar/AiAssistantChatSidebar.tsx
apps/app/src/features/openai/client/components/AiAssistant/Sidebar/AiAssistantTree.tsx
apps/app/src/features/openai/client/stores/thread.tsx
apps/app/src/features/openai/interfaces/ai-assistant.ts
apps/app/src/features/openai/interfaces/thread-relation.ts
apps/app/src/features/openai/interfaces/vector-store.ts
apps/app/src/features/openai/server/models/thread-relation.ts
apps/app/src/features/openai/server/models/vector-store.ts
apps/app/src/features/openai/server/routes/get-threads.ts
apps/app/src/features/openai/server/routes/index.ts
apps/app/src/features/openai/server/routes/thread.ts
apps/app/src/features/openai/server/services/normalize-data/normalize-thread-relation-expired-at/normalize-thread-relation-expired-at.integ.ts
apps/app/src/features/openai/server/services/openai.ts

-  [#162019](https://redmine.weseek.co.jp/issues/162019) アシスタントに紐つくスレッド一覧を返却する API の実装
- [#162036](https://redmine.weseek.co.jp/issues/162036) thread 一覧を表示できる
https://github.com/user-attachments/assets/153f955e-83b9-42cd-b025-81f906bf2f20

feat: API to return thread list

---

apps/app/src/features/openai/client/components/AiAssistant/AiAssistantChatSidebar/AiAssistantChatSidebar.tsx
apps/app/src/features/openai/client/components/AiAssistant/Sidebar/AiAssistantTree.tsx
apps/app/src/features/openai/client/stores/ai-assistant.tsx
apps/app/src/features/openai/client/stores/message.tsx
apps/app/src/features/openai/client/stores/thread.tsx
apps/app/src/features/openai/server/routes/message.ts

- [#162181](https://redmine.weseek.co.jp/issues/162181) 各 thread をクリックした時に thread ごとのチャット画面を表示できる
https://github.com/user-attachments/assets/88e1d1ec-6023-486e-a1c6-05eebb1d7cf3

feat: Show thread messages

---

apps/app/src/features/openai/server/models/ai-assistant.ts
apps/app/src/features/openai/server/services/openai.ts
apps/app/src/features/openai/server/utils/generate-glob-patterns.spec.ts
apps/app/src/features/openai/server/utils/generate-glob-patterns.ts
apps/app/src/server/routes/apiv3/page/create-page.ts
apps/app/src/server/routes/apiv3/page/update-page.ts
apps/app/src/server/service/page/index.ts

- [#160334](https://redmine.weseek.co.jp/issues/160334) [GROWI AI Next][特化型アシスタント] ページを作成した時に VectorStoreFile を作成できる
- [#161961](https://redmine.weseek.co.jp/issues/161961) 実装
- [#160336](https://redmine.weseek.co.jp/issues/160336) [GROWI AI Next][特化型アシスタント] ページを複製した時に VectorStoreFile を作成できる
- [#162016](https://redmine.weseek.co.jp/issues/162016) 実装

feat: Create vector store file on page creation

---

apps/app/src/features/openai/client/components/AiAssistant/AiAssistantChatSidebar/AiAssistantChatSidebar.tsx
apps/app/src/features/openai/client/components/AiAssistant/Sidebar/AiAssistantTree.tsx
apps/app/src/features/openai/client/stores/ai-assistant.tsx
apps/app/src/features/openai/client/stores/thread.tsx
apps/app/src/features/openai/interfaces/thread-relation.ts
apps/app/src/features/openai/server/models/thread-relation.ts
apps/app/src/features/openai/server/routes/thread.ts
apps/app/src/features/openai/server/services/client-delegator/azure-openai-client-delegator.ts
apps/app/src/features/openai/server/services/client-delegator/interfaces.ts
apps/app/src/features/openai/server/services/client-delegator/openai-client-delegator.ts
apps/app/src/features/openai/server/services/openai.ts

- [#162037](https://redmine.weseek.co.jp/issues/162037) thread ごとに thread 名を表示できる
https://github.com/user-attachments/assets/c81fde82-9512-45fc-9cc8-b0fd07415c96

feat: Auto generate thread title

---

apps/app/src/features/openai/client/components/AiAssistant/AiAssistantChatSidebar/AiAssistantChatSidebar.tsx
apps/app/src/features/openai/client/stores/message.tsx
apps/app/src/features/openai/interfaces/message.ts
apps/app/src/features/openai/server/routes/get-messages.ts
apps/app/src/features/openai/server/routes/message.ts
apps/app/src/features/openai/server/routes/thread.ts
apps/app/src/features/openai/server/services/client-delegator/azure-openai-client-delegator.ts
apps/app/src/features/openai/server/services/client-delegator/interfaces.ts
apps/app/src/features/openai/server/services/client-delegator/openai-client-delegator.ts
apps/app/src/features/openai/server/services/openai.ts

- [#162311](https://redmine.weseek.co.jp/issues/162311) [GROWI AI Next][特化型アシスタント] Additional Instruction を入れてチャットができる
- [#162314](https://redmine.weseek.co.jp/issues/162314) 実装

feat: Eable chat with additional instruction

---

apps/app/src/server/routes/apiv3/slack-integration-legacy-settings.js

- GET /_api/v3/slack-integration-legacy-settings/
- PUT /_api/v3/slack-integration-legacy-settings/

support(jsdoc): add swagger document to slack-integration-legacy-settings

---

apps/app/src/features/openai/server/routes/middlewares/upsert-ai-assistant-validator.ts

- [#162616](https://redmine.weseek.co.jp/issues/162616) [GROWI AI Next][特化型アシスタント] feat/growi-ai-next ブランチで出ている CodeQL エラーの修正
- [#162617](https://redmine.weseek.co.jp/issues/162617) 修正
https://github.com/weseek/growi/security/code-scanning/692

fix: CodeQL error

---

apps/app/src/features/openai/client/components/AiAssistant/AiAssistantChatSidebar/AiAssistantChatSidebar.tsx
apps/app/src/features/openai/server/routes/message.ts
apps/app/src/features/openai/server/routes/thread.ts
apps/app/src/features/openai/server/services/openai.ts

- [#162665](https://redmine.weseek.co.jp/issues/162665) [GROWI AI Next][特化型アシスタント] メッセージ作成時にスレッドの削除期限を延長できる 
- [#162669](https://redmine.weseek.co.jp/issues/162669) 実装

feat: Extend thread expiration on message creation

---

apps/app/src/server/service/config-manager/config-definition.ts

https://redmine.weseek.co.jp/issues/162849
[TS Playgroud](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAwg9gOwGYEsDmUC8UDeAoKKAawhAC4oBnYAJxQTQG4CoIEA3ANQEMaA5bgFsIFanQZQAPlACuCACYRUCCPLwBfPHgD02qOwDsAOgCMRgJxQdegKJ9OAfU4BBAEoO+zgLI2HAFQB5BxgAvgAxAEkAcQcI8ICoQGkGQEiGQE6GQHqGQCuGQHWGQAmGQCSGQApXQBEGQDMGQB15QAQjaygAC2BgMEoyXTQUYFqZACMjAGM4QW0AdwhKCAgibTQaOCGUbS6AGzgu7UNTC21uMCatne1KGl6DiBp2U5OzlF6IbX7kdABaZe5FGiNgSgBiABkAVgATI9-gBmPD3ahQe6oNAmLBQADaLBwrA4PH4QhEUAA5JEfr4AKoABR+AWcABFsQAaYikCjY7ZgMioRYQAlgF7yPzgCDYqDqKnIliENhcXgCYT0vGEklk8kOAkAZRsiocoR+AE0HHZHC53GEAvqIviFbKKf4NUSbNThbTyDjGWQZGMAghFiAbGjeGE4DQwihWezOdzIDbCALkaixRjJTiSc4+H4CV4fgrXBFqXb6Y6OdwEMAZIJFgS6HyI4QUaL0RKsdjya5nAB1CJBAnpzMke0MnZkeQ0bhzOAllBlwUVqPVzH0vgwAASCbTGZpnezPYQvVqeeHo8jVfFU5xziJRIcioifkJrh+HbpDp7lHabJoix3Fdt …

fix: Revert environment variable name

---

.changeset/fair-worms-wait.md
apps/app/src/features/growi-plugin/client/components/GrowiPluginsActivator.tsx
packages/core/src/interfaces/growi-facade.ts

https://redmine.weseek.co.jp/issues/162903

feat: Expose React Insance to window via GrowiFacade

---

apps/app/src/server/service/config-manager/config-definition.ts
apps/app/src/server/service/config-manager/config-loader.ts
apps/app/src/server/service/config-manager/config-manager.ts

- [#162941](https://redmine.weseek.co.jp/issues/162941) saml 認証でログインできない
- [#162942](https://redmine.weseek.co.jp/issues/162942) 修正

fix: SAML authentication error

---

apps/app/src/server/routes/attachment/get.ts

imprv: Do not render html attachments

---

apps/app/src/client/components/Admin/App/AppSettingsPageContents.tsx
apps/app/src/client/services/AdminAppContainer.js
apps/app/src/features/page-bulk-export/server/service/check-page-bulk-export-job-in-progress-cron.ts
apps/app/src/pages/[[...path]].page.tsx
apps/app/src/server/routes/apiv3/app-settings.js

https://redmine.weseek.co.jp/issues/163219

disable bulk export when GROWI_CLOUD_URI is set

---

apps/app/src/migrations/19700101000000-foremost-1000-20241123211930-remove-index-for-ns-from-configs.js

https://redmine.weseek.co.jp/issues/163527

fix: Migration script to remove index for 'ns' from config collection

---

apps/app/src/server/routes/apiv3/import.js

GET /_api/v3/import/
GET /_api/v3/import/status
POST /_api/v3/import/
POST /_api/v3/import/upload
DELETE /_api/v3/import/all

support(jsdoc): add swagger document to import.js

---

apps/app/src/server/routes/apiv3/healthcheck.ts

support(jsdoc): Fix/doc v3 healthcheck

---

apps/app/src/server/routes/apiv3/attachment.js
apps/app/src/server/routes/apiv3/customize-setting.js
apps/app/src/server/routes/apiv3/g2g-transfer.ts
apps/app/src/server/routes/index.js

[#163456](https://redmine.weseek.co.jp/issues/163456)
└[#163491 修正](https://redmine.weseek.co.jp/issues/163491)
review task -> https://redmine.weseek.co.jp/issues/163492

fix: The order of multer middleware

---

apps/app/public/static/locales/ja_JP/commons.json
apps/app/src/client/components/Me/AccessTokenScopeList.tsx

[#163553 [Enhanced Access Token] /me の i18n 化](https://redmine.weseek.co.jp/issues/163553)
└[#163560 locale に、デスクリプションを書けるように、 useTranslation を仕込む](https://redmine.weseek.co.jp/issues/163560)
https://redmine.weseek.co.jp/issues/163636

feat: Setup for i18n of accesstoken scopes

---

.changeset/violet-ties-draw.md
packages/pluginkit/src/v4/client/utils/growi-facade/growi-react.spec.ts
packages/pluginkit/src/v4/client/utils/growi-facade/growi-react.ts

https://redmine.weseek.co.jp/issues/163743

fix: growi pluginkit growifacade typo

---

apps/app/src/server/routes/apiv3/statistics.js

- GET /_api/v3/statistics/user

support(jsdoc): Add swagger document to statistics.js

---

apps/app/bin/swagger-jsdoc/definition-apiv3.js
apps/app/src/server/routes/apiv3/user-ui-settings.ts

- PUT /_api/v3/user-ui-settings/

support(jsdoc): Add swagger document to user-ui-settings.ts

---

apps/app/bin/swagger-jsdoc/definition-apiv3.js
apps/app/src/server/routes/apiv3/staffs.js

support(jsdoc): Add swagger document to staffs.js

---

apps/app/bin/swagger-jsdoc/definition-apiv3.js
apps/app/src/server/routes/apiv3/activity.ts

support(jsdoc): Add swagger document to activity.ts

---

apps/app/bin/swagger-jsdoc/definition-apiv3.js
apps/app/src/server/routes/apiv3/page-listing.ts

- GET /_api/v3/page-listing/root
- GET /_api/v3/page-listing/ancestors-children
- GET /_api/v3/page-listing/children
- GET /_api/v3/page-listing/info

support(jsdoc): Add swagger document to page-listing.ts

---

apps/app/bin/swagger-jsdoc/definition-apiv3.js
apps/app/bin/swagger-jsdoc/generate-spec-apiv3.sh
apps/app/src/features/growi-plugin/server/routes/apiv3/admin/index.ts

- GET /_api/v3/plugins/
- POST /_api/v3/plugins/
- PUT /_api/v3/plugins/:id/activate
- PUT /_api/v3/plugins/:id/deactivate
- DELETE `/_api/v3/plugins/:id/remove`

support(jsdoc): Add swagger document to features/growi-plugin/server/routes/apiv3/admin/index.ts

---

apps/app/src/server/routes/apiv3/user-group-relation.js

- GET /_api/v3/user-group-relations

support(jsdoc): Add swagger document to user-group-relation.js

---

apps/app/bin/swagger-jsdoc/generate-spec-apiv3.sh
apps/app/src/server/routes/login.js

- POST /_api/v3/login
- POST /_api/v3/register

support(jsdoc): Add swagger document to login.js

---

apps/app/src/features/external-user-group/server/routes/apiv3/external-user-group-relation.ts

- GET /_api/v3/external-user-group-relations/

support(jsdoc): Add swagger document to external-user-group-relation.ts

---

apps/app/src/server/routes/apiv3/users.js

A critical problem "Type confusion through parameter tampering" was occured by CodeQL

fix: CodeQL problems for Users API

---

apps/app/src/features/openai/server/routes/edit/index.ts

- [#164705](https://redmine.weseek.co.jp/issues/164705) [GROWI AI Next][エディターアシスタント] CodeQL の警告 (Database query built from user-controlled sources) の修正
- [#164706](https://redmine.weseek.co.jp/issues/164706) 修正

fix: CodeQL problems 

---

apps/app/src/features/openai/client/components/AiAssistant/AiAssistantSidebar/AiAssistantSidebar.tsx

- [#164797](https://redmine.weseek.co.jp/issues/164797) [GROWI AI Next][エディターアシスタント] エディターモードでは無い時にも右サイドバーが開き続けてしまう
- [#164798](https://redmine.weseek.co.jp/issues/164798) 修正

fix: Right sidebar remains open outside editor mode

---

apps/app/src/server/service/config-manager/config-loader.spec.ts
apps/app/src/server/service/config-manager/config-loader.ts
apps/app/src/server/service/config-manager/config-manager.spec.ts

- https://redmine.weseek.co.jp/issues/164998
- https://redmine.weseek.co.jp/issues/164997
- https://redmine.weseek.co.jp/issues/164999

fix: ConfigLoader.loadFromDB for JSON parsing error handling

---

apps/app/src/client/components/AuthorInfo/AuthorInfo.module.scss
apps/app/src/client/components/Bookmarks/BookmarkFolderTree.module.scss
apps/app/src/client/components/PageComment.tsx
apps/app/src/client/components/PageComment/Comment.module.scss
apps/app/src/client/components/PageComment/Comment.tsx
apps/app/src/client/components/PageComment/CommentEditor.module.scss
apps/app/src/client/components/PageComment/CommentEditor.tsx
apps/app/src/client/components/PageComment/_comment-inheritance.scss
apps/app/src/client/components/PageEditor/EditorNavbar/EditingUserList.tsx
apps/app/src/client/components/PageHistory/Revision.module.scss
apps/app/src/client/components/Sidebar/RecentChanges/RecentChangesSubstance.tsx
apps/app/src/client/components/UsersHomepageFooter.module.scss
apps/app/src/components/User/UserInfo.module.scss
apps/app/src/components/User/UserInfo.tsx
apps/app/src/styles/style-app.scss
packages/ui/scss/molecules/_page_list.scss
packages/ui/src/components/UserPicture.module.scss
packages/ui/src/components/UserPicture.tsx

https://github.com/weseek/growi/discussions/9756

imprv: User picture tooltip

---

apps/app/src/client/components/PageEditor/EditorNavbar/EditingUserList.tsx
packages/core/src/utils/page-path-utils/index.ts
packages/editor/src/client/stores/use-collaborative-editor-mode.ts
packages/editor/src/interfaces/editing-client.ts
packages/ui/src/components/UserPicture.tsx

How to reproduce? (再現手順)
---------------------------
1. Open editor
1. Hover over the user icon  in the top right corner of the screen
What happens? (症状)
---------------------
- No tooltip is shown
What is the expected result? (期待される動作)
-------------------------------------------
- The tooltip is shown and the user name should be displayed

imprv: User picture tooltip (2)

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/fr_FR/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/features/openai/client/components/AiAssistant/AiAssistantSidebar/AiAssistantChatInitialView.tsx
apps/app/src/features/openai/client/services/knowledge-assistant.tsx
apps/app/src/features/openai/server/routes/message.ts
apps/app/src/features/openai/server/services/assistant/assistant.ts
apps/app/src/features/openai/server/services/openai.ts
apps/app/src/server/service/config-manager/config-definition.ts

- https://redmine.weseek.co.jp/issues/165458
- https://redmine.weseek.co.jp/issues/165457

imprv: AI models and instructions

---

apps/app/src/features/openai/client/components/AiAssistant/AiAssistantSidebar/MessageCard.tsx

- [#163577](https://redmine.weseek.co.jp/issues/163577) [GROWI AI Next][UIUX] 出典リンクを開いたときにチャットが継続できるようになっている
- [#165552](https://redmine.weseek.co.jp/issues/165552) 改善

imprv: Keep right sidebar open when citation link is clicked

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/fr_FR/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/client/components/Navbar/GrowiContextualSubNavigation.tsx

https://redmine.weseek.co.jp/issues/165289

imprv: Disable page bulk export when file upload settings are not configured

---

apps/app/src/client/components/PageHeader/PagePathHeader.tsx

https://redmine.weseek.co.jp/issues/165841

fix: PagePathHeader maxWidth for editor

---

apps/app/src/client/components/Admin/Customize/CustomizeLogoSetting.tsx
apps/app/src/client/components/Me/ProfileImageSettings.tsx
apps/app/src/client/components/Sidebar/SidebarBrandLogo.tsx

https://redmine.weseek.co.jp/issues/165952

fix: Picture size

---

apps/app/src/migrations/20250522105040-delete-old-index-for-vector-store-file-relation.js

- [#166327](https://redmine.weseek.co.jp/issues/166327) [GROWI AI Next] feat/save-attachment-to-vector-store をリリースしたバージョンで正常に GROWI を起動できる
- [#166328](https://redmine.weseek.co.jp/issues/166328) 実装

feat: Add migration script

---

apps/app/src/features/openai/server/services/openai.ts
apps/app/src/server/service/attachment.js

- [#165323](https://redmine.weseek.co.jp/issues/165323) [GROWI AI Next] Attachment データを VectorStore に保存できる
- [#166394](https://redmine.weseek.co.jp/issues/166394) attachmentService.createAttachment のメモリリーク対策 (2)

fix: Memory leak prevention (2)

---

apps/app/src/features/openai/server/routes/delete-thread.ts
apps/app/src/features/openai/server/routes/get-threads.ts

https://redmine.weseek.co.jp/issues/166712

fix: OpenAI threads can be retrieved regardless of assistant's public permissions

---

apps/app/src/server/routes/apiv3/app-settings.js
apps/app/src/server/service/config-manager/config-definition.ts
apps/app/src/server/service/file-uploader/aws/index.ts
apps/app/src/server/service/file-uploader/azure.ts
apps/app/src/server/service/file-uploader/gcs/index.ts

- related to #10010 
- related to #10012

imprv: Type safe configuration for file uploading

---

apps/app/src/client/components/Common/CopyDropdown/CopyDropdown.jsx
apps/app/src/client/components/Common/CopyDropdown/CopyDropdown.module.scss

https://redmine.weseek.co.jp/issues/160673
┗https://redmine.weseek.co.jp/issues/166869

fix: Prevent dropdown menu from hiding behind sidebar

---

apps/app/src/server/routes/apiv3/app-settings.js

https://github.com/weseek/growi/pull/10118 の approve 後にマージする

fix: Cannot change file upload destination to "MongoDB (GridFS)" or "local" for dev/7.2.x

---

apps/app/src/styles/_layout.scss

https://redmine.weseek.co.jp/issues/153645

imprv: Adjust margin-top for .main at md and lg breakpoints

---

apps/app/src/utils/axios-date-conversion.spec.ts
apps/app/src/utils/axios.ts

https://redmine.weseek.co.jp/issues/113876
┗https://redmine.weseek.co.jp/issues/167506

imprv: Circular reference prevention in axios date conversion

---

apps/app/src/client/components/Admin/ExportArchiveDataPage.tsx

https://redmine.weseek.co.jp/issues/159084
┗https://redmine.weseek.co.jp/issues/167837
┗https://redmine.weseek.co.jp/issues/167843

fix: Bug causing export zip file to display twice

---

apps/app/docker/Dockerfile
apps/pdf-converter/docker/Dockerfile
apps/slackbot-proxy/docker/Dockerfile

- [#168173](https://redmine.weseek.co.jp/issues/168173) node.js サポートバージョンの変更
- [#168383](https://redmine.weseek.co.jp/issues/168383) サポートバージョンの変更 (2)

support: Node.JS 22 (2)

---

apps/app/src/server/routes/apiv3/g2g-transfer.ts

https://redmine.weseek.co.jp/issues/162909
https://redmine.weseek.co.jp/issues/168675
修正内容等は上の#168675の方に書いています

fix: Add checking attachment file name and file size for g2g transformation

---

apps/app/src/server/routes/admin.js

https://redmine.weseek.co.jp/issues/169039
詳細はredmine内に書いています

fix: validate invalid key in qiita importer

---

apps/app/public/static/locales/en_US/translation.json
apps/app/public/static/locales/fr_FR/translation.json
apps/app/public/static/locales/ja_JP/translation.json
apps/app/public/static/locales/zh_CN/translation.json
apps/app/src/features/openai/client/components/AiAssistant/AiAssistantManagementModal/AiAssistantManagementKeywordSearch.module.scss
apps/app/src/features/openai/client/components/AiAssistant/AiAssistantManagementModal/AiAssistantManagementKeywordSearch.tsx

- [#163538](https://redmine.weseek.co.jp/issues/163538) [GROWI AI Next] アシスタント作成ウィザードを利用できる
-  [#169248](https://redmine.weseek.co.jp/issues/169248) キーワード入力時に検索用の API にリクエストできる
- [#169601](https://redmine.weseek.co.jp/issues/169601) キーワードの検索結果を表示できる
https://www.figma.com/design/ZiEcjZ8sYt6YvowboA5Um6/GROWI-v7?node-id=2967-30252&t=M09YnNCYUUwnwAAH-0
https://github.com/user-attachments/assets/74fd60c2-4a55-45d1-b6e1-c8677044ddef

feat(ai) Keyword search

---

apps/app/src/features/openai/server/routes/get-recent-threads.ts

https://redmine.weseek.co.jp/issues/169758

support(EnhancedAccessToken): Use new access token parser

---

apps/app/src/services/renderer/recommended-whitelist.ts

https://redmine.weseek.co.jp/issues/169436
https://redmine.weseek.co.jp/issues/169440

fix: remove srcdoc from whitelist

---

apps/app/src/components/PageView/PageView.tsx

Backport from https://github.com/weseek/growi/pull/10181

fix: Auto-scroll to anchor for page view (for dev7.2.x)

---

apps/app/src/server/routes/apiv3/page/index.ts
apps/app/src/server/routes/apiv3/share-links.js
apps/app/src/server/routes/apiv3/users.js

https://redmine.weseek.co.jp/issues/170293

fix: Swagger for growi-sdk-typescript

---

apps/app/src/features/openai/client/components/AiAssistant/AiAssistantManagementModal/AiAssistantManagementHome.tsx
apps/app/src/features/openai/client/components/AiAssistant/AiAssistantManagementModal/AiAssistantManagementKeywordSearch.tsx
apps/app/src/features/openai/client/components/AiAssistant/AiAssistantManagementModal/AiAssistantManagementModal.tsx
apps/app/src/features/openai/client/components/AiAssistant/AiAssistantManagementModal/AiAssistantManagementPageTreeSelection.module.scss
apps/app/src/features/openai/client/components/AiAssistant/AiAssistantManagementModal/AiAssistantManagementPageTreeSelection.tsx
apps/app/src/features/openai/client/components/AiAssistant/Sidebar/AiAssistantList.tsx

- [#163538](https://redmine.weseek.co.jp/issues/163538) [GROWI AI Next] アシスタント作成ウィザードを利用できる
- [#170380](https://redmine.weseek.co.jp/issues/170380) デザイナーチェック後の FB 対応

imprv: Assistant wizard UI

---

apps/app/.eslintrc.js
apps/app/src/features/mermaid/components/MermaidViewer.tsx
apps/app/src/features/mermaid/services/mermaid.ts
apps/app/src/features/plantuml/services/plantuml.ts
apps/app/src/features/search/client/components/SearchForm.tsx
apps/app/src/features/search/client/components/SearchHelp.tsx
apps/app/src/features/search/client/components/SearchMenuItem.tsx
apps/app/src/features/search/client/components/SearchMethodMenuItem.tsx
apps/app/src/features/search/client/components/SearchModal.tsx
apps/app/src/features/search/client/components/SearchResultMenuItem.tsx
apps/app/src/features/search/client/interfaces/downshift.ts
apps/app/src/features/search/client/stores/search.ts
biome.json

external-user-group feature の biome 移行
https://github.com/weseek/growi/pull/10270/commits/620be95118a325a29a598865e9e96b59ec2fb844
差分がフォーマット変更や軽微なロジック変更だったため、未実施。
https://redmine.weseek.co.jp/issues/170908

support: Configure biome for mermaid search plantuml features

---

apps/app/src/client/components/ReactMarkdownComponents/RichAttachment.tsx

- [#170760](https://redmine.weseek.co.jp/issues/170760) ゲストユーザー時に RichAttachment に削除ボタンが表示されている (削除はできない)
- [#170781](https://redmine.weseek.co.jp/issues/170781) 修正

fix: Delete button is displayed on RichAttachment in guest mode

---

README.md
README_JP.md
apps/app/docker/README.md

https://redmine.weseek.co.jp/issues/171371

chore: Update Docker Hub links to growilabs

---

apps/app/src/features/opentelemetry/server/custom-metrics/index.ts
apps/app/src/features/opentelemetry/server/custom-metrics/page-counts-metrics.spec.ts
apps/app/src/features/opentelemetry/server/custom-metrics/page-counts-metrics.ts
apps/app/src/server/service/growi-info/growi-info.integ.ts
apps/app/src/server/service/growi-info/growi-info.ts
packages/core/src/interfaces/growi-app-info.ts

- https://redmine.weseek.co.jp/issues/169222
- apps/app/src/features/opentelemetry/server/custom-metrics/index.ts
- apps/app/src/features/opentelemetry/server/custom-metrics/page-counts-metrics.spec.ts
- apps/app/src/features/opentelemetry/server/custom-metrics/page-counts-metrics.ts
- apps/app/src/server/service/growi-info/growi-info.integ.ts
- apps/app/src/server/service/growi-info/growi-info.ts
- packages/core/src/interfaces/growi-app-info.ts

feat: add page counts metrics

---

apps/app/.eslintrc.js
apps/app/src/features/rate-limiter/config/index.ts
apps/app/src/features/rate-limiter/middleware/consume-points.integ.ts
apps/app/src/features/rate-limiter/middleware/consume-points.ts
apps/app/src/features/rate-limiter/middleware/factory.ts
apps/app/src/features/rate-limiter/middleware/rate-limiter-factory.ts
apps/app/src/features/rate-limiter/utils/config-generator.ts
biome.json

app の rate-limiter feature の biome 移行。
なし
https://redmine.weseek.co.jp/issues/172235

support: Configure biome for rate-limiter feature

---

apps/app/src/client/components/PageEditor/PageEditor.tsx
apps/app/src/client/services/side-effects/drawio-modal-launcher-for-view.ts
apps/app/src/client/services/side-effects/handsontable-modal-launcher-for-view.ts
apps/app/src/server/routes/apiv3/page/update-page.ts
apps/app/src/server/service/page/index.ts

https://redmine.weseek.co.jp/issues/172144

fix: Cannot update v4 format pages
