- README.md
「Deploy to Heroku」利用時に検索でエラーとなるため、手順の追加
Bonsaiのバージョンが初期設定では古い為、管理画面からアップグレードが必要
> 「Deploy to Heroku」利用時に検索でエラーとなるため手順を追加

- lib/models/group.js
- lib/models/index.js
- lib/models/userGroup.js
- lib/routes/admin.js
- lib/routes/index.js
- lib/views/admin/user_groups.html
- lib/views/admin/widget/menu.html
* Prepare group model.(methods are not complete) 「グループモデルの用意(グループ管理ページ向け検索メソッドのみ実装済み)」
* Add group-model method to models index. 「グループモデルを、 `/lib/models/index.js` に追加」
* Add group route to routes index. 「 `/admin/groups` パスでのグループクラスのメソッド呼び出しを、
`/lib/routes/index.js` に追加」
> # Feature/196, 198, 199 Grouping users

- package.json
- resource/css/_wiki.scss
- resource/js/util/PostProcessor/Emoji.js
- yarn.lock
Because,
-   emojify.js is already unmaintained.
-   `emojify.replace()` can't detect emojiname at the beginning of a line.
e.g.
```markdown
:hatched_chick: piyopiyo
```
```markdown
```
> Change emojify.js to emojione

- resource/js/components/PageComments.js
* add "in" class for "Comments for Newer Revision"
> fixed #239: "Comments for Newer Revision" to be opened with default

- lib/models/comment.js
- lib/models/page.js
- lib/routes/comment.js
This PR fixes the bug of comment count not being updated when a comment of a page is deleted, **even when you reload the page**.
This means that there still remains a bug of comment count not being updated automatically after you click "Delete" button in the modal. Since comment counts are rendered using a template (pug?), it is a bit tricky to reflect the change without reloading the page. Hence, I will tackle this issue in another PR.
> fix: Update comment count of a page on comment deletion

- lib/crowi/index.js
This PR enables custom session name when `SESSION_NAME` environment variable is passed.
I happened to run several web applications on the same domain but on different ports.
Since crowi-plus (and crowi) uses session library provided by expressjs, session name is by default `connect.sid`.
The problem is that when the other web apps use the same session name, the session is overwritten by each other. This is because sessions are namespaced only by domain (**NOT** including ports) Therefore, it causes an authentication problem.
Of course, we should use different domain names for different apps in production.
But it is still nice to have this feature, at least for me.
`SESSION_NAME=connect.sid:8080 yarn server`
`SESSION_NAME=connect.sid:8080 yarn start`
You can add `SESSION_NAME` to …
> Enable custom session name with SESSION_NAME env var

- app.json
bonsai:sandbox-6 5.1 is not available now on Heroku.
```
An error was encountered when contacting the add-on partner to create bonsai:sandbox-6: The requested version [5.1] is not available in this region on your plan. Available options are: 1.7.5, 2.4.0, 5.3.2, 5.4.3, 5.6.8, 6.0.1
```
> changed bonsai version to latest 5.x (5.4.3)

- lib/views/not_found.html
Before page editor started to use React (before January this year), a title was automatically inserted when creating a new page. 
But since then, it stopped working correctly. This PR fixes the bug.
> Fix: Insert title when a page is created

- lib/routes/page.js
- lib/util/pagePathUtil.js
- lib/views/widget/page_list.html
- resource/js/components/Page/RevisionPath.js
- resource/js/legacy/crowi.js
Fix to generate link correctly when creating a new page containing `?` in the path.
`?` をパスに含む新規に作成したページのリンクを正しく生成するよう修正しました。
e.g.: `/Sandbox/foo?bar`
> Fix broken path

- lib/form/admin/securityGeneral.js
- lib/locales/en-US/translation.json
- lib/locales/ja/translation.json
- lib/models/config.js
- lib/models/external-account.js
- lib/routes/admin.js
- lib/views/admin/security.html
When an existing user logged in with LDAP for the first time, the user data (including his/her articles) are linked to an external account, instead of creating a new user.
> Migrate from original user when ldap auth succeeds

- lib/form/comment.js
- lib/models/comment.js
- lib/routes/comment.js
- lib/views/layout-growi/widget/comments.html
- resource/js/components/PageComment/Comment.js
- resource/js/components/PageCommentFormBehavior.js
一時的にチェックボックスを追加して、チェックの有無でmarkdown/plainを差別化
一時的にmarkdown/plainをユーザーネームの下に表示
> differentiate markdown/plain comments in backend

- lib/models/page.js
* Fix the bug that caused by "grant user group"-grantLabel has been commented out...
* Page view is not looks to be published "only inside the group", but actually it grant data is published only inside the group.
* なぜかどこかのタイミングでグループの公開範囲ラベルをコメントアウトしてしまっていたため、コメントアウトから復帰させました。
> refs Bug #410 公開範囲「特定グループのみ」でグループ指定できない

- lib/models/config.js
- package.json
- resource/js/util/GrowiRenderer.js
- resource/js/util/markdown-it/blockdiag.js
- yarn.lock
I implemented live preview of blockdiag.
If you like this please merge.
* http://blockdiag.com/en/
* https://www.npmjs.com/package/markdown-it-blockdiag
> add markdown-it-blockdiag (like PlantUML)

- package.json
- yarn.lock
* react-bootstrap-typeahead
react-bootstrap-typeahead above v3.1.0 ommited `submitFormOnEnter`
https://github.com/ericgio/react-bootstrap-typeahead/releases/tag/v3.1.0
> downgrade libs

- resource/js/components/SearchPage/DeletePageListModal.js
- resource/js/components/SearchPage/SearchResult.js
https://github.com/weseek/growi/issues/560
原因は不明。`React-Bootstrap`のバグだと思われます。
`<Checkbox>`のpropsの`inline={true}`で解決された。
agile-adminのclass`.checkbox .checkbox-info`をつけようとするとこの`inline`がもたらすsytleか何かが上書きされて、checkがつかなくなるので、素のHTMLのcheckboxを採用
> check toggle

- resource/locales/en-US/translation.json
- resource/locales/ja/translation.json
- src/server/form/admin/securityPassportSaml.js
- src/server/models/config.js
- src/server/models/external-account.js
- src/server/models/user.js
- src/server/routes/login-passport.js
- src/server/views/admin/widget/passport/saml.html
Currently, growi uses `username` for account linking when SAML federation.
This PR adds option to use `email` for the linking. Using `email` is better approach for security than using `username` to find existing user.
Note: To further improve security, we should perform re-authentication or mail authentication when account linking, but adding the `email` option is the first step for improvement.
> Imprv/Add option to use email for account link when using SAML federation

- config/migrate.js
herokuでgrowiのバージョンを更新しようとすると、preserver:prodで実行されるmigrate upが`ERROR: Authentication failed.`になります
前提: すでにherokuにmy-growiというapp名でdeployされている
```
heroku git:clone -a my-growi
cd my-growi
git remote add origin https://github.com/weseek/growi
// v3.3.3をリリース
git pull origin refs/tags/v3.3.3:master
git push heroku master
```
`config/migrate.js`にて設定される`mongodb.url`はDB名を含まないconnection urlになっています
`migrate-mongo/lib/env/database.js`はこのDB名を含まないconnection urlを利用して`MongoClient.connect()`します
herokuで通常使われるmLabのmongodbは、DBごとに権限が付与されるのでDB名なしconnection urlだと`ERROR: Authentication failed.`になります
heroku以外の環境は動作確認していません
> bugfix: mongodb migration failed in heroku

- src/server/util/swigFunctions.js
> ensure to return an empty array when passportService is null

- src/server/util/search.js
> fix #815: null check for 'user' when searching

- src/lib/service/xss/recommended-whitelist.js
Fix #1010 
----
FYI: 
```
diff --git a/a b/b
index f3b0f2c..1728520 100644
--- a/a
+++ b/b
@@ -1,37 +1,59 @@
-
a
+abbr
b
+bdi
+bdo
blockquote
br
+caption
+cite
code
col
colgroup
+data
dd
del
+details
+dfn
div
dl
dt
em
+figcaption
+figure
h1
h2
h3
h4
h5
h6
+h7
+h8
hr
i
iframe
img
+ins
kbd
li
+mark
ol
p
pre
+q
+rb
+rp
+rt
+ruby
s
+samp
+small
span
strike
strong
sub
+summary
sup
table
tbody
@@ -39,5 +61,11 @@ td
tfoot
th
thead
+time
tr
+tt
+u
ul
+var
+wbr
```
> Add more HTML tags to whiltelist

- src/server/crowi/index.js
Without this changes, we need to save OIDC settings manually to setup strategy.
> Missing initialization for OIDC Strategy

- src/server/routes/index.js
It looks like these routes for OIDC are removed by mistake.
> Restore URL routes regarding OIDC

- resource/locales/en-US/translation.json
- resource/locales/ja/translation.json
- src/server/routes/login-passport.js
- src/server/views/admin/widget/passport/ldap.html
LDAPグループ検索フィルタのことを、本来の「LDAPログインできるユーザを特定のグループに制限する」ものではなく、「LDAPグループをGROWIのグループに追加するため」のものであると当初勘違いしてしまいました。
そこで、同じような人が今後出てこないように、当該フィルタの説明に、「それにマッチするグループが存在したときのみLDAPログインが成功する」という文言を加え、当該フィルタがどのようなことをするのかをわかりやすくしました。さらに、おまけで、「LDAPログインのデバッグダイアログで、当該フィルタにマッチしないユーザの名前とパスワードでログインした際の警告メッセージ」を変更しました。
> Add description what LDAP group search filter is

- resource/cdn-manifests.js
It seems the number of mobile app projects which is using Kotlin and/or Swift is increasing. So I think it is better to add these languages to syntax highlighting.
> Add syntax highlighting for Kotlin and Swift

- resource/locales/en-US/translation.json
- resource/locales/ja/translation.json
- src/server/form/admin/aws.js
- src/server/models/config.js
- src/server/service/file-uploader/aws.js
- src/server/service/file-uploader/uploader.js
- src/server/util/middlewares.js
- src/server/views/admin/app.html
Related: #770 
- Append an new setting, custom endpoint
- Replace the direct access to files in S3 via URL, which depends on the static website hosting feature (MinIO won't have), with `s3.getObject()`.
I made it sure that images were successfully uploaded by drag-and-dropped to MinIO and they appeared properly after uploaded.
I don't know if we may use `s3.getObject()` instead of `axios.get([object URL])` in terms of, e.g., cost.
- 新しい設定項目「カスタムエンドポイント」を追加
- S3中のファイルのURLに直接アクセス(MinIOがサポートしないウェブサイトの静的ホスティング機能に依存)→`s3.getObject()` に置き換え
ドラッグ&ドロップでアップロードした画像がMinIOに正常にアップロードされ、その後正常に表示されることは確認できました。
ただし、料金等の面から、`axios.get([オブジェクトのURL])`の代わりに`s3.getObject()`を使ってよいのかはわかりません。
> Support S3-compatible object storage services like MinIO

- src/client/js/components/Page.jsx
#1156 「Bug: 「特定グループのみ」のページで「Edit Table」の「Done」を押すとエラーが表示され、編集できません。」を修正になります。
オプションが足りていなかったようなのでオプションを追加しました。
> fix can't save table modal window (limited group)

- src/server/views/admin/widget/passport/ldap.html
Bind DN password is shown as a plain text in the LDAP configuration page.
Since this is a password, it should be masked.
> use password as type in input field for LDAP Bind DN password

- src/server/service/search-delegator/elasticsearch.js
WHATWG URL APIの方だとauthプロパティは使えないのでusernameとpasswordを使うように変更.
> Elasticsearch Clientに渡すhttpAuthの作成方法を修正

- README.md
https://github.com/weseek/growi/issues/323
こちらの ISSUE にコメントを追加し、ファイル参照元を追加しました。
以下の Gif アニメに差し替える PR です。
指摘後、英語に変更しました。
GROWI の設定も 英語の状態で Gif 再作成しています。
> gw698-714-change-readme-gif-file

- src/server/routes/apiv3/app-settings.js
Format for API document in `app-settings.js` is wrong.
The PR will modify this miss takes.
Confirmed to enable to build `swagger.json`.
* before fix
```bash
> yarn run build:apiv3:jsdoc
yarn run v1.19.1
$ swagger-jsdoc -o tmp/swagger.json -d config/swagger-definition.js src/server/**/*.js
components:
schemas:
AppSettingParams:
type: object
properties:
title:
type: String
description: site name show on page header and tilte of HTML
confidential:
type: String
description: confidential show on page header
globalLang:
type: String
description: language set when create user
fileUpload:
type: boolean
description: enable upload file except image file
SiteUrlSettingParams: -------------- Pay attention at this place
type: object
properties:
siteUrl:
type: String
description: Site URL. e.g. …
```
> modify openapii format in app-settings.js

- src/client/js/components/Admin/MarkdownSetting/WhiteListInput.jsx
XSS設定のインポートボタンがずれているのを修正しました
(before)
(after)
> bst4 admin/markdown XSSsettings fix buttons

- resource/locales/en-US/translation.json
- resource/locales/ja/translation.json
- src/server/form/admin/securityPassportSaml.js
- src/server/routes/admin.js
- src/server/routes/login-passport.js
- src/server/service/config-loader.js
- src/server/service/config-manager.js
- src/server/service/passport.js
- src/server/views/admin/widget/passport/saml.html
- yarn.lock
SAML Responseの <code>&lt;saml:AttributeStatement&gt;</code> 要素に含まれる <code>&lt;saml:Attribute&gt;</code> 要素と, その子要素 <code>&lt;saml:AttributeValue&gt;</code> を利用してログイン制限を行う.
- 他のSAMLの設定項目同様にDBと環境変数の両方から設定可能
- <code>属性名 = 値</code> を <code>|</code>(論理和),  <code>&</code>(論理積) で連結した形式で記述する
-  <code>属性名</code>は<code>&lt;saml:Attribute&gt;</code> 要素のName属性の値
- <code> 値 </code> は <code>&lt;saml:AttributeValue&gt;</code> の値
> SAMLの属性値を利用したログイン制限機能を実装

- src/client/js/components/PageEditor/MarkdownDrawioUtil.js
fix #1738 
Fix string evaluation in JSON.stringify.
The comparison is based on the assumption that the order of the objects does not change.
Because `getBod` and` getEod` return objects in a comparable.
Had compared the identity of the objects
> Fix #1738: Bug: DrawioModal is not opened when editing blank page

- src/client/js/components/Drawio.jsx
- src/client/js/util/interceptor/drawio-interceptor.js
> Fix #1755: draw.ioを含むページを編集するときに編集画面のスクロール位置が移動してしまう

- src/client/js/components/Page/RevisionBody.jsx
* 3.7.0 or higher
* With this fix, it can be changed from "almost no rendering" to "sometimes not rendering"
* refs: #1808 #1754
* do not close this issue.
* Errors still occur, but MathJax can be rendered.
* Rendering is in CHTML format because MathJax of draw.io is used.
* SVG cannot be used because it uses MathJax of draw.io
* Addition of draw.io Integration causes initialization conflict between MathJax of draw.io and MathJax of GROWI.
* So, before MathJax is initialized, execute renderMathJaxWithDebounce again.
* Avoiding initialization of MathJax of draw.io solves the problem.
* refs: https://github.com/jgraph/drawio/pull/831 https://github.com/jgraph/drawio/pull/833
> Workaround MathJax rendering.

- src/client/styles/scss/_layout_kibela.scss
- src/server/views/layout-kibela/base/layout.html
> change to expand element unless its reach to max

- src/client/js/components/Admin/Security/LdapAuthTest.jsx
master
this
border は overrideされて付けられているのでそのままにしました。
> update bstr classes

- src/client/js/components/Admin/Customize/CustomizeLayoutOptions.jsx
before remove Crowi Classic Layout
before adjust layout
after
> remove Crowi Classic Layout and adjust layout

- src/client/js/components/Admin/Notification/SlackAppConfiguration.jsx
- 小さいサイズ
- 中くらい
04-22 14 45 15](https://user-images.githubusercontent.com/27404438/79945175-382bfb00-84a8-11ea-9d56-f45c679bfb55.png)
- 大
> be responsive

- src/client/styles/scss/_layout_kibela.scss
- src/client/styles/scss/theme/_apply-colors-kibela.scss
- src/server/views/layout-kibela/base/layout.html
> fix color and subnav position

- src/server/crowi/express-init.js
セッション管理にMongoDBを用いている場合に, MongoDBへのコネクションを確立できない状態でGROWIに複数回アクセスすると, 以下のようにイベントリスナのリークが起きていた(Redisを利用している場合は未検証).
```
(node:7908) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added to [MongoStore]. Use emitter.setMaxListeners() to increase limit
```
[こちらのIssueのケース](https://github.com/expressjs/session/issues/623)と同様に, リクエストが来るたびにexpress-sessionの[セットアップ処理](https://github.com/expressjs/session/blob/master/index.js#L87)を呼んでしまっていることが原因なので, 一度しか呼ばないように修正した.
> Fix event listener leak

- yarn.lock
以下の環境で, fseventsのビルドが失敗する(node.jsが`v10.20.1`の場合は成功する).
v14系はまだGROWIではサポートされていないが, 今後サポートされることを考え検証した.
| item     | version |
| ---      | --- |
|OS        |macOS Mojave(10.14.6)|
|node.js   |v12.17.0, v14.3.0|
fseventsはmacOSのバージョンが上がると古いバージョンのものは動かなることがあるため, 最新版(fsevents @1.2.13)にアップデートを行い, node.jsの`v10.20.1`, `v12.16.3`, `v14.3.0`のすべてについてビルドが成功することを確認した.
以下のように, 現在GROWIには`1.2.4`, `1.2.7`, `2.1.2`が入っているが, ビルドに失敗しているのは`1.2.4`, `1.2.7`の1系のfsevents.
```
$ yarn why fsevents
yarn why v1.22.4
[1/4] 🤔  Why do we have the module "fsevents"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "fsevents@1.2.7"
info Reasons this module exists
- "browser-sync#chokidar" depends on it
- Hoisted from "browser-sync#chokidar#fsevents" …
```
> Update fsevents to latest version

- src/client/styles/scss/atoms/_nav.scss
- src/server/views/widget/page_tabs.html
> imprv dont break tabs

- src/server/routes/page.js
`pages.update`は現在`body`と `page_id`が必須パラメータになっているが, `revision_id`も必須のため, これを追加した.
以下のようなペイロードで`pages.update`にリクエストを行うと
```
{
"body": "hoge",
"page_id": "5edc8a3eb9f6209e66d0cea6"
}
```
以下のようなレスポンスが返ってくる
```
{
"ok": false,
"error": "TypeError: Cannot read property 'body' of null"
}
```
サーバのログを見ると以下のようなエラーが発生している.
```
[2020-06-07T07:00:17.195Z] ERROR: growi:routes:page/41102 on Localhost:
error on _api/pages.update TypeError: Cannot read property 'body' of null
at api.update (/Users/utsushiiro/growi/src/server/routes/page.js:861:69)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
該当部分を見ると, revision_idが未指定の場合はpreviousRevisionがnullになるので, previousRevision.bodyのプロパティアクセスでエラーになっている.
https://github.com/weseek/growi/blob/ee86a33c12cc477635eac7b667a0faeeda43f1b5/src/server/rou …
> Fix pages.update API

- src/client/js/components/Admin/ExportArchiveData/ArchiveFilesTableMenu.jsx
アーカイブデータのダウンロードボタンをクリックしてもデータがダウンロードできない問題を修正した.
原因としてはbuttonにhrefを用いていることだったため, onClickによる遷移に差し替えた.
> Fix archive download button

- src/client/js/components/PageEditor/CodeMirrorEditor.jsx
- src/client/js/components/PageEditor/LinkEditModal.jsx
- src/client/js/components/PageEditor/MarkdownLinkUtil.js
テキスト選択中にリンク追加モーダルを開くとそのテキストがラベルのフォームに反映され、Doneを押すと選択中テキストにリンクが置き換わる、選択中テキストがない場合はリンクが挿入される
> apply and replace selected text

- yarn.lock
現在のnode-sassのバージョン(`4.12.0`)ではNode.jsのv14はサポートされておらず, ビルド済みバイナリが無いため`yarn install`時にビルドされる.
参考: [node-sass v4.12.0 Release Note](https://github.com/sass/node-sass/releases/tag/v4.12.0)
開発環境等では問題ないが, weseek/growiのDockerイメージのビルド環境はnode-sassをビルドすることを想定する作りになっていないため, DockerイメージのNode.jsのバージョンをv12からv14に更新した場合, ビルドエラーとなる.
これを修正するため, node-sassをv14をサポートしている`4.12.0`から`4.14.1`に`yarn update node-sass`にて更新した.
参考: [node-sass v4.14.1 Release Note](https://github.com/sass/node-sass/releases/tag/v4.14.1)
> Update node-sass to the latest version compatible with Node.js v14

- src/server/routes/attachment.js
attachmentsのレスポンスヘッダの Last-Modified に設定する値の形式を変更した.
```
{ 'Last-Modified': 'Sat Jun 20 2020 17:37:13 GMT+0900 (GMT+09:00)'}
{ 'Last-Modified': 'Sat, 20 Jun 2020 08:32:14 GMT' }
```
現在, attachmentsのレスポンスヘッダの Last-Modified にはDateオブジェクトを渡している.
https://github.com/weseek/growi/blob/86037b82d25ac889e5a0dd596b6d7c5570f5dcfc/src/server/routes/attachment.js#L215-L219
このDateオブジェクトはExpressのres.setの中で文字列に変換される.
https://github.com/expressjs/express/blob/351396f971280ab79faddcf9782ea50f4e88358d/lib/response.js#L749-L767
こうしてできた値は以下のようなフォーマットになる.
```
Sat Jun 20 2020 17:37:13 GMT+0900 (GMT+09:00)
```
これはRFCにて定義された Last-Modified のフォーマットに反している.
- https://tools.ietf.org/html/rfc7232#appendix-C
- https://tools.ietf.org/html/rfc7231#section-7.1.1.1
また, Node.js …
> Fix Last-Modified header for attachments

- src/server/routes/attachment.js
- src/server/service/config-loader.js
- src/server/service/file-uploader/local.js
- src/server/service/file-uploader/uploader.js
アップロード済みの添付ファイルの配信方法としてnginxの内部リダイレクト、もしくはApacheのSendFileを使用するオプションを追加します．
#2470
　
Growiが直接容量の大きい添付ファイルを配信すると速度が遅いので改善したい
- Growiをnginxのリバースプロキシを通して運用している場合
- FILE_UPLOAD=local
| オプション名|  説明|  デフォルト値|
| -- | -- | -- |
| USE_INTERNAL_REDIRECT | true の場合、nginxの内部リダイレクト機能，もしくはApacheのSendFile機能を使用して添付ファイルを配信します．| false |
| INTERNAL_REDIRECT_PATH | nginxの内部リダイレクト先のURLパスを指定します．ApacheのSendFile機能を使用する場合，このオプションは無視されます．| /growi-internal/ |
上記のオプションを適切に設定した後，下記の要領でサーバーの設定を更新する
serverディレクティブ内に下記を追加する
```
location ~ ^/growi-internal/(.*) {
alias (Growiのファイルパス)/public/$1;
}
```
location ディレクティブのパスは上記の`INTERNAL_REDIRECT_PATH`と一致するように設定します．
```
XSendFile on
XSendFilePath (Growiのファイルパス)/public
```
> Supports nginx internal redirect and Apache SendFile.

- resource/locales/en_US/translation.json
- resource/locales/ja_JP/translation.json
- resource/locales/zh_CN/translation.json
- src/client/js/components/Admin/Security/OidcSecuritySetting.jsx
- src/client/js/services/AdminOidcSecurityContainer.js
- src/server/routes/apiv3/security-setting.js
- src/server/service/passport.js
Description
-------------
Add detailed configurations for OpenID Connect.
Background
-------------
OpenID Connect mandates HTTPS URL for authorization endpoint and other endpoint URLs.
As a result, some OpenID Connect Identity Provider gives only HTTPS endpoint URLs in `.well-known/openid-configuration` for production environment even if actually provides only HTTP endpoint (for example: [doorkeeper-gem/doorkeeper-openid_connect](/doorkeeper-gem/doorkeeper-openid_connect)).
This is reasonable decision for IdP, and we cannot ensure SSO in our corporation's internal network without making endpoint URLs.
(Of course I understand that we should use valid certificates even in internal network, however, it is very hard to achieve.)
Pull Request
--------------
I add detailed manual configurations …
> Add detailed configurations for OpenID Connect

- src/client/js/components/PageEditor/GridEditModal.jsx
- src/client/js/components/PageEditor/GridEditorUtil.js
- src/client/styles/scss/_on-edit.scss
> grid division menu responsive size

- package.json
- src/client/js/components/Page.jsx
- src/client/js/components/PageEditor/MarkdownDrawioUtil.js
- yarn.lock
* fix #2571.
* The cause is Off-by-One error. (Fixed GROWI code)
* Wrong begin-line-number and end-line-number (Fixed by markdown-it-drawio-viewer upgrade)
> Fix draw.io diagram cannot be saved properly.

- resource/cdn-manifests.js
- src/server/views/widget/headers/mathjax.html
* fix #2494 #1754
* Suppress MathJax related errors by upgrading MathJax to 3
---
* MathJax を draw.io に先行して 3 にアップグレードすることで、
MathJax 関連のエラーを抑止します。
---
変化が無いことの確認 ( Confirm that there is no change )
> Upgrade Mathjax (2 -> 3)

- src/client/styles/scss/_override-bootstrap-variables.scss
- src/client/styles/scss/theme/_apply-colors-light.scss
- src/client/styles/scss/theme/_apply-colors.scss
- src/client/styles/scss/theme/default.scss
- XDで調整した色設定を反映させました。
- 見た目をほぼ変えずに、変数の書き方が変わっています。
- 色の設計の際に、アクセントカラーという考え方を使っているので、該当する変数を追加した。
- 似ている色は同じ色に統一する
- グレー系は$dark/$lightを使って表現する
- 例： darken($light, 20%), lighten($dark, 10%)
- 色が乱立することを避けるため、同じ色相で明度が違うものに関してはdarken/lighten関数を使う
- 色が乱立してしまっていたので、XDにて色変数を整理した。
- やったこと
- 特にグレー系は似ている色が多かったので、見た目的に問題のないものは同じ色を使うようにする。
- グレー系はlightとdarkをsass関数で出し分けるようにする
- ![image](https://user-images.githubusercontent.com/20252919/89192731-e6832880-d5df-11ea-9aea-626b33211022.png)
> default_lightの色をXDの方で整理した変数に変更しました。

- src/client/js/components/PageEditor/LinkEditModal.jsx
linkのoriginがアクセス中のページurlのorigin と同じ場合、linkのオリジンを取り除き pathのみにする
> enable-to-get-preview-from-origin-and-path

- src/server/models/user.js
GW-3584 ユーザー管理画面で、ステータスが表示されないBugを修正
> add space before "status"

- src/client/js/components/TableOfContents.jsx
作業ブランチに問題があったため、ブランチを変えプルリク新規作成
変更前のブランチ `feat/gw-3755-toc-maxheight-for-userhome `
UserHome専用のボタン（Bookmark,RecentCreate）移動に伴い、TOC高さ上限の調整
> Changed TOC height in user home and other pages.

- src/client/js/components/PageEditor/DrawioModal.jsx
* Change www.draw.io to embed.diagrams.net
* refs: https://twitter.com/koboshi_kyopro/status/1309180532899622912
> Fix draw.io warning dialog.

- src/client/js/components/PageAttachment/Attachment.jsx
PageAttachmentModal がデザイン適用がまだだったので、追加で作成しました。
xd デザイン
適用後
適用前
> apply design

- src/client/js/components/Admin/ManageExternalAccount.jsx
- src/client/js/components/Admin/Security/ShareLinkSetting.jsx
- src/client/js/components/Admin/UserGroup/UserGroupPage.jsx
- src/client/js/components/Admin/UserGroupDetail/UserGroupPageList.jsx
- src/client/js/components/Admin/UserManagement.jsx
- src/client/js/components/MyDraftList/MyDraftList.jsx
- src/client/js/components/PaginationWrapper.jsx
- src/client/js/components/RecentCreated/RecentCreated.jsx
- src/client/js/components/TagsList.jsx
GW-4021 pagination-wrapper を拡張してサイズを変更できる
元々どのページネーションにも`sm`が指定されるようになっていましたが、標準でmdサイズにし、smやlgにする時はpropsで渡すしように変更しました。
[変更前 smサイズ]
[変更後 普通サイズ]
> change pagenation size by adding proptype

- src/server/views/widget/not_creatable_content.html
couldn't create において、 tab の削除を実行しました。
前
後
> delete tab of pageList

- src/client/js/components/Navbar/GrowiSubNavigation.jsx
- src/client/js/components/Page/RevisionPathControls.jsx
- src/client/styles/scss/_on-edit.scss
- src/lib/components/PagePathHierarchicalLink.jsx
- ![image](https://user-images.githubusercontent.com/20252919/95542414-aa7da100-0a30-11eb-9ee0-a1cd71409116.png)
- calcを使って横幅を決定していた書き方から、自然に横幅が決定するような書き方に変更
- ついでにやったこと
- タイトルの横の[copyPagePathDropdown]ボタンは単体で改行してしまっていた(flex-wrapがついていた)
- ページタイトルの右横に位置しているほうが、デザイン的に美しいのでそのようにした
> ページパスとページタイトルが長い場合のEditモードのサブナビバーの表示

- src/client/js/components/SlackNotification.jsx
- src/client/styles/scss/molecules/slack-notification.scss
- src/client/styles/scss/theme/_apply-colors-light.scss
- custom switchとフォームの幅を詰めた
- placeholderの色が濃いので別のgrayを入れて薄くした（その他のText-Inputにも反映させた）
- Switchの丸い部分が縦にやや長いので、真円にした
- スマホ版のスタイルが崩れていたので修正
- PC
- ![image](https://user-images.githubusercontent.com/20252919/95846185-19872c80-0d86-11eb-9326-675840435956.png)
- SP
- ![image](https://user-images.githubusercontent.com/20252919/95846235-2ad03900-0d86-11eb-8d22-1df72a24a684.png)
> Slackボタンのデザインの当て（デザインチェックFB対応）

- src/client/js/components/Page/RevisionPathControls.jsx
> abolish icon

- src/client/js/components/Navbar/GrowiSubNavigation.jsx
> add !isPageInTrash

- src/client/styles/scss/_mixins.scss
- src/client/styles/scss/theme/antarctic.scss
- src/client/styles/scss/theme/christmas.scss
- src/client/styles/scss/theme/default.scss
- src/client/styles/scss/theme/future.scss
- src/client/styles/scss/theme/halloween.scss
- src/client/styles/scss/theme/island.scss
- src/client/styles/scss/theme/kibela.scss
- src/client/styles/scss/theme/mono-blue.scss
- src/client/styles/scss/theme/nature.scss
- src/client/styles/scss/theme/spring.scss
- src/client/styles/scss/theme/wood.scss
- Kibelaテーマの三連ボタンの見た目を実装
- 関連箇所のリファクタ
- 3連ボタンのactiveステートを3連ボタンの@mixinに内包させた
- デグレっていた箇所を修正
- 封印したはずのBS4によるfocus時のbox-shadowが復活していた
> Implementation completed and eliminate the degreasing.

- src/server/views/widget/user_page_content.html
This unclosed tag breaks _Bookmarks_ and _Recently Created_ lists in user page, when `bookmarkList.length == 0`.
> Fix unclosed conditional tag in user page

- .github/workflows/ci.yml
- .github/workflows/release-rc.yml
- .github/workflows/release.yml
* actions/cache (v1->v2)
* Better performance
* Avoid stuck in some cases
* actions/upload-artifct (v1->v2)
* Fix for artifact uploads sometimes not working with containers
* crazy-max/ghaction-docker-buildx (v3->docker/setup-buildx-action@v1)
* Migrated (original is no longer maintained)
* peter-evans/dockerhub-description (v2.1.0->v2)
* (Just updating)
> Bump version of GitHub Actions

- .github/workflows/ci.yml
It is better to use *service containers* instead of executing `docker run -d` (or its equivalents).
https://docs.github.com/en/free-pro-team@latest/actions/guides/about-service-containers
`wbari/start-mongoDB@v0.2` expects the availability of `27017/tcp` of the runner, but it is not always guaranteed.
> Actions: Launch MongoDB as a service

- src/client/js/components/PageTimeline.jsx
タイムラインリストに対象ページがなかった時に何も表示されなかったので以下のメッセージを追加しました。
> add message in timeline when the page does not have children pages

- src/client/js/components/Navbar/GrowiSubNavigation.jsx
前回までの使用では、GrowiSubNavigation.jsx に user の情報を持たせていました。
しかし、今回の仕様変更によりその部分が不必要になったので削除しています。
> Fix/delete unuse code in growi sub navigation.jsx

- resource/locales/en_US/translation.json
- resource/locales/ja_JP/translation.json
- resource/locales/zh_CN/translation.json
- src/server/views/page_presentation.html
> translate last section of presentation

- src/client/styles/scss/atoms/_buttons.scss
GW-4369 Likeボタンのhover時のBGカラーをXDどおりに変更
[デザインスペック]
[変更前]
[変更後]
青いカラーはデザインスペックと若干違いますが、一旦このままで良いそうです。
> change hover color of the like button

- src/client/js/components/Me/PasswordSettings.jsx
パスワードの更新時に誤ったメッセージが表示されていたのを修正しました
修正前
修正後
> fixed update password message

- src/client/styles/scss/theme/halloween.scss
GW-4372 テーマハロウィンの時、背景が白いと文字が見えづらい
[変更前]
[変更後]
> changed gray-50 to bgcolor-global cus the background colors of the cards were too bright

- src/client/js/components/ShareLink/ShareLinkForm.jsx
GW-4410 Share settingsモーダル、custom入力時のデフォルトの時間が12時間ずれているので修正
元々、defalultの値(現在時刻)は12時間表記になっており、
リンクを発行しようとすると
「それは過去の時間だよ」というエラーが出てしまっていました。
これは、ドロップダウン内部の選択できる値が24時間表記になっていたことが原因であると判明したため、defaultで表示される値も24時間表記に統一しました。
https://date-fns.org/v1.28.5/docs/format
> change to 24 hour fomat

- src/client/js/legacy/crowi.js
- src/client/js/services/PageContainer.js
- src/server/views/widget/not_creatable_content.html
GW-4317 could'nt create page作成時のテキストにmarginをつける
could'nt page 作成時(#edit)に、メッセージが端によってしまっていたのでmarginをつけて余白を作りました。
> improve could'nt create page

- src/client/js/components/Drawio.jsx
- src/server/views/widget/headers/drawio.html
(日本語で)
* `DrawioViewer.prototype.responsive = true;` を設定することでレンダリング時に width の計算をするように修正
* 4.2.0 では親要素が width: 100% とは限らない (`flex-grow-1` を指定しているところ)ので drawio 側が計算できていなかった
* 追加修正として、初期レンダリング時のフローが分かりづらかった点を修正しました
* `GraphViewer..processElements();` を呼び出すことを止めました
* その代わりに MathJax と同様に debounce を利用する形に修正しました
> refs GC-4383: If the figure of drawio is too big, it will be out of view.

- src/client/styles/scss/theme/_apply-colors-dark.scss
- src/client/styles/scss/theme/_apply-colors-light.scss
- src/client/styles/scss/theme/mixins/_list-group.scss
- [前回のプルリク](https://github.com/weseek/growi/pull/3044/files)で`$border-color`を入れていた箇所に、独自の変数`$border-color-global`を挿入。
- 色がわかりやすいのでfutureテーマで撮影
- ボーダーがグレーの箇所が`$border-color-global`
> Add variables `$border-color-global` and and apply.

- src/client/styles/scss/theme/spring.scss
GW-4398 【spring theme】ボタンの文字色が薄いのを修正
spring themeなんかコードが微妙なので(自分が書いたのですが....)時間があるときに大幅改修しようと思います
> change btn-outline color

- src/client/js/components/Page/CopyDropdown.jsx
h* のアンカーリンクをクリックし PagePath#hoge などに移動した際、ページタイトル横の CopyDropdown のURLの値のhashが変わっていない
Dropdown ないのコンテンツは CopyDropdown の render() の中で生成処理が走るようになっている。添付した gifのように PagePathNavigation のコンパクトモードが切り替わるたびに CopyDropdown の render()が走るためその場合はコンテンツが更新されるが、コンパクトモードのままの場合は render() は走らず、コンテンツは更新されない
コンテンツをstate管理し、dropdown を開くたびにコンテンツ生成処理を走らせるようにした。
> fix gw-4438 not update hash in CopyDropdown

- src/client/js/components/Page/NotFoundAlert.jsx
guest mode のときに create Page をクリックできないようにしています。
（前回の実装では、 disabled に見えるだけで実際にクリックすることができてしまうことが発覚したので改修しました。)
見た目は変更はありません。
> change position

- src/client/js/components/RecentCreated/RecentCreated.jsx
recentCreated において margin が適用されていなかったので修正しています。
修正前
修正後
> add mb-3 in recentCreated.jsx

- src/client/styles/scss/theme/_apply-colors.scss
- src/client/styles/scss/theme/christmas.scss
```apply.colors.scss
/*
* Modal
*/
.modal {
.modal-header {
border-bottom-color: $border-color-theme;
.modal-title {
color: color-yiq($primary);
}
.close {
color: color-yiq($primary);
opacity: 0.5;
&:hover {
opacity: 0.9;
}
}
}
```
` color: color-yiq($primary);`これが指定されていたことによって、modal-headerに柄のあるクリスマスとはうまく共存できていなかった。
> fix text color of modal headers in christmas theme

- src/client/js/components/Admin/Users/UserMenu.jsx
userテーブル内のドロップダウンボタンのpositionがabsolute だったため横幅が小さい時に以下のようにレイアウトが崩れる ([#3091](https://github.com/weseek/growi/pull/3091) での変更)
なのでCopyDropdown を真似て reactstrap の Dropdown (with positionFixeD) を使って修正
修正後↓
> use Dropdown of reactstrap

- src/server/routes/apiv3/mongo.js
`GET /_api/v3/mongo/collections` というエンドポイントに対し、セキュリティリスクはないものの認証がないことに関して指摘されたため loginRequiredStrictly, adminRequired を追加しました。
> add admin required to api for getting mongo collections

- src/client/styles/scss/_linkedit-preview.scss
以前のFB: https://github.com/weseek/growi/pull/2764#discussion_r490956433
font-size の変更で縮小するようにしました。画像はpopoverの幅に合わせて縮小するため問題なかったです。ただbootstrap の alert や card のようにmargin, paddingが指定してあるものは大きめに表示されます。あくまでプレビューなので致命的な問題ではないと考えていますが、気になるようであれば transform の scale() を使うよう変更します。
> modify layout of linkedit-preview

- src/server/routes/attachment.js
対応している脆弱性の内容はレビュー用タスクに記載しています。
アタッチメントアップロード時にファイルのmimetypeによりフィルタリングする方法も提案されていましたが、アタッチメント表示時のサーバーからのレスポンスでのセキュリティポリシーを追加することで対応しています。
> enhance security policy about getting attachment

- src/client/js/components/Page/RevisionLoader.jsx
制限ページにおいて,
[Object, object] の表示問題を修正しました。
修正前
修正後 / アクセス権限ない user
修正後 / アクセス権限ある user
> fix state in revision loader

- src/lib/service/xss/xssOption.js
- src/server/crowi/index.js
- src/server/routes/page.js
[概要]
presentation mode のときに alert が出る問題を修正しました。
当初 xss を導入しました。
しかし、xss に引っかかってしまうと、`</script><script></script>` が文字として表示されなくなるので replace する方法に変更しました。
replace した結果 < と > が内在するものは html において　`'&lt;/script&gt;` のように置換され、アラートも発生せず、presentation mode でも文字として表示させることが可能になりました。
[実際の挙動]
alert が出現しなくなった。
[server log]
> fix xss for presentation mode

- src/client/js/components/PageEditor/LinkEditModal.jsx
リンク編集モーダルの下部のボタンを他のモーダルのレイアウトに合わせフッターに移動（デザインチームに相談済み）
- before
- after
> move buttons to footer

- src/server/models/page.js
再起的に page を delete する操作 (実質 rename 操作) のパフォーマンス修正を行いました。
現時点で elasticsearch に不具合がありますが、
この修正は takeru-n が修正 task を進行中です。
不具合の内容は、
renameRevursively において、pageEvent.emit を設定していないことによって発生します。
現状では delete した page が / trash / hoge と検索できません。
また elasticsearch の docs の deleted が 消した ページ分だけ増えるのですが現状では増えません。
> reduce load of delete(rename)

- src/client/js/components/PageEditor/GridEditModal.jsx
- src/client/styles/scss/_on-edit.scss
- src/client/styles/scss/theme/_apply-colors.scss
> apply different colors to each col

- src/client/styles/scss/_on-edit.scss
- GW-4807 デザイン実装
>- 横幅最大値を980pxに設定する(記事エリア)
>- 左右のPaddingを30pxに設定する
>## XD
>- https://xd.adobe.com/view/cd3cb2f8-625d-4a6b-b6e4-917f75c675c5-986f/screen/5337bc82-f365-4e61-ad04-8d49c0bc701b/
- edit modeのpreviewの画面の横幅に少しだけpadddingが追加された
> width and padding adjustment for the preview area on edit mode

- src/server/routes/hackmd.js
Hi,
I've noticed that Growi integration with HedgeDoc failed due to invalid header check. 
As CodiMD has been forked to HedgeDoc, "codimd-version" header has been renamed to "hedgedoc-version".
Thanks.
> allow hedgedoc integration

- src/client/js/components/ContentLinkButtons.jsx
GW-5038 commentsボタンの表示を修正する
commentのエリアがないページにもコメントに飛ぶボタンが表示されてしまっていたので修正しました。
> Imprv/gw5038 make comments button unvisiable in the top and the shared user's pages

- src/client/js/components/Navbar/GrowiSubNavigation.jsx
- src/client/js/components/Navbar/PageEditorModeManager.jsx
One of solutions for #2957 
HackMD button will be disabled for common users like disabling edit buttons for guests.
> Disable unconfigured HackMD button for common users

- src/server/service/bolt.js
動作確認の FB を受けて若干修正しています。
これは、/ growi create を実行した結果発生したエラーなのに、その原因をしてめさずに、Hint /growi create というなんとも無意味なメッセージを載せていたので、 err 内容がわかるようにしています。
> change error

- src/server/routes/apiv3/slack-bot.js
- src/server/service/bolt.js
slackbotにはslackからのリクエスト送信から3秒以内に応答がなかったら timeoutエラーとなるので、リクエストを受け取ったらレシーバーないの処理に行く前に 空のres.send() を実行して、その後に内部の処理を実行するようにしています。（動作は確認済みです)
またレシーバー内での処理中にエラーが生じた場合もtimeout エラーが生じるため、「検索ワードが設定されていない」などはエラーとしてthrowはせず、slackユーザーにその旨のメッセージを送るだけにしています。
> change timing to send response

- src/client/js/components/Navbar/PageEditorModeManager.jsx
#3477 の尻拭いです。
- HackMDが利用不可時にでるツールチップのメッセージを変更
- ツールチップが出る条件の変更（管理者&HackMD未設定&**HackMD未設定画面を出していない**）
- ~~`showHackmdDisabledTooltip`の削除~~
本当はHackMDボタンに!⃘ (！+○)のようなバッジを表示したいのですが、ボタン内の文字が窮屈になるのでどう対処したらいいのか（React BootstrapのPill Badgeコンポーネント内に「`!`」）がわからなかったので断念しました。
お願いします。
> Change message & condition of HackMD-not-available tooltip

- package.json
- resource/locales/en_US/admin/admin.json
- resource/locales/ja_JP/admin/admin.json
- resource/locales/zh_CN/admin/admin.json
- src/client/js/components/Admin/MarkdownSetting/IndentForm.jsx
- src/client/js/components/Admin/MarkdownSetting/MarkDownSettingContents.jsx
- src/client/js/components/PageComment/CommentEditor.jsx
- src/client/js/components/PageEditor.jsx
- src/client/js/components/PageEditor/CodeMirrorEditor.jsx
- src/client/js/components/PageEditor/Editor.jsx
- src/client/js/components/PageEditor/OptionsSelector.jsx
- src/client/js/services/AdminMarkDownContainer.js
- src/client/js/services/EditorContainer.js
- src/server/models/config.js
- src/server/routes/apiv3/markdown-setting.js
- yarn.lock
Closes #3439
- ユーザが自分で変更可能にする
- `EditorOptions`をページエディタから持ってくる？
- 管理者がデフォルト値を変更可能にする
- デフォルト値
- 管理者がユーザによる変更を禁止する
- 管理画面のUIの訳
- 中国語
インデント値は、`editorContainer`の状態と`CodeMirrorEditor`のプロパティ（`Editor`が`editorContainer`の状態から横流し）に持たせています。
管理者側の値をエディタに反映させるには、`appContainer.config`を経由させています。
管理者設定のインデント幅のドロップダウンは突貫工事です。
> Make it possible to change indent size / インデント幅を変更可能にする

- src/server/service/bolt.js
Slackにて、/growi searchコマンド実行時に検索結果が0の場合にエラーが出ていたので修正しました。
【Before】
```
[ERROR]  bolt-app UnknownError: Cannot destructure property 'resultPaths' of '(intermediate value)' as it is undefined.
at Object.asCodedError (/workspace/growi/node_modules/@slack/bolt/dist/errors.js:25:12)
at App.handleError (/workspace/growi/node_modules/@slack/bolt/dist/App.js:486:43)
at App.processEvent (/workspace/growi/node_modules/@slack/bolt/dist/App.js:479:25)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async BoltReciever.requestHandler (/workspace/growi/src/server/service/bolt.js:45:5)
at async /workspace/growi/src/server/routes/apiv3/slack-bot.js:39:5 {
code: 'slack_bolt_unknown_error',
original: TypeError: Cannot destructure property 'resultPaths' of '(intermediate value)' as it …
```
> Fixed cannot destructure error

- src/client/js/components/Admin/Common/AdminNavigation.jsx
Slack連携のアイコンを紙飛行機からSlackのアイコンに変えました。
Before
After
> Changed slack icon

- src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
- src/server/routes/apiv3/slack-integration.js
Slack連携 -> Custom Bot (Without Proxy) のコンソール画面にてBoltServiceのsetupの状態を確認できるようにしました。
> imprv/allows check the setup status of BoltService on the management screen

- src/server/service/page.js
- `/page` と `/page/child` にページを作成する
- `/page`を`/pages`等に名前変更し、子ページを含めて再起的に移動を行う
- サイドバーの「最新の変更」に `/pages/child` が表示されない
- 「最新の変更」に `/pages/child` が表示される
- 子ページの`updatedAt`がDateではなくDouble型としてDBに記録されてしまったため
`Date.now`を`Date.now().toISOString()`に変更しました。
他に`Date.now()`を用いているところはバグが出ていないので変更することはしませんでした。
`updatedAt: new Date()`
→CI でエラーが出ます。
`updatedAt: { $dateFromString: { dateString: Date.now() } }`
→CI でエラーが出ます。
済
> Fix/5711 Bug: 再起的な操作を行うと子供のページがサイドバーの最新の変更に表示されない GW-5710 

- src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettingsAccordion.jsx
Custom Bot (Without-Proxy) 設定 の 連携手順4のinput要素にカーソルを合わせてenterを押した時にreloadさせないかつテストを走らせるようにする処理の実装を行いました。
> prevent browser refresh

- src/client/js/components/Admin/SlackIntegration/ConfirmBotChangeModal.jsx
> Changed modal color

- resource/locales/en_US/admin/admin.json
- resource/locales/ja_JP/admin/admin.json
- resource/locales/zh_CN/admin/admin.json
- src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
- src/server/routes/apiv3/slack-integration.js
こちら、問題なく作動しました。
https://user-images.githubusercontent.com/66785624/116038455-6ab49900-a6a4-11eb-9b6e-58bd7524562c.mov
3言語に対応させました。
こちら、後続の『5774 TokenとSecretが正しくても、Scopeが間違っていたら連携図は赤いままにする』に必要で、
調査の結果scopeを取得するためのAPIがEnterprise専用だったりDeprecatedだったりするので、代替案として、帰ってくるエラーによってScopeのStateを切り替えるという対処をしました。
> 5775 5773 5781 

- public/images/slack-integration/slackbot-difficulty-level-easy.svg
- public/images/slack-integration/slackbot-difficulty-level-hard.svg
- public/images/slack-integration/slackbot-difficulty-level-normal.svg
GW-5809 難易度のsvg画像の表示が異なるのを修正
バッジのテキストをアウトライン化して、画像を差し替えることで修正しました。
- スティーブンさんPCでの表示
-  市澤さんPCでの表示
- スティーブンさんPCでの確認
> fix  botTypes' badges

- src/client/js/components/Admin/SlackIntegration/CustomBotWithProxyIntegrationCard.jsx
- src/client/js/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
CustomBotWithouProxy の連携成功時の UI を作成しました。
連携成功の判断は一時的に isSlackScopeSet という props を用意して行っています。
> integration success ui

- src/client/js/components/Admin/SlackIntegration/CustomBotWithProxyIntegrationCard.jsx
- src/client/js/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
- src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
CustomBotWithProxy の連携図において、ワークスペース名の表示と siteName を表示できるようにしました。
ワークスペース名と siteName を表示させるために一時的に slackWSNameInWithProxy と siteName の props を作成しました。
> enable display workspace name and growi app name

- resource/locales/en_US/admin/admin.json
- resource/locales/ja_JP/admin/admin.json
- resource/locales/zh_CN/admin/admin.json
- src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
currentBotType が officialBot か customBotWithProxy の時に、全ての設定をリセット というボタンを表示させるようにしました。
【officialBot】
【customBotWithProxy】
> reset button

- packages/slackbot-proxy/src/Server.ts
GW-5938 SERVER_URIがセットされていない場合、サーバーが起動できてしまうのを修正
- https://tsed.io/docs/services.html#lifecycle-hooks
> fix server uri error

- src/client/js/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
- src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
- src/client/js/components/Admin/SlackIntegration/DeleteSlackBotSettingsModal.jsx
- src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
全ての設定をリセット のボタンを押した際にモーダルを表示させるようにしました。
- DeleteSkackBotSettingsModal.jsx に resetAll props を持たせてモーダルの文言を変更するようにした。
- リセットボタンを押した際のロジックは後続タスクで行う。
> reset modal

- config/env.dev.js
- src/server/models/slack-app-integration.js
環境変数に ```SALT_FOR_GTOP_TOKEN``` と ```SALT_FOR_PTOG_TOKEN```  を作成し、slack-app-integration.js 内でアクセストークンを作成する際の salt として利用できるようにした。
> add token salt to env

- src/server/routes/apiv3/slack-integration-settings.js
- 考慮漏れです
proxy型 の botType から他の botType に移行するときに、proxy uri を削除する必要がありました。
追加で削除しています。
> add slack:botserverUri null

- src/client/js/components/Admin/SlackIntegration/WithProxyAccordions.jsx
GW-6014 AccessToken２つをClipboardにコピーできるようにする
> copy to clip board

- resource/locales/ja_JP/admin/admin.json
- src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxyIntegrationCard.jsx
withouProxy の連携図をレスポンシブに対応させました。
- 連携完了時
- 未完了時
- 現在は連携未完了の状態で表示させていいます
- 導通の成否によって、表示を切り替える実装は [GW-5998](https://youtrack.weseek.co.jp/agiles/84-39/current?issue=GW-5998) で行っています。
> responsive integration diagram

- src/server/routes/apiv3/slack-integration-settings.js
GW-6106 bot type変更時に、slackAppIntegraitonの値も破棄させる
> delete all slackAppIntegration documents

- src/server/form/invited.js
- src/server/form/register.js
ユーザー登録でパスワードが5文字以下のときに “registerForm.password has invalid characters” と表示される問題の修正です。
修正前:
修正後:
英数字記号以外の文字を使い、かつ短い場合:
> Add an error message "password is too short" to the user registration pages

- src/client/js/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
- src/client/js/components/Admin/SlackIntegration/OfficialBotSettings.jsx
- src/client/js/components/Admin/SlackIntegration/SlackIntegration.jsx
- src/client/js/components/Admin/SlackIntegration/WithProxyAccordions.jsx
Token GtoP, PtoGを再発行した際にFetchするようにしました。
今までは再発行した際に新しい値がinputに表示されてなかったが、表示されるようになった
> 6160 Fetch Access Tokens Upon Update

- src/client/js/components/PageEditor/LinkEditModal.jsx
[GW-6166 Bug: LinkEditModal.jsxの「パーマリンクを使う」チェックボックスがdisabledのままになっている
](https://youtrack.weseek.co.jp/issue/GW-6166)
[GW-6360 一度Linkを入力すると、空にしてもPreviewが表示されてしまうBugを修正](https://youtrack.weseek.co.jp/agiles/84-39/current?issue=GW-6360)
- 一度Linkを入力しPermalinkを取得すると、inputを空にしたにも関わらずPreviewが表示されるBugを修正しました。原因は、Permalinkのステートが空になっていないためでした。
- ページプレビューボタンを押した際に、Permalinkを取得できる仕様を復活させました。
- Typeaheadのクリアボタンを押したときにPreviewを空にする処理は入れてません。理由は、react-bootstrap-typeaheadがそのような仕様になっていない（[クリアボタンを押したときに、onInputChangeが発動しない](https://github.com/ericgio/react-bootstrap-typeahead/issues/408)）ことと、他のところで使われているSearchTypeahead.jsxを編集するのは困難なためです。
- Linkを入力すると、Typeaheadやページプレビューボタンを押さなくてもPermalinkを取得する処理は入れてません。理由は、文字を入力する度にTypeahead側とLinkEditModal.jsxの2箇所でAPIを叩く仕様になってしまうためです。
> GW-6360 一度Linkを入力すると、空にしてもPreviewが表示されてしまうBugを修正

- src/server/service/slackbot.js
Slackでキーワード検索時に、どのGROWIからの検索結果かわかるようにGROWI名を表示させました。
> Added ws name

- src/client/js/components/Admin/SlackIntegration/CustomBotWithoutProxySettings.jsx
bot manual が master にマージされるまで一旦非表示にしています。
> comment out

- src/client/js/components/Admin/SlackIntegration/CustomBotWithProxySettings.jsx
withProxy の slack app が10個に達したら `slackワークスペースを追加` ボタンを非表示になるようにしました。
> imprv/ button hidden

- src/client/js/components/Page/RevisionRenderer.jsx
GW-6573 修正
検索画面でlsxが正常に表示されないのを修正しました。
- 検索結果のSidebarに関しては仕様なので、no Contentsの表示のままです。
> used window.location not pageContainer

- src/client/js/components/Sidebar/RecentChanges.jsx
コメント数を表示
距離感気持ち悪いのはデザイン決まってから後続タスクで
（footstampの色が目立つのはhelloweenテーマだけでした）
> add number of comment

- src/client/js/components/Admin/Security/LdapSecuritySettingContents.jsx
コード修正の提案です。
セキュリティ設定画面
LDAP認証設定
検索フィルターの設定例を `{{ username }}`（スペースあり）から`{{username}}`（スペースなし）に変更
検索フィルターの設定例として
```
例1 - 'uid' または 'mail' に一致:(|(uid={{ username }})(mail={{ username }}))
例2 - 'sAMAccountName' に一致 (Active Directory):(sAMAccountName={{ username }})
```
と記載されていますが実際に`(sAMAccountName={{ username }})`を設定したところ認証に失敗し、
`(sAMAccountName={{username}})`に修正したところ認証に成功しました。
※動作確認を行なった環境ではActive Directoryを使用しています
上記の動作は環境要因でありスペースが含まれていても正常に動作する場合もあるという可能性も考えましたが、
初期値には`(uid={{username}})`（スペースなし）が設定されていること、注釈では
```
ログイン時のユーザー名を使用するには {{username}} の形式を使用してください。
空欄の場合 (uid={{username}}) が使用されます。
```
のようにスペースなしで記載されていることから、スペースなしで統一した方が良いのではないかと思いPRをお送りした次第です。
お手隙の際にご確認の上、ご検討頂ければと思います。
> [Fix] Remove spaces from the LDAP authentication code example.

- src/client/js/components/Admin/Security/LdapAuthTest.jsx
- src/client/js/components/Me/AssociateModal.jsx
外部アカウント作成モーダルはライト, ダーク含めて全テーマ同じ色だった
→ 各テーマ色に対応
↓
（参考）その他のテーマ一部
> Create external account

- resource/locales/en_US/translation.json
- resource/locales/ja_JP/translation.json
- resource/locales/zh_CN/translation.json
- src/client/js/components/LoginForm.jsx
- src/client/js/components/PasswordResetExecutionForm.jsx
- src/client/js/components/PasswordResetRequestForm.jsx
- src/server/views/forgot-password.html
- src/server/views/reset-password.html
GW-6861 [front] i18nを適用させる
- ボタンを「パスワードリセット」から「送信」に変更しました。
> improve i18n for password reset

- src/client/js/components/Sidebar/RecentChanges.jsx
- src/server/models/page.js
コンフリクトしたのでpage.jsの770行目だけ前のtagの差分反映されてます。
表示されているページの閲覧数 がサイドバーの全ての閲覧数に表示されていた
→ 各ページに対応した閲覧数を表示
（画像はホームだけ2）
> fix view count

- src/client/js/components/Sidebar/RecentChanges.jsx
- src/client/styles/scss/_recent-changes.scss
- src/client/styles/scss/theme/_apply-colors.scss
> cahnge color & position

- src/client/js/components/Sidebar/RecentChanges.jsx
更新日時の長さを考慮して，これから
↓
これに変更になったのでタグの場所を移動させました。
> change tag position

- src/client/js/components/Sidebar/RecentChanges.jsx
- src/client/styles/scss/theme/_apply-colors.scss
> change font color

- packages/slackbot-proxy/src/controllers/slack.ts
- packages/slackbot-proxy/src/views/top.ejs
slack からの review を修正すること
- 修正内容
> Could you please add some information to your landing page regarding the steps required to configure the GROWI Slack app e.g how to get a GROWI domain, how to get required access tokens etc.
おおよその意味
GROWI Slackアプリの設定に必要な手順について、ランディングページに情報を追加していただけないでしょうか（GROWIドメインの取得方法、必要なアクセストークンの取得方法など）。
- slack.ts （controllers の handleCallback） に docs の link を追加
- top.ejs に docs の link を追加
> Imprv/slack app review for adding info in lp(add links)

- packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
Textlint有効/無効の際にCodeMirrorに渡す引数を整理しました。
それに伴い、Gutterも有効/無効で表示/非表示が切り替わるようになりました。
無効の際
有効
> Lintが有効/無効のロジックを追加

- src/client/js/components/Sidebar/RecentChanges.jsx
- src/client/styles/scss/_recent-changes.scss
footstampを含め下1行の横並びを綺麗にしました。
親要素からはみ出さないようにspan → div
上下の距離感がまだ少し違ったので一緒に修正しました
> aligned in a line

- packages/app/src/components/Admin/SlackIntegration/SlackIntegration.jsx
- packages/app/src/server/routes/apiv3/slack-integration-settings.js
- packages/app/src/server/service/config-loader.ts
without-proxy でもチャンネルごとに権限設定を行うために、権限情報を config-loader に保持するようにしました。
JSON.stringify で string 化し、フロントで parse する予定です。
> Feat:create permission in withoutproxy

- packages/slackbot-proxy/src/services/RelationsService.ts
- https://github.com/weseek/growi/pull/4251 の PR で指摘された内容を修正しました。
> これって後続タスク？
第一引数が relation: Relation のメソッドがどこかにないといけない。
- relations でまとめて処理するのではなく relation に対して行う method を作成しました。
> Imprv:create one relation method

- packages/app/src/components/PagePathHierarchicalLink.jsx
タイトルが長い場合に 鍵アイコンがタイトルの右ではなく下にずれてしまうのを修正
> remove inline-block

- packages/app/src/components/Admin/AdminHome/AdminHome.jsx
- copy prefilled host informationの挙動を画像のように修正
- Copied to clipboard! は、0.5秒後に消えます
- then submit your issue to Github の余白の取りかたがスペース文字で行われていて変だと思ったため、marginに変更
> modify-copy-prefilled-hots-info-btn-effect

- packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
- packages/app/src/components/PageEditor/Editor.jsx
[GW-7420 Editor SettingsでOFFにした設定がLintに適用されてないのを修正する](https://youtrack.weseek.co.jp/issue/GW-7420
)
各LintルールをON/OFFしても反映されず、時にはすべてのルールが有効になってしまうことがある
`retrieveEditorSettings()`を呼ぶ前にTextlintの設定を生成(`createValidator()`)されることがあるため
(親であるEditor.jsxと子であるCodeMirrorEditor.jsxのレンダーの順番によってステートが最新でないことがあるため)
対応箇所: https://github.com/weseek/growi/pull/4268#discussion_r703423743
CodeMirrorEditor.jsxにある`initializeTextlint()`をcomponentDidMountに移し、親であるEditor.jsxのcomponentWillMountにある`retrieveEditorSettings()`より後に呼び出されるようにする
- 治らず
`initializeTextlint()`内でawaitで呼ぶようにし、必ず最新の情報を取ってきてから`createValidator()`するようにした
> GW-7420 Editor SettingsでOFFにした設定がLintに適用されてないのを修正する

- packages/app/src/server/util/slack-integration.ts
- packages/slack/src/utils/get-supported-growi-actions-regexps.ts
- packages/slackbot-proxy/src/services/RelationsService.ts
以下を slack package の util のものを使うように改修しました。
```const commandRegExp = new RegExp(`(^${tempCommandName}$)|(^${tempCommandName}:\\w+)`);```
> imprv: get supported growi actions reg exps

- packages/slackbot-proxy/src/controllers/growi-to-slack.ts
**GW-7411 [Bot](app) bot が private channel に入っていない場合、bot を join させる旨の toastr を出す**
**GW-7377 [エラー回り改修] Proxy から GROWI のレスポンスで WebclientError の 'not_in_channel' などのエラーコードを取得できる**
- `slack_webapi_platform_error`などのerror typeではなく`channel_not_found`などのエラー名を返すようにしました。
- 後続タスクでToastrを表示させるときに使用します。
> imprv: Send error name instead of error type

- packages/app/src/server/service/slack-command-handler/search.js
[**GW-7463 [Bug][Bot]/growi searchでヒットしなかった場合にundefined/NaNと出る**](https://youtrack.weseek.co.jp/agiles/84-39/current?issue=GW-7463)
[**修正**](https://youtrack.weseek.co.jp/agiles/84-39/current?issue=GW-7464)
- `/growi search`コマンド実行時に検索結果が0の場合、Undefined/NaN等の応答が帰ってくるBugを修正
- 原因: `handleCommand`が`retrieveSearchResults`呼び出し、検索結果が0のときに`retrieveSearchResults`がpostEphemeralをしたにも関わらず、returnをしていないため`handleCommand`の方でもpostEphemeralをしてしまう
> fix: Response when no pages are found /growi search

- packages/app/resource/locales/en_US/admin/admin.json
- packages/app/resource/locales/ja_JP/admin/admin.json
- packages/app/resource/locales/zh_CN/admin/admin.json
- packages/app/src/client/services/AdminCustomizeContainer.js
- packages/app/src/components/Admin/Customize/CustomizeFunctionSetting.jsx
- packages/app/src/components/Navbar/GlobalSearch.jsx
- packages/app/src/server/models/config.ts
- packages/app/src/server/routes/apiv3/customize-setting.js
#4331 の提案実装です。
`isAllReplyShown`が性格的に近いかと思い、参考にしながら実装してみました。  
[開発環境構築手順](https://docs.growi.org/ja/dev/startup-v2/launch-system.html#%E5%88%9D%E5%9B%9E%E8%B5%B7%E5%8B%95)を参考に「フロントエンド・バックエンドサーバーの起動」を実施しての動作確認は実施しています。
Web開発・GitHubともに不慣れですので不足している部分がありましたらご指摘ください。（Pullが難しいようでしたらCloseしていただいても構いません）
> feat: Switching the global search scope

- packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
> fix: Backspace key on last line doesn't work in vim mode

- packages/app/src/components/SearchPage.jsx
- packages/app/src/components/SearchPage/SearchResult.jsx
- packages/app/src/styles/_search.scss
- XDに合わせて、ページを分割させました。
- 左右に跨るサーチバーを一旦コメントアウトしました。
Before
After
> Modify layout for new search page

- packages/app/package.json
- yarn.lock
Update passport-saml 2.2.0 (latest update 24 Apr 2021)
- Tested with keycloak
- Configuration based on https://qiita.com/sahya/items/d8ad66aadcf587c6f0a3
- Checked passport-saml v1 OK
- Checked passport-saml v3.1.2 OK
- eslint --quiet "**/*.{js,jsx,ts,tsx}" PASSED
> chore: Update passport-saml 2.2.0

- packages/app/src/server/service/search-delegator/elasticsearch.js
elasticsearch 側で highlight,snippet の設定をし、Highlight を含む snippet の取得をしています。
hoge の検索結果
```
GET /_api/v3/pages/recent 304 137.889 ms - -
{
'body.en': [
'航空機売込みに絡んだ贈収賄事件（ロッキード事件）で逮捕収監され、<em>hoge</em>',
'小学校卒業まで\n新潟県刈羽郡二田村大字坂田（現：柏崎市）に父・<em>hoge</em>',
'しかし、<em>hoge</em>の中央工学校は専門学校として東京都から認可を受'
],
'body.ja': [
'航空機売込みに絡んだ贈収賄事件（ロッキード事件）で逮捕収監され、<em>hoge</em>',
'などに強い影響力を持ち、政治家による官僚統制の象徴、族議員の<em>hoge</em>',
'1972年8月7日の駐日<em>hoge</em>大使から本国への機密の報告書には',
'小学校卒業まで\n新潟県刈羽郡二田村大字坂田（現：柏崎市）に父・<em>hoge</em>',
'しかし、<em>hoge</em>の中央工学校は専門学校として東京都から認可を受'
]
} 
```
body が en と ja に分かれているため、body.en と body.ja で引っかかります。
調査したところ句読点やスペースの次に hoge がきた場合 body.en で検知されるようです。
こちらの対策は、 重複する内容を排除して本体に返すことを考えています。
また、path に hoge が含まれる場合 path.en と path.ja 双方に検索結果が引っかかっります。こちらはいずれか一方を取得しようと考えています。
```
highlight: {
'path.en': [ …
```
> feat: create snippet

- packages/app/src/components/Sidebar/RecentChanges.jsx
「最新の変更」サイドバーにあるS/L切り替えボタンについて、変更がlocalStorageに反映されておらずリロードのたびにデフォルト（L）に戻ってしまっていました。
localStorageへの保存を伴うハンドラーがchangeSizeHandlerとして既に用意されていたのでそちらを使うようにしたところ期待する動作となりました。  
→ 意図・懸念があって元コードの状態にしているようでしたらすみません（ご指摘ください）。
* localStorageを消去してページをリロードする
* 「L」の状態で表示、OK
* 「S」に変更してページをリロードする
* 「S」の状態で表示、OK
* 再度「L」に変更してページをリロードする
* 「L」の状態で表示、OK
> fix: SidebarSmall button does not keep selection on reload

- packages/app/src/components/Admin/Security/SamlSecuritySettingContents.jsx
「セキュリティ設定」のSAML設定に関して、セットアップが完了して動作している状態でも「セットアップはまだ完了してません」のアラートが表示されている状況になっています。  
当初は「動いているけど設定は不完全なのだろう」と考えていたのですが、コードを確認していたところLDAPのセットアップ完了を誤ってチェックしているようでした。
本変更を実施して、仮の設定値を埋めてセットアップしたところ、アラートが表示されなくなることを確認できました。
> fix: SAML setting says 'setup is not yet complete' even if setup properly

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/SearchPage/DeleteAllButton.jsx
- packages/app/src/components/SearchPage/IncludeSpecificPathButton.jsx
- packages/app/src/components/SearchPage/SearchResult.jsx
- packages/app/src/styles/_search.scss
見た目:
xd: https://xd.adobe.com/view/cd3cb2f8-625d-4a6b-b6e4-917f75c675c5-986f/screen/dad28d9f-d727-45e4-9853-bdcb9c083914/specs/
77543 storyで実際にdeleteの部分は実装します。まだ、どう実装されるかわかってないので一旦chekedはIncludeSpecificPathButton同様外からprops渡すようにしました。
> GW 77739 add deleteAllButton component

- packages/app/resource/search/mappings.json
- packages/app/src/server/events/page.js
- packages/app/src/server/models/page.js
- packages/app/src/server/routes/page.js
- packages/app/src/server/service/page.js
- packages/app/src/server/service/search-delegator/elasticsearch.js
- packages/app/src/server/service/search.js
- 検索した時に、elasticsearch から seenUsers を取得することができる
- 検索時
elasticsearch.js の search メソッド  の result に seenUsers が含まれることを確認
```
[
{
...
_source: {
comment_count: 0,
path: '/Sandbox/Math',
updated_at: '2021-09-27T23:22:13.237Z',
seenUsers_count: 1,
bookmark_count: 1
},
highlight: {
'path.en': [Array],
...
}
},
{
...
_source: {
comment_count: 0,
path: '/Sandbox',
updated_at: '2021-09-27T23:22:13.228Z',
seenUsers_count: 1,
bookmark_count: 0
},
...
```
> Feat: 77797 get seen users

- packages/app/src/server/crowi/index.js
- packages/app/src/server/events/activity.ts
- packages/app/src/server/models/activity.ts
- packages/app/src/server/models/comment.js
- packages/app/src/server/models/in-app-notification.ts
- packages/app/src/server/models/page.js
- packages/app/src/server/models/revision.js
- packages/app/src/server/service/activity.ts
- packages/app/src/server/service/comment.ts
- packages/app/src/server/service/in-app-notification.ts
Activity のデータが作られる時に同時に InAppNotification を生成 OR 更新 するようにしました。
- export 方法変えた時にネストが一段深くなったのでコード変更量が多くなってしまいました
- モデル層のリファクタ & 不要なコードの精査・削除は後続の 77970 で最後の方でやります
- InAppNotification の取り扱いについては一旦 crowi の仕様と合わせました
- 7日単位で一つの InAppNotification に activity を溜め込んでいく
- InAppNotification の対象ユーザーは、対象オブジェクト(今はPageのみ)に編集 or コメントしたユーザーかつ Activity のもととなる actionUser でも ignoreUser でもないユーザー
> imprv: Save in-app-notification when an activity is created

- packages/app/src/server/service/activity.ts
- packages/app/src/server/service/comment.ts
[#78067 コメントが単体で削除された時に、そのActivityの削除を行わないようにする](https://estoc.weseek.co.jp/redmine/issues/78067)
> remain activity even if comment deleted

- packages/app/src/server/routes/login-passport.js
SAMLログインのABLC（Attribute-based login control）ルールを設定した状態で有効化しているとき、ABLCルールにマッチしないユーザーがログインを試みるとログインは失敗するものの新規ユーザーが作成されます。
`loginPassportSamlCallback `内の処理において、ABLCルールのチェックタイミングを`getOrCreateUser`の前に移動します。
Azure AD IdPにて下記を確認しました。
* ABLCルールにマッチするユーザーのログイン → ログイン成功・ユーザー作成される：OK
* ABLCルールにマッチしないユーザーのログイン → ログイン失敗・ユーザー作成されない：OK
* ABLCルール未設定 → ログイン成功・ユーザー作成される：OK
> fix: New user is created on SAML login even if attribute-based login control failure

- packages/app/src/migrations/20210906194521-slack-app-integration-set-default-value.js
- packages/app/src/migrations/20210913153942-migrate-slack-app-integration-schema.js
- packages/app/src/migrations/20211005120030-slack-app-integration-rename-keys.js
- packages/app/src/migrations/20211005131430-config-without-proxy-command-permission-for-renaming.js
```
想定１(現在の master)
SlackAppIntegration
{
permissionsForSingleUseCommands: {
create: true,
togetter: ['srv', 'admin']
},
permissionsForBroadcastUseCommands: {
search: true,
},
}
想定２
SlackAppIntegration
{
permissionsForSingleUseCommands: {
note: true,
keep: ['srv', 'admin']
},
permissionsForBroadcastUseCommands: {
search: true,
},
}
```
想定１<=>想定２ のマイグレーションを実装しました。
Config の key: 'slackbot:withoutProxy:commandPermission' の value に create togetter があれば改名
- 元々あった togetter 用のマイグレーションは元に戻しました
- その他 logger の namespace を修正しました
- Proxy 側でもマイグレーション欲しいと思うのでそれをやります
> Migration for renaming

- packages/app/src/client/services/AdminAppContainer.js
- packages/app/src/components/Admin/App/V5PageMigration.tsx
- packages/app/src/server/models/page.js
- packages/app/src/server/routes/apiv3/pages.js
- packages/app/src/server/service/page.js
Redmine: https://estoc.weseek.co.jp/redmine/issues/80257
マイグレーション完了後にユニーク制約を取り除く処理を実装しました
Page スキーマの以下の部分についての動作確認は Page.create の改修後の方が楽なのでそのタスクの時におこないます
```typescript
// TODO: test this after modifying Page.create
// ensure v4 compatibility using partial index
pageSchema.index({ path: 1 }, { unique: true, partialFilterExpression: { parent: null } });
```
> feat: page migration remove unique constraint

- packages/app/src/components/PageEditor/DrawioModal.jsx
#4586 の改修案です。
#3643 を参考にbackdrop="static"を適用しました。
draw.ioの編集ダイアログにてダイアログ外のクリックを実施し、閉じなくなった（表編集ダイアログと同じ挙動になった）ことを確認しています。
> fix: draw.io editor dialog is closed by backdrop clicked

- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/models/page.ts
- packages/app/src/server/routes/index.js
- packages/app/src/server/routes/page.js
Redmine(２つ): https://estoc.weseek.co.jp/redmine/issues/80349, https://estoc.weseek.co.jp/redmine/issues/80350
パス付きリンクとパーマリンクを入れ替えました。
1. `redirectTo` が `/A` であるページ `/B` にアクセス
2. `res.redirect('/A?redirectFrom=/B');`
3. `/A` からページ探す
- １つしかない場合 => `'/Aのid?redirectFrom=/B'` にリダイレクト
- ２つ以上ある場合 => `redirectFrom = /B` を `renderVars` に入れた上でページ遷移先選択ページを render (後続で実装)
- 選択した遷移先 URL に `?redirectFrom=` を添加
- ない場合 => `page.notFound` の挙動
`pageSchema.statics.findByPathAndViewer` は path がユニーク前提で findOne していたので、一旦新規に `findByPathAndViewerV5` を追加して find するようにしました
- 複数のページが見つかった時に遷移先選択ページをレンダーするようにします。(UI はほぼ白紙)
- `findByPathAndViewer` が使われているところが正常に動くように改修して、最終的に `findByPathAndViewerV5` を `findByPathAndViewer` にマージします
- duplicate や移動などの時にやる必要があると思う
> feat: Switch pathlink and permalink

- packages/app/src/components/InAppNotification/InAppNotification.tsx
- packages/app/src/components/InAppNotification/InAppNotificationList.tsx
- packages/app/src/components/InAppNotification/NotificationContent.tsx
- packages/app/src/interfaces/has-object-id.ts
- packages/app/src/server/routes/apiv3/in-app-notification.ts
- packages/app/src/server/service/in-app-notification.ts
- [#80940](https://estoc.weseek.co.jp/redmine/issues/80940) 通知をクリックしたときに、apiを叩いて既読にすることができる
※マージ先間違っていたので作り直し(元のPR -> https://github.com/weseek/growi/pull/4628)
> change notification status OPEND

- packages/app/src/client/services/PageContainer.js
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemNode.ts
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- packages/app/src/components/Sidebar/SidebarContents.jsx
- packages/app/src/interfaces/has-object-id.ts
- packages/app/src/interfaces/page-listing-results.ts
- packages/app/src/interfaces/page.ts
- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/models/page.ts
- packages/app/src/server/routes/apiv3/page-listing.ts
- packages/app/src/server/routes/page.js
- packages/app/src/server/views/widget/page_content.html
- packages/app/src/stores/context.tsx
- packages/app/src/stores/page-listing.tsx
- packages/app/src/stores/use-static-swr.tsx
Redmine: https://estoc.weseek.co.jp/redmine/issues/80791
- isPartialChildren は不要になったので削除しました
- １回目の SWR で ancestors のみを取得していたのを target と ancestors 両方を取得するように書き換えました
- ２回目の SWR で target 以外の node の children をサーバーから取得し、各 node を更新してからレンダリングするようにしました
- ancestors-children API はハリボテです
- 正しく動けば計３回 ItemsTree がレンダリングされるようになっています (null, target & ancestors, target & ancestors & ancestors-children)
- ancestors-children API を実装します
- ItemsTree コンポーネントに props で path と id を渡すようにします
> feat: Pt fetch initial data (client)

- packages/app/src/server/routes/tag.js
https://estoc.weseek.co.jp/redmine/issues/80986
- タグの count が同じものがページネーションしたときにランダムな順番で戻ってきてしまう問題の修正
**↓を解消**
- 修正前の挙動(1ページ目を表示しているが、タグリストの並び順がクリックのたびに変わってしまう)
https://user-images.githubusercontent.com/83065937/141060300-9b0f000f-df54-42f2-9466-4a8ae89a5cd1.mov
> feat: add id sort field

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/server/routes/index.js
- packages/app/src/server/routes/user-activation.ts
https://youtrack.weseek.co.jp/issue/GW-7568
- Add incorrect_token_or_expired_url translation en_US, ja_JP, zh_CN
- Change redirection to /login#register instead of render forgot-password-error view
- Fix lint errors 'Cant find method' for flash and t methods
> Fix email auth error page [7568]

- packages/app/src/components/InAppNotification/InAppNotificationDropdown.tsx
- [81245](https://estoc.weseek.co.jp/redmine/issues/81245) ベルマークを押したときに/listのapiが叩かれていないのを修正
dropdown buttonが isOpenの時に、`mutate()` でdataを再取得するようにしました。
> hit in-app-notification api with mutate

- packages/app/src/client/app.jsx
- packages/app/src/stores/context.tsx
Redmine: https://redmine.weseek.co.jp/issues/81481
```
Warning: Cannot update a component (`SidebarNav`) while rendering a different component (`ContextExtractor`). To locate the bad setState() call inside `ContextExtractor`, follow the stack trace as described in https://fb.me/setstate-in-render
```
このエラーを解消しました
ContextExtractor の render のコールバックにその他のコンポーネントの render を入れました。
> Extract context before rendering other components

- packages/app/package.json
- packages/app/src/components/InAppNotification/InAppNotificationList.tsx
- packages/app/src/interfaces/in-app-notification.ts
- packages/app/src/server/models/in-app-notification-settings.ts
- packages/app/src/server/models/in-app-notification.ts
- packages/app/src/server/service/in-app-notification.ts
- packages/app/src/stores/in-app-notification.ts
- yarn.lock
- [#81697](https://redmine.weseek.co.jp/issues/81697) マスターからトピックブランチのマージによるmongoose-paginate関連のエラー調査 / 修正
> remove @types/mongoose-paginate-v2 to avoid typescript errors

- packages/app/src/server/service/search-delegator/elasticsearch.js
- [#80702](https://redmine.weseek.co.jp/issues/80702) 検索結果のresultsにコメントを含むことができる
- 検索した時に、コメントも検索結果のresultsに含まれるようにしました。
- 「検索結果でのコメントの**表示**」は、検索結果画面改修の方でスコープに入るので、ここでは触れていません。
「インデックスのリビルド」も検証済み。元々あるコメントもリビルドすれば、検索対象に入ることを確認してあります。
順番は以下の通りです。
1. リビルドインデックスしようとすると、以下のようなトーストエラーが出るのと、「インデックスの状態」が「破損」のラベルになる。
2.  インデックスの正規化
3.  再度「インデックスのリビルド」を行いました。
https://user-images.githubusercontent.com/59536731/142247895-68f5c942-e491-4bc7-a24b-bab93116f5b6.mov
> get search results including comments

- packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
- packages/app/src/server/service/page.js
- packages/app/src/server/util/activityDefine.ts
- [#81700](https://redmine.weseek.co.jp/issues/81700) ページをリネームしたときにイベントを受け取れるようにする
- [#81679](https://redmine.weseek.co.jp/issues/81679) ページ名が変更されたときにに Activityドキュメント, Notificationドキュメントを作成し、socket.Io を通じてフロント側で通知を受け取ることができる
通知のドロップダウンのアイコンは、`移動/名前変更` に使われている `icon-action-redo` を利用しました。
> feat: 81679 81700 create notification when page is renamed

- packages/app/src/components/SearchPage/SearchPageLayout.tsx
- packages/app/src/server/views/search.html
[#81762](https://redmine.weseek.co.jp/issues/81762)
※変なborder等は別タスク対応
Before
After
> 81762 replace grid with flex

- packages/app/src/client/app.jsx
- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/routes/apiv3/pages.js
- packages/app/src/server/routes/index.js
- packages/app/src/server/routes/page.js
Redmine: https://redmine.weseek.co.jp/issues/81693
Empty ページを編集できるようにしました。
notFound と Page.create を改修して、isEmpty: true のページが存在した場合は create の代わりに update するようにしました。
UI/UX 上は notFound と全く同じ挙動になるように実装しました。
- app.jsx で ContextExtractor が null のときに対応しました (Context Extractor を移動するので必要なくなります)
> feat: Enable to edit empty pages

- packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
- [#81863](https://redmine.weseek.co.jp/issues/81863) UNOPENDの印によってズレた通知一覧の表示を整える
- [#4690](https://github.com/weseek/growi/pull/4690#issuecomment-971498133)
ドロップダウン内のボタンが楕円になってしまう問題はどのように修正すればいいかまだわかっていませんが、ここで時間かけすぎるのも良くないと判断したので、別のタスクを優先させることにします。
> improve: notification view

- packages/app/resource/locales/en_US/admin/admin.json
- packages/app/resource/locales/ja_JP/admin/admin.json
- packages/app/resource/locales/zh_CN/admin/admin.json
- packages/app/src/server/routes/apiv3/slack-integration.js
- packages/app/src/server/util/slack-integration.ts
- packages/slack/src/index.ts
- packages/slack/src/interfaces/channel.ts
- packages/slack/src/utils/interaction-payload-accessor.ts
- packages/slackbot-proxy/src/controllers/slack.ts
- packages/slackbot-proxy/src/services/RelationsService.ts
- packages/slackbot-proxy/src/services/SelectGrowiService.ts
https://redmine.weseek.co.jp/issues/81429
Private channelからのinteractionsはchannel_nameが一律で"privategroup"になっていたため、interactionsが失敗していました。
channel_nameだけでなく、channel_idでも判別できるようにしました。
> fix: Interactions from private channels not working

- packages/app/resource/locales/en_US/admin/admin.json
- packages/app/resource/locales/ja_JP/admin/admin.json
- packages/app/resource/locales/zh_CN/admin/admin.json
- packages/app/src/server/service/slack-event-handler/link-shared.ts
- packages/app/src/server/service/slack-integration.ts
Redmine: https://redmine.weseek.co.jp/issues/82042
Unfurl の権限を channelId のみに対応して修正しました
それに伴って admin 画面の文言も修正しました
> fix: Unfurl permission

- packages/app/src/components/InAppNotification/InAppNotificationPage.tsx
- packages/app/src/server/routes/apiv3/in-app-notification.ts
- packages/app/src/server/service/in-app-notification.ts
- [#81907](https://redmine.weseek.co.jp/issues/81907) 全て既読にする用のエンドポイントを追加する
- [#81951](https://redmine.weseek.co.jp/issues/81951) 「全て既読にする」ボタンを押すと、通知のステータスがOPENDになり、未読のカテゴリーに表示されなくなるようにする
- 「全て既読にする」ボタンを押すと `UNOPENED` の通知が `OPENED`に更新されるようにしました。
(現状、ドロップダウンアイコンを押すと、全ての通知のステータスは`UNREAD` -> `UNOPENED`になります。)
- TODO
- 「全て既読にする」ボタンを押した後に、「全て」のカテゴリーに移動すると、ステータスが反映されていません。
- (リロードすると反映されます。)
- これは、後続タスクの[#81953「全て」「未読」カテゴリー内部のリストを共通化させる](https://redmine.weseek.co.jp/issues/81953)にて、修正予定です。
https://user-images.githubusercontent.com/59536731/143210757-a6ebabcf-9518-43f5-b707-2b0e92c12608.mov
> Imprv/81907 update notification statuses by clicking on the "mark as read" button

- packages/app/src/server/interfaces/search.ts
- packages/app/src/server/service/search-delegator/elasticsearch.ts
- packages/app/src/server/service/search.ts
- packages/app/src/test/integration/service/search/search-service.test.js
Redmine: https://redmine.weseek.co.jp/issues/80342
検索クエリの Parser と Resolver を実装しました。
それぞれのテストも書きました。
引き続き CI の lint 以外の警告は無視で大丈夫です。今回書いたテストはローカルで Pass しています
行数多いですが、処理の移動とテストを書いたためです。
- parse と resolve を実行している searchKeyword メソッド
- SearchDelegator が持つ delegator の初期化 & テスト
- PrivateLegacyPages 用 delegator の実装 ＆ テスト
> feat: Implement search query parser and resolver

- packages/app/src/server/util/slack-integration.ts
- packages/slack/src/index.ts
- packages/slack/src/utils/permission-parser.ts
- packages/slackbot-proxy/src/controllers/slack.ts
- packages/slackbot-proxy/src/services/RelationsService.ts
- [**82301:【GROWI】【Slackbot】許可されていないページに向けてスラッシュコマンドを実行するとInternal Server Errorが表示される**](https://redmine.weseek.co.jp/issues/82301)
- [**82302: 調査**](https://redmine.weseek.co.jp/issues/82302)
- [**82327: Fix**](https://redmine.weseek.co.jp/issues/82327)
- [**81007: [Slackbot] チャンネルによるアクセス制御を行っている場合に interaction が動作しない問題を解消する**](https://redmine.weseek.co.jp/issues/81007)
- [**82181: 権限機能のBooleanを返すfunctionをutility化**](https://redmine.weseek.co.jp/issues/82181)
- 権限をbooleanで返すはずのファンクションがarray<string>を返していたため、スラッシュコマンドを実行したときに正しいレスポンスを返していなかったバグを修正
- booleanを返すfunctionをutility化
> fix(Slackbot): Slash commands response when sent from disabled channels

- packages/app/src/server/service/slack-event-handler/link-shared.ts
Redmine: https://redmine.weseek.co.jp/issues/82345
unfurl したときに GROWI の siteUrl を表示するように改善しました
> imprv: Show site url in unfurl footer

- packages/app/src/components/InAppNotification/InAppNotificationElm.tsx
[#82492](https://redmine.weseek.co.jp/issues/82492) [client] ページを完全に削除したときに受信する通知をクリックしてもページを遷移させないようにする
81946 ストーリー用のブランチを feat/notification から作成しました。
> feat: 82492 prevent transitions to pages that have been completely deleted

- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/routes/apiv3/pages.js
- packages/app/src/server/service/page.js
- packages/app/src/test/integration/service/page.test.js
Redmine: https://redmine.weseek.co.jp/issues/81980
pageId の配列からページをマイグレーションする処理を実装しました
- [filter になる部分](https://github.com/weseek/growi/compare/feat/migrate-initial-named-queries...feat/migrate-private-legacy-pages?expand=1#diff-54e9932d0d509507eff4b4551f57d5ad48472e94bbc618727db0858c3bb51bffR876-R893)をリファクタしました
- テストも書きました
- パブリックページのマイグレーションと同じく socket でユーザーに進行状況を伝えられるようにします
> feat: Migrate private legacy pages

- packages/app/src/client/admin.jsx
- Bug fix: [#81899](https://redmine.weseek.co.jp/issues/81899)【GROWI】【通知機能】Admin ページ遷移するとエラーが出る
- [#81971](https://redmine.weseek.co.jp/issues/81971) 修正（並行）
`socketIoContainer` が、adminの`<Provider inject={injectableContainers}>`の`injectableContainers`に含まれていなかったことにより、管理画面でエラーが生じていたので、含めるようにしました。
ナビバー上のベルアイコン(InAppNotificationDropdown)にて、`socketIoContainer` が使用されています
```
SocketIoContainer.js?4cf4:19 Uncaught TypeError: Cannot read properties of undefined (reading 'registerContainer')
at new SocketIoContainer (SocketIoContainer.js?4cf4:19)
at eval (unstated.es.js?75c5:128)
at Array.map (<anonymous>)
at Subscribe._createInstances (unstated.es.js?75c5:119)
at eval (unstated.es.js?75c5:150)
at Consumer.render (index.js?9c24:133)
at finishClassComponent (VM21976 react-dom.development.js:17160)
at …
```
> inject socketIoContainer instance into admin injectableContainers

- packages/app/package.json
- packages/app/src/server/routes/avoid-session-routes.js
- yarn.lock
- upgrade passport version from v0.4.0 to v0.5.0
- exclude _hackmd from routes that don't use session
> imprv: upgrade passport from v0.4.x to v0.5.x

- packages/app/src/client/services/PageContainer.js
- packages/app/src/components/PageEditor/ConflictDiffModal.tsx
- packages/app/src/components/SavePageControls.jsx
- packages/app/src/server/routes/page.js
https://redmine.weseek.co.jp/issues/82378
socket.io がなんらかの理由で動かなった際に、ユーザーが page 更新を行い revision is outdated と toaster が出現した際に、サーバーサイドから latest の revision 情報をフロントに戻して、PageStatusAlert.jsx でコンフリクト解消を出現させるようにしました。
> feat: retrieve data from server side on conflict

- packages/app/src/components/PageEditor/ConflictDiffModal.tsx
https://redmine.weseek.co.jp/issues/82795
差分が出ている個所の条件分岐を pageContainer の state ではなくて、すでに渡していた props に修正。
> imprv: change state to props on jsx confitional branch

- packages/app/resource/locales/en_US/translation.json
- packages/app/src/components/PageEditor/ConflictDiffModal.tsx
https://redmine.weseek.co.jp/issues/82792
- 英語表示の revision の表示される名前を変更
- コード側の変数名は変更しないほうが開発者的に分かりやすいと思ったため、修正していません
以下のように変更しました。
- requested page body → mine
- origin page body → origin
- latest page body → theirs
> imprv: change displayed revision name

- packages/app/src/server/routes/page.js
https://redmine.weseek.co.jp/issues/82836
edit モードで、ページに tag をつけて update したときに tag が検索結果にひっかからないバグ修正のもれを修正
> feat: add tagevent to page route to fix not to show search result

- packages/app/src/server/service/slack-command-handler/search.js
- packages/app/src/server/service/slack-event-handler/link-shared.ts
- packages/slack/src/index.ts
- packages/slack/src/utils/generate-last-update-markdown.ts
- packages/slack/src/utils/required-scopes.ts
Redmine: https://redmine.weseek.co.jp/issues/83099
```
'links:read'
'links:write'
```
この二つを追加しました
ついでに unfurl のフッターも改善しました (search の share に揃えました)
> fix: Added scope for unfurl

- packages/app/src/components/BookmarkButton.jsx
- packages/app/src/styles/_subnav.scss
https://redmine.weseek.co.jp/issues/83038
before (bookmark の font-sizeと位置が変)
after
> 80374 adjust bookmark design

- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/SearchPage/SearchResultListItem.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- packages/app/src/interfaces/page.ts
- packages/app/src/stores/page.tsx
Redmine: https://redmine.weseek.co.jp/issues/81437
検索の dropdown を切り離して Common に移動しました
ページツリーでも同じものを使いました
- Page 用の interface を IPageHasId に統一しました
- deleteModal 表示
> feat: Show dropdown

- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/models/page.ts
Redmine: https://redmine.weseek.co.jp/issues/83059
ページ取得時に以下の条件をつけ忘れていたのでつけました
```
$or: [
{ parent: { $ne: null } },
{ path: '/' },
],
```
> imprv: Add condition when find pages for rendering pagetree

- packages/app/src/client/services/ContextExtractor.tsx
- packages/app/src/components/Sidebar/PageTree.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- packages/app/src/interfaces/page-listing-results.ts
- packages/app/src/server/models/page.ts
- packages/app/src/server/routes/apiv3/page-listing.ts
- packages/app/src/stores/context.tsx
- packages/app/src/stores/page-listing.tsx
Redmine: https://redmine.weseek.co.jp/issues/83061
ページツリーをレンダリングする際、Page の情報がないページではルートページがターゲットになるようにしました
rootPage を別で持ってくる必要があったのでそれ用の swr を追加で実装しました
- 将来的に Modal の中でも ItemsTree.tsx, Item.tsx が使えるように Props を見直してリファクタしました
> imprv: Normalize pt rendering condition

- packages/app/src/styles/_layout.scss
Redmine: https://redmine.weseek.co.jp/issues/83285
Mac, iOS でラバーバンドスクロールを無効化しました
> imprv: Disable rubber band scroll for Mac & iOS users

- packages/app/src/components/SearchPage/SearchResultListItem.tsx
- packages/app/src/interfaces/search.ts
- packages/app/src/server/service/search.ts
旧PR: https://github.com/weseek/growi/pull/4779
task : https://redmine.weseek.co.jp/issues/82533 
dev5.0 mergeしたら少し形変わってたので、しんブランチ切って対応した方がスムーズだと思い新しくブランチ切りました。
対応内容としては
- isHtmlInPathをsearchの結果に追加
- タイトルでもハイライトが表示されるようにする。
このPRがまーじされたら旧PRを閉じます。
> 82533 add isHtmlInPath to esResult

- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- packages/app/src/server/models/page.ts
Redmine: https://redmine.weseek.co.jp/issues/83272
- マイグレートされていないページがターゲットのページの祖先に存在する際にレンダリングでエラーが発生するのを修正しました
- サーバーでそもそもマイグレートされていないページが発見された時にそれ以降の祖先のデータは返さないようにしました
- ソートに関する処理も全てサーバー側に移行しました
> fix: Stop rendering non migrated pages

- yarn.lock
https://youtrack.weseek.co.jp/issue/GW-7587
My step to make decision:
- Read and implement solution from dependabot alert page
- Remove yarn.lock then rebuild to get new yarn.lock
- Trace and collect `set-value` update from new yarn.lock, save the `set-value` update to yarn.lock.tmp
- Revert / reset yarn.lock, compare original yarn.lock with yarn.lock.tmp
Result:
- Remove set-value@^0.4.3 because there is another set-value version (v2)
- Adjust set-value version to 2.0.1
- Adjust union-value version from 1.0.0 to 1.0.1
- Adjust set-value version parameter on union-value
> fix: dependabot alert set-value

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/styles/_override-bootstrap-variables.scss
- packages/app/src/styles/theme/_apply-colors-dark.scss
- packages/app/src/styles/theme/_apply-colors-light.scss
- packages/app/src/styles/theme/_reboot-bootstrap-text.scss
- [#83046](https://redmine.weseek.co.jp/issues/83046) Empty ページだとわかるようなスタイルを当てる(XD を参考に)
> apply secondary color to empty page path

- packages/app/src/styles/_page-tree.scss
- [#83431](https://redmine.weseek.co.jp/issues/83431) ページの文字色をXDのように修正
> fix page tree path color

- packages/app/src/client/services/PageContainer.js
- packages/app/src/components/Page/TagLabels.jsx
- packages/app/src/server/service/page.js
https://redmine.weseek.co.jp/issues/83278
https://redmine.weseek.co.jp/issues/82980
- page に tag を付けた際に、 revision が outdated となり、ページ更新が行えなくなる挙動を修正
- duplicate した際に、 elasticsearch 側に tag が保存されず、検索にひっかからないバグを修正
- 動作確認
- master へマージ
> fix: fix tag search

- packages/app/src/components/SearchPage/SortControl.tsx
https://redmine.weseek.co.jp/issues/83697
- 文字をXD通りグレーに変更
- ドロップダウン開いた中のアイコンの位置を真ん中に寄せた
before
after
> 83697 83703 fix sort design

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/styles/_page-tree.scss
[#83644](https://redmine.weseek.co.jp/issues/83644) page path title の間隔を狭める
- ページツリーのコンテンツを左側に寄せて、「Page Tree」の左側と合うようにしました。
- 各ページパスの行間を詰めました
> apply margin to Item component not using scss

- packages/app/resource/locales/en_US/admin/admin.json
- packages/app/resource/locales/ja_JP/admin/admin.json
- packages/app/resource/locales/zh_CN/admin/admin.json
- packages/app/src/components/Sidebar/PageTree.tsx
- packages/app/src/interfaces/page-listing-results.ts
- packages/app/src/server/routes/apiv3/pages.js
- packages/app/src/stores/page-listing.tsx
https://redmine.weseek.co.jp/issues/83473
page v5のmigrationが済んでない場合にはpageTreeにメッセージを表示させる。
> feat: 83427 hide page tree if migration is not done yet

- yarn.lock
https://youtrack.weseek.co.jp/issue/GW-7595
- Consolidate all ini v1.x to use v1.3.8
> imprv: dependabot alert ini

- yarn.lock
https://youtrack.weseek.co.jp/issue/GW-7596
- Consolidate all kind-of v6.0.x to use v6.0.3
> imprv: dependabot alert kind-of

- packages/app/src/components/PageEditor.jsx
https://redmine.weseek.co.jp/issues/83926
PRから抜けていたPageEditor.jsxのgetCurrentOptionsToSaveのSWR化を追加しました。
> Fix isSlackEnabled not sent with request

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
Redmine(2つ): https://redmine.weseek.co.jp/issues/83807, https://redmine.weseek.co.jp/issues/83808
ページツリーアイテムのレンダリングのバグを修正しました
- isOpen が warning によって正常に伝播されていなかったのを warning 解消によって修正
- isTarget を伝播させるように修正
- renderer が１回のみ走るように改善
> fix: Normalize isOpen isTarget & Run renderer once

- packages/app/src/components/Sidebar/PageTree.tsx
- packages/app/src/styles/_page-tree.scss
- packages/app/src/styles/_variables.scss
- [#82623](https://redmine.weseek.co.jp/issues/82623)待避所リンクの位置を調整する(XD に合わせる)
Legacypages は常に表示させるのではなく、スクロール内部に入れることになりました。
- 待避所がある場合
https://user-images.githubusercontent.com/59536731/146164947-eeded9f9-46cf-478b-a10b-5a3907e57340.mov
- 待避所がない場合
https://user-images.githubusercontent.com/59536731/146164924-d8a2120f-ce4d-4d0e-9708-5f85a0b216f8.mov
> improve legacy private pages position

- packages/app/src/server/models/page.ts
- packages/app/src/server/service/page.js
- packages/app/src/test/integration/service/page.test.js
Redmine: https://redmine.weseek.co.jp/issues/83846
パブリックマイグレーションで全てのパブリックページがページツリーに表示できるように修正しました
- private ページが親になる場合はその部分に Empty ページを生成するようにしました
- テストコードも書きました
- ついでに `(){}[]` を含むパスでのマイグレーションが正常動作するかもテストに含めました
- 一旦 socket に関する記述はコメントアウトしました
- テスト時に socketIoService を初期化する必要がでるため
> imprv: Public migration fill with empty pages over private pages

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/styles/theme/_apply-colors-dark.scss
- packages/app/src/styles/theme/_apply-colors-light.scss
- [#83903](https://redmine.weseek.co.jp/issues/83903) isTarget が true の時、 Item にbgColorがつくようにする
> apply isTarget style

- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/SearchPage/SearchResultListItem.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
Redmine: https://redmine.weseek.co.jp/issues/83810
Empty または Top ページの時の DeleteModal の挙動を修正しました
> fix: Improve delete modal when top page or empty page

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/SearchPage/SearchResultListItem.tsx
https://redmine.weseek.co.jp/issues/83704
story内に記載してあること。
- 3点ボタン自体クリック時のフォーカスの色が違う <- yoheiさんの対応で改善済み
- 検索pageのxd上だと灰色になってるが、mos さんに確認したところここは濃い青でいいとのことです。
- 3点ボタンのアイコンの種類が違う
- 移動・名前変更のアイコンが違う
mosさんにデザインチェックしてもらっていくつか出た内容は後継タスクにしました。
[後継タスク](https://redmine.weseek.co.jp/issues/84033)
> 83704 three dot icon and rename icon

- packages/app/src/components/ExpandOrContractButton.tsx
https://redmine.weseek.co.jp/issues/84113
インターフェースに1つ不要な props を残してしまって、前のタスクが merge されてしまったので削除
> fix: remove one props type

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/styles/_page-tree.scss
[#84051](https://redmine.weseek.co.jp/issues/84051) ページアイテムを、ページリストにする
- 階層に関係なく、bgColorがpage-itemの左端まで適用されることを確認
- ページリストは使用せずに、CSSで実現
> realize a hierarchical structure

- packages/app/src/styles/_search.scss
- packages/app/src/styles/_sidebar.scss
- packages/app/src/styles/_variables.scss
https://redmine.weseek.co.jp/issues/84034
サイドバー内に存在する3つのクラスの高さが100vhで固定だった影響で、上部ナビバーの高さ分だけ下にスクロールできてしまう状態にあった。
検索ページのみ、ナビバーのheightを引いた値をサイドバーの高さに指定し、スクロールできないように変更
左ペインの高さも調節した
> always show navbar

- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/models/page.ts
Redmine: https://redmine.weseek.co.jp/issues/83895
サーバーでページツリーの結果をソートしてから返すように改善しました
> imprv: Sort pagetree items by path

- yarn.lock
https://youtrack.weseek.co.jp/issue/GW-7618
- Rebuild socket.io-parser v3.3.0, resolved by v3.3.2
> fix: dependabot alert socket.io-parser

- packages/app/docker/Dockerfile
- packages/slackbot-proxy/docker/Dockerfile
/app/docker/Dockerfile, /slackbot-proxy/docker/Dockerfile のベースイメージを node:14-slim に下げました
ci エラー: https://github.com/weseek/growi/runs/4578512955?check_suite_focus=true
References:
- https://github.com/nodejs/node-gyp/issues/1599
- https://github.com/nodejs/docker-node/blob/6f740b0ca772e978b44c11d194f369e554c54a14/16/buster-slim/Dockerfile
- https://github.com/weseek/growi/commit/5d2b86a59d5916aac1750cf7665b4376b94709b3
> fix: Downgrade node image for build

- packages/app/src/styles/_page-tree.scss
- [#84226](https://redmine.weseek.co.jp/issues/84226) ３点リーダーのドロップダウンが透けるのを修正する
https://xd.adobe.com/view/cd3cb2f8-625d-4a6b-b6e4-917f75c675c5-986f/screen/27a328ec-c82d-4fd1-b97a-1dc6cb549080/specs/
> fix dropdown background

- packages/app/src/components/PageEditor/ConflictDiffModal.tsx
https://redmine.weseek.co.jp/issues/78641
デザインFBに基づいて軽めのデザイン修正を行いました。
https://app.slack.com/client/T4V7GA7CM/C0111HG81GB/thread/C0111HG81GB-1639639218.378900
- モーダルの範囲外をクリックしたときにモーダルを閉じない設定にしました
- ボタンカラーを primary から outline-primary に変更しました
- 上と下の並びの横幅を揃えました（画像参照）
- 動作確認
- 統合ブランチを master へマージ
> imprv: modify conflict modal design

- packages/app/src/server/routes/apiv3/personal-setting.js
[#84315](https://redmine.weseek.co.jp/issues/84315) CodeQL のテストで出た警告の修正
トピックブランチ（feat/notification）の CodeQL のテストで `Building a database query from user-controlled sources is vulnerable to insertion of malicious code by the user.` という警告が出ていたので修正しました。
> fix: 84315 codeql test

- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
https://redmine.weseek.co.jp/issues/84265
#　内容
dev5を統合にマージしたら、buttonのクリックした時の幅が調整されていたが、84265storyで button内のfont-awesomeからsimple-iconに変えたのでdev5での変更が意図した通りに動いていなかった為の対応タスク。
paddingいじっただけ。
> 84265 adjast to changes from dev5

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/styles/_page-tree.scss
- packages/app/src/styles/theme/_apply-colors-dark.scss
- packages/app/src/styles/theme/_apply-colors-light.scss
- [#84326](https://redmine.weseek.co.jp/issues/84326) アイテムとアイテムの間の余白を失くす
- [#84327](https://redmine.weseek.co.jp/issues/84327) タイトルのfont-sizeを変更する
- [#84329](https://redmine.weseek.co.jp/issues/84329) 子ページ開閉ボタンのホバー範囲を広げる
> remove margin

- packages/app/src/components/SearchPage/SortControl.tsx
https://redmine.weseek.co.jp/issues/84305
- 不要なアイコン削除
- border の調整(input group の分け目に位置する border radius が変)
before 
after
> remove icon and modify border

- packages/app/src/server/service/config-loader.ts
- packages/app/src/server/service/page.js
Redmine: https://redmine.weseek.co.jp/issues/84294
Mongo で dbOwner の権限しかない場合にパブリックマイグレーションが開始できない不具合を修正しました
> imprv: Remove unrunnable mongo methods

- packages/app/package.json
- yarn.lock
https://youtrack.weseek.co.jp/issue/GW-7622
- Rebuild packages webpack-bundle-analyzer
- acorn upgraded from v5.7.3 to v7.1.1
> fix: dependabot alert acorn

- yarn.lock
https://youtrack.weseek.co.jp/issue/GW-7623
- Rebuild browserify-sign and create-ecdh
- Both packages requires elliptic "^6.5.3"
> fix: dependabot alert elliptic

- packages/app/package.json
- yarn.lock
https://youtrack.weseek.co.jp/issue/GW-7625
- Rebuild easzy-logger v3.0.2, resolved by v3.1.0
- No more object-path required
> fix:  dependabot alert object-path

- packages/app/src/client/services/ContextExtractor.tsx
- packages/app/src/components/Navbar/GrowiNavbar.tsx
- packages/app/src/components/Navbar/GrowiNavbarBottom.jsx
- packages/app/src/stores/context.tsx
https://redmine.weseek.co.jp/issues/84092
SearchPageかではGlobalSearchを表示しないようにする。
Navバーにあるのと、spサイズ時画面下にも出てきてた。
> 84092 hide search page

- packages/app/src/server/models/activity.ts
[#84410](https://redmine.weseek.co.jp/issues/84410) 修正
Activity を作成する action（like や rename） を行う際にエラーが発生する問題を修正しました。
```
E11000 duplicate key error collection: growi.activities index: user_1_target_1_action_1_createdAt_1 dup key: { user: ObjectId('61c1b80c785f329b92d771d1'), target: ObjectId('61c1b83a785f329b92d7734a'), action: "PAGE_LIKE", createdAt: new Date(1640085622854) }
```
Activity モデルの createdAt がスキーマが作成された時間になっており、すべての activity の createdAt が同一の時間に保存されてしまうようになっていたことがで原因でした。
> fix: 84410 error that activity is not saved

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/styles/_page-tree.scss
[#84325](https://redmine.weseek.co.jp/issues/84325) 長いタイトルは省略する
> improve long pagetree title

- packages/app/src/server/crowi/index.js
- packages/app/src/server/service/page.js
- packages/app/src/server/service/search-delegator/elasticsearch.ts
- packages/app/src/server/service/search.ts
- packages/app/src/test/integration/service/page.test.js
[#84367](https://redmine.weseek.co.jp/issues/84367) 修正
ページを完全に削除したときに以下のようなエラーがでる問題、完全に削除したページの path を検索したときに検索結果画面に `Cannot  read proety '_doc' of undifined` というエラーが表示される問題を修正しました。
```
deletePages:ES Error TypeError: pages.forEach is not a function
at ElasticsearchDelegator.deletePages (/workspace/growi/packages/app/src/server/service/search-delegator/elasticsearch.ts:575:11)
at ElasticsearchDelegator.syncPagesDeletedCompletely (/workspace/growi/packages/app/src/server/service/search-delegator/elasticsearch.ts:967:25)
at PageEvent.emit (events.js:412:35)
at PageService.deleteCompletely (/workspace/growi/packages/app/src/server/service/page.js:661:20)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at api.remove …
```
> fix: 84367 error that occurs when a page is completely deleted 

- packages/app/src/components/Page/RevisionRenderer.jsx
Redmine(２つ): https://redmine.weseek.co.jp/issues/84436, https://redmine.weseek.co.jp/issues/84274
検索の右ペインでハイライトが正常にかかるように修正しました
ついでに a で検索すると右ペインの結果がリンクになってしまう問題も修正しました
動作確認は https://redmine.weseek.co.jp/issues/84488 でまとめてやります
> fix: Highlight all keywords in search content

- packages/app/src/client/services/AdminHomeContainer.js
- packages/app/src/components/Admin/AdminHome/AdminHome.jsx
[#84328](https://redmine.weseek.co.jp/issues/84328) Wiki management home page & App Settingsで isV5Compatible が true でも一瞬だけマイグレーション促進のメッセージが表示されるのを防ぐ
`migrationStatus` の値がnull でもアラートメッセージが表示されてしまっていたのを修正しました。
やったこと
- class componentを funtional componentに書き換え
- AdminHomeContainerからではなく、`useSWRxV5MigrationStatus`で`data(migrationStatus)`を取得
- アラートを表示する条件式に、`migrationStatus != null` を追加
https://user-images.githubusercontent.com/59536731/146971741-45aac76b-3c00-4c89-ace8-3404e8a6fb8a.mov
https://user-images.githubusercontent.com/59536731/146971686-a5d80828-ad4d-4b1a-8db7-8f29997fc11c.mov
> fix alert message

- packages/app/src/styles/_sidebar.scss
dev5が統合先になってます。
動作確認してからmergeするのではmergeはお待ちください。
https://redmine.weseek.co.jp/issues/84335
sidbarのボタンの範囲が広くてpage treeの+ボタンが押せなくなっていたのを解消。
幅変更前：
幅変更後 :
> 84335 sidebar button clickable area smaller

- packages/app/src/components/Page/RevisionBody.jsx
Redmine: https://redmine.weseek.co.jp/issues/84443
MathJax のレンダリングで warning が出ていたので修正しました
> fix: Warning at mathjax

- packages/app/src/components/Page/RevisionRenderer.jsx
Redmine(２つ): https://redmine.weseek.co.jp/issues/84436, https://redmine.weseek.co.jp/issues/84274
RevisionRenderer のハイライトを修正しました
- html タグ内はハイライトの対象から外しました
- テストコード追加
- keyword に "" が含まれている場合をケア
- renderHtml メソッド周り改修 (既存のバグ)
- コードブロック内が正しくレンダリングされていない
- view と render のされ方が違うので view に揃える
- ハイライターによるものではない
> fix: Highlight all keywords in search content (second)

- packages/app/src/server/routes/page.js
- packages/app/src/server/views/widget/page_alerts.html
Redmine: https://redmine.weseek.co.jp/issues/84536
NotFoundAlert が forbidden と not_creatable で表示されないようにしました
> fix: Not show NotFoundAlert when not creatable or forbidden

- packages/app/src/client/app.jsx
- packages/app/src/components/Page/RevisionRenderer.jsx
- packages/app/src/components/Page/TrashPageAlert.jsx
- packages/core/src/models/devided-page-path.js
Redmine(２つ): https://redmine.weseek.co.jp/issues/84600, https://redmine.weseek.co.jp/issues/84204
正規表現の後読みがサポートがされていないブラウザで GROWI が正常に動作しなくなる不具合を修正しました
> fix: Regex support for non-chrome browsers

- packages/app/src/server/service/page.js
- packages/app/src/server/service/search.ts
[#84451](https://redmine.weseek.co.jp/issues/84451) ページを revert したときにエラーが発生する
> fix: 84451 do not fire the delete completely event when page revert

- yarn.lock
https://youtrack.weseek.co.jp/issue/GW-7617
Some packages are on latest version but still requires trim-newlines v1.0.0 and v2.0.0
- main package lerna is on the latest version , requires trim-newlines v1.0.0 and v3.0.0
- shipjs (also latest version) requires trim-newlines v1.0.0 and v3.0.0
- prettier-stylelint is on the latest version, requires trim-newlines v1.0.0 and v2.0.0
- stylelint v14.0.1 requires trim-newlines v3.0.0
- Rebuild trim-newlines v3.0.0, resolved by v3.0.1
> fix: dependabot alert trim-newlines

- packages/app/src/components/Sidebar/RecentChanges.tsx
https://redmine.weseek.co.jp/issues/85053
- tag が null の場合(DB から直接削除された場合)に、null の tag のみを除外して表示するように変更
- ↑(同じ page でも 直接 DB から削除されたもの以外は表示される)
- 動作確認
> imprv: add filter method about tag to recent changes

- packages/app/package.json
- packages/app/src/server/crowi/express-init.js
This PR is a partial fix for the issue https://github.com/weseek/growi/issues/5022. I added [the compression middleware](https://expressjs.com/en/resources/middleware/compression.html) to compress response bodies.
The HTTP response now has `Content-Encoding: gzip` and the transferred size is reduced to 1.88MB.
before:
> imprv: Compress response bodies

- packages/app/src/server/service/config-loader.ts
- packages/app/src/server/service/passport.ts
https://youtrack.weseek.co.jp/issue/GW-7637
- add oidc client clock tolerance object in config loader
- implement config manager to get value of oidc client clock tolerance
- set default oidc client clock tolerance  value to 10
> feat: add oidc client clock tolerance to config manager

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- [85035](https://redmine.weseek.co.jp/issues/85035) useDrag hookを使用して単一の要素でドラック状態を再現することができる
https://user-images.githubusercontent.com/59536731/148185493-d2495032-6fdc-4379-acec-f3bd24239437.mov
今回のPRでは、単一の要素(pageItem)のみのDragを対象にしています。
以下の後続タスクで子供のページも同様にドラッグ対象に含むようにします。
(**※こちらのタスクは不要になる可能性があります**)
- [85045](https://redmine.weseek.co.jp/issues/85045) 親ページをドラッグした際に、子供もついてくるようにする
> dragging one page tree item

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- [85173](https://redmine.weseek.co.jp/issues/85173) Drag中の要素が、他のページ要素に重なった時にchildrenも表示されるようにする
- Drag中のページとDropターゲットのページが1s以上重なった場合にのみ、Dropターゲットページの子供が表示されるようにしました。
(現状、子供がいなくても三角ボタンは表示される)
https://user-images.githubusercontent.com/59536731/148947952-b05a56bf-e3dc-4536-b78d-99b20fe84a7e.mov
> show children

- packages/app/package.json
- packages/app/src/server/service/config-loader.ts
- packages/app/src/server/service/passport.ts
- yarn.lock
https://youtrack.weseek.co.jp/issue/GW-7669
- Add axios-retry package
- Implement axios-retry instead of got
- Modify Issuer host availability check with `/.well-known/openid-configuration`
- Add config loader for OIDC Issuer default timeout options
- Set default OIDC clock tolerance to 60 (1 minute)
> fix: OIDC issuer host availability check

- packages/app/src/components/Common/ClosableTextInput.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- packages/app/src/styles/_page-tree.scss
- packages/app/src/styles/theme/_apply-colors-dark.scss
- packages/app/src/styles/theme/_apply-colors-light.scss
- packages/app/src/styles/theme/_apply-colors.scss
- [85059](https://redmine.weseek.co.jp/issues/85059) リストグループ化
- ページツリーのDOM構造を bootstrapのlist-groupを使用して置き換えました。
- TODO
色関係は、後続タスクにて着手します。
[85800](https://redmine.weseek.co.jp/issues/85800) サイドバー専用のmixinを作成し、各テーマに適用させる
> improve dom structure

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/styles/theme/_apply-colors-dark.scss
- packages/app/src/styles/theme/_apply-colors-light.scss
- packages/app/src/styles/theme/mixins/_list-group.scss
- [85800](https://redmine.weseek.co.jp/issues/85800) サイドバー専用のmixinを作成し、defaultテーマに適用させる
default以外のテーマは以下の後続タスクにて着手します
[86183](https://redmine.weseek.co.jp/issues/86183) default 以外のテーマで、見づらい部分があれば調整する
- light
- dark
- light
- dark
https://user-images.githubusercontent.com/59536731/149884357-9cfb8aa2-3e74-40bc-801a-77f57b5c0689.mov
> using mixin for light theme

- packages/app/resource/locales/en_US/translation.json
- packages/app/src/server/routes/apiv3/forgot-password.js
- packages/app/src/server/routes/apiv3/personal-setting.js
- packages/app/src/server/routes/index.js
- [79291](https://redmine.weseek.co.jp/issues/79291) [Report3][修正] 新規にパスワードを作成する時に8文字以上にする
- [86186](https://redmine.weseek.co.jp/issues/86186) [Report3][修正] ログイン時にrate limitを使用する
**※マージ先はマスターです**
- パスワード作成するケースは以下の2つなので、各ケースにてパスワードを8文字以上に設定するようにしました。
　　　- User Settings の Password Settings
　　　- Forgot Password の Reset Password
　　　
　　　
　　　
また、rate limit を5 から10 にあげました。(5は少ないと判断しました)
> imprv: 79291 make password min length 8 charactors

- packages/app/src/components/PageEditor/AbstractEditor.tsx
- packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
- packages/app/src/components/UncontrolledCodeMirror.tsx
https://redmine.weseek.co.jp/issues/86391
- https://github.com/weseek/growi/issues/5060
- https://github.com/weseek/growi/pull/5061/files ← 応急処置で追加されたコードを revert
- https://github.com/weseek/growi/pull/4764/files ← で忘れ去られた isGfmMode を復活
- その他、変数を1つ修正
- AbstractEditor.tsx の isGfmMode の default 値が消えていた
- そのため CodeMirrorEditor.jsx の `handleEnterKey` メソッドなどをはじめとした `isGfmMode` が true な場合の処理が実行されていなかった
- マークダウンハイライト → 出る
- オートインデント → される
- テーブルが自動で作れる
> imprv: commonize codemirror

- packages/app/src/components/Sidebar/RecentChanges.tsx
- packages/app/src/server/routes/apiv3/pages.js
https://redmine.weseek.co.jp/issues/86650
- tag を MongoDB から直接削除した場合のためのコード
- `routes/apiv3/pages/recent` 側で page についている null な tag を除外し、フロントで null なタグを除外する処理をなくしました
> exclude null tag on server side in routes/apiv3/pages

- yarn.lock
- Adjust follow-redirects@^1.0.0, @^1.14.0, @^1.14.4 to use version 1.14.7
- Checked axios by run API action, all is OK
https://youtrack.weseek.co.jp/issue/GW-7674
> imprv: update follow-redirects to v1.14.7

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/Common/ClosableTextInput.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
[#86741](https://redmine.weseek.co.jp/issues/86741) エンターキーを押した時に rename できる
https://user-images.githubusercontent.com/34241526/151123372-c2040c9f-de62-4219-8090-42def1080b93.mov
↑ やっていること
- 既存のパスにリネーム
- スラッシュを含むタイトルにリネーム
- 空文字のタイトルにリネーム
- 正しいタイトルにリネーム
> feat: 86741 Rename when press enter

- packages/app/src/server/routes/apiv3/page.js
- packages/app/src/server/service/page.js
```
08:05:21.737Z ERROR growi:routes:apiv3:page:
get-page-failed TypeError: Cannot read property 'match' of undefined
at /workspace/growi/packages/core/src/utils/page-path-utils.ts:54:59
at Array.some (<anonymous>)
at isDeletablePage (/workspace/growi/packages/core/src/utils/page-path-utils.ts:54:38)
at PageService.findPageAndMetaDataByViewer (/workspace/growi/packages/app/src/server/service/page.js:149:26)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at /workspace/growi/packages/app/src/server/routes/apiv3/page.js:250:16
```
4.5.x is fixed by #5212
> fix: /_api/v3/page with pageId param occurs an 500 error (merge into master)

- packages/app/src/components/PageHistory/RevisionDiff.jsx
- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/models/page.ts
- packages/app/src/server/models/revision.js
- packages/app/src/server/routes/apiv3/revisions.js
- packages/app/src/server/routes/installer.js
- packages/app/src/server/service/page.ts
- packages/app/src/test/integration/service/page.test.js
Redmine: https://redmine.weseek.co.jp/issues/84989
Revision の path アトリビュートを使っているところを pageId に置き換えました
> imprv: Rewrite revision process using pageId

- .devcontainer/docker-compose.yml
- Research Kibana can use ES6 and ES7 with single version
- Remove elasticsearch-head docker image
- Checked all working fine, Kibana version need to adjusted based on ES version
https://youtrack.weseek.co.jp/issue/GW-7683
> imprv: add kibana docker image

- packages/app/resource/locales/en_US/admin/admin.json
- packages/app/resource/locales/ja_JP/admin/admin.json
- packages/app/resource/locales/zh_CN/admin/admin.json
- packages/app/src/components/Admin/UserGroup/UserGroupDropdown.tsx
- packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
[#87613](https://redmine.weseek.co.jp/issues/87613) [Front] Add child groups ボタンを押すと追加可能グループ一覧（ボタン）+ UserGroupの新規作成ボタンをドロップダウンで表示できる
https://user-images.githubusercontent.com/34241526/152379762-a74edcca-7142-44f5-bd39-f057c0e01ed3.mov
> feat: 87613 Selectable User Groups Dropdown

- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/PageList/PageList.tsx
- packages/app/src/components/PageList/PageListItemL.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
PageItemControlの複製ボタンをクリックするとPageDuplicateModalが表示され、ページの複製を実行する
https://user-images.githubusercontent.com/59536731/152637045-2d700125-d11f-4e32-bca5-396397e9839c.mov
※dev.5.0.xをマージした際にisRecursiveryの処理が正常に動作されなくなりましたが(単体の複製のみが成功する)、原因はこのブランチにはないと判断したためそのままPR依頼を出します(増山くんには共有済み)
モーダルで`isRecursively`にチェックした際、`routes/apiv3/pages.js` の`/duplicate` でisRecursivelyはtrueのままちゃんと渡っています。
↓原因はこの中にある
> Imprv/87696 show PageDuplicateModal when clicking DuplicateMenuItem

- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- [87710](https://redmine.weseek.co.jp/issues/87710) PageItemControlのrenameボタンをクリックしてモーダルを表示する
- 再帰的なrename/ リダイレクト / メタデータを更新しない / も正常に動作します。
(現状、ページツリーの反映に関してはリロードしないといけないです。)
https://user-images.githubusercontent.com/59536731/152697541-1fc08553-4da8-4a92-ad58-5eacb3cb511f.mov
> show rename modal

- packages/app/src/components/Common/ClosableTextInput.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
[#87839](https://redmine.weseek.co.jp/issues/87839) [Front] ClosableInputText のバリデーション有効時に、ページの保存処理をさせない　にリネーム
> feat: 87839 Don't let ClosableInputText do onPressEnter when validation is enabled

- packages/app/src/server/service/page.ts
- packages/core/src/test/util/page-path-utils.test.js
- packages/core/src/utils/page-path-utils.ts
Redmine: https://redmine.weseek.co.jp/issues/87768
「パスの配列のうち、その子孫部分が被っている部分を計算して必要のないパスを配列から取り除くメソッド」を実装しました
複数かつ再帰的な削除・待避所からのマイグレーションをするときに、処理対象のページが被らないようにするために使われます
- 複数指定かつ再帰的な削除の API 実装
> imprv: Pre-calculate paths to process

- packages/app/src/components/Sidebar/SidebarNav.tsx
- packages/app/src/components/Sidebar/Tag.tsx
- packages/app/src/components/TagCloudBox.tsx
- packages/app/src/components/TagList.tsx
https://redmine.weseek.co.jp/issues/87031
- XD( https://xd.adobe.com/view/cd3cb2f8-625d-4a6b-b6e4-917f75c675c5-986f/screen/2c321a4b-f25f-4ee8-b6c2-77c9334ea48f/ ) に基づいて、サイドバーのタグゾーンのデザインを修正しました
- デザイナーチェック依頼
- デザイナーとの相談
- ① /tags のページが、サイドバーと分離したため、より柔軟なデザインができるようになったため、相談
- ② swr 経由でサーバーサイドと問い合わせてる最中の loading 状態のデザイン
> imprv: redesign tag sidebar and modify related components

- packages/app/src/server/routes/apiv3/pages.js
Redmine: https://redmine.weseek.co.jp/issues/88021
単体で再帰的でない Duplicate でからページが対象だった場合に res.apiV3Err するように修正しました
> fix: Fixed duplicate route

- packages/app/src/server/service/page-grant.ts
- packages/app/src/server/service/page.ts
Redmine: https://redmine.weseek.co.jp/issues/87259
権限チェックを同時にできるページの最大数を 20 に制限しました
> imprv: Limit pages to validate grant at once

- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
[#88142](https://redmine.weseek.co.jp/issues/88142) 三点リーダーからページの削除が正常に終了した後に、PageTree から対象のページの表示を消す
> feat: 88142 Remove the display from PageTree when a page is deleted

- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
[#88020](https://redmine.weseek.co.jp/issues/88020) [PageItemControl] 空ページのアイテムの３点リーダーに Delete と Duplicate が表示できる
> feat: 88096 Show delete and duplicate in empty pages

- packages/app/src/components/PageDeleteModal.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- packages/app/src/stores/modal.tsx
- [87936](https://redmine.weseek.co.jp/issues/87936) [ItemsTree]`isDeleteCompletelyModal`と`isAbleToDeleteCompletely`をSWR管理下において、完全削除かそうでないかによってモーダルの表示を切り替える
- #5307 から移行して新しくPRを作成しました。
- このPRではPageTreeのDeleteModalのみに適用しています。
- その他のdeleteModalに関しては、https://redmine.weseek.co.jp/issues/88317 のタスクで行います。
https://user-images.githubusercontent.com/59536731/153808550-d48b8593-07b7-4bcb-ba57-ff4f77f47f47.mov
https://user-images.githubusercontent.com/59536731/153808482-197a5621-5988-42b1-a33d-f848e3e9adbe.mov
> imprv: 87936 switch delete modal ui of  pagetree pageItemControl

- .devcontainer/docker-compose.yml
https://redmine.weseek.co.jp/issues/88371
-  docker-compose の indent を忘れて devcontainer が立ち上がらなかったため修正
- ci は失敗してますが、`dev/4.5.x` から切ったブランチのため
> fix: modify docker-compose indent

- packages/app/src/components/Sidebar/PageTree/Item.tsx
[#88258](https://redmine.weseek.co.jp/issues/88320)  [5.x][Bug][PageTree][RreactDnD] ドラッグ中のアイテムを他のページアイテム以外の範囲にドロップした時にドラッグ中のアイテムがページツリーから消えてしまう
> fix: 88258 Prevent items hidden when dropped outside the PageTree

- packages/app/src/components/SearchPage/SearchResultContent.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- [88477](https://redmine.weseek.co.jp/issues/88477) [SearchResultContent]`isAbleToDeleteCompletely`かどうかによって、modalのUIを切り替える
- 削除が実行された時、完全削除かどうかに関わらずページをリロードするようにしました。
https://user-images.githubusercontent.com/59536731/154253699-83af6ce6-e84d-476c-b9dc-eb254a2a29a2.mov
> imprv: switch delete modal ui of search result content

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- [88029](https://redmine.weseek.co.jp/issues/88029)  i18n
ページツリーからページを削除した時に表示されるトースターのi18n対応をしました。
> imprv: add i18n

- packages/app/src/components/Page/TrashPageAlert.jsx
- packages/app/src/components/PageDeleteModal.tsx
- [88597](https://redmine.weseek.co.jp/issues/88597) [TrashPageAlert]  openDeleteModalの引数に`isDeleteCompletelyModal`と`isAbleToDeleteCompletely`を渡し、完全削除モーダルを表示させる
`TrashPageAlert`からは「完全削除」しかできないので、openDeleteModalの第四引数に`isDeleteCompletelyModal` を渡すことで、完全削除用のModalのみが表示されるようにしています。
https://user-images.githubusercontent.com/59536731/154266696-403150d4-cee7-46ec-8f58-dd79412933d1.mov
> imprv: show delete compreatly modal on trash page

- packages/app/src/server/routes/apiv3/pages.js
[#88632](https://redmine.weseek.co.jp/issues/88632) ページ複製時に '//' などでページが複製できてしまう
> fix: 88632 Prevent duplication with not creatable paths

- packages/app/src/components/PrivateLegacyPages.tsx
https://redmine.weseek.co.jp/issues/88696
PrivateLegacyPageのヘッダー部分が検索のHelpドロップダウンの上にかぶるのを修正しました。
> fix: Header for PrivateLegacyPage overlaps search help dropdown

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- packages/app/src/stores/modal.tsx
Redmine: https://redmine.weseek.co.jp/issues/88725
ページツリーから削除したあとに削除したアイテムの兄弟を更新することで変更を UI に反映できるようにしました
> fix: Call mutate to update siblings after deletion

- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/service/page.ts
- packages/app/src/server/service/search-delegator/private-legacy-pages.ts
Redmine: https://redmine.weseek.co.jp/issues/88598
待避所に表示するページの条件を「マイグレート可能なページのみ」になるように修正しました
> fix: Show only migratable pages

- packages/app/src/server/service/page.ts
Redmine: https://redmine.weseek.co.jp/issues/88773
重複パスのページを削除・リネームする際に PageRedirect モデルが重複して作成されるために操作を続行できないバグを修正しました
> fix: No throw when PageRedirect insertion dup key error

- packages/app/src/server/models/page.ts
https://redmine.weseek.co.jp/issues/88254
- https://github.com/weseek/growi/issues/5189 の issue の問題を修正
- PR 箇所の `grantUserGroupId`  がタグを TagEditModal からつけた時に undefined になってしまっていたため、
- https://github.com/weseek/growi/blob/fix/87052-88254-fix-tag-issue-about-adding-tag-in-view-mode/packages/app/src/server/service/page-grant.ts#L54 ←の 箇所に引っかかっていたみたいです
> fix: grantedGroup issue when adding tag

- packages/app/src/components/Sidebar/PageTree/Item.tsx
[#88961](https://redmine.weseek.co.jp/issues/88961) isEnabledAttachTitleHeader が true だった場合、ページパスではなくページタイトルを挿入できる
> fix: 88961 Insert page title header

- packages/app/src/server/models/page.ts
- packages/app/src/server/service/page.ts
- packages/app/test/integration/global-setup.js
Redmine: https://redmine.weseek.co.jp/issues/88956
ターゲットがターゲットの配下のパスに移動するとデータが壊れるのを修正しました
> fix: Renaming to under target

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- [88810](https://redmine.weseek.co.jp/issues/88810) +ボタンの背景色, ページアイテムの縦幅を修正する
- +ボタンの背景色が灰色になっていたのを修正
- ページアイテムの縦幅を狭くしました
> fix: 88620 background color of plus button on pagetree and padding adjustment

- packages/app/src/server/routes/apiv3/pages.js
- packages/app/src/server/service/page-operation.ts
- packages/app/src/server/service/page.ts
- packages/core/src/utils/page-path-utils.ts
Redmine(２つ): https://redmine.weseek.co.jp/issues/89220, https://redmine.weseek.co.jp/issues/89173
canMovePath を @growi/core に実装して、renamePage のバリデーションで使用しました
PageOperationService の private メソッドを @growi/core に移動しました
> imprv: Utilize canMoveByPath

- packages/app/src/components/Page.jsx
- packages/app/src/components/Page/RevisionRenderer.jsx
[#88984](https://redmine.weseek.co.jp/issues/88984)  isEnabledAttachTitleHeader が True になっている状態で空ページに遷移するとあらかじめタイトルのヘッダーが挿入されてしまう
- before
- after
> fix: 88984 Prevent rendering of revision on empty pages

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/PageRenameModal.jsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- packages/app/src/interfaces/ui.ts
- packages/app/src/stores/modal.tsx
- [88872](https://redmine.weseek.co.jp/issues/88872)  rename(トースター表示まで)
- Story
- [PageItemControl][ItemsTree] duplicate/rename/delete の処理が完了したときにrevalidateを走らせる
- このPRでは、ページツリーからrename処理を行なった際にトースターを表示させるようにしました。
- revalidateの処理は検討が必要なので後続タスクにしています。
┗ページをリロードするか、親フォルダを閉じて再度開けるかしないとrenameの変更が反映されません
> imprv: revalidate when page has been renamed

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/PageDuplicateModal.jsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- packages/app/src/interfaces/ui.ts
- packages/app/src/stores/modal.tsx
- [88871](https://redmine.weseek.co.jp/issues/88871) duplicate
[PageItemControl][ItemsTree] duplicate/rename/delete の処理が完了したときにrevalidateを走らせる
https://user-images.githubusercontent.com/59536731/155595178-723b3388-9216-4040-be94-82c41a5dc598.mov
> imprv: 88871 revalidate after duplication on pagetree

- packages/app/src/components/SearchPage/SearchResultContent.tsx
- [89043](https://redmine.weseek.co.jp/issues/89043) duplicate
[story]
- [#88858](https://redmine.weseek.co.jp/issues/88858): [PageItemControl][Search][GrowiSubNavgation] duplicate/rename/delete の処理が完了したときにrevalidateを走らせる
検索結果画面のサブナビゲーションの3点ボタンからページを**複製**した時に
- トースター表示
- revalidate
をするようにしました。
https://user-images.githubusercontent.com/59536731/155714575-e2d2078e-91cc-49a1-84c6-9b67293cb287.mov
> imprv: revalidate when page has been duplicated on search result content

- packages/app/src/components/SearchPage/SearchResultContent.tsx
**※  #5431 がまだマージされていない場合は、このPRをマージしないでください。**
- [89259](https://redmine.weseek.co.jp/issues/89259) delete 
[story]
- [#88858](https://redmine.weseek.co.jp/issues/88858): [PageItemControl][Search][GrowiSubNavgation] duplicate/rename/delete の処理が完了したときにrevalidateを走らせる
検索結果画面のサブナビゲーションの3点ボタンからページを**削除**した時に
- revalidate
をするようにしました。
(トースターは別タスクで追加していただいたようなのでこのPRはrevalidateのみです。)
https://user-images.githubusercontent.com/59536731/155716722-16a0e96b-7819-47f4-a79a-430429583359.mov
> imprv: revalidate when page has been deleted

- packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
- [89047](https://redmine.weseek.co.jp/issues/89047) rename
story: [PageItemControl][GrowiContextualSubNavgation]duplicate/rename/delete の処理が完了したときに対象ページに遷移させる
- GrowiContextualSubNavgation上の3点ボタンからリネーム操作した時に、ページがリロードされるようにしました。
https://user-images.githubusercontent.com/59536731/155723885-776d2a75-65d5-44ce-9bee-cdf85696a1ca.mov
dev-4 系までは、以下の画像のように、`RenamedAlert`が表示されていました。
- 4系は、クエリストリングに`renamedFrom`がある場合、`RenamedAlert` が表示されるようになっています。
- 5系は、urlがpageIdになっています。
こういう場合ってPageIdの後ろにくっつけちゃっていいのでしょうか...?
その場合以下のようなURLなってしまうんですかね... :eyes: 
```
http://localhost:3000/6218cd71655a6e063280e81f?renamedFrom=6218cd71655a6e063280e81f
```
↓4系
```
https://demo.growi.org/download-test-2?renamedFrom=%2Fdownload-test
```
https://github.com/weseek/growi/blob/9f3e8d180a4bd2f6fe1790fd17d6e4671b148a72/packag …
> imprv: reload page when page has been renamed on growi contextual subnavigation

- packages/app/src/components/PageList/PageListItemL.tsx
- packages/app/src/components/SearchPage/SearchResultList.tsx
- [89049](https://redmine.weseek.co.jp/issues/89049) duplicate
- story: [PageItemControl][Search][PageListItemL] duplicate/rename/delete の処理が完了したときにrevalidateを走らせる
https://user-images.githubusercontent.com/59536731/155726146-8a145fb1-db7c-448c-8bd4-cfd9a74e2ff7.mov
> imprv: revalidate after page has been duplicated

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
- packages/app/src/components/PageDuplicateModal.jsx
- packages/app/src/components/SearchPage/SearchResultContent.tsx
- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- packages/app/src/interfaces/ui.ts
- [89046](https://redmine.weseek.co.jp/issues/89046) duplicate
- story: [PageItemControl][GrowiContextualSubNavgation]duplicate/rename/delete の処理が完了したときに対象ページに遷移させる
やったこと
- onDuplicated の第二引数に複製先のpagePathを渡すようにし、delete処理が完了した後にそのページに遷移するようにしました。
┗ onDuplicated は　第一引数に 元のパス、第二引数に 新しいパス を渡しています。
後続タスク([89403](https://redmine.weseek.co.jp/issues/89403))で
- DuplicatedAlert
- RenamedAlert
関連の不要なコードを削除します。
https://user-images.githubusercontent.com/59536731/155738153-4ea99ded-5129-4eb2-8cf8-a61698806042.mov
> imprv: 89046 reload after page has been duplicated on growi contextual subnavgation

- packages/app/src/server/routes/apiv3/personal-setting.js
https://redmine.weseek.co.jp/issues/89334
https://github.com/weseek/growi/issues/5408
- `/me` にて、whitelist が登録されていて、かつ、whitelist の中に存在しないメールアドレスドメインのメールアドレスを更新できないようにしました
> fix: fix issue of email whitelist bug

- packages/app/src/server/routes/apiv3/pages.js
- packages/app/src/server/service/page-operation.ts
- packages/app/src/server/service/page.ts
Redmine: https://redmine.weseek.co.jp/issues/89366
自分の配下へのリネームを修正しました
- `PageCursorsForDescendantsFactory` の AsyncGenerator を生成するメソッドでたまに `Mamimum call stack error` が発生していたので、発生しないように改修しました
> fix: Rename to under descendant

- packages/app/src/components/PageList/PageListItemL.tsx
- packages/app/src/components/SearchPage/SearchResultList.tsx
以下の2つです。
- [89422](https://redmine.weseek.co.jp/issues/89422) duplicate, delete時にトースターを表示させる
- [89050](https://redmine.weseek.co.jp/issues/89050) rename
以下の対応をしました
- duplicate
- :new: トースター表示
- (revalidateは実装済み)
- delete
- :new: トースター表示
- (revalidateは実装済み)
- rename
- :new:  トースター表示
- :new:  revalidate 
https://user-images.githubusercontent.com/59536731/156099707-a83c25d7-23d6-4bda-a0b2-2bfc1ee10fe8.mov
https://user-images.githubusercontent.com/59536731/156104829-8b2cbb59-104a-4680-be5f-2265ee440351.mov
> imprv: show toaster after page has been deleted and duplicateed

- packages/app/src/components/SearchPage/SearchResultContent.tsx
- [89044](https://redmine.weseek.co.jp/issues/89044)  rename
- story: [PageItemControl][Search][GrowiSubNavgation] duplicate/rename/delete の処理が完了したときにrevalidateを走らせる
- SearchPageの右ペインのサブナビゲーションからページのrenameを行った時に、 **トースター表示 ** + **revalidate** を行うようにしました。
※ delete時の挙動と同様、右ペインの更新が行われないのでrename前のページが表示されたままになります。
https://user-images.githubusercontent.com/59536731/156101656-33c233bd-7442-4a09-9ef0-0a98bf917d5e.mov
> imprv: show toaster and revalidate after page has been renamed on Growi Search Result Content

- packages/app/src/server/routes/page.js
- [89501](https://redmine.weseek.co.jp/issues/89501) 修正
- Story: [5.x][bug] 全ての子ページも元に戻す のチェックを外して、revert するとエラーが起きる
https://user-images.githubusercontent.com/59536731/156112629-18794255-963c-4401-b953-5376d8cbb764.mov
https://user-images.githubusercontent.com/59536731/156112826-b4fd3640-38b4-4a44-a263-5598aacde95b.mov
> fix: revert error in case that recursively property is null

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/DescendantsPageList.tsx
- packages/app/src/components/PageList/PageList.tsx
- packages/app/src/components/PageList/PageListItemL.tsx
- packages/app/src/components/PutbackPageModal.jsx
**※ #5466 がマージされていない場合はまだマージしないでください**
- [89624](https://redmine.weseek.co.jp/issues/89624) /trash ページのページリストの3点ボタンからrevertした際に、toasterを表示しrevalidateが走るようにする
- トースターの表示
- revalidate
を行いました
https://user-images.githubusercontent.com/59536731/156358340-77a87eab-adf5-49da-9d58-9a214fa42589.mov
> imprv: revalidate pagelist and show toaster when page has been reverted

- packages/app/src/server/routes/apiv3/personal-setting.js
- https://redmine.weseek.co.jp/issues/89386
- whitelist にないメールアドレスドメインを `/me` から登録できないように修正しました
- issue: fix #5408 
https://github.com/weseek/growi/issues/5408
> fix: Domain whitelist is not respected (fix #5408)

- packages/app/src/components/Page/RevisionRenderer.jsx
- packages/app/src/components/Sidebar/CustomSidebar.tsx
[#89241](https://redmine.weseek.co.jp/issues/89241) /Sidebar が存在しない時に <SidebarNotFound> が表示されない
- before 
- after 
-
> fix: 89241 Custom Sidebar

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/styles/_page-tree.scss
- [89782](https://redmine.weseek.co.jp/issues/89782) [ページツリー] +ボタンのサイズを18pxに変更
やったこと
- Icon-plusのサイズを18pxに変更
- ページアイテム内部のpositionの調整
> imprv: change icon-plus size and the position

- packages/app/src/components/SearchPage/SearchControl.tsx
- [89795](https://redmine.weseek.co.jp/issues/89795) [検索結果] [/user 下も含む, /trash 下も含む, 表示件数] hover時にcursor pointerにする
- `custom-control` を使用
- class から`card` をなくし、`border`を代わりに使用しました。
VRT見るとわかるんですけど、「user下を含む」「trash下を含む」の要素がちょっと大きくなっています。
custom-controlを使用したことによって、inputの枠線も大きくなってます。
https://user-images.githubusercontent.com/59536731/156643112-603b1d56-a0ce-47a5-afb9-03961c3f9fcb.mov
> imprv: 89795 add cursor pointer to sort elm on search page

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/styles/_page-tree.scss
以下の2つ
- [89773](https://redmine.weseek.co.jp/issues/89773) [ページツリー][子孫数] 文字のフォントサイズを12pxに変更
- [89777](https://redmine.weseek.co.jp/issues/89777) [ページツリー][子孫数] 1桁と2桁の場合の横幅を固定させる
XDだとwidth 23px だが、3桁の場合に子孫数がギリギリになってしまうのでwidth 26pxに変更しました。
(XDだと3桁の場合の表示がない)
> imprv: chnage fontsize of page item count

- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/PageList/PageListItemL.tsx
- packages/app/src/styles/_page_list.scss
- packages/app/src/styles/_subnav.scss
- [89790](https://redmine.weseek.co.jp/issues/89790) 3点ボタンを正方形にする
> imprv: 89790  page item control style on pagelist

- packages/app/src/components/PageList/PageListItemL.tsx
- [89788](https://redmine.weseek.co.jp/issues/89788) [検索結果] ページリストのチェックボックスの位置を上下中央揃えにする
- CIのエラーは関係ない部分で出ているので気にしなくてよし
- list内のコンテンツが中央寄せになっていることを確認できます。
> fix: checkbox position on search page

- packages/app/src/styles/_layout.scss
Redmine: https://redmine.weseek.co.jp/issues/89907
Mac ユーザーがスワイプで前後のページに移動できるように修正しました
https://github.com/weseek/growi/issues/5425
> fix: Swiping to previous/next page for Mac users (5.0.x)

- packages/app/src/components/PageList/PageListItemL.tsx
- packages/app/src/components/PageList/PageListItemS.jsx
- packages/app/src/components/SearchTypeahead.tsx
- packages/plugin-lsx/src/client/js/components/LsxPageList/LsxPage.jsx
- packages/ui/src/components/PagePath/PageListMeta.jsx
- [89783](https://redmine.weseek.co.jp/issues/89783) [検索結果] 文字列が右端までいくとアイコンボタンが崩れてしまうのを修正
このPRで行ったこと
- PageListMetaについていたマージンを、使用している箇所で指定するように置き換えた
- `text-nowrap`を追加することで、長いタイトルのページアイテムでもPageListMetaのアイコンたちが崩れるのを防いだ。
- CIのエラーは関係ない部分で出ているので気にしなくてよし
PageListMetaについていたマージンを、使用している箇所で指定するように置き換えたので、デグレしていないかの確認をしました。
> fix: page list meta layout

- packages/app/src/components/Sidebar/PageTree.tsx
- packages/app/src/styles/theme/_apply-colors-dark.scss
- packages/app/src/styles/theme/_apply-colors-light.scss
- [89825](https://redmine.weseek.co.jp/issues/89825) [ページツリー][待避所] マウスホバー時の見た目を変更する
Private Legacy Pagesのhover時の差分は検査されていないみたいです
> imprv: private legacy pages UI when it's hovered

- packages/app/src/server/service/page.ts
- packages/app/test/integration/service/v5.migration.test.js
https://redmine.weseek.co.jp/issues/89993
このタスクでは  `isEmpty: true` なページが含まれず、`null.descendantCount` という読み込みでエラーになってしまう問題を解消
新たに見つかったバグの修正タスクを作成したので、テストはコメントアウトしたまま↓
https://redmine.weseek.co.jp/issues/90060
> fix: test empty page not included on normalize

- packages/app/src/server/models/page.ts
- packages/app/src/server/service/page.ts
Redmine: https://redmine.weseek.co.jp/issues/90060
待避所からのマイグレーション処理を修正しました
一応連絡として、https://github.com/weseek/growi/pull/5485 で椎名さんがテスト拡充してくれています
> fix: Normalize parent when empty pages already exist

- packages/app/src/styles/theme/_apply-colors-dark.scss
- [90000](https://redmine.weseek.co.jp/issues/90000) [dark theme] inputの色が明るすぎるのを修正
ok
> imprv: dark theme form color

- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/styles/theme/_apply-colors.scss
- [89998](https://redmine.weseek.co.jp/issues/89998) [PageItemControl] 3点ボタン, プラスボタンをクリックした際に3角アイコンと同じ挙動になるように修正する
- 対象: 3点ボタン、プラスボタン
- 変更箇所: hover時に、アイコンにprimary color色をつけるようにしました。
(Before / After のスクリーンショットを見るとわかりやすいです)
- hover時にアイコンに色がついていない
- Pagetree
- subnaviBar
- pageListItemL
> imprv: btn-page-item-control ui

- packages/app/src/components/SearchPage/SearchControl.tsx
- packages/app/src/styles/_navbar.scss
- packages/app/src/styles/_variables.scss
https://redmine.weseek.co.jp/issues/90046
z-idnex の値
1020:  navbar
1030:  SearchControl
1000:  ユーザのメニュー（ホーム等）
1020 の navbar が SearchControl より高くないと 1000 のメニュー部分が下に隠れてしまう
> imprv: show personal dropdown over search control

- packages/app/src/styles/theme/default.scss
- [89770](https://redmine.weseek.co.jp/issues/89770) [サイドバー] [default light]サイドバーの背景色を変更する
ok
┗サイドバーの色が変わっていることを確認できます
┗CIのcypressのエラーは関係ない部分なのでスルーして大丈夫です
- サイドバーのbgColorは、`$bgcolor-sidebar-context`という変数で各テーマにで指定されているので、今回の変更が他テーマには影響することはありません
> imprv: sidebar bg-color for default light

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/styles/theme/_apply-colors-dark.scss
- packages/app/src/styles/theme/_apply-colors-light.scss
- packages/app/src/styles/theme/mixins/_list-group.scss
- [89863](https://redmine.weseek.co.jp/issues/89863) [ページツリー][子孫数] 文字色 / 背景色をXD通りに変更する
このPRでは、default theme(light / dark) に色指定をしています。
┗default (light / dark) で設定した色が他のテーマにも適用されていますが何かが見えづらくなるとかはないので問題はないと思っています。
┗後続でmosさんが各テーマカラーの提案をするとのことです。
- 子孫数に関する色が変わっていることを見ることができます。
- CIのcypressに関するエラーは本PRとは関係ない部分なので無視して大丈夫です
> imprv: pagetree count colors

- packages/app/src/server/service/page.ts
- packages/app/test/integration/service/v5.migration.test.js
Redmine: https://redmine.weseek.co.jp/issues/90031
待避所からのマイグレーションを修正しました。テストコードのコメントアウトを外しました
> fix: Normalize parent with empty pages

- packages/app/src/components/Common/ClosableTextInput.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- [89954](https://redmine.weseek.co.jp/issues/89954) 修正
- renamenのinputが表示される時は子孫数カウントを表示しないようにしました
- inputの長さをサイドバーの横幅いっぱいまで伸ばすようにしました
- ok(renameのinput部分は普段隠れているので検出されないです)
┗cypress のCIでエラー出ているが関係ない部分なので無視して大丈夫です
> fix: 89954 rename input and count position

- packages/app/src/styles/theme/default.scss
- [90330](https://redmine.weseek.co.jp/issues/90330) [Pagetree][default dark] サイドバーの背景色をXD通りに変更
OK
各テーマで`  $bgcolor-sidebar-context`の変数に色を指定しているので、default themeを変えたことにより他のテーマの背景色が変わることはないです。
> improve sedebar bgColor on default dark

- packages/app/src/components/Sidebar/PageTree/ItemsTree.tsx
- [90436](https://redmine.weseek.co.jp/issues/90436) 修正
┗[PageTree] レンダリング後に Target ページまで自動スクロールできる
https://user-images.githubusercontent.com/59536731/157801136-728fd8d7-ee13-46cb-b34d-7d83c3399291.mov
> fix: scroll target item class name

- packages/app/resource/locales/en_US/admin/admin.json
- packages/app/resource/locales/ja_JP/admin/admin.json
- packages/app/resource/locales/zh_CN/admin/admin.json
- packages/app/src/components/Admin/App/AppSettingsPageContents.jsx
- packages/app/src/components/Admin/App/ConfirmModal.tsx
- packages/app/src/components/Admin/App/MaintenanceMode.tsx
Redmine: https://redmine.weseek.co.jp/issues/90232
メンテナンスモードを i18n しました
セクション
開始時モーダル
成功時トースター(エラーなどもありますが参考までに)
メンテ中の表示
終了時モーダル
> imprv: i18n maintenance mode

- packages/app/src/components/Sidebar/PageTree/Item.tsx
> fix: hide plus btn on page tree item if the item is user page

- packages/app/src/components/Sidebar/PageTree.tsx
- packages/app/src/components/Sidebar/RecentChanges.tsx
[#90457](https://redmine.weseek.co.jp/issues/90457) [5.x][PageTree] Open時に spinner を表示する
https://user-images.githubusercontent.com/34241526/157813031-5da7cefd-9085-45cc-a5fc-b8baf3384c90.mov
> feat: 90457 Show spinner until page tree has finished loading

- packages/app/src/server/models/page.ts
Redmine(２つ): https://redmine.weseek.co.jp/issues/90463, https://redmine.weseek.co.jp/issues/90464
ページの更新を修正しました
- GRANT_RESTRICTED のページをその他の grant にした場合、isV5Compatible true ならば parent をつけるようにした
- 逆に GRANT_RESTRICTED にした時、新しい空の親で子ページの parent を更新するようにしました
- その際余分な空ページを削除するようにしました
> fix: Update parent after page update & remove unnecessary empty pages

- packages/core/src/utils/page-path-utils.ts
- [90563](https://redmine.weseek.co.jp/issues/90563)[backend] /user直下にはページをcreate / renameできないようにする
- create
- rename
- pagetree
`/user/hoge/xxxx`
は作成できる
> fix: isCreatablePage pattern

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/server/views/maintenance-mode.html
[#5538 90556](https://redmine.weseek.co.jp/issues/90556) [メンテナンス画面]ログイン中でも「ログイン」と表示され、管理者でないユーザはログアウトできない
> feat: 90556 add logout

- packages/app/resource/locales/en_US/admin/admin.json
- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/admin/admin.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/admin/admin.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/Admin/App/V5PageMigration.tsx
https://redmine.weseek.co.jp/issues/90562
画像にあるタイトルの v5 は V5 に修正してある
修正後 Japanese
修正後 English
修正後 Chinese
> fix(i18n): use same words

- packages/app/src/components/Sidebar/PageTree/Item.tsx
[#90724](https://redmine.weseek.co.jp/issues/90724) PageTree からページの作成に失敗した時に spinner を非表示できる
> fix: Hide spinner after page creation failure

- packages/app/src/server/routes/page.js
- [90656](https://redmine.weseek.co.jp/issues/90656) 修正
┗[5.x][Bug] Revert 修正
Revert時のエラーの原因がフロント側でもわかるように表示しました。
> imprv: show specific err reason on put back modal

- packages/app/src/components/PageRenameModal.tsx
- [90506](https://redmine.weseek.co.jp/issues/90506) PageRenameModalで、/user/hoge にrenameしようとした時に、エラーの表示をし、submitボタンをdisabledにする
https://user-images.githubusercontent.com/59536731/158578902-d94f6518-034a-4cb6-aaf0-09a5021fb35f.mov
- user page直下にパスをrenameしようとした時
┗rename不可能
- user page直下にパスをrenameしようとした時
かつ
- 重複したページパスになってしまっている時
┗rename不可能
- `/user/${user_name}/hoge` の場合
┗rename可能
> imprv: show error message in case page path is set directory under user page

- packages/app/src/components/Sidebar/SidebarContents.tsx
- packages/app/src/components/Sidebar/SidebarNav.tsx
- packages/app/src/stores/ui.tsx
Redmine: https://redmine.weseek.co.jp/issues/90933
サイドバーナビゲーションのタブの順序を変更しました
> imprv: Switch sidebar tabs' position

- packages/app/src/components/LegacyPrivatePagesMigrationModal.tsx
- packages/app/src/server/routes/apiv3/pages.js
- packages/app/src/server/service/page.ts
[#90952](https://redmine.weseek.co.jp/issues/90952) [bug] 待避所からマイグレートするページを再起的に変換にチェックマークを入れずに変換すると isRecursively が true の状態でリクエストされる
> fix: 90952

- packages/app/src/components/PageCommentList.tsx
https://redmine.weseek.co.jp/issues/90922
- 検索結果ページのコメント表示を通常ページのコメント表示と同じにしました
- className でのスタイルの調整は、https://github.com/weseek/growi/blob/imprv/90378-90922-share-view-between-search-page-comment-and-normal-page/packages/app/src/components/PageComments.jsx ← 共通化される予定のコンポーネントと合わせて、不要な class (存在するが css があたってないなど)は取り除いてます
> imprv: update view of search-page-comment to get closer to normal page comment

- packages/app/src/client/app.jsx
- packages/app/src/components/PageComment/CommentEditorLazyRenderer.tsx
- packages/app/src/components/PageEditor.jsx
- packages/app/src/components/PageEditor/Editor.jsx
- packages/app/src/components/SearchPage/SearchResultContent.tsx
https://redmine.weseek.co.jp/issues/90683
- 検索結果ページから ` CommentEditorLazyRenderer` を除去 (不要と判明したため)
- https://github.com/weseek/growi/pull/5568/commits/fbed15c5e9f8c5342d05ec8b6e30ef43c10b1ec8
- このタスクの差分ではほとんど変更を行っていませんが、後続タスクの方針決め（タスク作成）を行いました
- 実際に試行錯誤しないと実装方針が決まらなかったため
- `PageComment.jsx` と `PageCommentList.tsx` を共通化するというよりも、`PageCommentList.tsx` を `PageComment.jsx`  の実装に寄せて同じ見た目と機能にする方針に決定しました
> imrpv: share page comment component between normal page and search page

- packages/app/src/components/Admin/Security/SecuritySetting.jsx
[#91053](https://redmine.weseek.co.jp/issues/91053) 設定値を変えた時にルール通りになるように強制変更できる & .map() のレンダリングに key をつける
> feat: 91053 Forced change settings

- packages/app/src/components/Page/TrashPageAlert.jsx
[#91291](https://redmine.weseek.co.jp/issues/91291) [5.x] Anyone with the link のページをゴミ箱に入れたあと、完全削除できない問題を修正する
┗ [#91297](https://redmine.weseek.co.jp/issues/91297) 修正
> fix: Remove "Anyone with the link page" completely

- packages/app/resource/locales/en_US/admin/admin.json
- packages/app/resource/locales/ja_JP/admin/admin.json
- packages/app/resource/locales/zh_CN/admin/admin.json
- packages/app/src/components/Admin/UserGroupDetail/UserGroupUserModal.jsx
Redmine: https://redmine.weseek.co.jp/issues/91096
ユーザーグループにユーザーを追加する時に「親グループにもそのユーザーが追加される」という説明を表示するようにしました
> imprv: Add description for user addition

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/styles/_page-tree.scss
[#91529](https://redmine.weseek.co.jp/issues/91529) [PageTree][UI 改善] 子孫数の表示が４桁以上の時にはみ出さないようにできる
┗ [#91550](https://redmine.weseek.co.jp/issues/91550) 実装
> imprv: Item Count Badge

- yarn.lock
- remove js-base in yarn.lock since it's no needed when run npx lerna bootstrap, this is based on depdendabot conflict from master.
> remove js-base in yarn.lock

- packages/app/src/components/Fab.jsx
- packages/app/src/components/Hotkeys/Subscribers/CreatePage.jsx
Redmine: https://redmine.weseek.co.jp/issues/91785
Fab ボタンからページ作成モーダルを表示した時と、ショートカット'C'で表示した時に現在開いているページのパスが自動で入力されるように修正しました
> fix: Create modal auto fill page path

- packages/app/src/styles/style-presentation.scss
Redmine: https://redmine.weseek.co.jp/issues/91787
プレゼンテーションモードで文章が長い場合に全て表示しきれない問題を修正しました
縦スクロールできるようにしました
初め dev wiki から始まります
https://user-images.githubusercontent.com/58432773/160992733-d8ce50d8-b662-4a50-9fc7-ad8abd592093.mov
> fix: Show full text on presentation mode

- packages/app/src/components/Sidebar/PageTree/Item.tsx
[#90903](https://redmine.weseek.co.jp/issues/90903) [5.x][Bug][ReactDnd] dndした時にページアイテムが消えてしまう
┗ [#90872](https://redmine.weseek.co.jp/issues/90872) 修正
before
https://user-images.githubusercontent.com/34241526/161475564-65e04462-36f4-456e-a002-f02b29d43cbe.mov
after 
https://user-images.githubusercontent.com/34241526/161475589-b8aab244-9f34-4a4f-b3c8-35e220c0130f.mov
> fix: Page items disappear when dnd

- packages/app/src/components/SearchPage/SortControl.tsx
- packages/app/src/styles/_search.scss
- [90589](https://redmine.weseek.co.jp/issues/90589) SortボタンのスタイルをXD通りに修正
- 固定
- textの長さによって、横幅が変化する
┗ それに伴い左側の要素(input)の横幅も可変する
┗mosさんには確認済み
> imprv: remove min-width from search-sort-option-btn

- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/styles/_page-tree.scss
[#90587](https://redmine.weseek.co.jp/issues/90587) [5.x][UI/UX改善] 第２回デザイナーチェックででたFB修正(色関連以外)
┗ [#91994](https://redmine.weseek.co.jp/issues/90587) 子孫数カウントの badge の横幅を2桁までは同じにする
> imprv: Adjust layout for PageTree Descendant Count

- packages/app/src/server/models/user.js
- [修正](https://redmine.weseek.co.jp/issues/92496)
- sprint追加依頼済みですが、まだ追加されていないです
- [[GROWI][Bug] ユーザーを新規登録しようとすると、Failed to register.と表示され、登録に失敗する](https://redmine.weseek.co.jp/issues/92489)
- クリーンインストールしてユーザーAを作成
- SignupでユーザーBを作成
で成功することを確認しました。
> fix: Cannot register new users

- packages/app/src/components/Page/DisplaySwitcher.tsx
- packages/app/src/styles/_page-accessories-control.scss
https://redmine.weseek.co.jp/issues/91816
各言語それぞれ、左アイコンの位置と width は合わせて、テキストは中央寄せ
> imprv: Adjust pagelist and comment position

- packages/app/src/server/service/search-delegator/elasticsearch.ts
[#92157](https://redmine.weseek.co.jp/issues/92157) Anyone with the link ページの挙動がおかしい問題を修正する
┗ [#92240](https://redmine.weseek.co.jp/issues/92240) Anyone with the link のページが検索対象にならないようにする
> fix: Do not include in search results if the page grant is restricted

- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/models/page.ts
[#92157](https://redmine.weseek.co.jp/issues/92157) Anyone with the link ページの挙動がおかしい問題を修正する
┗ [#92239](https://redmine.weseek.co.jp/issues/92239) ページの権限を anyone with the link に変更した時に、grantedUsers を空配列にする
> fix: Do not include granted users if change page permission restricted

- packages/app/src/components/User/SeenUserInfo.tsx
- packages/app/src/interfaces/page.ts
- packages/app/src/server/routes/apiv3/page.js
[#92069](https://redmine.weseek.co.jp/issues/92069) [bug] ページ右上の足跡アイコンの数値と、画面左メニューの「最近の更新」で表示される足跡アイコンの数値が、同じページでも異なる場合がある
┗ [#92805](https://redmine.weseek.co.jp/issues/92805) 修正
> fix: Page view count stops at 15

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/PrivateLegacyPages.tsx
- packages/app/src/server/service/page-grant.ts
- packages/app/src/server/service/page.ts
- packages/app/test/integration/service/v5.migration.test.js
Redmine(２つ): https://redmine.weseek.co.jp/issues/92269, https://redmine.weseek.co.jp/issues/92282
待避所からのマイグレーションで兄弟ページが巻き込まれるのを修正しました
テストコードも追記しました
> fix: Normalize parent so it does not include siblings

- packages/app/src/server/routes/apiv3/forgot-password.js
- packages/app/src/server/routes/user-activation.ts
[#92912](https://redmine.weseek.co.jp/issues/92912) ユーザー登録時のメール認証 , ユーザーによるパスワード再設定 のメールに記載されている有効期限をタイムゾーンを考慮したものにする for v5
┗ [#92913](https://redmine.weseek.co.jp/issues/92913) 修正
> fix: Correction of expiredAt attached to email

- packages/app/src/server/crowi/index.js
- packages/app/src/server/service/user-group.ts
- packages/app/test/integration/service/user-groups.test.ts
- packages/app/test/integration/service/v5.user-groups.test.ts
- packages/app/test/integration/setup-crowi.js
- [85131](https://redmine.weseek.co.jp/issues/85131) [updateUserGroup] testfileを新規作成し基本的なテストを記述する(変更された値の反映, nameの重複, 親解除)
タスク分割しました
- name, description, parentIdの変更が反映される
- 更新したい名前が既存のグループ名とかぶっている場合、throw err される
- 親を解除した時、parentがnullになる
> support: creating test file for v5 updateGroup 

- packages/app/src/components/PageAttachment.jsx
- packages/app/src/server/routes/apiv3/attachment.js
[#93137](https://redmine.weseek.co.jp/issues/93137) [GROWI][issue][5.0.x] Bug: Get attachment list API without "page" parameter returns 500 response
┗ [#93138](https://redmine.weseek.co.jp/issues/93138) 修正
> fix: Get attachment list api without "page" parameter returns 500 response

- packages/app/src/styles/theme/_apply-colors-dark.scss
> imprv: Dark theme color optimization

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/PutbackPageModal.jsx
- packages/app/src/server/models/errors.ts
- packages/app/src/server/routes/page.js
- packages/app/src/server/service/page.ts
- [i18n対応](https://redmine.weseek.co.jp/issues/92989)
- revert時のエラーのi18n対応をしました。
- 既存の`already_exists` コードを使用しています。
- エラーメッセージを変更したので、Duplicateなどの他のモーダルにも変更が反映されています。
- PutBackPageModal
- DuplicateModal
> imprv: i18n for already_exists error in PutBackPageModal

- .github/workflows/release-rc.yml
- .github/workflows/release-slackbot-proxy.yml
- .github/workflows/release.yml
- packages/app/docker/Dockerfile
- packages/slackbot-proxy/docker/Dockerfile
This PR adds the following improvements to Docker Build to Growi
- Use GHA native cache in GHA including the build stage image layers (brings sugnificant build speed improvemetnt)
- `type=gha,mode=max`
- chmod and chown can be with COPY and it makes the image layer lighter
Planning future work
- Add `--link` options to `COPY` ref. https://codezine.jp/article/detail/15745
> imprv: Use latest BuildKit feature and GHA for faster/lighter docker build

- packages/app/src/styles/_layout.scss
タスク：https://redmine.weseek.co.jp/issues/93339
トラックパッドで左右にジェスチャーをした際、ページを進んだり戻ったりできるようにしました。
レビューをお願いします。
> fix: Swiping to previous/next page for Mac users (4.5.x)

- packages/app/src/styles/_page_list.scss
- [93647](https://redmine.weseek.co.jp/issues/93647) 修正
┗[GROWI] user home の Bookmarks と Rescently Created の足跡が大きすぎる
> fix:  footstamp-icon size

- packages/app/src/server/models/page.ts
Redmine: https://redmine.weseek.co.jp/issues/93978
祖先の位置に v4 のパブリックページが存在する際に不必要な空ページが生成されるバグを修正しました
> fix: Not create unnecessary empty pages when ancestors are public

- packages/app/src/components/Me/ProfileImageSettings.jsx
- packages/app/test/cypress/integration/6-home/home.spec.ts
- packages/app/test/integration/models/v5.page.test.js
Redmine: https://redmine.weseek.co.jp/issues/93977, https://redmine.weseek.co.jp/issues/93978
getParentAndFillAncestors が不必要な空ページを生成しないことを確かめるテストコードを追記しました
ci は test のみ無視でお願いします
> fix: Switch v4 v5 process testcode

- packages/app/src/components/Admin/Users/UserInviteModal.jsx
タスクなし
クリップボードにパスワードをコピーする際の余計な余白を取り除きました
> fix: Trim space when copying password to a clipboard

- packages/app/src/server/routes/apiv3/pages.js
[#93769](https://redmine.weseek.co.jp/issues/93769) [GROWI] [AuditLog] ページを create した時に activity を作成できる
└ [#94211](https://redmine.weseek.co.jp/issues/94211) page を create した時に activity が作成されないバグ修正
> fix: Activity is not generated when a page is created

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/Sidebar/PageTree/Item.tsx
[94336](https://redmine.weseek.co.jp/issues/94336) ページツリー上で複数階層のページを作成する
https://user-images.githubusercontent.com/59536731/167087585-c7e9cc36-b6c6-44fa-b7b9-36f4c73d1307.mov
本PRでは、作成されたページの展開(isOpen)は考慮に入れていません。
もし展開まで行うのであれば以下のストーリーが関わってくるかと思います。
https://redmine.weseek.co.jp/issues/94221
> imprv: Rename function on pagetree

- packages/app/src/components/PageCreateModal.jsx
- packages/app/src/components/PageDuplicateModal.tsx
- packages/app/src/components/PageRenameModal.tsx
[94310](https://redmine.weseek.co.jp/issues/94310) 検索結果のページリスト上でのリネーム時にページのサジェストが表示されるようにする
- PageRenameModalにpagePathAutoComplete 機能を追加しました。
https://user-images.githubusercontent.com/59536731/167061017-afadcfd9-e101-4e64-ab7b-0f404d6aae9d.mov
> feat: 94310 page path auto complete function for page rename modal

- packages/app/src/components/User/SeenUserInfo.tsx
- packages/app/src/server/routes/apiv3/page.js
- packages/app/src/stores/page.tsx
┗ [94566](https://redmine.weseek.co.jp/issues/94566) 修正
close #5815
```
SeenUserInfo.tsx?9e58:23 Uncaught TypeError: Cannot read properties of undefined (reading 'length')
at SeenUserInfo (SeenUserInfo.tsx?9e58:23:1)
at renderWithHooks (VM42678 react-dom.development.js:14803:18)
at updateFunctionComponent (VM42678 react-dom.development.js:17034:20)
at beginWork (VM42678 react-dom.development.js:18610:16)
at HTMLUnknownElement.callCallback (VM42678 react-dom.development.js:188:14)
at Object.invokeGuardedCallbackDev (VM42678 react-dom.development.js:237:16)
at invokeGuardedCallback (VM42678 react-dom.development.js:292:31)
at beginWork$1 (VM42678 react-dom.development.js:23203:7)
at performUnitOfWork (VM42678 react-dom.development.js:22157:12)
at workLoopSync (VM42678 …
```
> fix: Guest user cannot access share link pages

- packages/app/src/components/Navbar/AppearanceModeDropdown.tsx
- packages/app/src/components/Navbar/PersonalDropdown.jsx
https://redmine.weseek.co.jp/issues/94599
- 見た目を設定するドロップダウンの中身の処理を追加
ログイン済みユーザーの処理は実装済みのコードをそのまま使用
未ログインのユーザーの処理は別タスクでやります
> feat: 94599 navbar menu cliant

- packages/app/src/components/PageEditor/EmojiPickerHelper.ts
- packages/app/src/styles/_override-bootstrap.scss
**[bug] Emoji picker modal scrolling up when opened** 
Body scrolls up when emoji picker modal opened from comment editor
https://user-images.githubusercontent.com/92426728/167987119-344096e7-fa88-44a7-99bc-f9b02743e6fd.mp4
Emoji picker position relative to comment editor
https://user-images.githubusercontent.com/92426728/167987557-8e286e89-ecf6-4c01-a3b0-53e77d6e5248.mp4
https://youtrack.weseek.co.jp/issue/GW-7804
- Set body style position to static on modal opened
> fix: Emoji picker modal scrolling up when opened

- packages/app/docker/Dockerfile
https://redmine.weseek.co.jp/issues/94637
> fix: Change the execution user of the official docker image to root

- packages/app/src/components/PageEditor/OptionsSelector.jsx
[GROWI][Issue][Bug] Editor画面でtextlintをoff にして別ページに遷移した後に再度Editor画面を開くと textlint設定がONになってしまう
┗ [95047 修正(5.0.x)](https://redmine.weseek.co.jp/issues/95047)
textlint をoff にしてページ更新 -> 再度編集画面に戻ると、textlintがoffになっている
textlint をon にしてページ更新 -> 再度編集画面に戻ると、textlintがonになっている
https://user-images.githubusercontent.com/59536731/168740165-920d926a-fbfd-4f97-868b-df4eee55ff61.mov
close #5407
> fix: Can not toggle textlint function on v5.0.x

- packages/app/src/components/PageEditor/OptionsSelector.jsx
[GROWI][Issue][Bug] Editor画面でtextlintをoff にして別ページに遷移した後に再度Editor画面を開くと textlint設定がONになってしまう
┗ [95047 修正(4.5.x)](https://redmine.weseek.co.jp/issues/95266)
v5での修正をv4にも反映
close #5407
> fix: Can not toggle textlint function on v4.5.x

- packages/app/src/server/models/activity.ts
- packages/app/src/server/routes/apiv3/activity.ts
- packages/app/src/stores/activity.ts
[#93429](https://redmine.weseek.co.jp/issues/93429) [GROWI] [AuditLog] 管理画面に AuditLog の view を追加して、Activity をテーブルに一覧表示できる
└ [#95203](https://redmine.weseek.co.jp/issues/95203) [backend] /activity で行っている User ドキュメントの populate 処理を消す
> imprv: Remove user population

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/Page/FixPageGrantAlert.tsx
- packages/app/src/interfaces/page-grant.ts
- packages/app/src/interfaces/page.ts
- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/routes/apiv3/page.js
- packages/app/src/stores/page.tsx
https://redmine.weseek.co.jp/issues/95249
実装前の画像
実装後の画像
- 権限修正モーダルの中で、現在のページの権限と親のページの権限を表示する機能を実装
- 親のページの権限を閲覧可能な場合は表示、閲覧できない場合は表示しない機能を実装
> feat: fix grant alert show grant in modal

- packages/app/src/components/RevisionComparer/RevisionComparer.jsx
https://redmine.weseek.co.jp/issues/95488 
ページ更新履歴からページ更新後のurlを取得するときにパーマリンクを作成してクリップボードにコピーできるようにする。
すでにパーマリンクを取得できるDropDownMenuがあるのでそちらを参照してデザインも統一
> imprv: Added permanent link on the editing tag

- packages/app/src/server/models/page-operation.ts
- packages/app/src/server/service/page-operation.ts
Tasks
- https://redmine.weseek.co.jp/issues/95309
- https://redmine.weseek.co.jp/issues/95418
- https://redmine.weseek.co.jp/issues/95419
内容
- PageOperation の fromPath から始まるページパスの Rename は不可
- PageOperation の fromPath の直系の祖先にあたるページパスの Rename は不可
- PageOperation の fromPath から始まるページパスへの Rename は不可
canOperate を参照している delete なども上記同様に制限を受けるようになっている
> feat: Add more conditions to canOperate in PageOperation service and apply the condition to sub operation

- packages/app/src/components/Sidebar/CustomSidebar.tsx
[94345](https://redmine.weseek.co.jp/issues/94345) カスタムサイドバーを開いた後の loading 中に "Create /Sidebar page" というリンクを表示しない
┗ [94640](https://redmine.weseek.co.jp/issues/94640) 実装
> imprv: Initial rendering when opening Custom Sidebar

- packages/app/src/server/models/page.ts
- packages/app/src/server/service/page-grant.ts
- packages/app/src/server/service/page.ts
- packages/app/test/integration/models/v5.page.test.js
Redmine: https://redmine.weseek.co.jp/issues/95605
PageService の `create`, `createEmptyPagesByPaths`, `getParentAndFillAncestors` をリファクタしつつ、既存のモデル層のメソッドをいじらずにシステムによる処理を切り出しました
元あるメソッドを何段階かに切り分けて、そのうちシステムによる操作の場合に違う処理が必要なものだけそれ用のメソッドに差し替えて実装するという流れでリファクタしたので、まずユーザーによる操作のメソッドを確認していただいた後にシステムによる操作のメソッドを読んでいただけると多少わかりやすいかなと思います
> feat: Separate processes ran by system

- packages/app/src/components/Me/PasswordSettings.jsx
https://redmine.weseek.co.jp/issues/95682 
version 5以降ではすでに解決している、User SettingsにおいてGoogleの自動入力が誤動作してしまいEmailフィールドにusernameが入力されてしまうバグの修正。
以下#Issue2152リンク
https://github.com/weseek/growi/issues/2152
> Fixed the bug of auto-filling unintended values into the Email field of the User settings at version 4.5.x

- packages/app/src/components/PrivateLegacyPages.tsx
https://redmine.weseek.co.jp/issues/96181
- パスを入力して変換ボタンを管理者のみに表示する
- 「理解しました」のラベルを押してもチェックが入るようにする　
> only admin

- packages/app/src/styles/theme/_apply-colors-dark.scss
- https://redmine.weseek.co.jp/issues/90392
- dark themeにおけるoverride-list-group-item-for-pagetreeをgrayを使わない記述にする
- 文字色($color-sidebar-context)と背景色($bgcolor-sidebar-context)の2つさえ確定すれば自動的に決まるようにした
> imprv: Mixin of argument-of-override-list-group-item-for-pagetree for dark theme

- packages/app/src/server/service/page.ts
タスクなし
canDeleteLogic で operator が null の場合に exception が発生するのを修正しました
> fix: Server error due to the canDeleteLogic method

- packages/app/resource/locales/en_US/translation.json
- packages/app/resource/locales/ja_JP/translation.json
- packages/app/resource/locales/zh_CN/translation.json
- packages/app/src/components/Sidebar/Tag.tsx
https://redmine.weseek.co.jp/issues/96344
- タグリストとタグクラウドの入れ替え.
- タグリスト用の見出しタグを追加して、translation.jsonに文言追加.
- fontは他タスクチケットで対応.
**Before**
**After**
> imprv: change sidebar tag layout places add json

- packages/app/package.json
- packages/app/src/components/Sidebar/Tag.tsx
- packages/app/src/components/TagCloudBox.tsx
- packages/app/src/styles/_tag.scss
- packages/app/src/styles/theme/_apply-colors-dark.scss
- packages/app/src/styles/theme/_apply-colors-light.scss
- yarn.lock
対象タスク：https://redmine.weseek.co.jp/issues/96380
次のタスクでマージやフォント等を整えます。
**Before**
**タグリストデータとタグクラウドデータが連携している、順番とレイアウトがreact-tagcloudに依存している**
**After**
**タグリストデータに依存せず上位20件を順番に表示、レイアウト修正**
**リストページを変更してもtagcloudデータは変わらない.**
> imprv separate taglistdata amd tagclouddata

- packages/app/src/server/interfaces/api-rate-limit-config.ts
- packages/app/src/server/middlewares/api-rate-limiter.ts
- packages/app/src/server/util/generateApiRateLimitConfig.ts
https://redmine.weseek.co.jp/issues/96274
https://redmine.weseek.co.jp/issues/96275
- apiの制限をmongoDBで管理する
- 利用者が一定時間の回数でリクエストを制限できるようにする
現在のデフォルト設定
1秒間に10回
環境変数による設定の例
API_RATE_LIMIT_010_FOO_ENDPOINT=/_api/v3/foo
API_RATE_LIMIT_010_FOO_METHODS=GET,POST
API_RATE_LIMIT_010_FOO_MAX_REQUESTS=10 ← 1秒間の最大リクエスト回数
無制限にするエンドポイント決めたり、デフォルト値を考えるのは後続タスクでやります。
> feat: 96274 96275 connect to mongo and refactor config system

- packages/app/src/components/PageHistory.jsx
- packages/app/src/components/PageHistory/PageRevisionTable.jsx
- packages/app/src/components/PageHistory/Revision.jsx
- packages/app/src/interfaces/revision.ts
- packages/app/src/stores/page.tsx
https://redmine.weseek.co.jp/issues/95892
- PageHistoryContainerの中にあったロジックをstateとswrでPageHistoryの中に移動、PageHistoryContainerがなくても正常に動作するようにした（PageHistoryContainerは次のPRで消します）
> imprv: 95892 add swr

- packages/app/src/server/routes/apiv3/pages.js
- packages/app/src/server/service/page.ts
- packages/app/test/integration/service/page.test.js
[#96622](https://redmine.weseek.co.jp/issues/96622) [GROWI] [AuditLog] activity ドキュメントを生成する Express Middleware を実装する
└  [#96720](https://redmine.weseek.co.jp/issues/96720) ページリネーム時の activity 生成処理を add-activity-middleware を使った処理に置き換える
> imprv: Use add-activity middleware with page rename

- packages/app/src/client/services/CommentContainer.js
- packages/app/src/client/services/ContextExtractor.tsx
- packages/app/src/components/Page.jsx
- packages/app/src/components/PageComment/CommentEditor.jsx
- packages/app/src/components/PageEditor.jsx
- packages/app/src/components/PageEditor/EditorNavbarBottom.tsx
- packages/app/src/components/PageEditorByHackmd.jsx
- packages/app/src/components/SavePageControls.jsx
- packages/app/src/interfaces/common.ts
- packages/app/src/interfaces/user-trigger-notification.ts
- packages/app/src/server/models/page.js
- packages/app/src/server/service/user-notification/index.ts
- packages/app/src/server/views/widget/page_content.html
- packages/app/src/stores/context.tsx
- packages/app/src/stores/editor.tsx
- packages/app/test/integration/models/update-post.test.js
[GROWI][Issue] [bug] User trigger notifacationでデフォルトパターン設定後も記事作成時にInput channelsが自動入力されない
┗[95875](https://redmine.weseek.co.jp/issues/95875) 修正 (4.5.x)
5系での修正で差分があった以下二つのファイルは、本PRには反映されていません。
- [/SlackNotification.tsx](https://github.com/weseek/growi/pull/5911/files#diff-30d44cac3e4904751761b107333e4a35b58fc86a5add47ef88a5e7299f75ad8e)
┗一行追加されただけ
- [packages/app/src/components/Page/DisplaySwitcher.tsx](https://github.com/weseek/growi/pull/5911/files#diff-dc91afbcf95bb5a5c4fe1e1fe227c15f7966b13ee9bb0d9d3d1093bcfec95160)
┗currentPath -> currentPagePath に変更 (4系では、DisplaySwitcherにcurrentPathが使われていない)
5系での修正は 👉🏻 https://github.com/weseek/growi/pull/5911
> fix: Slack channels are not automatically filled after setting up user trigger notification on v4.5.x

- packages/app/src/server/routes/attachment.js
96384 [GROWI] attachmentルートのレスポンスヘッダにContent-Lengthをセットする
https://redmine.weseek.co.jp/issues/96690
説明はここに
https://redmine.weseek.co.jp/issues/96384
> imprv: Set Content-Length header in response of attachment

- packages/app/src/styles/theme/_apply-colors-light.scss
- packages/app/src/styles/theme/blackboard.scss
- packages/app/src/styles/theme/christmas.scss
- packages/app/src/styles/theme/fire-red.scss
- packages/app/src/styles/theme/future.scss
- packages/app/src/styles/theme/halloween.scss
- packages/app/src/styles/theme/hufflepuff.scss
- packages/app/src/styles/theme/jade-green.scss
- packages/app/src/styles/theme/nature.scss
- packages/app/src/styles/theme/spring.scss
- packages/app/src/styles/theme/wood.scss
- https://redmine.weseek.co.jp/issues/94754
- 各色の変更
- ついでにLightテーマ系については影をつけました（Light系は影ついてるのが正しいので）
- [こちら](https://kudakurage.hatenadiary.com/entry/2019/07/29/083000)の「[高さに応じてLightではshadowが、Darkでは明るさが変わる](https://kudakurage.hatenadiary.com/entry/2019/07/29/083000#:~:text=%E9%AB%98%E3%81%95%E3%81%AB%E5%BF%9C%E3%81%98%E3%81%A6Light%E3%81%A7%E3%81%AFshadow%E3%81%8C%E3%80%81Dark%E3%81%A7%E3%81%AF%E6%98%8E%E3%82%8B%E3%81%95%E3%81%8C%E5%A4%89%E3%82%8F%E3%82%8B)」の部分のセオリーを採用し、Darkでは基本的にサイドバーの色のほうがBodyの色よりも明るくするようにしました
- 周囲との色との整合性を取るように主に色相を調整しました
> imprv: 94754-each-theme-sidebar-color-fix

- packages/app/src/components/Admin/App/AwsSetting.jsx
[96330](https://redmine.weseek.co.jp/issues/96330) [Omit Unstated] withTranslation を useTranslation に置き換える
┗[97518](https://redmine.weseek.co.jp/issues/97518) 修正
console上にエラーが出てたので修正
> fix: Remove unnecessary type definition

- packages/app/src/interfaces/activity.ts
- packages/app/src/server/service/activity.ts
[#96531](https://redmine.weseek.co.jp/issues/96531) [GROWI] [AuditLog] ログイン / ログアウト / アカウント作成 / コメント削除 /  ページ閲覧時 に activity ドキュメントを作成できる
└ [#97267](https://redmine.weseek.co.jp/issues/97267) activity.user の型を string -> user ref に変更する
> fix Change IActivity user type from string to user ref

- packages/app/src/server/routes/index.js
- packages/app/src/server/routes/installer.js
[#96531](https://redmine.weseek.co.jp/issues/96531) [GROWI] [AuditLog] ログイン / ログアウト / アカウント作成 / コメント削除 /  ページ閲覧時 に activity ドキュメントを作成できる
└ [#97564](https://redmine.weseek.co.jp/issues/97564) 初回ユーザーを作成した時に Activity ドキュメントを作成できる
> feat: Create activity document when initial user is created

- packages/app/src/client/services/CommentContainer.js
- packages/app/src/components/PageComment/CommentEditor.jsx
https://redmine.weseek.co.jp/issues/95889
- CommentContainerの中にあった`uploadAttachment`メソッドの処理をCommentEditorに移動
> imprv: move uploadAttachment

- package.json
- packages/app/src/components/UncontrolledCodeMirror.tsx
- packages/app/src/server/service/s2s-messaging/nchan.ts
- tsconfig.base.json
- yarn.lock
Redmine: https://redmine.weseek.co.jp/issues/98216
Typescript のバージョンを `~4.6` に指定しました。yarn.lock 上では `4.2.4` => `4.6.4`
- `noImplicitOverride` を使うように tsconfig を改善
> support: Upgrade typescript to ^4.6.0

- packages/app/src/client/services/ContextExtractor.tsx
- packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
- packages/app/src/components/Navbar/SubNavButtons.tsx
- packages/app/src/components/NotFoundPage.tsx
- packages/app/src/components/Page/DisplaySwitcher.tsx
- packages/app/src/components/PageContentFooter.tsx
- packages/app/src/components/PageRenameModal.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/src/interfaces/page.ts
- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/models/page.ts
- packages/app/src/server/routes/apiv3/page-listing.ts
- packages/app/src/server/routes/apiv3/page.js
- packages/app/src/server/routes/apiv3/pages.js
- packages/app/src/server/routes/page.js
- packages/app/src/server/service/page.ts
- packages/app/src/server/views/layout-growi/not_found.html
- packages/app/src/stores/context.tsx
- packages/app/src/stores/ui.tsx
https://redmine.weseek.co.jp/issues/91682
サブナビゲーションの3点ボタンメニュー
ページツリーの3点ボタンメニュー
仕様変更対応（フロントでパーマリンクをパスリンクに置き換える）
https://github.com/weseek/growi/pull/5638#issuecomment-1101434033
> imprv: Show page control on subnavigation at existing empty page 

- packages/app/src/client/services/CommentContainer.js
- packages/app/src/components/PageComment/CommentEditor.tsx
- packages/app/src/server/routes/comment.js
https://redmine.weseek.co.jp/issues/98296
- コメントでMarkdown形式を選択できる機能を削除
- apiでは常にisMarkdown = trueを送信するように仕様変更
> remove markdown at comment

- packages/app/src/interfaces/page.ts
- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/models/page.ts
- packages/app/src/server/service/page.ts
https://youtrack.weseek.co.jp/issue/GW-7823
- Add isContainerFluid to page schema and interface
- Add isContainerFluid to page metadata
- Set value of isContainerFluid in page metadata by config if attribute not exists in page document
> Add isContainerFluid to page schema

- packages/app/src/client/services/ContextExtractor.tsx
- packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
- packages/app/src/components/NotFoundPage.tsx
- packages/app/src/components/Page/FixPageGrantAlert.tsx
- packages/app/src/stores/context.tsx
- packages/app/src/stores/page.tsx
- packages/app/src/stores/ui.tsx
https://redmine.weseek.co.jp/issues/98424
-  swr: `useIsEmptyPage` の命名等を修正
- replace 箇所のrefactor
- contextExtractor 内で `pageId` と `emptyPageId` に分離 およびそれに伴う修正
> feat: Modify swr hook for isEmptyPage & separate pageId and emptyPageId

- packages/app/src/server/service/page.ts
- packages/app/test/integration/service/page.test.js
以下ストーリー参照
https://redmine.weseek.co.jp/issues/84441 
子孫ページを含む親ページが削除されたときに、子孫ページのみをサブスクライブしているユーザーに対して通知を飛ばせるようにする。
> feat: Feat/create notification when parent page are deleted

- packages/app/src/server/service/search-delegator/elasticsearch.ts
Redmine: なし
ES6 が highlight.query.max_analyzed_offset に対応していないので、ES6 でない時のみ max_analyzed_offset をつけるようにしました。
ES6 の人が index.highlight.max_analyzed_offset の設定値以上の文字列を highlight クエリにかけるには ES7 に上げる以外の方法は今の所 GROWI にはない状態ですが、そもそもサポートを外していく予定なのでこれで OK だと判断しました
> fix: Ensure backword compatibility for ES6 when using max_analyzed_offset

- packages/app/src/server/service/search-delegator/elasticsearch.ts
Redmine: なし
https://github.com/weseek/growi/pull/6115 と https://github.com/weseek/growi/pull/6121 の 4.5.x 向け
> fix: Set max_analyzed_offset to elasticsearch querying options (for 4.5.x)

- packages/app/src/client/services/ContextExtractor.tsx
- packages/app/src/server/models/config.ts
- packages/app/src/server/routes/apiv3/activity.ts
- packages/app/src/stores/activity.ts
- packages/app/src/stores/context.tsx
[#98233](https://redmine.weseek.co.jp/issues/98233) [GROWI] [AuditLog] AuditLog 機能自体の ON / OFF ができる
└ [#98236](https://redmine.weseek.co.jp/issues/98236) 環境変数を参照し OFF 時に req / res しないようにする
> imprv: No Request / Response when Audit Log is disabled

- packages/app/public/static/locales/en_US/admin/admin.json
- packages/app/public/static/locales/ja_JP/admin/admin.json
- packages/app/public/static/locales/zh_CN/admin/admin.json
- packages/app/src/components/Admin/AuditLog/AuditLogDisableMode.tsx
- packages/app/src/components/Admin/AuditLogManagement.tsx
- packages/app/src/stores/context.tsx
[#98233](https://redmine.weseek.co.jp/issues/98233) [GROWI] [AuditLog] AuditLog 機能自体の ON / OFF ができる
└ [#98235](https://redmine.weseek.co.jp/issues/98235) 環境変数を参照しOFF時には AuditLog を表示しないようにする
> feat: Audit Log disable mode

- packages/app/src/client/services/ContextExtractor.tsx
- packages/app/src/client/services/PageContainer.js
- packages/app/src/components/Page/TrashPageAlert.jsx
- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/views/layout-growi/identical-path-page.html
- packages/app/src/server/views/widget/page_content.html
- packages/app/src/stores/context.tsx
- packages/app/src/stores/ui.tsx
ストーリー: https://redmine.weseek.co.jp/issues/99078
タスク: https://redmine.weseek.co.jp/issues/99080
- useIsDeletedを削除し、useIsTrashPageに置き換えた。それに伴い、swigにisDeletedのデータを注入していた部分を削除。
- pageSchema.methods.isDeletedをリファクタし、ロジックをisTrashPageと一致させた（Next化に伴い、pageSchema.methods.isDeletedは削除予定？）
> imprv: remove isDeleted

- packages/app/src/server/routes/apiv3/pages.js
https://redmine.weseek.co.jp/issues/99106
- もともとモデル層にあった`findChildrenByParentPathOrIdAndViewer`というメソッドがサービス層に移動されたときに、呼び出しもとが変更されていなかった
> fix: Empty trash doesn't work

- packages/app/test/integration/service/v5.page.test.ts
https://redmine.weseek.co.jp/issues/98782
このPR #6120 のCIエラーの対応
- `resumeRenameSubOperation` の改修
- 引数が変更された
- リネームが途中で中断された時におけるリネームの再開によって、パス修復後に祖先ページの子孫数が正常でなくなることを確認するテストが不要になり削除した `x2`
> Feat: Fix errors that occurered by refactoring resumeRenameOperation

- packages/app/src/stores/ui.tsx
https://redmine.weseek.co.jp/issues/99261
useEditorMode 内の `determineEditorModeByHash` で window を参照していたため、エラーが出ていたのを解消
> feat: Universilize useEditorMode

- packages/app/src/components/Me/AssociateModal.tsx
- packages/app/src/stores/personal-settings.tsx
[Omit Unstated] [SWR化] PersonalContainer
┗[99693](https://redmine.weseek.co.jp/issues/99693)Cypress のエラー修正
[マスターマージPR (Omit Personal Contaiener)](https://github.com/weseek/growi/pull/6182) にて、Cypressのエラーが出ていたので、修正しました。
```
1 failing
1) Access User settings
Update settings:
AssertionError: Timed out retrying after 4000ms: Expected to find element: `.toast`, but never found it.
at Context.eval (http://localhost:3000/__cypress/tests?p=test/cypress/integration/60-home/home.spec.ts:144:26)
```
https://github.com/weseek/growi/runs/7168852916?check_suite_focus=true
> fix/96693 Show toast error

- packages/app/src/components/Admin/MarkdownSetting/MarkDownSettingContents.tsx
- packages/app/src/components/Admin/MarkdownSetting/PresentationForm.jsx
- packages/app/src/components/Admin/MarkdownSetting/WhiteListInput.jsx
- packages/app/src/components/Admin/MarkdownSetting/XssForm.jsx
┗[100058](https://redmine.weseek.co.jp/issues/100058) [Markdown Settings] PresentationForm & XssForm  の表示
コメントアウトしていた「PresentationForm」　と「XssForm」を表示しました。
> show Markdown and XSS Settings

- packages/app/src/server/middlewares/login-required.js
- packages/app/src/server/routes/login.js
[GROWI][bug][4.5.x] Bug: 「ID&Password」有効状態で管理者が「新規ユーザーの仮発行」を使用したユーザーがログインボタンを押下時にユーザー新規登録画面に遷移しない
┗[100217](https://redmine.weseek.co.jp/issues/100217) 修正
- 5系での修正PR は 👉🏻 https://github.com/weseek/growi/pull/6197
- 動作確認は終了済み
> fix: User registration page is not redirected after tmp login on v4.5.x

- packages/app/src/server/crowi/express-init.js
- packages/app/src/server/service/config-loader.ts
[#101027](https://redmine.weseek.co.jp/issues/101027) [AuditLog] 環境変数 Trust Proxy を boolean、string、number の3種類の型で設定できる
└ [#101028](https://redmine.weseek.co.jp/issues/101028) 実装
> feat: Separate trust proxies by type

- packages/app/package.json
- packages/app/src/services/renderer/renderer.tsx
- packages/slackbot-proxy/src/controllers/slack.ts
- yarn.lock
Redmine: https://redmine.weseek.co.jp/issues/100847
remark-gfm が remark-footernotes を含むため、remark-footernote を削除しました。
see: https://github.com/remarkjs/remark-footnotes
> support: Remove remark-footernotes

- packages/app/src/components/Theme/ThemeIsland.module.scss
- packages/app/src/components/Theme/ThemeIsland.tsx
- packages/app/src/components/Theme/ThemeMonoBlue.module.scss
- packages/app/src/components/Theme/ThemeMonoBlue.tsx
- packages/app/src/components/Theme/ThemeNature.module.scss
- packages/app/src/components/Theme/ThemeNature.tsx
- packages/app/src/components/Theme/ThemeSpring.module.scss
- packages/app/src/components/Theme/ThemeSpring.tsx
- packages/app/src/components/Theme/ThemeWood.module.scss
- packages/app/src/components/Theme/ThemeWood.tsx
- packages/app/src/components/Theme/utils/ThemeProvider.tsx
- Island, Spring, Nature, Wood, MonoBlue
- Cardの bg-primary (おそらくそれ以外も)に theme の色が適用されていない
- https://redmine.weseek.co.jp/issues/101210
- 特定のテーマの背景画像が表示されていない
- https://redmine.weseek.co.jp/issues/101211
height="200"/>
height="200"/>
> feat: Nextjs apply themes

- packages/app/public/static/locales/en_US/admin/admin.json
- packages/app/public/static/locales/ja_JP/admin/admin.json
- packages/app/public/static/locales/zh_CN/admin/admin.json
- packages/app/src/components/Admin/AuditLog/ActivityTable.tsx
- packages/app/src/server/models/activity.ts
- packages/app/src/server/routes/apiv3/activity.ts
- packages/app/src/stores/activity.ts
[#100580](https://redmine.weseek.co.jp/issues/100580) [AuditLog] テーブルの username 周りの改善
└ [#100596](https://redmine.weseek.co.jp/issues/100596) 実装
> feat: Show user picture in Audit Log

- packages/app/src/services/renderer/markdown-it/link-by-relative-path.ts
https://redmine.weseek.co.jp/issues/101748
- Related issue: https://github.com/weseek/growi/pull/5788
- Produced by https://github.com/weseek/growi/pull/6223
> fix: Default markdown linker with relative path does not respect the current page path (v5.1.0)

- packages/app/src/server/util/rate-limiter.ts
https://redmine.weseek.co.jp/issues/101762
- ipアドレス当たりのユーザー数を環境変数を用いてエンドポイントごとに設定できるようにした
> feat: Users can set users per ip from env var at API Rate Limit 

- packages/app/src/components/Admin/Customize/Customize.jsx
- packages/app/src/components/Admin/Customize/CustomizeSidebarSetting.tsx
[GROWI][Next.js][Admin][Customize] 各種設定の更新ができる
┗[101155](https://redmine.weseek.co.jp/issues/101155) [CustomizeSidebarSetting][fix err] A component is changing an uncontrolled input to be controlled.
ブラウザに出力される以下のエラー修正をし、`CustomizeSidebarsetting` コンポーネントの表示をしました。
```
next-dev.js?36dd:25 Warning: A component is changing an uncontrolled input to be controlled. This is likely caused by the value changing from undefined to a defined value, which should not happen. Decide between using a controlled or uncontrolled input element for the lifetime of the component.
```
> resolve  uncontrolled input err on browser

- packages/app/src/components/Admin/Security/SecurityManagementContents.jsx
- packages/app/src/components/Admin/UserManagement.jsx
- packages/app/src/components/Admin/Users/UserInviteModal.jsx
- packages/app/src/pages/admin/[[...path]].page.tsx
[GROWI][Next.js][Admin][Customize以外] 残存の不具合を修正し、全てのページで正常に表示 & 更新ができる
┗ [101815](https://redmine.weseek.co.jp/issues/101815) [Secyrity][UserGroupManagement][UserManagement] 表示されていないコンテンツの表示
`<InviteUserControl />` を有効化し、`UserInviteModal` を表示
https://github.com/weseek/growi/blob/support/apply-nextjs-2/packages/app/src/components/Admin/UserGroup/UserGroupPage.tsx#L147-L159
↑の部分で`isAclEnabled` の値が undefined になっていたので、`ユーザーグループ作成ボタン` が表示されていませんでした。
よって、`isAclEnabled` を server side から取得し、ユーザーグループ作成ボタンを表示 & ユーザーグループをを新規作成できるようにしました。
> Imprv/101815 Security settings  /  UserManagement  / UserGroupManagement  contents

- packages/app/src/client/services/page-operation.ts
- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/src/components/Navbar/SubNavButtons.tsx
- packages/app/src/components/PageList/PageListItemL.tsx
- packages/app/src/components/SearchPage/SearchResultContent.tsx
- packages/app/src/components/SearchPage/SearchResultList.tsx
- packages/app/src/interfaces/page.ts
- packages/app/src/server/models/obsolete-page.js
- packages/app/src/server/models/page.ts
- packages/app/src/server/routes/apiv3/page.js
- packages/app/src/server/service/page.ts
- packages/app/src/server/views/layout/layout.html
- Fix the logic for isContainerFluid in swig template
- Move the wide view menu item into SubNavButtons
- Rename `Page.isContainerFluid` to `Page.expandContentWidth`
- Unset `Page.expandContentWidth` attribute if the specified value is the same to the system's one
> imprv: Switch content width

- packages/app/src/components/Navbar/AuthorInfo.module.scss
- packages/app/src/components/Navbar/GrowiContextualSubNavigation.tsx
- packages/app/src/components/Navbar/GrowiSubNavigation.tsx
- packages/app/src/components/Navbar/PageEditorModeManager.module.scss
- packages/app/src/components/Page/TagLabels.module.scss
- packages/app/src/components/Page/TagLabels.tsx
- packages/app/src/components/Sidebar/RecentChanges.tsx
- packages/app/src/components/Skelton.tsx
- packages/app/src/styles/_tag.scss
https://redmine.weseek.co.jp/issues/101877
- スケルトンコンポーネントからwidth, heightのpropsを削除、スタイルはcssで当てる実装に変更
- 親コンポーネントでスケルトンのwidth, heightをハードコーディングしていた部分をcssでスタイルを当てるように修正
TagLabelsとAuthorInfoのスケルトンリファクタは既存コンポーネントのスタイルを変更する必要がありそうだったので別タスク(https://redmine.weseek.co.jp/issues/102017)
でやります
> imprv: refactor skelton component

- packages/app/src/components/Navbar/AuthorInfo.module.scss
- packages/app/src/components/Navbar/GrowiSubNavigation.module.scss
- packages/app/src/components/Navbar/GrowiSubNavigation.tsx
- packages/app/src/components/Page/RenderTagLabels.tsx
- packages/app/src/components/Page/TagLabels.module.scss
- packages/app/src/components/Page/TagLabels.tsx
https://redmine.weseek.co.jp/issues/102017
before
after
- TagLabelsのデザインが少しずれていたのを修正（プラスボタンがめちゃめちゃ少し上にずれていた）
- TagLabelsとAuthoInfoのスケルトンの高さをハードコーディングではなく、本物のコンポーネントの情報から計算するように実装
> imprv: 102017 refactor tag labels author info skelton

- packages/app/src/stores/page.tsx
https://redmine.weseek.co.jp/issues/102041
[[...page]]の中で
```
useSWRxPageInfo(pageId, undefined, pageWithMeta?.meta); // store initial data
```
このようにして、initial dataを入れているが、swrのfallbackDataが機能しておらず、キャッシュにデータが保存できていない
useSWRxPageInfoの中で明示的にmutateをする
> fix: 102041 refactor use sw rx page info

- packages/app/src/components/Layout/AdminLayout.tsx
- packages/app/src/components/Layout/RawLayout.tsx
- packages/app/src/components/Theme/ThemeAntarctic.module.scss
- packages/app/src/components/Theme/ThemeAntarctic.tsx
- packages/app/src/components/Theme/ThemeChristmas.module.scss
- packages/app/src/components/Theme/ThemeChristmas.tsx
- packages/app/src/components/Theme/ThemeHalloween.module.scss
- packages/app/src/components/Theme/ThemeHalloween.tsx
- packages/app/src/components/Theme/ThemeHufflepuff.module.scss
- packages/app/src/components/Theme/ThemeHufflepuff.tsx
- packages/app/src/components/Theme/ThemeIsland.module.scss
- packages/app/src/components/Theme/ThemeIsland.tsx
- packages/app/src/components/Theme/ThemeSpring.module.scss
- packages/app/src/components/Theme/ThemeSpring.tsx
- packages/app/src/components/Theme/ThemeWood.module.scss
- packages/app/src/components/Theme/ThemeWood.tsx
- packages/app/src/components/Theme/utils/ThemeImageProvider.tsx
- packages/app/src/pages/[[...path]].page.tsx
https://redmine.weseek.co.jp/issues/101211
https://redmine.weseek.co.jp/issues/102458
- 背景画像の表示
- ThemeImageProvider を実装
- ThemeImageProvider の getBackgroundImageSrc に現在のテーマと light/dark mode の値を渡すと、テーマに応じた背景画像のURLを返すようにしている
- 背景画像のURLは、背景画像を使用するテーマのコンポーネント内に実装した getBackgroundImageSrc を ThemeImageProvider の getBackgroundImageSrc から呼び出すことで取得している
- ナビバー画像の表示
- こちらは scss で background-image を用いて表示している
HufflePuff / light
HufflePuff / dark
ここから下は light/dark による画像の違いなし
Wood (背景が木目の画像)
Island(背景がグラデーションの画像)
Christmas (ナビバーと背景に画像)
Antarctic
Spring
Halloween (ナビバーと背景に画像)
> feat: Apply background image and navbar image for themes

- packages/app/src/server/service/activity.ts
- packages/app/src/server/service/in-app-notification.ts
- packages/app/src/server/service/page.ts
AuditLog実装に伴って、再度「親ページに対するアクションが起こされたとき、子孫ページのみをサブスクライブしているユーザーに対して通知を送る」機能実装を、renameから行う。
武井さんと仕様確認した際、現状descendantsPagesを一気に取得する仕様においてコストが高すぎると指摘されたため、ベースは同じにしつつ、以下の変更を加えた。
- activityインスタンスをサービス層で生成するという仕様は変わらず。
- batch処理でメモリーに負担をかけないためdescendant pagesを塊ごとにとってくる処理の最中で、getSubscriptionsメソッドを用いてユーザーを取得。
- よってリネームされたページの配下にあるページをサブスクライブしているユーザー全てを先に取得し、activityEvent.emit('update')を呼ぶ。
以上の仕様に変更したのち、動作確認済み。
> feat: Created the activity inside service/page.ts and gathered descendants users.

- packages/app/src/server/routes/index.js
- packages/app/src/server/routes/page.js
- packages/app/src/server/service/page.ts
- packages/app/test/integration/service/page.test.js
- packages/app/test/integration/service/v5.non-public-page.test.ts
- packages/app/test/integration/service/v5.public-page.test.ts
ActivityLog実装後に仕様変更した、親ページに何らかのアクティビティが起きた場合に、子孫ページのみをサブスクライブしているユーザーに対して通知を送る機能の実装が確定したので、rename以外のアクティビティへの実装タスク。
なお、マージ先はfat/descendant-notifications
本ブランチがマージされたのち、親ブランチをmasterにマージさせるPRを作成・依頼予定。
以下参照：
https://redmine.weseek.co.jp/issues/102591
> feat: Feat/descendant notifications delete/delete completely/revert

- packages/app/src/components/Me/BasicInfoSettings.tsx
- packages/app/src/pages/me.page.tsx
- packages/core/src/interfaces/lang.ts
https://redmine.weseek.co.jp/issues/102587
- meページのユーザー設定タブの言語の項目を表示
- このタスクとはあまり関係ないですが、現在のアイコンが表示されていないことに気が付いたので修正しました
> imprv: 102587 i18n for me page

- packages/app/src/components/DescendantsPageList.tsx
[#102947](https://redmine.weseek.co.jp/issues/102947) [Bug] ページリストの機能を使って表示するとページの一覧が20件までしか表示されない
└ [#102948](https://redmine.weseek.co.jp/issues/102948) 修正
> fix: Pager is not displayed

- packages/app/src/server/crowi/express-init.js
[GROWI][Next.js][Admin][Customize以外] 残存の不具合を修正し、全てのページで正常に表示 & 更新ができる
┗[102704](https://redmine.weseek.co.jp/issues/102704) [UserGroup Management] [external_account_management][Share link]  fix invalid csrf token
削除ボタンを押したときに、` invalid csrf token` のエラーがブラウザのコンソールに出力され、削除できない問題を修正しました。
以下で正常に動作することを確認しています
- UserGroup Management の delete user
- External Account Management の delete user
- Share link の delete
このタスク用の動作確認タスクを新規作成しました。
https://redmine.weseek.co.jp/issues/102623
> Fix/102704 ignore csrf: api delete

- packages/app/public/static/locales/en_US/translation.json
- packages/app/public/static/locales/ja_JP/translation.json
- packages/app/public/static/locales/zh_CN/translation.json
- packages/app/src/components/PageEditor/Editor.tsx
https://redmine.weseek.co.jp/issues/103018
修正後
画像の添付も確認済み
> fix: Uploading image using shortcut key(ctrl+v) shows toastError

- packages/app/src/pages/admin/[[...path]].page.tsx
[#101095](https://redmine.weseek.co.jp/issues/101095) [GROWI][Next.js][Admin][Customize以外] 残存の不具合を修正し、全てのページで正常に表示 & 更新ができる 
└ [#103137](https://redmine.weseek.co.jp/issues/103137) メーラーのセットアップが済んでいる状態でユーザーを招待をする際に Email を送るオプションにチェックをつけられない問題の修正
> fix: Unable to check the option to send an email when inviting users

- packages/app/src/components/Fab.jsx
- packages/app/src/components/Fab.module.scss
- packages/app/src/components/Layout/BasicLayout.tsx
タスク: [103755](https://redmine.weseek.co.jp/issues/103755)
- ページ右下 Fab のレンダリング
- フェードアニメーションの実装
- ボタンの background-color や color は　`.btn-primary` のテーマ等が原因
theme-default 関連のため,　theme修正後に修正見込み
> feat: Rendering Fab component

- packages/app/src/server/routes/apiv3/page.js
https://redmine.weseek.co.jp/issues/104243
> fix: Disallow retrieval of revision data that does not match the page

- packages/app/src/components/Common/ClosableTextInput.tsx
- packages/app/src/components/Sidebar/PageTree/Item.tsx
- packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
Redmine: https://redmine.weseek.co.jp/issues/102144
PageTree の input で変換のためにエンターを押した時に Create/Rename の POST リクエストが飛ばないように修正しました
> fix: Pagetree input hit enter

- packages/app/src/components/Admin/UserGroupDetail/UpdateParentConfirmModal.tsx
- packages/app/src/components/Admin/UserGroupDetail/UserGroupDetailPage.tsx
[Issue][userGroup][bug] 親を指定せずにUserGroupの概要を更新しようとすると「Error Something went wrong. Please try again.」のエラーが表示され、更新できない
┗[104025](https://redmine.weseek.co.jp/issues/104025)
https://user-images.githubusercontent.com/59536731/189270967-ca6db315-55b3-4a2e-a65a-fbbc3bc5b22a.mov
https://user-images.githubusercontent.com/59536731/189271435-601d7728-2260-4185-a6fd-8881c73474f5.mov
あとこれでいいのかわかっておらず見落としもありそうなので確認お願いします。
(もしかしたら実装者が修正した方が早いかもしれません)
`Something went wrong. Please try again.` エラー内容がわからず改善した方がいいんじゃなかろうか と思っているがどうすればいいかわからず....。そのままでいいとのことであればそのままにします。
https://github.com/weseek/growi/blob/9faad941647406d36348355a0c71ad5a6791490b/packages/app/src/components/Admin/UserGroupDetail/UpdateParentConfirmModal.tsx#L75-L79
関係のない部分で差分が出ているのでスルーでOK
> fix: Cannot update user group without parent

- packages/app/src/components/Fab.module.scss
- packages/app/src/components/Layout/BasicLayout.tsx
- Fab.jsxの`sticky-events`エラーの回避のため、Fabコンポーネントのコメントアウト
> feat: Disable Fab component

- packages/app/src/components/PageContentFooter.tsx
- packages/app/src/components/SearchPage/SearchResultContent.tsx
- packages/app/src/pages/[[...path]].page.tsx
task: [104310](https://redmine.weseek.co.jp/issues/104310)
- EditページのUpdate後にViewに自動遷移しても PageContentFooter の `Last revision posted at` が更新されない の修正
> imprv: Update PageContentFooter for present updated data

- packages/app/src/pages/[[...path]].page.tsx
[#99801](https://redmine.weseek.co.jp/issues/99801) [Next.js] ゴミ箱ページ（/trash）をnext.jsでレンダリングできる
└ [#104757](https://redmine.weseek.co.jp/issues/104757) /trash 配下にあるページにアラートを表示する
> fix: Display trash page alert

- packages/app/src/components/PrivateLegacyPages.tsx
https://redmine.weseek.co.jp/issues/104818
PrivateLegacyPageの動作確認を自分でしているときに、パスでページを変換した後に古いページのリストが更新されていないことに気が付いたのでそれを修正しました。
> fix: 104818 reload private legacy with path

- packages/app/src/components/PageComment/CommentEditor.tsx
- packages/app/src/components/PageEditor/CodeMirrorEditor.module.scss
タスク: https://redmine.weseek.co.jp/issues/104913
- あったこと：CommentEditorのボタンが使えない箇所があった。
- 原因：CodeMirror-scrollが被っていた。CodeMirror-scrollはSCSSモジュールの中で外部ライブラリとしてscssインポートされていたため、box-sizing: content-box; が優先されていた。
- 修正：box-sizing: border-boxが適用されてほしいのでscssモジュール内で上書き
> feat: Fix CommentEditor button

- packages/app/test/cypress/integration/21-basic-features-for-guest/access-to-page.spec.ts
[#105213](https://redmine.weseek.co.jp/issues/105213) ゲストモード時はサイドバーを閉じた状態でtrash ページに訪れる
> fix: Visiting the trash page with the sidebar closed when in guest mode (VRT)

- packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
[#105237](https://redmine.weseek.co.jp/issues/105237) UserUiSettings の保存を待たずにカスタムサイドバーのスクリーンショットを撮影する
[access-to-sidebar-custom-sidebar-3-custom-sidebar-created.png](https://growi-vrt-snapshots.s3.amazonaws.com/254b050e9b981bda33ac5c51e999b9e6d30c856e/index.html?id=changed-50-sidebar/access-to-side-bar.spec.ts/access-to-sidebar-custom-sidebar-3-custom-sidebar-created.png#changed-50-sidebar/access-to-side-bar.spec.ts/access-to-sidebar-custom-sidebar-3-custom-sidebar-created.png)
> fix: Do not wait to save user-ui-settings (VRT)

- packages/app/src/components/PageList/PageListItemL.tsx
- packages/app/test/cypress/integration/20-basic-features/use-tools.spec.ts
- packages/app/test/cypress/integration/30-search/search.spec.ts
https://redmine.weseek.co.jp/issues/105162
期待されるスクショ
実際のスクショ
アプリ側で検索後にページリストで選択状態にならない不具合があったのでそこをcypress側で無理やりつじつまを合わせました。この不具合は武井さんも認識していましたが、割と沼りそうなのと、Next化に伴って表示のロジックが変わるため、アプリ側の修正ではなく、VRTのエラーをいったん無くすという方針になりました。
VRTでこれ関係のエラーが2つ出ていますが
- https://growi-vrt-snapshots.s3.amazonaws.com/904cd9d76552c3be55834a7293232e73e6257efe/index.html?id=changed-20-basic-features/use-tools.spec.ts/tag-operations-page-duplicate-1-click-tag-name.png
- https://growi-vrt-snapshots.s3.amazonaws.com/904cd9d76552c3be55834a7293232e73e6257efe/index.html?id=changed-20-basic-features/use-tools.spec.ts/tag-operations-page-duplicate-2-click-three-dots-menu.png
afterのスクショの方が本来の挙動なので、比較元のbeforeのスクショが間違っており、このエラーは無視しても大丈夫です
メモ
- VRTではなく、アプリ側がおかしいのでページのリストのDOMを直接操作してactiveクラスを付与する方法でVRTを通す
- …
> support: Fix Page List VRT with force to focus the element

- packages/app/test/cypress/integration/20-basic-features/access-to-pagelist.spec.ts
https://redmine.weseek.co.jp/issues/105391
PageList→TimeLine表示のVRTでページのレンダリングを待って、スクショを撮るようにした
https://growi-vrt-snapshots.s3.amazonaws.com/5542da4806158eb4f4d38b0c164310e948bbbb2b/index.html?id=changed-20-basic-features/access-to-page.spec.ts/access-to-page--sandbox-headers.png
上記のVRTで差分が出ていますが、beforeのスクショが間違っているのでスルーでいいと思います
> support: VRT fix waitind for pagelist rendering

- packages/app/package.json
- packages/app/src/components/Me/BasicInfoSettings.tsx
- packages/app/src/pages/me/[[...path]].page.tsx
- packages/app/src/pages/utils/commons.ts
- yarn.lock
https://redmine.weseek.co.jp/issues/104833
meページの言語選択の一覧で言語が正しく表示されていない不具合を修正しました
before
after
やったこと
- next-i18nextのバージョンを11.0.0から11.3.0に上げた
- https://github.com/i18next/next-i18next/releases/tag/v11.3.0
- ver11.3.0から、言語のpreloadの機能が追加されたため
- injectNextI18NextConfigurationsを修正し、各ページですべての言語をpreloadするか選択できるようにした
> fix: 104833 fix me page i18n

- packages/app/test/cypress/integration/30-search/search.spec.ts
- packages/app/test/cypress/integration/40-admin/access-to-admin-page.spec.ts
https://redmine.weseek.co.jp/issues/105469
https://growi-vrt-snapshots.s3.amazonaws.com/ea85240af5df47c008876257774ef76570a37657/index.html?id=changed-40-admin/access-to-admin-page.spec.ts/access-to-admin-page--admin-customize.png
- admin画面の画像のローディング&スタイル適用が完了していない段階でスクリーンショットがとられてしまっていたのでwaitを追加してタイミングを合わせるようにしました。
- 対象のタスクではないですが、ページリストに強制的にactiveクラスを付与するコードの抜けがあったので追加しました。
あたらしい差分があったのでタスクを作りました
https://redmine.weseek.co.jp/issues/105501
> support: Add wait for loading layout image in VRT

- packages/app/src/components/Sidebar/RecentChanges.tsx
- packages/app/test/cypress/integration/20-basic-features/access-to-pagelist.spec.ts
- packages/app/test/cypress/integration/50-sidebar/access-to-side-bar.spec.ts
タスク:
- https://redmine.weseek.co.jp/issues/105464
-> 時刻のため, Blackoutで対応. CSSコンテナを指定するとblackoutがずれるので全画面キャプチャに変更
- https://redmine.weseek.co.jp/issues/105501
- https://redmine.weseek.co.jp/issues/105460
-> should('be.visible').scrollTo() で対応.
- https://redmine.weseek.co.jp/issues/105463
-> こちらはその後確認できないため、一旦そのまま。
> support: Update spec ts for VRT normalization

- packages/app/public/static/locales/en_US/admin.json
- packages/app/public/static/locales/ja_JP/admin.json
- packages/app/public/static/locales/zh_CN/admin.json
- packages/app/src/components/Admin/App/AppSetting.jsx
- packages/app/src/pages/admin/[[...path]].page.tsx
https://redmine.weseek.co.jp/issues/105556
admin画面のアプリ設定画面で言語リストが正常に表示されていなかったのを修正しました
修正前
修正後
> fix: show language lists in admin app setting

- packages/app/src/components/Common/Dropdown/PageItemControl.tsx
- packages/app/test/cypress/integration/20-basic-features/access-to-pagelist.spec.ts
VRT正常化_2022_09_16
┗[105459](https://redmine.weseek.co.jp/issues/105459) pagelist 3点ボタンメニュー
モーダルの要素だけのスクショを撮るようにした　(ついで)
| Before | After | 
| ---- | ---- | 
| ![Screen Shot 2022-09-27 at 2 48 05](https://user-images.githubusercontent.com/59536731/192346041-1bd58083-35b1-46d7-81d3-ada8ef190fb8.png)     |  ![Screen Shot 2022-09-27 at 2 48 09](https://user-images.githubusercontent.com/59536731/192346049-14029709-2b4b-4d5c-875b-3999aedf40e6.png)    |  
pageItemControl の dropdown menu の要素のみのスクショを撮ることで、menu の場所が移動する差分が検出するのを防ぎました。
> fix: VRT page Item control position

- packages/app/src/server/routes/login.js
https://redmine.weseek.co.jp/issues/99075
新規登録時にパスワードがない場合、/ページではなく、/me#passwordにリダイレクトする処理を追加
- 修正したコードで新規登録したあと、/ページにリダイレクトすることを確認（正常な場合）
- コードの条件分岐部分を削除して、強制的に/me#passwordにリダイレクトする状況を作り、動作確認をしたところ新規登録後、/me#passwordにリダイレクトすることを確認
> add code to redirect to /me#password

- packages/app/src/pages/[[...path]].page.tsx
[#103550](https://redmine.weseek.co.jp/issues/103550) [Nextjs]ページを閲覧しても足跡の数が更新されない
└ [#105558](https://redmine.weseek.co.jp/issues/105558) 足跡が更新されるように修正
> fix: Footprints are not displayed

- packages/app/src/components/Fab.tsx
- packages/app/src/components/Layout/BasicLayout.tsx
- packages/app/src/components/Layout/ShareLinkLayout.tsx
タスク:https://redmine.weseek.co.jp/issues/105718
- ページ遷移時に sticky エラーが発生するため, FabのstickyEventsを無効化
- `position: relative` が適用されないため、`grep='<Fab'` でその child 要素に style を適用
後続タスク:https://redmine.weseek.co.jp/issues/102126
> feat: Disable StickyEvents

- packages/app/src/components/PageEditor/Editor.tsx
- packages/app/test/cypress/integration/20-basic-features/access-to-page.spec.ts
- packages/app/test/cypress/integration/30-search/search.spec.ts
- packages/app/test/cypress/integration/40-admin/access-to-admin-page.spec.ts
https://redmine.weseek.co.jp/issues/105468
https://growi-vrt-snapshots.s3.amazonaws.com/ea85240af5df47c008876257774ef76570a37657/index.html?id=changed-20-basic-features/access-to-page.spec.ts/access-to-page--sandbox-headers.png
- Sandbox#Headersにアクセスした直後は「Headers」という文字の背景が灰色っぽく、時間がたつにつれて薄くなる仕様になっており、その途中でスクショがとられてVRTで差分が出ていたので、header部分のアニメーションを削除してスクショを撮るようにしました。
- ページリストの表示で強制的にactiveクラスを付与する部分の抜けがあったため、追加しました。
> support: add wait for header style in VRT

- lerna.json
- package.json
- packages/app/bin/github-actions/update-readme.sh
- packages/app/docker/README.md
- packages/app/package.json
- packages/codemirror-textlint/package.json
- packages/core/package.json
- packages/plugin-attachment-refs/package.json
- packages/plugin-lsx/package.json
- packages/remark-growi-plugin/package.json
- packages/slack/package.json
- packages/slackbot-proxy/package.json
- packages/ui/package.json
Bump version `5.1.5-RC.0` to `6.0.0-RC.1`.
`6.0.0-RC.0` has already released.
> support: Apply nextjs 2 bump version 6.0.0-RC.1

- packages/app/src/pages/me/[[...path]].page.tsx
- packages/app/src/server/routes/index.js
https://redmine.weseek.co.jp/issues/105879
https://redmine.weseek.co.jp/issues/105878
軽微な修正だったので2つのタスクを1つのPRにまとめました
- 未ログイン状態でもmeページにアクセスできてしまっていたのを修正
- adminの翻訳ファイルが適用されていなかったことの修正
before
after
> fix: 105878 me routing 105879 i18n

- packages/app/src/components/PageEditor/CodeMirrorEditor.jsx
Redmine: https://redmine.weseek.co.jp/issues/105814
CodeMirror の forceToFocus メソッドの setInterval の callback が走り続けてしまうのを修正しました。
> fix: CodeMirror focus
